src/ButtonGroup/index.js
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-buttongroup-border.surge.sh</url>
=> fix(ButtonGroup): mobile border radius

.github/workflows/main.yml, package.json, yarn.lock
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-compressed-size.surge.sh</url>
=> chore: fix compressed-size action

src/Portal/index.js
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-portal-ssr.surge.sh</url>
=> fix(Portal): state init on SSR

src/InputStepper/__tests__/index.test.js, src/InputStepper/index.js
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-stepper-disabled.surge.sh</url>
=> fix(InputStepper): onChange is triggered when disabled

src/Stepper/README.md
To match Flow.
<br/><br/><br/><url>LiveURL: https://orbit-components-docs-stepper.surge.sh</url>
=> docs: update Stepper docs

src/Modal/README.md
<br/><br/><br/><url>LiveURL: https://orbit-components-docs-modal.surge.sh</url>
=> docs: update Modal example for fixed footer

src/SocialButton/README.md, src/SocialButton/SocialButton.stories.js, src/SocialButton/consts.js, src/SocialButton/helpers/getSocialButtonBoxShadow.js, src/SocialButton/helpers/getSocialButtonIcon.js, src/SocialButton/helpers/getSocialButtonTypeToken.js, src/SocialButton/index.d.ts, src/SocialButton/index.js.flow
Adding twitter type as for Figma specs<br/><br/><br/><url>LiveURL: https://orbit-components-new-twitter-social-button.surge.sh</url>
=> feat(SocialButton): adding twitter type

.eslintignore, .eslintrc.js, package.json, src/Button/index.js.flow, src/ButtonLink/helpers/getButtonLinkStyles.js.flow, src/Slider/components/Bar/index.js.flow, src/common/common.js.flow, src/index.js.flow
<br/><br/><br/><url>LiveURL: https://orbit-components-lint-js-flow-files.surge.sh</url>
=> chore: lint .js.flow files as well

src/Modal/README.md, src/Modal/consts.js, src/Modal/index.d.ts, src/Modal/index.js, src/Modal/index.js.flow
<br/><br/><br/><url>LiveURL: https://orbit-components-feat-extrasmall-modal.surge.sh</url>
=> feat(Modal): adding extraSmall size option

src/utils/rtl/index.js.flow
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-rtl-def.surge.sh</url>
=> fix(Rtl): flow definition of destructured assigment

src/Alert/AlertButton/index.d.ts, src/Alert/index.d.ts, src/Heading/index.d.ts, src/Layout/LayoutColumn/index.d.ts, src/ListChoice/index.d.ts, src/ListChoice/index.js.flow, src/Select/index.d.ts, src/Text/index.d.ts, src/Tooltip/index.d.ts, src/common/common.d.ts, src/utils/Grid/index.d.ts, src/utils/mediaQuery/index.d.ts
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-ts-errors.surge.sh</url>
=> fix(Typescript): updating definitions

src/Popover/components/ContentWrapper.js
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-popover-memory-leak.surge.sh</url>
=> fix: popover memory leak

src/hooks/useTheme/index.d.ts
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-usetheme-ts.surge.sh</url>
=> fix(UseTheme): typescript declaration

src/Card/CardSection/index.d.ts
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-cardsection-ts.surge.sh</url>
=> fix(CardSection): typescript type for header prop

src/Table/index.d.ts
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-table-export-ts.surge.sh</url>
=> fix(Table): typescript default export

src/common/common.d.ts
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-ts-component.surge.sh</url>
=> fix(Typescript): definition of component common type

.browserslistrc, .github/contribution/testing-conventions.md, babel.config.js, config/eslintJS.js, markdown.config.js, package.json, yarn.lock
Added a company-wide browser list to the project so we can run tests on it and see if everything behaves as previously 🤞 
Will test it also on few other projects just to ensure that everything behaves the same 😉 
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-supported-browsers.surge.sh</url>
=> fix(Browsers): added kiwicom supported browsers to the project

src/ServiceLogo/README.md, src/ServiceLogo/consts.js
<br/><br/><br/><url>LiveURL: https://orbit-components-feat-icon-elo.surge.sh</url>
=> feat(ServiceLogo): adding elo logo

src/common/common.d.ts
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-ref-ts-type.surge.sh</url>
=> fix(Typescript): common ref type, support callback function

src/Alert/index.d.ts
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-alert-icon-ts.surge.sh</url>
=> fix(Alert): typescript type for icon prop

src/InputFile/index.d.ts, src/SocialButton/index.d.ts, src/primitives/ButtonPrimitive/index.d.ts
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-forwardref-ts.surge.sh</url>
=> fix(Typescript): mismatched use of RefForwardingComponent

src/ButtonMobileStore/ButtonMobileStore.stories.js
<br/><br/><br/><url>LiveURL: https://orbit-components-a11y-mobile-button-store.surge.sh</url>
=> chore(ButtonMobileStore): adding alt to stories

src/primitives/ButtonPrimitive/index.js
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-button-disable.surge.sh</url>
=> fix(ButtonPrimitive): disabled state is not calling onClick

packages/orbit-components/src/ChoiceGroup/__tests__/index.test.js, packages/orbit-components/src/ChoiceGroup/index.js
<br/><br/><br/><url>LiveURL: https://orbit-components-ref-choicegroup.surge.sh</url>
=> refactor(ChoiceGroup): refactoring ChoiceGroup to hooks

lerna.json, packages/orbit-components/CHANGELOG.md
- docs: add missing changelog header
- chore: fix Lerna publish commit message
<br/><br/><br/><url>LiveURL: https://orbit-components-chore-fix-lerna-release.surge.sh</url>
=> chore: lerna fixes

packages/orbit-components/src/ChoiceGroup/ChoiceGroup.stories.js, packages/orbit-components/src/InputField/InputField.stories.js, packages/orbit-components/src/InputGroup/InputGroup.stories.js, packages/orbit-components/src/Select/Select.stories.js
<br/><br/><br/><url>LiveURL: https://orbit-components-ref-error-stories-unification.surge.sh</url>
=> refactor: unification of error and help storybook stories

packages/babel-plugin-orbit-components/package.json
<br/><br/><br/><url>LiveURL: https://orbit-chore-fix-babel-plugin-eslint-error.surge.sh</url>
=> chore: fix ESLint error

.github/workflows/deploy_master.yml
<br/><br/><br/><url>LiveURL: https://orbit-fix-master-deploy.surge.sh</url>
=> chore: fix master deploy token variable

.github/workflows/deploy_master.yml
<br/><br/><br/><url>LiveURL: https://orbit-fix-master-deploy.surge.sh</url>
=> chore: fix master deploy token name

.github/workflows/deploy_master.yml
<br/><br/><br/><url>LiveURL: https://orbit-fix-deploy-setup.surge.sh</url>
=> chore: use github actor for master deploy

packages/orbit-components/src/Alert/index.d.ts, packages/orbit-components/src/SocialButton/index.d.ts, packages/orbit-components/src/TextLink/index.d.ts, packages/orbit-components/src/TextLink/index.js.flow, packages/orbit-components/src/hooks/useTheme/index.d.ts, packages/orbit-components/src/primitives/ButtonPrimitive/index.d.ts
<br/><br/><br/><url>LiveURL: https://orbit-ts-fixes.surge.sh</url>
=> fix:  updating typescript definitions to match flow

packages/orbit-components/src/Layout/LayoutColumn/index.js
Reverts kiwicom/orbit#2181<br/><br/><br/><url>LiveURL: https://orbit-revert-2181-fix-card-edge.surge.sh</url>
=> revert(Layout): width of Card on mobile

packages/orbit-components/src/FormFeedback/index.js
<br/><br/><br/><url>LiveURL: https://orbit-fix-formfeedback-render.surge.sh</url>
=> fix(FormFeedback): render null if error or help is not present

packages/orbit-components/src/InputGroup/index.js
<br/><br/><br/><url>LiveURL: https://orbit-fix-inputgroup-filled.surge.sh</url>
=> fix(InputGroup): filled should be when values are set to all children

packages/babel-plugin-orbit-components/__tests__/__snapshots__/index.test.js.snap, packages/babel-plugin-orbit-components/__tests__/index.test.js, packages/babel-plugin-orbit-components/index.js
<br/><br/><br/><url>LiveURL: https://orbit-tbergq-list-item-babel-plugin.surge.sh</url>
=> feat(BabelPlugin): add import path for ListItem

flow-typed/npm/jest_v26.x.x.js
This adds support for newer matchers from `@testing-library/jest-dom`.<br/><br/><br/><url>LiveURL: https://orbit-chore-update-jest-libdef.surge.sh</url>
=> chore: update Jest libdef

packages/orbit-components/src/Hide/index.js
<br/><br/><br/><url>LiveURL: https://orbit-fix-hide.surge.sh</url>
=> fix(Hide): span to div

.github/contributing.md, .github/contribution/commits.md
- adjust to the monorepo
- don't duplicate guidelines for git commit
- update advice on how to try out development changes
<br/><br/><br/><url>LiveURL: https://orbit-docs-contributing.surge.sh</url>
=> docs: update contribution guidelines

packages/orbit-components/src/Breadcrumbs/BreadcrumbsItem/index.js
[Jira issue](https://jira.kiwi.com/browse/ORBIT-1288)<br/><br/><br/><url>LiveURL: https://orbit-fix-breadcrumbs.surge.sh</url>
=> fix(Breadcrumbs): spacing from 8 to 4

packages/orbit-components/src/Illustration/README.md, packages/orbit-components/src/Illustration/consts.js
[Jira issue](https://jira.kiwi.com/browse/ORBIT-1415?workflowName=0K%3A+To+Do+%7C+In+Progress+%7C+Blocked+%7C+Done&stepId=3)
=> feat(Illustration): added image to images.kiwi

packages/orbit-components/src/Modal/ModalSection/index.js
[slack issue in #plz-orbit](https://skypicker.slack.com/archives/CAMS40F7B/p1598524518004100)<br/><br/><br/><url>LiveURL: https://orbit-fix-modal.surge.sh</url>
=> fix(ModalSection): margin-top

packages/orbit-components/src/TextLink/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-textlink-library.surge.sh</url>
=> test(TextLink): use testing library

packages/babel-plugin-orbit-components/package.json
closes #2368
--------
remove internal dependency (it will use it anyway, but won't affect version bumps)
<br/><br/><br/><url>LiveURL: https://orbit-sampi-fix-2368.surge.sh</url>
=> chore(BabelPlugin): move devDependency to peer

packages/orbit-components/src/Tooltip/index.js
<br/><br/><br/><url>LiveURL: https://orbit-fix-tooltipprimitive.surge.sh</url>
=> fix(Tooltip): missing MobileDialog data-test

package.json, packages/orbit-components/config/checkIcons.js, packages/orbit-components/config/checkIconsCli.js, packages/orbit-components/package.json
<br/><br/><br/><url>LiveURL: https://orbit-improve-check-icons-cli.surge.sh</url>
=> Check icons only in pre-commit and CI

package.json, packages/orbit-components/transforms/TextLink-iconRight.js, packages/orbit-components/transforms/__testfixtures__/TextLink-iconRight.input.js, packages/orbit-components/transforms/__testfixtures__/TextLink-iconRight.output.js, packages/orbit-components/transforms/__tests__/TextLink-iconRight.test.js, yarn.lock
<br/><br/><br/><url>LiveURL: https://orbit-improve-codemod-text-link-icon-right.surge.sh</url>
=> improve(TextLink): add codemod for `iconRight`

package.json, packages/orbit-components/.storybook/orbitDecorator.js, packages/orbit-components/package.json
closes #2346 (again)
related to #2389
<br/><br/><br/><url>LiveURL: https://orbit-sampi-fix-2346.surge.sh</url>
=> refactor(Storybook): hide Code in TEST env

packages/orbit-components/src/ButtonGroup/__tests__/index.test.js, packages/orbit-components/src/ButtonMobileStore/__tests__/index.test.js, packages/orbit-components/src/primitives/ButtonPrimitive/__tests__/index.test.js, packages/orbit-components/src/primitives/ButtonPrimitive/index.js
- fix(ButtonPrimitive): correctly forward ref
- test(ButtonPrimitive): rewrite to Testing Library
- test(ButtonGroup): rewrite to Testing Library
- test(ButtonMobileStore): rewrite to Testing Library
<br/><br/><br/><url>LiveURL: https://orbit-test-testing-library-two.surge.sh</url>
=> Migrate to Testing Library: ButtonPrimitive, ButtonGroup, ButtonMobileStore

.github/contribution/testing-conventions.md
Considering that we're rewriting tests, I think it would be useful to establish some conventions, not only for others but for ourselves. I wrote down some basic stuff, do you have some thoughts and ideas for more?<br/><br/><br/><url>LiveURL: https://orbit-docs-testing-conventions.surge.sh</url>
=> docs: update testing conventions

.github/contribution/README.md
<br/><br/><br/><url>LiveURL: https://orbit-update-contribution-guide.surge.sh</url>
=> chore(Docs): update contribution guide

packages/orbit-components/src/SkipNavigation/SkipNavigation.stories.js
<br/><br/><br/><url>LiveURL: https://orbit-fix-typo-skip-navigation-playground.surge.sh</url>
=> fix(SkipNavigation): fix typos in stories

packages/orbit-components/src/ChoiceGroup/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-testing-librarry-choice-group.surge.sh</url>
=> test(ChoiceGroup): rewrite to Testing Library

packages/orbit-components/src/Collapse/__tests__/index.test.js
The comment about `max-width` has been removed because, even though
Testing Library supports `useEffect`, it's not necessary to test visual
properties of components in unit tests.
<br/><br/><br/><url>LiveURL: https://orbit-test-testing-library-collapse.surge.sh</url>
=> test(Collapse): rewrite to Testing Library

packages/orbit-components/src/ClickOutside/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-testing-library-click-outside.surge.sh</url>
=> test(ClickOutside): rewrite to Testing Library

packages/orbit-components/src/Coupon/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-testing-library-coupon.surge.sh</url>
=> test(Card): rewrite to Testing Library

packages/orbit-components/src/Desktop/__tests__/index.test.js
Simplify test with snapshot testing.
<br/><br/><br/><url>LiveURL: https://orbit-test-testing-library-desktop.surge.sh</url>
=> test(Desktop): rewrite to Testing Library

packages/orbit-components/src/Dialog/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-testing-library-dialog.surge.sh</url>
=> test(Dialog): rewrite to Testing Library

packages/orbit-components/src/Heading/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-testing-library-heading.surge.sh</url>
=> test(Heading): rewrite to Testing Library

packages/orbit-components/src/Hide/__tests__/index.test.js
There was too much logic in the test file, this is a good case for
snapshot testing.
<br/><br/><br/><url>LiveURL: https://orbit-test-testing-library-hide.surge.sh</url>
=> test(Hide): rewrite to Testing Library

packages/orbit-components/src/Illustration/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-testing-library-illustration.surge.sh</url>
=> test(Illustration): rewrite to Testing Library

packages/orbit-components/src/FormLabel/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-testing-library-form-label.surge.sh</url>
=> test(FormLabel): rewrite to Testing Library

packages/orbit-components/src/FormFeedback/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-testing-library-form-feedback.surge.sh</url>
=> test(FormFeedback): rewrite to Testing Library

packages/orbit-components/src/Stack/index.d.ts
[#plz-orbit](https://skypicker.slack.com/archives/CAMS40F7B/p1604277424217200)<br/><br/><br/><url>LiveURL: https://orbit-fix-Stack-types.surge.sh</url>
=> fix(Stack): add forgotten interface export

packages/orbit-components/src/Icon/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-testing-library-icon.surge.sh</url>
=> test(Icon): rewrite to Testing Library

packages/orbit-components/src/Inline/Inline.stories.js, packages/orbit-components/src/Inline/README.md, packages/orbit-components/src/Inline/__tests__/index.test.js, packages/orbit-components/src/Inline/consts.js, packages/orbit-components/src/Inline/helpers.js, packages/orbit-components/src/Inline/index.d.ts, packages/orbit-components/src/Inline/index.js, packages/orbit-components/src/Inline/index.js.flow, packages/orbit-components/src/index.d.ts, packages/orbit-components/src/index.js, packages/orbit-components/src/index.js.flow
Adding an Inline component 
<br/><br/><br/><url>LiveURL: https://orbit-new-inline-component.surge.sh</url>
=> feat: introduce Inline component

packages/orbit-components/src/InputStepper/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-testing-library-input-stepper.surge.sh</url>
=> test(InputStepper): rewrite to Testing Library

packages/orbit-components/src/Stack/index.d.ts
=> fix(Stack): change spacing value TS types

packages/orbit-components/src/Modal/__tests__/index.test.js, packages/orbit-components/src/Modal/index.d.ts, packages/orbit-components/src/Modal/index.js, packages/orbit-components/src/Modal/index.js.flow
<br/><br/><br/><url>LiveURL: https://orbit-fix-modal-ref.surge.sh</url>
=> fix(Modal): expose setScrollPosition via forwardRef

packages/orbit-components/src/Modal/index.d.ts
<br/><br/><br/><url>LiveURL: https://orbit-fix-modal-typedef.surge.sh</url>
=> fix(Modal): fix TypeScript definition for ref

packages/orbit-components/src/Inline/README.md, packages/orbit-components/src/Inline/consts.js, packages/orbit-components/src/Inline/helpers.js, packages/orbit-components/src/Inline/index.d.ts, packages/orbit-components/src/Inline/index.js.flow
<br/><br/><br/><url>LiveURL: https://orbit-fix-Inline.surge.sh</url>
=> fix(Inline): missing space-between and space-around

.github/contribution/testing-conventions.md
I overdid it again, didn't I? 😜
=> docs: add guidelines for visual regression testing

packages/orbit-components/CHANGELOG.md, packages/orbit-components/package.json
- @kiwicom/orbit-components@0.97.0
<br/><br/><br/><url>LiveURL: https://orbit-release.surge.sh</url>
=> chore: publish

packages/orbit-components/src/ListChoice/index.js
[plz-orbit](https://skypicker.slack.com/archives/CAMS40F7B/p1604581597225600)
[jira issue](https://jira.kiwi.com/browse/ORBIT-1472)<br/><br/><br/><url>LiveURL: https://orbit-fix-listChoices.surge.sh</url>
=> fix(ListChoice): Disabled items should not get focus

packages/orbit-components/src/Popover/Popover.stories.js, packages/orbit-components/src/Popover/__tests__/index.test.js, packages/orbit-components/src/Popover/components/ContentWrapper.js
<br/><br/><br/><url>LiveURL: https://orbit-feat-popover-a11y.surge.sh</url>
=> fix(Popover): a11y issues

packages/orbit-components/.storybook/preview.js
<br/><br/><br/><url>LiveURL: https://orbit-fix-storybook-viemport.surge.sh</url>
=> fix(Storybook): add smallMobile viewport

packages/orbit-components/src/Timeline/TimelineStep/components/TimelineStepDesktop.js, packages/orbit-components/src/Timeline/TimelineStep/components/TimelineStepMobile.js, packages/orbit-components/src/Timeline/TimelineStep/index.d.ts, packages/orbit-components/src/Timeline/TimelineStep/index.js.flow
<br/><br/><br/><url>LiveURL: https://orbit-fix-types.surge.sh</url>
=> fix(Timeline): subLabel optional

packages/orbit-components/src/TextLink/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-textlink.surge.sh</url>
=> test(TextLink): rewrite to Testing Library

packages/orbit-components/src/Text/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-text.surge.sh</url>
=> test(Text): rewrite to Testing library

packages/orbit-components/src/Table/__tests__/index.test.js, packages/orbit-components/src/Table/index.js
<br/><br/><br/><url>LiveURL: https://orbit-test-table.surge.sh</url>
=> test(Table): rewrite to Testing library

packages/orbit-components/src/Mobile/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-mobile.surge.sh</url>
=> test(Mobile): rewrite to testing library

packages/orbit-components/src/NavigationBar/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-navigation-bar.surge.sh</url>
=> test(NavigationBar): rewrite to testing library

packages/orbit-components/src/List/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-list.surge.sh</url>
=> test(List): rewrite to testing library

packages/orbit-components/src/Loading/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-loading.surge.sh</url>
=> test(Loading): rewrite to testing library

packages/orbit-components/src/Pagination/README.md, packages/orbit-components/src/Pagination/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-pagination.surge.sh</url>
=> test(Pagination): rewrite to testing library

packages/orbit-components/src/Pagination/__tests__/index.test.js
- group common tests that should work both when Pagination is normal and
compact
- test visibility of labels
<br/><br/><br/><url>LiveURL: https://orbit-test-pagination-breakpoints-and-labels.surge.sh</url>
=> test(Pagination): test labels and breakpoints

packages/orbit-components/src/LinkList/__tests___/index.test.js, packages/orbit-components/src/LinkList/index.js
- fixed `Linklist` a11y issue. [ORBIT-1437](https://jira.kiwi.com/browse/ORBIT-1437)
- rewrote test to testing-library<br/><br/><br/><url>LiveURL: https://orbit-fix-LinkList-a11y.surge.sh</url>
=> LinkList changes

packages/orbit-components/src/RatingStars/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-RatingStars.surge.sh</url>
=> test(RatingStars): rewrite to testing library

packages/orbit-components/src/Radio/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-Radio.surge.sh</url>
=> test(Radio): rewrite to testing library

packages/orbit-components/src/Select/__tests__/Select.test.js, packages/orbit-components/src/Select/index.js.flow
<br/><br/><br/><url>LiveURL: https://orbit-test-Select.surge.sh</url>
=> test(Select): rewrite to testing library

packages/orbit-components/src/SkipNavigation/__tests__/index.test.js, packages/orbit-components/src/SkipNavigation/index.js
<br/><br/><br/><url>LiveURL: https://orbit-test-SkipNavigation.surge.sh</url>
=> test(SkipNavigation): rewrite to testing library

packages/orbit-components/src/Stepper/StepperStateless/index.d.ts, packages/orbit-components/src/Stepper/__tests__/index.test.js
- rewrote tests to testing library<br/><br/><br/><url>LiveURL: https://orbit-test-Stepper.surge.sh</url>
=> test(Stepper): rewrite to testing library

packages/orbit-components/src/ServiceLogo/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-ServiceLogo.surge.sh</url>
=> test(ServiceLogo): rewrite to testing library

packages/orbit-components/src/Popover/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-popover.surge.sh</url>
=> test(Popover): rewrite to testing-library

packages/orbit-components/src/PricingTable/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-PricingTable.surge.sh</url>
=> test(PricingTable): rewrite to testing library

packages/orbit-components/src/Seat/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-seat.surge.sh</url>
=> test(Seat): rewrite to testing library

packages/orbit-components/src/PictureCard/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-picture-card.surge.sh</url>
=> test(PictureCard): rewrite to testing library

commitlint.config.js, packages/orbit-components/src/Modal/README.md, packages/orbit-components/src/Modal/__examples__/SIZES.js, packages/orbit-components/src/Modal/consts.js, packages/orbit-components/src/Modal/index.d.ts, packages/orbit-components/src/Modal/index.js, packages/orbit-components/src/Modal/index.js.flow, packages/orbit-components/transforms/Modal-size.js, packages/orbit-components/transforms/__testfixtures__/Modal-size.input.js, packages/orbit-components/transforms/__testfixtures__/Modal-size.input.tsx, packages/orbit-components/transforms/__testfixtures__/Modal-size.output.js, packages/orbit-components/transforms/__testfixtures__/Modal-size.output.tsx, packages/orbit-components/transforms/__testfixtures__/Stack-spacing.input.js, packages/orbit-components/transforms/__testfixtures__/Stack-spacing.output.js, packages/orbit-components/transforms/__testfixtures__/TextLink-iconRight.input.js, packages/orbit-components/transforms/__testfixtures__/TextLink-iconRight.output.js, packages/orbit-components/transforms/__tests__/Modal-size.test.js
added new size value, as we agreed before. Slack discussion [here](https://skypicker.slack.com/archives/CAMS40F7B/p1606485777342700)<br/><br/><br/><url>LiveURL: https://orbit-feat-modal.surge.sh</url>
=> feat(Modal): extended size

packages/orbit-components/src/Stack/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-stack-to-testing-lib.surge.sh</url>
=> test(Stack): rewrite to testing library

packages/orbit-components/src/NotificationBadge/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-notification-badge.surge.sh</url>
=> test(NotificationBadge): rewrite to testing library

packages/orbit-components/src/Truncate/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-testing-library-truncate.surge.sh</url>
=> test(Truncate): rewrite to Testing Library

packages/orbit-components/src/StopoverArrow/__tests__/index.test.js, packages/orbit-components/src/StopoverArrow/index.js
<br/><br/><br/><url>LiveURL: https://orbit-test-StopoverArrow.surge.sh</url>
=> test(StopoverArrow): rewrite to testling library

packages/orbit-components/src/Slider/__tests__/index.test.js, packages/orbit-components/src/Slider/components/Bar/_tests_/index.test.js, packages/orbit-components/src/Slider/components/Handle/_tests_/index.test.js, packages/orbit-components/src/Slider/components/Histogram/_tests_/index.test.js, packages/orbit-components/src/Slider/components/Histogram/index.js
<br/><br/><br/><url>LiveURL: https://orbit-test-Slider.surge.sh</url>
=> test(Slider): rewrite to testing library

packages/orbit-components/src/Sticky/README.md, packages/orbit-components/src/Sticky/__tests__/index.test.js, packages/orbit-components/src/Sticky/index.d.ts, packages/orbit-components/src/Sticky/index.js, packages/orbit-components/src/Sticky/index.js.flow
<br/><br/><br/><url>LiveURL: https://orbit-test-Sticky.surge.sh</url>
=> test(Sticky): rewrite to testing library

packages/orbit-components/src/TileGroup/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-tilegroup.surge.sh</url>
=> test(Tilegroup): rewrite to testing library

packages/orbit-components/src/Textarea/README.md, packages/orbit-components/src/Textarea/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-test-textarea.surge.sh</url>
=> test(textarea): rewrite to testing library

packages/orbit-components/src/primitives/BadgePrimitive/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-testing-library-badge-primitive.surge.sh</url>
=> test(BadgePrimitive): rewrite to Testing Library

packages/orbit-components/src/Tile/__tests__/index.test.js, packages/orbit-components/src/Tile/components/TileWrapper/index.js, packages/orbit-components/src/Tile/index.js
<br/><br/><br/><url>LiveURL: https://orbit-test-tile.surge.sh</url>
=> test(Tile): rewrite to testing library

packages/orbit-components/src/primitives/IllustrationPrimitive/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-testing-library-illustration-primitive.surge.sh</url>
=> test(IllustrationPrimitive): rewrite to Testing Library

packages/orbit-components/src/deprecated/Card/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-testing-library-deprecated-card.surge.sh</url>
=> test(DeprecatedCard): rewrite to Testing Library

packages/orbit-components/src/deprecated/DestinationCard/_tests_/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-testing-library-deprecated-destination-card.surge.sh</url>
=> test(DeprecatedDestinationCard): rewrite to Testing Library

packages/orbit-components/src/deprecated/DestinationHeader/_tests_/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-testing-library-deprecated-destination-header.surge.sh</url>
=> test(DeprecatedDestinationHeader): rewrite to Testing Library

packages/orbit-components/src/deprecated/Tile/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-testing-library-deprecated-tile.surge.sh</url>
=> test(DeprecatedTile): rewrite to Testing Library

packages/orbit-components/src/deprecated/TripSegment/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-testing-library-deprecated-trip-segment.surge.sh</url>
=> test(DeprecatedTripSegment): rewrite to Testing Library

packages/orbit-components/src/hooks/useIntersect/__tests__/index.test.js
<br/><br/><br/><url>LiveURL: https://orbit-testing-library-use-intersect.surge.sh</url>
=> test(useIntersect): rewrite to Testing Library

package.json, packages/orbit-components/src/examples.test.js, yarn.lock
<br/><br/><br/><url>LiveURL: https://orbit-testing-library-examples.surge.sh</url>
=> test(examples): rewrite to Testing Library

packages/orbit-components/src/InputFile/__tests__/index.test.js, packages/orbit-components/src/InputFile/index.js
<br/><br/><br/><url>LiveURL: https://orbit-test-inputfile.surge.sh</url>
=> test(inputFile): rewrite to testing library

packages/orbit-components/src/Tag/__tests__/index.test.js, packages/orbit-components/src/Tag/index.js
<br/><br/><br/><url>LiveURL: https://orbit-test-tag.surge.sh</url>
=> test(Tag): rewrite to testing library

packages/orbit-components/src/utils/Grid/__tests__/__snapshots__/index.test.js.snap, packages/orbit-components/src/utils/Grid/__tests__/index.test.js
`toHaveStyle` did not work with some styles, i think it's ok to have `toHaveStyleRule` since it will work with `testing-library` too, mediaQueries also did not work without `toHaveStyleRule`. 🤔 <br/><br/><br/><url>LiveURL: https://orbit-test-grid.surge.sh</url>
=> test(Grid): rewrite to testing library

packages/orbit-components/src/Box/README.md
<br/><br/><br/><url>LiveURL: https://orbit-docs-box-display.surge.sh</url>
=> docs(Box): document `display` prop

packages/orbit-components/src/Button/helpers/getButtonTypeToken.js
Request in [plz-orbit](https://skypicker.slack.com/archives/CAMS40F7B/p1607078251385500)<br/><br/><br/><url>LiveURL: https://orbit-fix-button-white.surge.sh</url>
=> fix(Button): change color of outline on focus

docs/src/components/Navbar.tsx, docs/src/hooks/useIsUrlExternal.ts
<br/><br/><br/><url>LiveURL: https://orbit-fix-docs-window.surge.sh</url>
=> fix(docs): window and document SSR

packages/orbit-components/src/Card/Card.stories.js, packages/orbit-components/src/Card/CardSection/index.d.ts, packages/orbit-components/src/Card/CardSection/index.js, packages/orbit-components/src/Card/CardSection/index.js.flow, packages/orbit-components/src/Card/README.md, packages/orbit-components/src/Card/__tests__/index.test.js, packages/orbit-components/src/Card/components/CardWrapper/index.js, packages/orbit-components/src/Card/components/CardWrapper/index.js.flow
- on request in [plz-orbit](https://skypicker.slack.com/archives/CAMS40F7B/p1608222507446600)
i think it might be also request in future, so why not to add it now<br/><br/><br/><url>LiveURL: https://orbit-feat-cardsection-onclick.surge.sh</url>
=> feat(CardSection): add onClick

packages/orbit-components/src/Card/components/CardWrapper/index.js
<br/><br/><br/><url>LiveURL: https://orbit-fix-cardsection-missing-hover.surge.sh</url>
=> fix(CardSection): missing hover

packages/orbit-components/src/Box/index.js
<br/><br/><br/><url>LiveURL: https://orbit-fix-box.surge.sh</url>
=> fix(Box): missing box-sizing

packages/orbit-components/src/Card/Card.stories.js, packages/orbit-components/src/Card/components/Header/index.js
<br/><br/><br/><url>LiveURL: https://orbit-fix-cardsection-title-alignment.surge.sh</url>
=> fix(CardSection): title and icon alignment

packages/orbit-components/src/Wizard/index.js
<br/><br/><br/><url>LiveURL: https://orbit-fix-wizard-close-translation.surge.sh</url>
=> fix(Wizard): translate close button

config/eslintTS.js
<br/><br/><br/><url>LiveURL: https://orbit-improve-ts-eslint-react-hooks.surge.sh</url>
=> improve: add ESLint rules for React hooks to TS

packages/orbit-components/src/Accordion/__examples__/ACTIONS.js, packages/orbit-components/src/Accordion/__examples__/DEFAULT.js, packages/orbit-components/src/Accordion/__examples__/FOOTER.js, packages/orbit-components/src/Accordion/__examples__/NONEXPANDABLE.js, packages/orbit-components/src/Seat/README.md, packages/orbit-components/src/Seat/Seat.stories.js, packages/orbit-components/src/Seat/SeatItem.js, packages/orbit-components/src/Seat/__examples__/LABEL.js, packages/orbit-components/src/Seat/__examples__/LEGEND.js, packages/orbit-components/src/Seat/__examples__/PRICE.js, packages/orbit-components/src/Seat/__examples__/SELECTED.js, packages/orbit-components/src/Seat/__examples__/TYPES.js, packages/orbit-components/src/Seat/__tests__/index.test.js, packages/orbit-components/src/Seat/consts.js, packages/orbit-components/src/Seat/index.d.ts, packages/orbit-components/src/Seat/index.js, packages/orbit-components/src/Seat/index.js.flow, packages/orbit-components/src/examples.js
Added changes to `Seat` component, faced some issues, don't know why, but after copying svgs path etc, they did not work as expected, so i changed them a bit. In order to add text, i used svg's text, aligned them somehow, hope that will be enough. 
<br/><br/><br/><url>LiveURL: https://orbit-feat-new-seat.surge.sh</url>
=> feat(seat): new version of seat component

docs/gatsby-node.js, docs/package.json
Just change and extened our schema a bit<br/><br/><br/><url>LiveURL: https://orbit-feat-graphql-schema.surge.sh</url>
=> docs: extend schema

packages/orbit-components/src/Table/README.md, packages/orbit-components/src/Table/TableCell/consts.js, packages/orbit-components/src/Table/TableCell/index.d.ts, packages/orbit-components/src/Table/TableCell/index.js, packages/orbit-components/src/Table/TableCell/index.js.flow
[plz-orbit-request](https://skypicker.slack.com/archives/CAMS40F7B/p1609941789470800)<br/><br/><br/><url>LiveURL: https://orbit-feat-tablecell-normal.surge.sh</url>
=> feat(TableCell): add normal white-space

packages/orbit-components/src/Popover/Popover.stories.js, packages/orbit-components/src/Popover/README.MD, packages/orbit-components/src/Popover/__tests__/index.test.js, packages/orbit-components/src/Popover/components/ContentWrapper.js, packages/orbit-components/src/Popover/components/ContentWrapper.js.flow, packages/orbit-components/src/Popover/helpers/resolvePopoverHorizontal.js, packages/orbit-components/src/Popover/helpers/resolvePopoverHorizontal.js.flow, packages/orbit-components/src/Popover/helpers/resolvePopoverPosition.js, packages/orbit-components/src/Popover/helpers/resolvePopoverPosition.js.flow, packages/orbit-components/src/Popover/index.d.ts, packages/orbit-components/src/Popover/index.js, packages/orbit-components/src/Popover/index.js.flow
[ORBIT-1436](https://jira.kiwi.com/browse/ORBIT-1436)<br/><br/><br/><url>LiveURL: https://orbit-feat-popover-offset.surge.sh</url>
=> feat(popover): offset

packages/orbit-components/src/Box/__tests__/index.test.js, packages/orbit-components/src/Box/normalize.js
[request in plz-orbit](https://skypicker.slack.com/archives/CAMS40F7B/p1610021752472800)<br/><br/><br/><url>LiveURL: https://orbit-fix-box.surge.sh</url>
=> fix(Box): null values in padding and margin

packages/orbit-components/src/Box/__tests__/index.test.js, packages/orbit-components/src/Box/normalize.js
<br/><br/><br/><url>LiveURL: https://orbit-fix-box-fix-on-fix.surge.sh</url>
=> fix(Box): set padding/marging to 0 if none

packages/eslint-plugin-orbit-components/package.json
<br/><br/><br/><url>LiveURL: https://orbit-fix-script-eslint.surge.sh</url>
=> fix: prepublishOnly script

packages/orbit-components/src/CountryFlag/consts.js
<br/><br/><br/><url>LiveURL: https://orbit-feat-flag-undefined.surge.sh</url>
=> feat(CountryFlag): add "undefined" flag

packages/orbit-components/src/Box/Box.stories.js, packages/orbit-components/src/Box/README.md, packages/orbit-components/src/Box/__tests__/index.test.js, packages/orbit-components/src/Box/index.d.ts, packages/orbit-components/src/Box/index.js.flow, packages/orbit-components/src/Box/normalize.js
request in [plz-orbit](https://skypicker.slack.com/archives/CAMS40F7B/p1610532299499900)<br/><br/><br/><url>LiveURL: https://orbit-feat-minwidth-box.surge.sh</url>
=> feat(Box): add minWidth

packages/orbit-components/src/Card/index.d.ts, packages/orbit-components/src/Heading/index.d.ts
missing `titleAs`, type in `index.d.ts` in `Card`<br/><br/><br/><url>LiveURL: https://orbit-fix-card-missing-type.surge.sh</url>
=> fix(Card): missing titleAs in d.ts

packages/orbit-components/src/primitives/IllustrationPrimitive/__tests__/index.test.js, packages/orbit-components/src/primitives/IllustrationPrimitive/index.js
[from AAAron ](https://skypicker.slack.com/archives/GSGN9BN6Q/p1610723763003800)<br/><br/><br/><url>LiveURL: https://orbit-fix-illustration-empty-string.surge.sh</url>
=> fix(IllustrationPrimitive): allow empty alt

packages/orbit-components/src/Tag/README.md, packages/orbit-components/src/Tag/Tag.stories.js, packages/orbit-components/src/Tag/__tests__/index.test.js, packages/orbit-components/src/Tag/helpers/resolveColor.js, packages/orbit-components/src/Tag/helpers/resolveColor.js.flow, packages/orbit-components/src/Tag/index.d.ts, packages/orbit-components/src/Tag/index.js, packages/orbit-components/src/Tag/index.js.flow
BREAKING CHANGE
- Icon prop removed
- Different colors
- Remove focusing if onClick/onRemove not provided
- rewrote to testing-library
3 commits in the end
I hope i got it right about colors, plz check if it's correct tokens @vepor 
<br/><br/><br/><url>LiveURL: https://orbit-feat-tag.surge.sh</url>
=> Tag component changes

packages/orbit-components/src/Tag/README.md, packages/orbit-components/src/Tag/index.d.ts, packages/orbit-components/src/Tag/index.js, packages/orbit-components/src/Tag/index.js.flow
[request in plz-orbit ](https://skypicker.slack.com/archives/CAMS40F7B/p1611232617003800)<br/><br/><br/><url>LiveURL: https://orbit-feat-tag-ref.surge.sh</url>
=> feat(Tag): add forwardRef

packages/orbit-components/src/Seat/SeatItem.js, packages/orbit-components/src/Seat/index.js
<br/><br/><br/><url>LiveURL: https://orbit-fix-seat-blue.surge.sh</url>
=> fix(Seat): blueDark change to blueNormal

packages/orbit-components/src/Seat/README.md, packages/orbit-components/src/Seat/Seat.stories.js, packages/orbit-components/src/Seat/SeatItem.js, packages/orbit-components/src/Seat/__tests__/index.test.js, packages/orbit-components/src/Seat/consts.js, packages/orbit-components/src/Seat/index.d.ts, packages/orbit-components/src/Seat/index.js, packages/orbit-components/src/Seat/index.js.flow
[Requested changes in #plz-orbit](https://skypicker.slack.com/archives/CAMS40F7B/p1611597280017400)<br/><br/><br/><url>LiveURL: https://orbit-fix-seat-align.surge.sh</url>
=> Seat component changes

packages/orbit-components/src/TextLink/README.md
<br/><br/><br/><url>LiveURL: https://orbit-fix-Textlink.surge.sh</url>
=> docs(Textlink): remove additional sentence

packages/orbit-components/transforms/__testfixtures__/tokens-deprecated.input.js, packages/orbit-components/transforms/__testfixtures__/tokens-deprecated.output.js, packages/orbit-components/transforms/__tests__/tokens-deprecated.test.js, packages/orbit-components/transforms/tokens-deprecated.js, packages/orbit-design-tokens/src/dictionary/build.ts, packages/orbit-design-tokens/src/dictionary/definitions/global/palette/social.json, packages/orbit-design-tokens/src/dictionary/formatters/index.ts, packages/orbit-design-tokens/src/dictionary/formatters/json-tokens.ts, packages/orbit-design-tokens/src/dictionary/utils/is.ts, packages/orbit-design-tokens/src/js/fromPlainObject.ts
- Implemented JSON output of deprecated tokens (marked with `deprecated` and `deprecated-replace` value).
- Implemented new codemod for replacing deprecated tokens – it will require more cases in later phases of refactoring, but works fine now.
=> feat(tokens): output of deprecated tokens

packages/orbit-components/src/PictureCard/index.js
[plz-orbit request](https://skypicker.slack.com/archives/CAMS40F7B/p1612339842076200)
=> fix(PictureCard): label semantic

packages/orbit-design-tokens/src/dictionary/build.ts, packages/orbit-design-tokens/src/dictionary/definitions/foundation/base/border-radius.json, packages/orbit-design-tokens/src/dictionary/definitions/global/border-radius.json, packages/orbit-design-tokens/src/dictionary/transforms/attributes/index.ts, packages/orbit-design-tokens/src/dictionary/transforms/values/index.ts, packages/orbit-design-tokens/src/dictionary/utils/__tests__/is.test.ts, packages/orbit-design-tokens/src/dictionary/utils/is.ts
Added border radius tokens for foundation and global level.
=> feat(tokens): add border radius tokens

docs/src/components/ElevationLevel.tsx
Orbit.kiwi: https://orbit-docs-fix-wrong-ext.surge.sh
Storybook: https://orbit-fix-wrong-ext.surge.sh
=> fix: wrong file ext

packages/orbit-design-tokens/src/dictionary/definitions/foundation/typography.json, packages/orbit-design-tokens/src/dictionary/definitions/global/typography.json
Added typography tokens – fontFamily, fontWeights, fontSize, fontLineHeight to foundation and global tokens.
It follows the new structure, so  #2724 needs to be merged first.
=> feat(tokens): add typography foundation and global tokens

packages/orbit-design-tokens/src/dictionary/definitions/foundation/size.json
Added size foundation tokens that can be used for global tokens (width/height) or variant tokens in the future.
=> feat(tokens): add size foundation tokens

packages/orbit-design-tokens/src/dictionary/definitions/foundation/breakpoints.json, packages/orbit-design-tokens/src/dictionary/definitions/global/breakpoints.json
Added breakpoints to foundation and global tokens. Also added old format `widthBreakpoint...` as deprecated tokens.
=> feat(tokens): add breakpoints to foundation and global tokens

docs/gatsby-config.js, docs/package.json, yarn.lock
Orbit.kiwi: https://orbit-docs-chore-gatsby-svg-plugin.surge.sh
Storybook: https://orbit-chore-gatsby-svg-plugin.surge.sh
=> chore: gatsby-styled-components

docs/package.json, docs/src/components/ImagesDownloadList.tsx, docs/src/data/bizdev-assets.yaml, docs/src/documentation/06-kiwi-use/03-guides/01-bizdev.mdx, yarn.lock
Orbit.kiwi: https://orbit-docs-docs-imagesdownloadlist.surge.sh
Storybook: https://orbit-docs-imagesdownloadlist.surge.sh
=> feat: add ImagesDownloadList component and use

packages/orbit-components/src/Seat/Seat.stories.js, packages/orbit-components/src/Seat/__tests__/index.test.js, packages/orbit-components/src/Seat/components/SeatLegend/index.js, packages/orbit-components/src/Seat/components/SeatNormal.js, packages/orbit-components/src/Seat/components/SeatSmall.js, packages/orbit-components/src/Seat/components/helpers/resolveFillColor.js, packages/orbit-components/src/Seat/index.js
Orbit.kiwi: https://orbit-docs-fix-seat-additional.surge.sh
Storybook: https://orbit-fix-seat-additional.surge.sh
=> fix(Seat): active state, spacing

docs/src/components/IconsList.tsx, docs/src/components/ImagesDownloadList.tsx, docs/src/documentation/02-foundation/07-icons/01-general.mdx, docs/src/utils/common.ts
And use in foundation/icons/ for now (will add to component page later). Not the prettiest list ever, but seems functional.
Orbit.kiwi: https://orbit-docs-docs-iconslist.surge.sh
Storybook: https://orbit-docs-iconslist.surge.sh
=> feat(docs): add IconsList

packages/orbit-components/src/InputStepper/InputStepperStateless/index.js
[Request from plz-orbit](https://skypicker.slack.com/archives/CAMS40F7B/p1613575924242200)
Orbit.kiwi: https://orbit-docs-fix-inputstepper-ff.surge.sh
Storybook: https://orbit-fix-inputstepper-ff.surge.sh
=> fix(InputStepper): missing font-family

packages/orbit-components/src/utils/Slide/index.d.ts, packages/orbit-components/src/utils/Slide/index.js, packages/orbit-components/src/utils/Slide/index.js.flow, packages/orbit-components/src/utils/transition/index.d.ts, packages/orbit-components/src/utils/transition/index.js.flow
Added ability to use different transition speed for Slide component
=> feat(slide): added transitionDuration support

.github/workflows/test.yml, docs/src/components/DocLayout.tsx, docs/src/components/Layout.tsx, docs/src/components/Navbar.tsx, docs/src/components/Navigation/index.tsx, docs/src/components/Sidenav/index.tsx, docs/src/pages/index.tsx, docs/utils/check-links.js
I had to turn off check on CI for dead links, because in navbar we are still have dead links, we can turn on it later, when all links will be ready :) Also it had missing token, so added it on CI from env for that task.
Orbit.kiwi: https://orbit-docs-fix-replace-hook-ssr.surge.sh
Storybook: https://orbit-fix-replace-hook-ssr.surge.sh
=> fix(docs): navbar

docs/plugins/contributors/gatsby-node.js, docs/src/components/Github/Contributor.tsx, docs/src/components/Github/index.tsx
Orbit.kiwi: https://orbit-docs-fix-url-contributors.surge.sh
Storybook: https://orbit-fix-url-contributors.surge.sh
=> fix(Contributors): correct github profile url

docs/src/components/FancyLink.tsx, docs/src/documentation/03-components/03-information/alert/meta.yml, docs/src/mdx-components.tsx, docs/src/pages/mdx-examples.mdx
with an example page. Also includes typography and such. Other components should be added to the page once they're ready.
Orbit.kiwi: https://orbit-docs-docs-mdx-examples.surge.sh
Storybook: https://orbit-docs-mdx-examples.surge.sh
=> docs(docs): document components available in MDX 

docs/src/components/Breadcrumbs.tsx, docs/src/components/DocLayout.tsx, docs/src/components/Layout.tsx, yarn.lock
Orbit.kiwi: https://orbit-docs-feat-docs-breadcrumbs.surge.sh
Storybook: https://orbit-feat-docs-breadcrumbs.surge.sh
=> feat(docs): added breadcrumbs

packages/orbit-components/src/utils/layout/index.js
Orbit.kiwi: https://orbit-docs-fix-get-direction.surge.sh
Storybook: https://orbit-fix-get-direction.surge.sh
=> fix(utils): getDirection

docs/src/snippets/illustration-types.mdx, packages/orbit-components/src/AirportIllustration/__examples__/SIZES.js, packages/orbit-components/src/Illustration/__examples__/SIZES.js, packages/orbit-components/src/Layout/__examples__/BOOKING.js, packages/orbit-components/src/Layout/__examples__/CUSTOM.js, packages/orbit-components/src/Layout/__examples__/MMB.js, packages/orbit-components/src/Layout/__examples__/SEARCH.js, packages/orbit-components/src/SmartPassIllustrations/illustrations/IllustrationWrapper.js, packages/orbit-components/src/primitives/IllustrationPrimitive/__examples__/SIZES.js, packages/orbit-components/src/primitives/IllustrationPrimitive/index.js, packages/orbit-design-tokens/src/dictionary/definitions/component-specific/illustration-height.json
Added component-specific token for height of Illustration components.
=> feat(tokens): implement illustration height specific tokens

packages/orbit-components/src/Box/Box.stories.js
Orbit.kiwi: https://orbit-docs-fix-box-regression-test.surge.sh
Storybook: https://orbit-fix-box-regression-test.surge.sh
=> fix(Box): regression test error

packages/orbit-components/src/index.d.ts
Orbit.kiwi: https://orbit-docs-fix-socialbutton-export.surge.sh
Storybook: https://orbit-fix-socialbutton-export.surge.sh
=> fix(SocialButton): missing export

packages/orbit-components/src/Radio/index.d.ts, packages/orbit-components/src/Radio/index.js, packages/orbit-components/src/Radio/index.js.flow
Found missing type inside Radio `d.ts`. Also, a bit refactored code inside. 
Orbit.kiwi: https://orbit-docs-fix-tooltip-missing-type.surge.sh
Storybook: https://orbit-fix-tooltip-missing-type.surge.sh
=> fix(Radio): missing tooltip type in d.ts

packages/orbit-components/src/index.d.ts
Orbit.kiwi: https://orbit-docs-fix-missing-accordion-export.surge.sh
Storybook: https://orbit-fix-missing-accordion-export.surge.sh
=> fix(Accordion): missing export

packages/orbit-components/src/Timeline/TimelineStep/index.d.ts
Orbit.kiwi: https://orbit-docs-fix-timeline-type.surge.sh
Storybook: https://orbit-fix-timeline-type.surge.sh
=> fix(Timeline): type property inside d.ts

packages/orbit-components/src/ThemeProvider/QueryContext/useMediaQueryContext.js, packages/orbit-components/src/hooks/useMediaQuery/__tests__/index.test.js
Orbit.kiwi: https://orbit-docs-fix-use-media-query-cleanup.surge.sh
Storybook: https://orbit-fix-use-media-query-cleanup.surge.sh
=> fix(useMediaQuery): remove listeners on cleanup

packages/orbit-components/src/Box/README.md
Orbit.kiwi: https://orbit-docs-docs-box-prop.surge.sh
Storybook: https://orbit-docs-box-prop.surge.sh
=> fix(docs): misnamed prop for Box

packages/orbit-components/src/InputFile/index.d.ts
Orbit.kiwi: https://orbit-docs-fix-InputField.surge.sh
Storybook: https://orbit-fix-InputField.surge.sh
=> fix(InputFile): ref ts type

packages/orbit-components/src/SocialButton/helpers/getSocialButtonTypeToken.js, packages/orbit-design-tokens/src/dictionary/definitions/component-specific/alert-button/alert-button-critical-subtle.json, packages/orbit-design-tokens/src/dictionary/definitions/component-specific/alert-button/alert-button-critical.json, packages/orbit-design-tokens/src/dictionary/definitions/component-specific/alert-button/alert-button-info-subtle.json, packages/orbit-design-tokens/src/dictionary/definitions/component-specific/alert-button/alert-button-info.json, packages/orbit-design-tokens/src/dictionary/definitions/component-specific/alert-button/alert-button-success-subtle.json, packages/orbit-design-tokens/src/dictionary/definitions/component-specific/alert-button/alert-button-success.json, packages/orbit-design-tokens/src/dictionary/definitions/component-specific/alert-button/alert-button-warning-subtle.json, packages/orbit-design-tokens/src/dictionary/definitions/component-specific/alert-button/alert-button-warning.json, packages/orbit-design-tokens/src/dictionary/definitions/component-specific/social-button/social-button-apple.json, packages/orbit-design-tokens/src/dictionary/definitions/component-specific/social-button/social-button-facebook.json, packages/orbit-design-tokens/src/dictionary/definitions/component-specific/social-button/social-button-google.json, packages/orbit-design-tokens/src/dictionary/definitions/component-specific/social-button/social-button-twitter.json, packages/orbit-design-tokens/src/dictionary/formatters/json-tokens.ts
Added component-specific tokens for alert-button and social-button components also with deprecated tokens that are semantically related to this two components.
=> feat(tokens): add type variant tokens for alert button and social button

packages/eslint-plugin-orbit-components/package.json
Orbit.kiwi: https://orbit-docs-improve-eslint-postinstall.surge.sh
Storybook: https://orbit-improve-eslint-postinstall.surge.sh
=> improve: build ESLint plugin on every install

packages/orbit-components/src/common/getSpacingToken/README.md
Orbit.kiwi: https://orbit-docs-docs-fix-spacing-token.surge.sh
Storybook: https://orbit-docs-fix-spacing-token.surge.sh
=> fix(docs): remove improper token in enum

.github/workflows/lint-prose.yml
Orbit.kiwi: https://orbit-docs-CollierCZ-patch-1.surge.sh
Storybook: https://orbit-CollierCZ-patch-1.surge.sh
=> fix(ci): lint right files with Vale

package.json, packages/orbit-components/.storybook/manager.js, packages/orbit-components/.storybook/orbitDecorator.js, yarn.lock
Orbit.kiwi: https://orbit-docs-chore-update-emotion.surge.sh
Storybook: https://orbit-chore-update-emotion.surge.sh
=> chore: update emotion

.github/workflows/lint-prose.yml
Due to https://github.com/errata-ai/vale-action/issues/33
=> fix: downgrade Vale version for now

docs/src/components/RocketImage.tsx
fixed the issue of overflowed content, check current master, how it looks like
Orbit.kiwi: https://orbit-docs-fix-overflow.surge.sh
Storybook: https://orbit-fix-overflow.surge.sh
=> fix: orbit.kiwi layout wrapper

packages/orbit-components/src/Breadcrumbs/Breadcrumbs.stories.js
Orbit.kiwi: https://orbit-docs-fix-breadcrumbs.surge.sh
Storybook: https://orbit-fix-breadcrumbs.surge.sh
=> fix(Breadcrumbs): missing action in default story

packages/eslint-plugin-orbit-components/__tests__/useRtl.test.ts, packages/eslint-plugin-orbit-components/src/rules/useRtl.ts
Orbit.kiwi: https://orbit-docs-fix-use-rtl.surge.sh
Storybook: https://orbit-fix-use-rtl.surge.sh
=> fix: use-rtl error messages

docs/package.json, package.json, yarn.lock
Orbit.kiwi: https://orbit-docs-chore-deploy.surge.sh
Storybook: https://orbit-chore-deploy.surge.sh
=> docs: deployment

.eslintrc.js, docs/src/components/DocLayout.tsx, docs/src/components/ImageContainer.tsx, docs/src/pages/mdx-examples.mdx, packages/orbit-components/src/index.d.ts
Orbit.kiwi: https://orbit-docs-docs-image-container.surge.sh
Storybook: https://orbit-docs-image-container.surge.sh
=> feat(docs): add image container

packages/orbit-design-tokens/src/dictionary/definitions/component-specific/heading/heading-font-size.json, packages/orbit-design-tokens/src/dictionary/definitions/component-specific/heading/heading-font-weight.json, packages/orbit-design-tokens/src/dictionary/definitions/component-specific/heading/heading-foreground.json, packages/orbit-design-tokens/src/dictionary/definitions/component-specific/heading/heading-line-height.json
Added component specific tokens for headings – font-size, line-height, font-weight and their deprecated alternatives.
=> feat(tokens): add heading specific tokens

.github/workflows/test_and_deploy.yml, docs/package.json
Storybook: https://orbit-chore-remove-docs-deploy.surge.sh
=> chore: remove docs deploy on surge

docs/gatsby-config.js, docs/package.json, docs/src/components/DocLayout/index.tsx, docs/src/components/Head/index.tsx, docs/src/components/Layout.tsx, docs/src/documentation/01-getting-started/01-for-designers/meta.yml, docs/src/documentation/01-getting-started/02-for-developers.mdx, docs/src/documentation/01-getting-started/03-github.mdx, docs/src/documentation/01-getting-started/04-support/meta.yml, docs/src/documentation/02-foundation/01-principles/meta.yml, docs/src/documentation/02-foundation/03-border-radiuses.mdx, docs/src/documentation/02-foundation/05-design-tokens.mdx, docs/src/documentation/02-foundation/06-elevation.mdx, docs/src/documentation/02-foundation/09-spacing.mdx, docs/src/documentation/04-design-patterns/02-action-components.mdx, docs/src/documentation/04-design-patterns/03-designing-forms.mdx, docs/src/documentation/05-development/01-guides/01-developing-layouts.mdx, docs/src/documentation/05-development/01-guides/02-dictionary.mdx, docs/src/documentation/05-development/01-guides/04-no-exporting-components.mdx, docs/src/documentation/05-development/01-guides/05-eslint-plugin.mdx, docs/src/documentation/05-development/02-utilities/01-media-queries.mdx, docs/src/documentation/05-development/02-utilities/02-rtl-languages.mdx, docs/src/documentation/05-development/03-hooks/usefocustrap.mdx, docs/src/documentation/05-development/03-hooks/usemediaquery.mdx, docs/src/documentation/06-kiwi-use/03-guides/02-preparing-carrier-logos.mdx, docs/src/pages/component-status.mdx, docs/src/pages/index.tsx, docs/src/pages/mdx-examples.mdx, docs/src/utils/document.ts, yarn.lock
Storybook: https://orbit-docs-page-meta.surge.sh
=> docs: add page title & description

packages/orbit-components/src/BaggageStepper/index.js
Storybook: https://orbit-fix-baggage-stepper.surge.sh
=> fix(BaggageStepper): forgotten prop

docs/src/components/Footer.tsx, docs/src/components/HeadingWithLink.tsx, docs/src/components/Navbar.tsx, docs/src/components/ReactExample/Board.tsx, docs/src/components/ScreenReaderText.tsx, docs/src/components/Switch.tsx, docs/src/components/Tile.tsx, docs/src/pages/index.tsx
I tried to get some quick fixes for accessibility issues identified by https://wave.webaim.org/
This doesn't address the many contrast issues (secondary text on a cloud background, product colors against themselves and against white, white text on a success background, and more)
Storybook: https://orbit-fix-accessibility.surge.sh
=> fix: accessibility issues for docs

packages/orbit-components/src/Popover/Popover.stories.js, packages/orbit-components/src/Popover/__tests__/index.test.js, packages/orbit-components/src/Popover/components/ContentWrapper.js, packages/orbit-components/src/primitives/MobileDialogPrimitive/__tests__/index.test.js, packages/orbit-components/src/primitives/MobileDialogPrimitive/components/DialogContent.js
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1620918962337700)
I've created the story, [that you can check if it works](https://orbit-fix-popover-split-renders.surge.sh/?path=/story/popover--with-tooltip)
Storybook: https://orbit-fix-popover-split-renders.surge.sh
=> fix(popover): close on overlay

packages/orbit-components/src/HorizontalScroll/index.js
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1620982969344600)
Storybook: https://orbit-fix-horizontall-scroll.surge.sh
=> fix(HorizontalScroll): remove automatic height calculation for wrapper

.github/workflows/lint-prose.yml, docs/src/__examples__/BadgeList/critical.tsx, docs/src/__examples__/BadgeList/default.tsx, docs/src/__examples__/BadgeList/info.tsx, docs/src/__examples__/BadgeList/neutral.tsx, docs/src/__examples__/BadgeList/progressive-disclosure.tsx, docs/src/__examples__/BadgeList/success.tsx, docs/src/__examples__/BadgeList/warning.tsx, docs/src/data/component-status.yaml, docs/src/documentation/03-components/03-information/badgelist/01-guidelines.mdx, docs/src/documentation/03-components/03-information/badgelist/02-react.mdx, docs/src/documentation/03-components/03-information/badgelist/meta.yml
Based on #2937
Storybook: https://orbit-docs-add-badgelist.surge.sh
=> docs: add BadgeList

.github/workflows/lint-prose.yml
Hopefully temporary solution to errata-ai/vale-action#39
Storybook: https://orbit-fix-vale.surge.sh
=> ci: touch markdown file in prose lint

packages/orbit-components/src/Text/index.js, packages/orbit-components/src/TextLink/README.md, packages/orbit-components/src/TextLink/TextLink.stories.js, packages/orbit-components/src/TextLink/consts.js, packages/orbit-components/src/TextLink/index.d.ts, packages/orbit-components/src/TextLink/index.js, packages/orbit-components/src/TextLink/index.js.flow
Orbit.kiwi: https://orbit-docs-feat-texlink-status.surge.sh
Storybook: https://orbit-feat-texlink-status.surge.sh
=> feat(TextLink): add status types

docs/src/__examples__/Alert/ACTIONS_SIDEBYSIDE.tsx, docs/src/documentation/03-components/01-action/buttonlink/01-guidelines.mdx, docs/src/documentation/03-components/01-action/textlink/01-guidelines.mdx, docs/src/documentation/03-components/03-information/alert/01-guidelines.mdx, docs/src/documentation/04-design-patterns/02-action-components.mdx
Storybook: https://orbit-docs-update-action-guide.surge.sh
=> docs: update guidance for action components

docs/src/components/DocLayout/index.tsx
Storybook: https://orbit-fix-inline-token.surge.sh
=> fix: remove extra InlineToken shortcode

packages/orbit-components/src/Illustration/README.md, packages/orbit-components/src/Illustration/consts.js
Storybook: https://orbit-feat-ground-transport.surge.sh
=> feat(Illustration): add GroundTransport404

packages/orbit-components/src/CarrierLogo/README.md, packages/orbit-components/src/CarrierLogo/consts.js, packages/orbit-components/src/CarrierLogo/index.js.flow, packages/orbit-components/src/common/common.d.ts
[Original request thread](https://skypicker.slack.com/archives/CAMS40F7B/p1621012917349400)
Storybook: https://orbit-feat-carrier-logo-kiwicom.surge.sh
=> feat(CarrierLogo): add kiwicom type fallback

docs/src/components/Footer.tsx
so it's not covered
Storybook: https://orbit-docs-fix-image-height.surge.sh
=> fix: free footer on home page

packages/orbit-components/src/CarrierLogo/__tests__/index.test.js, packages/orbit-components/src/CarrierLogo/index.js
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1622616584035800)
Storybook: https://orbit-fix-carrier-logo.surge.sh
=> fix(CarrierLogo): redirects

docs/src/documentation/04-design-patterns/02-action-components.mdx
Storybook: https://orbit-proofreading.surge.sh
=> fix: proofreading

docs/src/components/Footer.tsx
Storybook: https://orbit-docs-remove-changelog-link.surge.sh
=> docs: remove changelog link until we implement it

packages/orbit-components/src/TextLink/README.md, packages/orbit-components/src/TextLink/TextLink.stories.js, packages/orbit-components/src/TextLink/consts.js, packages/orbit-components/src/TextLink/index.d.ts, packages/orbit-components/src/TextLink/index.js, packages/orbit-components/src/TextLink/index.js.flow
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1624629038117800).
Storybook: https://orbit-feat-TextLink-white.surge.sh
=> feat(TextLink): add type "white"

docs/src/documentation/01-getting-started/meta.yml, docs/src/documentation/02-foundation/meta.yml, docs/src/documentation/03-components/01-action/meta.yml, docs/src/documentation/03-components/02-structure/meta.yml, docs/src/documentation/03-components/03-information/meta.yml, docs/src/documentation/03-components/04-overlay/meta.yml, docs/src/documentation/03-components/05-input/meta.yml, docs/src/documentation/03-components/06-accessibility/meta.yml, docs/src/documentation/03-components/07-interaction/meta.yml, docs/src/documentation/03-components/08-visuals/meta.yml, docs/src/documentation/03-components/09-text/meta.yml, docs/src/documentation/03-components/10-progress-indicators/meta.yml, docs/src/documentation/03-components/11-navigation/meta.yml, docs/src/documentation/03-components/12-layout/meta.yml, docs/src/documentation/03-components/13-responsive/meta.yml, docs/src/documentation/03-components/14-utility/meta.yml, docs/src/documentation/03-components/15-primitives/meta.yml, docs/src/documentation/03-components/meta.yml, docs/src/documentation/04-design-patterns/meta.yml, docs/src/documentation/05-development/01-guides/meta.yml, docs/src/documentation/05-development/02-utilities/meta.yml, docs/src/documentation/05-development/03-hooks/meta.yml, docs/src/documentation/05-development/meta.yml, docs/src/documentation/06-kiwi-use/01-brand/meta.yml, docs/src/documentation/06-kiwi-use/02-content/04-specific-areas/meta.yml, docs/src/documentation/06-kiwi-use/02-content/meta.yml, docs/src/documentation/06-kiwi-use/03-guides/meta.yml, docs/src/documentation/06-kiwi-use/meta.yml
Storybook: https://orbit-docs-overview-descriptions.surge.sh
=> feat: add descriptions for overview pages

docs/src/components/VisualList.tsx
Storybook: https://orbit-docs-fix-visual-list-search.surge.sh
=> fix: fix searching illustrations and icons

docs/gatsby-config.js, docs/src/components/Footer.tsx
Storybook: https://orbit-docs-pkg-versions.surge.sh
=> fix: use real package versions

docs/src/components/DocLayout/index.tsx, docs/src/components/TableOfContents.tsx, docs/src/services/table-of-contents.tsx
Storybook: https://orbit-fix-clean-table-of-contents.surge.sh
=> fix: clean table of contents between pages

docs/gatsby-config.js, docs/package.json, yarn.lock
Storybook: https://orbit-docs-ga-analytics.surge.sh
=> feat: track with Google Analytics

docs/src/documentation/03-components/01-action/button/01-guidelines.mdx, docs/src/documentation/04-design-patterns/02-action-components.mdx
Storybook: https://orbit-docs-button-frame.surge.sh
=> fix(docs): fix iframe width and add button states frame

docs/plugins/contributors/fetchedUsers.json, docs/src/components/Tile.tsx, docs/src/services/table-of-contents.tsx, docs/src/templates/Overview.tsx
Storybook: https://orbit-docs-fixes-overview.surge.sh
=> docs: fix overview inner spacing

docs/src/components/Footer.tsx, docs/src/mdx-components.tsx
[Slack thread](https://skypicker.slack.com/archives/CAMS40F7B/p1626212264189900)
Storybook: https://orbit-docs-fix-shadow.surge.sh
=> docs: fix Safari related bugs

docs/package.json, docs/src/components/Navbar.tsx, yarn.lock
=> feat(sandbox): github stars button

docs/package.json, docs/plugins/contributors/gatsby-node.js, docs/src/__examples__/Textarea/REF.tsx, docs/src/components/Navbar.tsx, docs/src/components/Search/SearchButton.tsx, docs/src/components/Search/primitives/StyledPrefix.ts, docs/src/pages/index.tsx, docs/src/services/KeyboardProvider.tsx, docs/wrap-with-providers.tsx, yarn.lock
Will suggested adding a feature to open the `SearchModal` by keyboard navigation by `cmd+k` or `cmd+f` 🤔  
Storybook: https://orbit-feat-keyboard-search.surge.sh
=> feat(docs): open search by keyboard

docs/src/components/Search/SearchButton.tsx
Storybook: https://orbit-search-button-update-1.surge.sh
=> fix(docs): update keyboard shortcut

docs/src/components/DocLayout/index.tsx
Storybook: https://orbit-fix-gradient-overview-pages.surge.sh
=> fix: always add footer gradient in document layout

packages/orbit-design-tokens/src/dictionary/build.ts, packages/orbit-design-tokens/src/dictionary/definitions/component-specific/heading/heading-line-height.json, packages/orbit-design-tokens/src/dictionary/formatters/json-tokens.ts, packages/orbit-design-tokens/src/dictionary/utils/is.ts, packages/orbit-design-tokens/src/theo/theo-spec.json
It will be used for the old documentation site.
=> feat(tokens): add old theo spec file for old documentation

packages/orbit-components/src/utils/Grid/Grid.stories.js, packages/orbit-components/src/utils/Grid/README.md, packages/orbit-components/src/utils/Grid/helpers/getViewportGridStyles.js, packages/orbit-components/src/utils/Grid/helpers/getViewportGridStyles.js.flow, packages/orbit-components/src/utils/Grid/index.d.ts, packages/orbit-components/src/utils/Grid/index.js, packages/orbit-components/src/utils/Grid/index.js.flow
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1626438673216500)
Storybook: https://orbit-feat-grid-space-after.surge.sh
=> feat(Grid): add spaceAfter utility prop

packages/orbit-components/src/Text/README.md, packages/orbit-components/src/Text/__examples__/ALIGN.js, packages/orbit-components/src/Text/consts.js, packages/orbit-components/src/Text/index.d.ts, packages/orbit-components/src/Text/index.js.flow
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1626959505230100).
Storybook: https://orbit-silvenon-feat-text-align-justify.surge.sh
=> feat(Text): add `justify` value to `align` prop

packages/orbit-components/src/Wizard/README.md, packages/orbit-components/src/Wizard/index.d.ts, packages/orbit-components/src/Wizard/index.js, packages/orbit-components/src/Wizard/index.js.flow
add option to turn off locking of scroll inside `Wizard`
Storybook: https://orbit-silvenon-fix-modal-header-on-ios.surge.sh
=> feat(Wizard): add lockScrolling prop

packages/orbit-components/src/Drawer/README.md, packages/orbit-components/src/Drawer/index.d.ts, packages/orbit-components/src/Drawer/index.js, packages/orbit-components/src/Drawer/index.js.flow
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1628675074018400)
Storybook: https://orbit-silvenon-feat-drawer-lock.surge.sh
=> feat(Drawer): add lockScrolling

packages/orbit-components/src/Illustration/README.md, packages/orbit-components/src/Illustration/consts.js
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1630419795030100)
Storybook: https://orbit-silvenon-feat-add-new-illustration.surge.sh
=> feat(Illustration): add EVisa image

docs/plugins/sandbox/gatsby/create-schema-customization.js, docs/plugins/sandbox/gatsby/on-create-page.js, docs/plugins/sandbox/gatsby/on-source-nodes.js, docs/src/__examples__/Box/DEFAULT.tsx, docs/src/__examples__/Button/ICONS.tsx, docs/src/__examples__/Button/TYPES.tsx, docs/src/components/ReactExample/Example.tsx, docs/src/components/ReactExample/components/Board.tsx, docs/src/components/ReactExample/components/Variants.tsx, docs/src/components/ReactExample/components/ViewportsRuler.tsx, docs/src/components/ReactExample/index.tsx, docs/src/components/Search/SearchModal.tsx, docs/src/documentation/03-components/01-action/button/01-guidelines.mdx, docs/src/templates/Sandbox/index.tsx, packages/orbit-components/src/Popover/components/ContentWrapper.js
Currently depends on #3108. Had to merge that branch here. I'll rebase it later after your review. Added variants only for button now. 
Storybook: https://orbit-silvenon-docs-variants.surge.sh
=> docs(sandbox): variants feature

packages/orbit-components/src/Skeleton/Skeleton.stories.js, packages/orbit-components/src/Skeleton/Svg.js, packages/orbit-components/src/Skeleton/helpers.js
Set the default children as `rect`, if children or rows are not passed. 
Storybook: https://orbit-silvenon-fix-skeleton-height.surge.sh
=> fix(Skeleton): default as single rect

docs/src/components/RocketImage.tsx, docs/src/pages/index.tsx
[Jira ticket](https://jira.kiwi.com/browse/ORBIT-1935)
Storybook: https://orbit-silvenon-docs-remove-image-on-mobile.surge.sh
=> docs: remove rocket image on mobile

packages/orbit-components/config/checkIcons.js
The advice to redraw the icon isn't practical, at least I don't know what that means, but fortunately there's a Figma plugin that solves this problem!
Storybook: https://orbit-silvenon-improve-fill-rule-plugin.surge.sh
=> improve: log solution for `fill-rule="evenodd"`

packages/orbit-design-tokens/package.json
😅 😅 😅
Storybook: https://orbit-silvenon-chore-tokens-publish.surge.sh
=> fix: restore missing ESM build

packages/orbit-components/src/SmartPassIllustrations/illustrations/SmartPassV1.jsx
Small visual bug in svg because of the same id. 
Storybook: https://orbit-silvenon-fix-smartpass-v1.surge.sh
=> fix(SmartPassIllustration): fix double id

packages/orbit-components/src/Modal/Modal.stories.jsx
Being able to close the Modals makes it possible to actually see the code behind them.
Storybook: https://orbit-silvenon-improve-modal-stories-closable.surge.sh
=> improve: make Modals closable in Storybook

packages/orbit-components/src/Checkbox/index.jsx, packages/orbit-components/src/ErrorFormTooltip/Tooltip/helpers/__tests__/resolveColor.test.js, packages/orbit-components/src/ErrorFormTooltip/Tooltip/helpers/resolveColor.js, packages/orbit-components/src/ErrorFormTooltip/Tooltip/index.jsx, packages/orbit-components/src/FormLabel/index.jsx, packages/orbit-components/src/Radio/index.jsx
Tickets:
- [ORBIT-1981](https://jira.kiwi.com/browse/ORBIT-1981)
- [ORBIT-1978](https://jira.kiwi.com/browse/ORBIT-1978)
- [ORBIT-1985](https://jira.kiwi.com/browse/ORBIT-1985)
- [ORBIT-1986](https://jira.kiwi.com/browse/ORBIT-1986)
Changes:
- fix border width and radius in Checkbox
- fix background color in help tooltip
- fix tooltip's padding
- increase font weight of labels
- lower Radio's focus glow amount
Storybook: https://orbit-silvenon-fix-form-elements-ui-discrepancies.surge.sh
=> Fix UI discrepancies in form components

docs/src/components/Search/SearchModal.tsx
[ORBIT-1972](https://jira.kiwi.com/browse/ORBIT-1972)
Storybook: https://orbit-silvenon-feat-tracking-global-search.surge.sh
=> feat(tracking): add search via props

.github/contribution/commits.md
- briefly explain why it's important to have good commit messages
- add a more realistic example of a bad commit message, with an
explanation what's wrong
- emphasize that we're using commit messages to generate changelogs, so
it's important to think about that as well
Storybook: https://orbit-silvenon-docs-commit-message-changelog-aspect.surge.sh
=> docs: improve guidelines for commit messages

packages/orbit-components/src/Toast/index.d.ts, packages/orbit-components/src/Toast/index.jsx.flow
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1642089548062000)
Storybook: https://orbit-silvenon-fix-toast-type.surge.sh
=> fix(Toast): fix message type

packages/orbit-components/src/Tag/README.md, packages/orbit-components/src/Tag/Tag.stories.jsx, packages/orbit-components/src/Tag/consts.js, packages/orbit-components/src/Tag/helpers/resolveCircleColor.js, packages/orbit-components/src/Tag/helpers/resolveCircleColor.js.flow, packages/orbit-components/src/Tag/helpers/resolveColor.js, packages/orbit-components/src/Tag/index.d.ts, packages/orbit-components/src/Tag/index.jsx, packages/orbit-components/src/Tag/index.jsx.flow
[Figma](https://www.figma.com/file/Y79I18H9w8HJZVxPdAkAHb/%5BOrbit%5D-Desktop-Components?node-id=1324%3A0)
Storybook: https://orbit-silvenon-feat-tag-adjustments.surge.sh
=> feat(Tag): add new colors and props

docs/__tests__/gatsby-node.test.js, package.json, packages/orbit-components/src/Toast/ToastMessage.jsx, packages/orbit-components/src/Toast/ToastRoot.jsx, packages/orbit-components/src/Toast/__tests__/index.test.jsx, packages/orbit-components/src/Toast/consts.js, packages/orbit-components/src/Toast/hooks/useSwipe.js, packages/orbit-components/src/Toast/index.d.ts, packages/orbit-components/src/Toast/index.jsx, packages/orbit-components/src/Toast/index.jsx.flow, packages/orbit-tracking/package.json, yarn.lock
https://github.com/timolins/react-hot-toast/issues/107#issuecomment-1017213020
I solved the problem by memoizing the ref, so it doesn't create a new one on every render, avoiding continuously updating state in react-hot-toast.
Storybook: https://orbit-silvenon-fix-toast-infinite-loop-jsdom.surge.sh
=> fix(Toast): fix infinite loop in unit tests

docs/src/components/ReactExample/components/ViewportsRuler.tsx, docs/src/utils/storage.ts
Solves [ORBIT-1888](https://jira.kiwi.com/browse/ORBIT-1888)
Storybook: https://orbit-silvenon-docs-remember-viewport.surge.sh
=> docs(sandbox): remember picked viewport

packages/orbit-components/src/InputGroup/index.jsx
[slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1643284689073969)
Storybook: https://orbit-silvenon-fix-inputgroup-labels.surge.sh
=> fix(InputGroup): fix issue with long labels

packages/orbit-components/src/primitives/TooltipPrimitive/TooltipPrimitive.stories.jsx, packages/orbit-components/src/primitives/TooltipPrimitive/helpers/resolveArrow.js
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1643794671447589)
Storybook: https://orbit-silvenon-fix-tooltip-primitive-rtl.surge.sh
=> fix(TooltipPrimitive): fix arrow positioning for RTL

.github/workflows/tracking-remove.yml, .github/workflows/tracking-update.yml, package.json
Added another cron job to ci, so it will delete old tracking files
Storybook: https://orbit-silvenon-feat-tracking-delete-old-data.surge.sh
=> docs(tracking): add clean up script

docs/src/__examples__/HorizontalScroll/default.tsx, packages/orbit-components/src/HorizontalScroll/HorizontalScroll.stories.jsx, packages/orbit-components/src/HorizontalScroll/README.md, packages/orbit-components/src/HorizontalScroll/__tests__/useScroll.test.js, packages/orbit-components/src/HorizontalScroll/index.d.ts, packages/orbit-components/src/HorizontalScroll/index.jsx, packages/orbit-components/src/HorizontalScroll/index.jsx.flow, packages/orbit-components/src/HorizontalScroll/useScroll.js, packages/orbit-components/src/Itinerary/Itinerary.stories.jsx, packages/orbit-components/src/Itinerary/ItinerarySegment/ItinerarySegmentDetail/index.jsx
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1642759474112400)
Storybook: https://orbit-silvenon-fix-overflowing-badges-itinerary.surge.sh
=> fix(Itinerary): fix overflowing badges

docs/src/__examples__/Drawer/DEFAULT.tsx, packages/orbit-components/src/Drawer/Drawer.stories.jsx, packages/orbit-components/src/Drawer/README.md, packages/orbit-components/src/Drawer/index.d.ts, packages/orbit-components/src/Drawer/index.jsx, packages/orbit-components/src/Drawer/index.jsx.flow
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1643974288562359)
Storybook: https://orbit-silvenon-feat-drawer-sticky-header.surge.sh
=> feat(Drawer): add fixedHeader prop

docs/src/__examples__/Alert/DEFAULT.tsx, packages/orbit-components/src/Alert/Alert.stories.jsx, packages/orbit-components/src/Alert/AlertButton/consts.js, packages/orbit-components/src/Alert/AlertButton/helpers/getAlertButtonTypeToken.js, packages/orbit-components/src/Alert/AlertButton/index.jsx, packages/orbit-components/src/Alert/README.md, packages/orbit-components/src/Alert/consts.js, packages/orbit-components/src/Alert/index.d.ts, packages/orbit-components/src/Alert/index.jsx, packages/orbit-components/src/Alert/index.jsx.flow
[ORBIT-2051](https://jira.kiwi.com/browse/ORBIT-2051)
=> feat(Alert): visual alert component updates

docs/plugins/contributors/users.json, docs/plugins/dashboard/gatsby-node.js, docs/plugins/dashboard/gatsby/onPreInit.js, docs/services/component-statuses.js, docs/src/data/component-status.yaml
It's better to automate the android and ios component statuses and merge them with our statuses.
Storybook: https://orbit-silvenon-feat-component-statuses.surge.sh
=> docs: component statuses

docs/src/__examples__/NavigationBar/DEFAULT.tsx, packages/orbit-components/src/NavigationBar/NavigationBar.stories.jsx, packages/orbit-components/src/NavigationBar/README.md, packages/orbit-components/src/NavigationBar/index.d.ts, packages/orbit-components/src/NavigationBar/index.jsx, packages/orbit-components/src/NavigationBar/index.jsx.flow
solves #2906 
Storybook: https://orbit-silvenon-feat-navbar-hideonscroll.surge.sh
=> feat(NavigationBar): add prop hideOnScroll 

packages/orbit-components/src/Tag/index.jsx
[Slack request](https://skypicker.slack.com/archives/CDHF6FPEJ/p1644911534550239)
Storybook: https://orbit-silvenon-fix-tag-focus-state.surge.sh
=> fix(Tag): fix persistant focus

packages/orbit-components/src/Popover/components/ContentWrapper.jsx
`Popper` threw warning on mobile about transition
Storybook: https://orbit-silvenon-fix-popover-actions.surge.sh
=> refactor(Popover): remove popper warning on mobile

packages/orbit-components/src/Card/components/Header/index.jsx, packages/orbit-components/src/Collapse/index.jsx, packages/orbit-components/src/Itinerary/ItinerarySegment/ItinerarySegmentDetail/index.jsx, packages/orbit-components/src/Select/index.jsx, packages/orbit-components/src/Tile/components/TileHeader/index.jsx
[ORBIT-2058](https://jira.kiwi.com/browse/ORBIT-2058)
=> fix: change chevron colors in different components

packages/orbit-components/src/Itinerary/Itinerary.stories.jsx, packages/orbit-components/src/Itinerary/ItinerarySegment/ItinerarySegmentDetail/index.d.ts, packages/orbit-components/src/Itinerary/ItinerarySegment/ItinerarySegmentDetail/index.jsx, packages/orbit-components/src/Itinerary/ItinerarySegment/ItinerarySegmentDetail/index.jsx.flow
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1646666547618649)
Storybook: https://orbit-silvenon-feat-itinerary-upd.surge.sh
=> fix(ItinerarySegmentDetail): expandable, only if content is provided

packages/orbit-components/src/Tag/index.jsx
[ORBIT-2056](https://jira.kiwi.com/browse/ORBIT-2056)
Storybook: https://orbit-silvenon-fix-tag-remove-icon.surge.sh
=> fix(Tag): selected circle color

packages/orbit-components/src/Switch/index.jsx
[ORBIT-2077](https://jira.kiwi.com/browse/ORBIT-2077)
Storybook: https://orbit-silvenon-fix-switch.surge.sh
=> fix(Switch): update size of Switch component

packages/orbit-components/src/SocialButton/README.md, packages/orbit-components/src/SocialButton/SocialButton.stories.jsx, packages/orbit-components/src/SocialButton/consts.js, packages/orbit-components/src/SocialButton/helpers/getSocialButtonBoxShadow.js, packages/orbit-components/src/SocialButton/helpers/getSocialButtonIcon.jsx, packages/orbit-components/src/SocialButton/helpers/getSocialButtonStyles.js, packages/orbit-components/src/SocialButton/helpers/getSocialButtonTypeToken.js, packages/orbit-components/src/SocialButton/index.d.ts, packages/orbit-components/src/SocialButton/index.jsx, packages/orbit-components/src/SocialButton/index.jsx.flow
[ORBIT-1992](https://jira.kiwi.com/browse/ORBIT-1992)
Storybook: https://orbit-silvenon-fix-socialbutton.surge.sh
=> feat(SocialButton): add type email and change layout

packages/orbit-components/src/primitives/ButtonPrimitive/index.jsx
[Slack issue](https://skypicker.slack.com/archives/CA76NCSUU/p1652857907450969)
Storybook: https://orbit-mainframev-fix-button-primitive-css-specifity.surge.sh
=> fix(ButtonPrimitive): prevent appearance css specifity issue

packages/orbit-components/src/ButtonMobileStore/ButtonMobileStore.stories.jsx, packages/orbit-components/src/ButtonMobileStore/README.md, packages/orbit-components/src/ButtonMobileStore/consts.js, packages/orbit-components/src/ButtonMobileStore/index.d.ts, packages/orbit-components/src/ButtonMobileStore/index.jsx, packages/orbit-components/src/ButtonMobileStore/index.jsx.flow
BREAKING CHANGE
`variant` prop was removed
[ORBIT-1976](https://jira.kiwi.com/browse/ORBIT-1976)
Storybook: https://orbit-silvenon-fix-buttonmobilestore.surge.sh
=> feat(ButtonMobileStore): add lang prop

docs/src/__examples__/Illustration/DEFAULT.tsx, packages/orbit-components/src/Illustration/consts.js
[ORBIT-2148](https://jira.kiwi.com/browse/ORBIT-2148)
Storybook: https://orbit-mainframev-feat-illustration-app-kiwi.surge.sh
=> feat(illustration): add AppKiwi illustration

packages/orbit-components/src/Switch/index.jsx
[ORBIT-2146](https://jira.kiwi.com/browse/ORBIT-2146)
Storybook: https://orbit-mainframev-fix-switch.surge.sh
=> fix(Switch): make circle icon to be 8px

packages/orbit-components/src/hooks/useIntersect/README.md, packages/orbit-components/src/hooks/useIntersect/index.d.ts, packages/orbit-components/src/hooks/useIntersect/index.js, packages/orbit-components/src/hooks/useIntersect/index.js.flow
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1656332161929049)
Storybook: https://orbit-mainframev-feat-export-observer.surge.sh
=> feat(useIntersect): export observer

docs/src/__examples__/Timeline/DEFAULT.tsx, packages/orbit-components/src/Timeline/README.md, packages/orbit-components/src/Timeline/Timeline.stories.jsx, packages/orbit-components/src/Timeline/TimelineStep/components/TimelineStepDesktop.jsx, packages/orbit-components/src/Timeline/TimelineStep/components/TimelineStepMobile.jsx, packages/orbit-components/src/Timeline/TimelineStep/index.d.ts, packages/orbit-components/src/Timeline/TimelineStep/index.jsx, packages/orbit-components/src/Timeline/TimelineStep/index.jsx.flow
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1657205558278469)
=> feat(Timeline): add asText property

docs/src/data/component-status.yaml
- Automatically generated PR.
- Check component statuses updates and new svgs in figma
Storybook: https://orbit-mainframev-chore-update-icons-and-svgs.surge.sh
=> docs: documentation updates

packages/orbit-components/src/List/ListItem/index.d.ts, packages/orbit-components/src/List/index.d.ts, packages/orbit-components/src/Text/index.d.ts, packages/orbit-components/src/primitives/BadgePrimitive/index.d.ts
[ORBIT-1417](https://jira.kiwi.com/browse/ORBIT-1417)
This exports StyledText, StyledBadge, IconContainer and Item (from ListItem)
Storybook: https://orbit-mainframev-feat-export-styled-components.surge.sh
=> feat: export styled components

packages/orbit-components/src/primitives/TooltipPrimitive/__tests__/index.test.jsx, packages/orbit-components/src/primitives/TooltipPrimitive/components/TooltipContent.jsx, packages/orbit-components/src/primitives/TooltipPrimitive/components/TooltipContent.jsx.flow, packages/orbit-components/src/primitives/TooltipPrimitive/index.jsx
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1665397270506109)
Storybook: https://orbit-mainframev-fix-extend-propagation-on-content.surge.sh
=> fix(TooltipPrimitive): add handleClick to content

docs/src/__examples__/HorizontalScroll/default.tsx, packages/orbit-components/src/HorizontalScroll/HorizontalScroll.stories.jsx, packages/orbit-components/src/HorizontalScroll/README.md, packages/orbit-components/src/HorizontalScroll/index.d.ts, packages/orbit-components/src/HorizontalScroll/index.jsx, packages/orbit-components/src/HorizontalScroll/index.jsx.flow
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1665581788551209)
Storybook: https://orbit-mainframev-feat-horizontalscroll-add-arrows.surge.sh
=> feat(HorizontalScroll): add arrows to scroll

package.json, scripts/helpers.mjs, scripts/publish.mjs, yarn.lock
fixed the script, so now, hopefully, it will correctly post messages in the slack channel (tested inside the temp channel). 
also added a new feature, if the slack message has two emojis (was-done and react) between the previous and current release, it will tag that user inside the release message to notify him about the released changes. 
Storybook: https://orbit-mainframev-chore-publish-script-bot.surge.sh
=> chore: publish script changes

packages/orbit-components/src/Breadcrumbs/BreadcrumbsItem/index.jsx, packages/orbit-components/src/Breadcrumbs/README.md, packages/orbit-components/src/CallOutBanner/index.jsx, packages/orbit-components/src/Card/CardSection/components/SectionHeader.jsx, packages/orbit-components/src/Card/components/CardWrapper/index.jsx, packages/orbit-components/src/Checkbox/index.jsx, packages/orbit-components/src/InputField/helpers/formElementFocus.js, packages/orbit-components/src/InputGroup/index.jsx, packages/orbit-components/src/Itinerary/ItinerarySegment/index.jsx, packages/orbit-components/src/Itinerary/ItineraryStatus/index.jsx, packages/orbit-components/src/ListChoice/index.jsx, packages/orbit-components/src/Radio/index.jsx, packages/orbit-components/src/Seat/index.jsx, packages/orbit-components/src/SegmentedSwitch/SwitchSegment/index.jsx, packages/orbit-components/src/Slider/components/Handle/index.jsx, packages/orbit-components/src/Stepper/StepperStateless/index.jsx, packages/orbit-components/src/Switch/index.jsx, packages/orbit-components/src/Tag/index.jsx, packages/orbit-components/src/TextLink/index.jsx, packages/orbit-components/src/Textarea/index.jsx, packages/orbit-components/src/Tile/components/TileHeader/index.jsx, packages/orbit-components/src/Tile/components/TileWrapper/index.jsx, packages/orbit-components/src/utils/common/index.d.ts, packages/orbit-components/src/utils/common/index.js, packages/orbit-components/src/utils/common/index.js.flow
This PR changes the focus in multiple components to look like the native browser ones
Storybook: https://orbit-mainframev-fix-focus-state-multiple-components.surge.sh
=> fix: focus state multiple components

docs/babel.config.js, docs/src/components/Navbar/Links.tsx, docs/src/components/Navbar/index.tsx
Just a small refactoring, supposed to remove that delay with hydration, only after which the links inside navbar appear. 
Storybook: https://orbit-mainframev-fix-navbar-hydartion.surge.sh
=> docs(Navbar): remove useMediaQuery, appears only after hydration

packages/orbit-components/src/TextLink/index.jsx
Storybook: https://orbit-mainframev-RobinCsl-patch-1.surge.sh
=> fix(TextLink): repair broken CSS rule

docs/src/data/component-status.yaml
- Automatically generated PR on 2022-11-14.
- Updates component statuses
=> chore: update component statuses

packages/orbit-components/src/Itinerary/ItinerarySegment/ItinerarySegmentStop/index.tsx
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1667995401356349)
Storybook: https://orbit-mainframev-fix-itinerary-stop-render-text-as-div.surge.sh
=> fix(Itinerary): render text as div

docs/src/components/DocLayout/index.tsx, docs/src/components/HeaderBox.tsx, docs/src/components/Navbar/index.tsx
fixed the container width for DocLayout, it has to be the same as navigation bar
=> docs(DocsLayout): fix max-width

packages/orbit-components/src/Itinerary/Itinerary.stories.tsx, packages/orbit-components/src/Itinerary/ItinerarySegment/ItinerarySegmentBanner/index.tsx
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1669032789199679)
=> fix(ItinerarySegmentBanner): fix RTL issue

packages/orbit-components/src/ServiceLogo/consts.mts, packages/orbit-components/src/ServiceLogo/consts.ts, packages/orbit-components/src/ServiceLogo/index.js.flow
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1669036525986299)
=> feat(ServiceLogo): add AirHelpPlus logo

.eslintrc.js, docs/src/components/DesignTokensList/index.tsx, packages/orbit-design-tokens/src/__tests__/index.test.ts, packages/orbit-design-tokens/src/convertRgbaToHex.ts, packages/orbit-design-tokens/src/index.ts
Token values are now presented in hex, instead of rgba
[ORBIT-1922](https://kiwicom.atlassian.net/browse/ORBIT-1922)
=> docs: Present token values in hex

packages/orbit-components/src/Itinerary/Itinerary.stories.tsx, packages/orbit-components/src/Itinerary/ItinerarySegment/ItineraryIcon.tsx
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1669385124992599)
[ORBIT-2421](https://kiwicom.atlassian.net/browse/ORBIT-2421)
=> fix(ItinerarySegmentStop): fix ItineraryIcon

packages/orbit-components/src/Card/CardSection/components/SectionHeader.tsx
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1669642524279699)
=> fix(CardSection): remove focus background style

packages/orbit-components/src/Illustration/consts.mts, packages/orbit-components/src/Illustration/types.d.ts
As requested [here](https://skypicker.slack.com/archives/CAMS40F7B/p1669797565357079).
=> feat(Illustration): add FastBooking illustration

docs/plugins/contributors/fetchedUsers.json
- Automatically generated PR on 2022-12-02.
- Updates contributors for docs
=> chore: update contributors

packages/orbit-components/src/HorizontalScroll/README.md
Added information about the possible values on the elevationColor prop
=> docs: improve elevationColor in HorizontalScroll

packages/orbit-components/src/CarrierLogo/index.tsx
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1670406929697879)
=> fix(CarrierLogo): useRandomidSeed

docs/src/__examples__/Card/DEFAULT.tsx, docs/src/__examples__/IllustrationPrimitive/DEFAULT.tsx, docs/src/__examples__/Text/DEFAULT.tsx, packages/orbit-components/src/ButtonLink/types.d.ts, packages/orbit-components/src/Card/README.md, packages/orbit-components/src/Card/__tests__/index.test.tsx, packages/orbit-components/src/Card/index.js.flow, packages/orbit-components/src/Card/index.tsx, packages/orbit-components/src/Card/types.d.ts, packages/orbit-components/src/Illustration/index.js.flow, packages/orbit-components/src/Illustration/types.d.ts, packages/orbit-components/src/Text/README.md, packages/orbit-components/src/Text/__tests__/index.test.tsx, packages/orbit-components/src/Text/index.js.flow, packages/orbit-components/src/Text/index.tsx, packages/orbit-components/src/Text/types.d.ts, packages/orbit-components/src/common/common.js.flow, packages/orbit-components/src/common/types.d.ts, packages/orbit-components/src/primitives/IllustrationPrimitive/README.md, packages/orbit-components/src/primitives/IllustrationPrimitive/__tests__/index.test.tsx, packages/orbit-components/src/primitives/IllustrationPrimitive/index.js.flow, packages/orbit-components/src/primitives/IllustrationPrimitive/index.tsx, packages/orbit-components/src/primitives/IllustrationPrimitive/types.d.ts, packages/orbit-components/src/utils/common/__tests__/index.test.ts, packages/orbit-components/src/utils/common/index.ts
[ORBIT-2408](https://kiwicom.atlassian.net/browse/ORBIT-2408)
[ORBIT-2410](https://kiwicom.atlassian.net/browse/ORBIT-2410)
[ORBIT-2411](https://kiwicom.atlassian.net/browse/ORBIT-2411)
Margin utility prop for Text, Card and Illustration
=> feat: add margin utility properties

docs/src/documentation/05-development/02-utilities/03-slide-animation.mdx, packages/orbit-components/src/utils/Slide/README.md
Adds simple documentation for Slide component.
=> docs: add Slide util docs

packages/orbit-components/src/Breadcrumbs/BreadcrumbsItem/index.tsx
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1671450724375909)
=> fix(Breadcrumbs): make last element always bold

docs/src/components/VisualList.tsx
=> fix: typo ("an visual" -> "a visual")

docs/src/__examples__/Breadcrumbs/BACK.tsx, docs/src/__examples__/Breadcrumbs/DEFAULT.tsx, docs/src/__examples__/ButtonMobileStore/DEFAULT.tsx, docs/src/__examples__/HorizontalScroll/default.tsx, docs/src/__examples__/Icon/DEFAULT.tsx, docs/src/__examples__/InputFile/DEFAULT.tsx, docs/src/__examples__/LinkList/DEFAULT.tsx, docs/src/__examples__/Stepper/DEFAULT.tsx, docs/src/__examples__/Table/DEFAULT.tsx, docs/src/__examples__/Tile/DEFAULT.tsx, docs/src/__examples__/Timeline/DEFAULT.tsx, docs/src/__examples__/Wizard/DEFAULT.tsx, docs/src/components/ReactExample/Example.tsx, docs/src/components/ReactExample/components/Board.tsx, docs/src/components/ReactExample/components/Playground.tsx, packages/orbit-components/src/Stepper/README.md, packages/orbit-components/src/Stepper/StepperStateless/index.js.flow, packages/orbit-components/src/Stepper/StepperStateless/types.d.ts
[ORBIT-2465](https://kiwicom.atlassian.net/browse/ORBIT-2465)
=> docs: fix knobs inconsistencies 

packages/orbit-components/src/utils/Grid/index.tsx
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1673786621761829)
=> fix(Grid): fix missing spaceAfter

.github/workflows/storybook.yml
[Understanding the risk of script injections
](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable)
=> chore(actions): fix branch_url vulnerability

packages/orbit-components/css-prop.d.ts, packages/orbit-components/src/Itinerary/ItineraryBadgeList/ItineraryBadgeListItem.tsx, packages/orbit-components/src/Itinerary/ItinerarySegment/ItinerarySegmentDetail/index.tsx, packages/orbit-components/src/Itinerary/ItinerarySegment/ItinerarySegmentStop/index.tsx, packages/orbit-components/src/Itinerary/ItineraryStatus/index.tsx, packages/orbit-components/src/Itinerary/ItineraryTemporaryText/index.tsx, packages/orbit-components/src/Wizard/WizardStep.tsx, packages/orbit-components/src/Wizard/index.tsx, packages/orbit-components/tsconfig.json
As we agreed to have temporary fix, I made it in a such way, so later we can quickly remove that
=> fix: Itinerary status color fixes

packages/orbit-components/src/Modal/index.tsx
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1677160071605909)
=> fix(Modal): fixed mobile header while scrolling

docs/src/hooks/useIsUrlExternal.ts, docs/src/services/table-of-contents.tsx, packages/eslint-plugin-orbit-components/docs/rules/unique-id.md, packages/orbit-components/src/Card/CardSection/index.tsx, packages/orbit-components/src/Collapse/index.tsx, packages/orbit-components/src/Dialog/index.tsx, packages/orbit-components/src/Drawer/index.tsx, packages/orbit-components/src/InputGroup/index.tsx, packages/orbit-components/src/Popover/index.tsx, packages/orbit-components/src/Slider/README.md, packages/orbit-components/src/Toast/ToastMessage.tsx, packages/orbit-components/src/deprecated/InputField/index.tsx, packages/orbit-components/src/deprecated/InputGroup/index.tsx, packages/orbit-components/src/hooks/useMediaQuery/index.ts
I decided to remove `useMemo`, where it's not necessary
=> refactor: remove useMemo

packages/orbit-components/src/ChoiceGroup/ChoiceGroup.stories.tsx, packages/orbit-components/src/ErrorForms.stories.tsx, packages/orbit-components/src/Slider/Slider.stories.tsx, packages/orbit-components/src/Toast/Toast.stories.tsx, packages/orbit-components/tsconfig.json
Stories will now have their types checked, to enable the detection of possible unexpected type changes.
[ORBIT-2661](https://kiwicom.atlassian.net/browse/ORBIT-2661)
The type error in Toast story will be fixed in [ORBIT-2663](https://kiwicom.atlassian.net/browse/ORBIT-2663).
=> Add type check to stories

packages/orbit-components/transforms/__testfixtures__/translations.input.js, packages/orbit-components/transforms/__testfixtures__/translations.input.tsx, packages/orbit-components/transforms/__testfixtures__/translations.output.js, packages/orbit-components/transforms/__testfixtures__/translations.output.tsx, packages/orbit-components/transforms/__tests__/translations.test.js, packages/orbit-components/transforms/translations.js, tsconfig.json
Skipped Pagination and SkipNavigation :D, according to our tracking data components are not being used anywhere
=> chore: add translations codemod

packages/orbit-components/src/Loading/index.tsx, packages/orbit-components/src/Tabs/README.md
[Slack request](https://skypicker.slack.com/archives/C7T7QG7M5/p1680002483466709)
=> fix(Loading): fix LoadingSpinner size with customSize prop

packages/orbit-components/src/Tabs/components/TabPanels/index.tsx
This makes the `width : 100%` of TabPanel have an effect.
=> feat(Tabs): add width: 100% to TabPanels

docs/src/components/InlineToken.tsx, packages/orbit-components/src/CountryFlag/index.tsx, packages/orbit-components/src/Slider/index.tsx
Just a small detail we missed after adeira removal 😞
=> fix: console warnings

packages/orbit-components/transforms/__testfixtures__/translations-new.input.js, packages/orbit-components/transforms/__testfixtures__/translations-new.input.tsx, packages/orbit-components/transforms/__testfixtures__/translations-new.output.js, packages/orbit-components/transforms/__testfixtures__/translations-new.output.tsx, packages/orbit-components/transforms/__tests__/translations-new.test.js, packages/orbit-components/transforms/translations-new.js
the same codemod as before, only to support react-intl and FormattedMessage
=> chore: add codemod to support react-intl

docs/src/components/DocLayout/index.tsx, docs/src/documentation/02-foundation/07-icons/01-general.mdx, docs/src/mdx-components.tsx
[Slack internal request](https://skypicker.slack.com/archives/GSGN9BN6Q/p1681294338545859)
Also changed the padding on DocLayout, which should be added from the largeDesktop
=> docs: fix zip download anchor

docs/src/__examples__/Modal/FIXED_FOOTER.tsx, packages/orbit-components/src/ErrorForms.stories.tsx, packages/orbit-components/src/Illustration/consts.mts, packages/orbit-components/src/Modal/Modal.stories.tsx, packages/orbit-components/src/Modal/ModalFooter/index.tsx, packages/orbit-components/src/SkipLink/SkipLink.stories.tsx
Small change so that the array only has possible illustration names. It is also valid for other stories that are relying on this array for knobs.
=> chore(Illustration): add type to consts file

packages/orbit-design-tokens/output/theo-spec.android.xml, packages/orbit-design-tokens/output/theo-spec.ios.json, packages/orbit-design-tokens/pages/theo-spec.kiwi.html, packages/orbit-design-tokens/src/theo/theo-spec.json
- Automatically generated PR on 2023-04-21.
- Updates palette tokens from Figma
=> feat(tokens): update palette tokens from figma

packages/orbit-components/src/Tag/README.md, packages/orbit-components/src/Tag/Tag.stories.tsx, packages/orbit-components/src/Tag/__tests__/index.test.tsx, packages/orbit-components/src/Tag/index.js.flow, packages/orbit-components/src/Tag/index.tsx, packages/orbit-components/src/Tag/types.d.ts
This fixes the border-radius on responsive and also adds the `iconLeft` prop
[ORBIT-2722](https://kiwicom.atlassian.net/browse/ORBIT-2722)
=> Add tag changes

docs/src/components/ReactExample/components/Frame.tsx
currently the example not really visible on production
=> docs(ReactExample): set min-height for iframe

docs/src/__examples__/Separator/DEFAULT.tsx, packages/orbit-components/src/Itinerary/Itinerary.stories.tsx, packages/orbit-components/src/Itinerary/ItinerarySeparator/index.js.flow, packages/orbit-components/src/Itinerary/ItinerarySeparator/index.tsx, packages/orbit-components/src/Itinerary/ItinerarySeparator/types.d.ts, packages/orbit-components/src/Itinerary/README.md, packages/orbit-components/src/Separator/README.md, packages/orbit-components/src/Separator/Separator.stories.tsx, packages/orbit-components/src/Separator/index.js.flow, packages/orbit-components/src/Separator/index.tsx, packages/orbit-components/src/Separator/types.d.ts
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1684133499157459)
=> feat: add type and color for separator components

docs/src/components/ReactExample/components/Frame.tsx, docs/src/hooks/useSandbox.ts, docs/src/pages/playground-full.tsx, docs/src/pages/playground.tsx
Unification of logic, without iframes modals, popovers and navigation bar appear on main window
=> docs: fix playground page with iframe

packages/orbit-components/src/Wizard/WizardStep.tsx, packages/orbit-components/src/Wizard/index.tsx
Fixing the issue, when we after updating eslint and adding useMemo to provider, forgot to pass correctly one prop 😞
=> fix(Wizard): fix missing provider prop

packages/orbit-components/src/Select/index.tsx
The first two points of [this report](https://skypicker.slack.com/archives/CAMS40F7B/p1686814850266989).
=> fix(Select): adjust height and alignment of Select and Prefix

packages/orbit-components/src/ErrorFormTooltip/Tooltip/index.tsx
[Slack request](https://skypicker.slack.com/archives/CCKFSMLG0/p1686305792394689?thread_ts=1686129534.897319&cid=CCKFSMLG0)
=> fix(ErrorFormTooltip): change font-weight to normal

packages/orbit-components/src/Select/index.tsx
Reported [here](https://skypicker.slack.com/archives/CAMS40F7B/p1687162661316219?thread_ts=1686814850.266989&cid=CAMS40F7B)
=> fix(Select): customValueText vertical alignment

docs/src/components/Guidelines/GuidelinesSideBySide.tsx, docs/src/components/Guidelines/index.tsx, docs/src/documentation/06-kiwi-use/02-content/01-voice-and-tone/02-empathetic.mdx, docs/src/documentation/06-kiwi-use/02-content/01-voice-and-tone/03-straightforward.mdx, docs/src/documentation/06-kiwi-use/02-content/01-voice-and-tone/04-passionate.mdx, docs/src/documentation/06-kiwi-use/02-content/01-voice-and-tone/05-inclusive.mdx, docs/src/documentation/06-kiwi-use/02-content/01-voice-and-tone/06-transparent.mdx, docs/src/documentation/06-kiwi-use/02-content/02-grammar-and-mechanics.mdx, docs/src/documentation/06-kiwi-use/02-content/03-glossary.mdx, lint-staged.config.js
Testing out the process of deployment
=> docs: update content section

packages/orbit-components/src/Slider/index.tsx
As a follow-up to #3878 this adjustment was missing.
=> fix(Slider): defaultValue now updates the slider

docs/src/documentation/06-kiwi-use/01-brand/brand-guidelines/01-kiwi-com.mdx
changed minimal logo size and removed section about offline usage
=> docs: update brand guidelines

packages/orbit-components/src/InputFile/InputFile.stories.tsx, packages/orbit-components/src/InputFile/README.md, packages/orbit-components/src/InputFile/__tests__/index.test.tsx, packages/orbit-components/src/InputFile/index.js.flow, packages/orbit-components/src/InputFile/index.tsx, packages/orbit-components/src/InputFile/types.d.ts
[ Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1689065228646649)
=> feat(InputFile): add multiple attribute

packages/orbit-components/src/InputSelect/__tests__/index.test.tsx, packages/orbit-components/src/InputSelect/index.tsx
[The list of fixes reported by QA ](https://docs.google.com/document/d/14kR9DpmWoFVUmCkorf7ptRLqCkEsFppCXfgOA_Sm9UM/edit?usp=sharing)
=> InputSelect fixes after QA report

packages/orbit-components/src/Separator/TYPESCRIPT_TEMPLATE.template, packages/orbit-components/src/Separator/index.tsx, packages/orbit-components/src/Separator/types.d.ts
[Reported in Slack](https://skypicker.slack.com/archives/CAMS40F7B/p1689588311958009)
=> fix(Separator): fix background and border issue

packages/orbit-design-tokens/output/tokens.css, packages/orbit-design-tokens/output/tokens.less, packages/orbit-design-tokens/output/tokens.styl, packages/orbit-design-tokens/src/dictionary/build.ts
I decided to remove the timestamps, as it creates for us conflicts usually that we need to handle
=> chore(tokens): remove timestamps

packages/orbit-components/src/HorizontalScroll/__tests__/useScroll.test.ts, packages/orbit-components/src/HorizontalScroll/useScroll.ts
Reported on Slack: https://skypicker.slack.com/archives/C7T7QG7M5/p1693917389783689
Jira: FEPLT-1736
Storybook: https://orbit-mainframev-rcsl-prevent-click-to-capture-drag.surge.sh
=> fix(HorizontalScroll): prevent click to induce scrolling

packages/orbit-components/src/Text/Text.stories.tsx, packages/orbit-components/src/Text/__tests__/index.test.tsx, packages/orbit-components/src/Text/index.tsx
Saves #3982 
Storybook: https://orbit-mainframev-fix-text-alignment-default.surge.sh
=> Fix text alignment default

packages/orbit-components/src/Breadcrumbs/BreadcrumbsItem/index.tsx, packages/orbit-components/src/Breadcrumbs/BreadcrumbsItem/types.d.ts, packages/orbit-components/src/Breadcrumbs/README.md, packages/orbit-components/src/Breadcrumbs/index.tsx
[FEPL-1738](https://kiwicom.atlassian.net/browse/FEPLT-1738)
Storybook: https://orbit-mainframev-tw-migrate-breadcrumbs.surge.sh
=> feat(Breadcrumbs): migrate Breadcrumbs to Tailwind

docs/package.json, docs/plugins/contributors/fetchContributors.mjs, docs/plugins/contributors/fetchedUsers.json, yarn.lock
It's just started to add automatically "actions-users" after we added rebase, so I excluded that 
Storybook: https://orbit-mainframev-chore-change-contributors.surge.sh
=> chore: adjust fetching contributors script

docs/src/documentation/02-foundation/11-tailwind/01-installation.mdx, docs/src/documentation/05-development/04-migration-guides/01-v7.mdx, docs/src/documentation/05-development/04-migration-guides/02-v9.mdx, docs/src/documentation/05-development/04-migration-guides/03-v10.mdx, packages/orbit-tailwind-preset/README.md, packages/orbit-tailwind-preset/src/presets/__tests__/font.test.tsx
Migration guide for v10
Storybook: https://orbit-mainframev-v10-migration-guide.surge.sh
=> V10 migration guide

.eslintrc.cjs, docs/src/components/DesignTokensList/components/DesignTokenValue.tsx, docs/src/components/DesignTokensList/components/DesignTokensTable.tsx, docs/src/components/DesignTokensList/types.d.ts, docs/src/docs-table.tsx, packages/orbit-components/config/build/buildIcons.mts, packages/orbit-components/src/Alert/AlertButton/types.d.ts, packages/orbit-components/src/Box/normalize.ts, packages/orbit-components/src/Button/Button.stories.tsx, packages/orbit-components/src/InputField/index.tsx, packages/orbit-components/src/InputGroup/InputGroup.stories.tsx, packages/orbit-components/src/InputSelect/InputSelectOption/index.tsx, packages/orbit-components/src/Modal/types.d.ts, packages/orbit-components/src/Radio/index.tsx, packages/orbit-components/src/Slider/components/Bar/index.tsx, packages/orbit-components/src/Slider/components/Handle/index.tsx, packages/orbit-components/src/Slider/components/Histogram/index.tsx, packages/orbit-components/src/TextLink/index.tsx, packages/orbit-components/src/common/types.d.ts, packages/orbit-components/src/hooks/useBoundingRect/index.ts, packages/orbit-components/src/primitives/ButtonPrimitive/components/ButtonPrimitiveContent.tsx
[as it was discussed here ](https://github.com/kiwicom/orbit/pull/3975#discussion_r1315770132)-> enforcing it for consistency 
Storybook: https://orbit-mainframev-chore-enforce-eslint-rules.surge.sh
=> chore: enforce interfaces for object-like types

.github/workflows/publish.yml
Did not help, let's use mine for now
=> actions: setup git credentials for release

.github/workflows/publish.yml
PAT: Personal Access Token
Storybook: https://orbit-mainframev-marco-pat.surge.sh
=> ci: set PAT on checkout step

packages/orbit-components/src/tmp-tailwind/ButtonGroup/ButtonGroup.stories.tsx, packages/orbit-components/src/tmp-tailwind/ButtonGroup/index.tsx, packages/orbit-tailwind-preset/src/presets/__tests__/__snapshots__/configs.test.ts.snap, packages/orbit-tailwind-preset/src/presets/foundation/index.ts
[WEBC-1754](https://kiwicom.atlassian.net/browse/FEPLT-1754)
Storybook: https://orbit-mainframev-oreqizer-tw-button-grouop.surge.sh
=> ButtonGroup to Tailwind

packages/orbit-components/src/tmp-tailwind/Switch/index.tsx
Had no time to look at Switch PR. Here are few small 💅🏻 
Storybook: https://orbit-mainframev-chore-switch-correct-classes.surge.sh
=> chore(Switch): use proper classes

packages/orbit-components/src/InputField/index.tsx, packages/orbit-components/src/Select/index.tsx, packages/orbit-components/src/tmp-tailwind/InputGroup/InputGroup.stories.tsx, packages/orbit-components/src/tmp-tailwind/InputGroup/__tests__/index.test.tsx, packages/orbit-components/src/tmp-tailwind/InputGroup/index.tsx
https://kiwicom.atlassian.net/browse/FEPLT-1694
Storybook: https://orbit-mainframev-oreqizer-tw-input-group.surge.sh
=> migrate InputGroup to Tailwind

docs/src/documentation/05-development/04-migration-guides/03-v10.mdx
Storybook: https://orbit-mainframev-RobinCsl-patch-1.surge.sh
=> fix(docs): fix example for "Mobile" component deprecation

.github/workflows/chromatic.yml
Add chromatic github workflow
Storybook: https://orbit-mainframev-chromatic-workflow.surge.sh
=> Add chromatic github workflow

packages/orbit-components/src/ServiceLogo/index.tsx, packages/orbit-components/src/Tag/index.tsx, packages/orbit-components/src/tmp-tailwind/InputField/InputField.stories.tsx, packages/orbit-components/src/tmp-tailwind/InputField/InputTags/index.tsx, packages/orbit-components/src/tmp-tailwind/InputField/__tests__/index.test.tsx, packages/orbit-components/src/tmp-tailwind/InputField/index.tsx
Closes [FEPLT-1692](https://kiwicom.atlassian.net/browse/FEPLT-1692)
Storybook: https://orbit-mainframev-tw-migrate-inputfield.surge.sh
=> chore(InputField): migrate to Tailwind

packages/orbit-components/src/Select/Select.stories.tsx, packages/orbit-components/src/tmp-tailwind/Select/Select.stories.tsx, packages/orbit-components/src/tmp-tailwind/Select/__tests__/Select.test.tsx, packages/orbit-components/src/tmp-tailwind/Select/index.tsx
Closes [FEPLT-1695](https://kiwicom.atlassian.net/browse/FEPLT-1695)
Storybook: https://orbit-mainframev-feplt-1695-tw-select.surge.sh
=> chore(Select): migrate to Tailwind

packages/orbit-components/src/tmp-tailwind/SegmentedSwitch/SegmentedSwitch.stories.tsx, packages/orbit-components/src/tmp-tailwind/SegmentedSwitch/SwitchSegment/index.tsx, packages/orbit-components/src/tmp-tailwind/SegmentedSwitch/__tests__/index.test.tsx, packages/orbit-components/src/tmp-tailwind/SegmentedSwitch/index.tsx
- chore(tailwind): add shadow-switch-segment class
- chore(SegmentedSwitch): migrate to Tailwind
Closes [FEPLT-1706](https://kiwicom.atlassian.net/browse/FEPLT-1706)
Storybook: https://orbit-mainframev-segmented-switch.surge.sh
=> chore(SegmentedSwitch): migrate to Tailwind

.eslintrc.cjs, .github/workflows/chromatic.yml, packages/orbit-components/.storybook/orbitDecorator.tsx, packages/orbit-components/src/Accordion/Accordion.stories.tsx, packages/orbit-components/src/AirportIllustration/AirportIllustration.stories.tsx, packages/orbit-components/src/Alert/Alert.stories.tsx, packages/orbit-components/src/Badge/Badge.stories.tsx, packages/orbit-components/src/BadgeList/BadgeList.stories.tsx, packages/orbit-components/src/BaggageStepper/Stepper.stories.tsx, packages/orbit-components/src/Breadcrumbs/Breadcrumbs.stories.tsx, packages/orbit-components/src/Button/Button.stories.tsx, packages/orbit-components/src/ButtonGroup/ButtonGroup.stories.tsx, packages/orbit-components/src/ButtonLink/ButtonLink.stories.tsx, packages/orbit-components/src/ButtonMobileStore/ButtonMobileStore.stories.tsx, packages/orbit-components/src/CallOutBanner/CallOutBanner.stories.tsx, packages/orbit-components/src/Card/Card.stories.tsx, packages/orbit-components/src/CarrierLogo/CarrierLogo.stories.tsx, packages/orbit-components/src/Checkbox/Checkbox.stories.tsx, packages/orbit-components/src/ChoiceGroup/ChoiceGroup.stories.tsx, packages/orbit-components/src/Coupon/Coupon.stories.tsx, packages/orbit-components/src/Dialog/Dialog.stories.tsx, packages/orbit-components/src/Drawer/Drawer.stories.tsx, packages/orbit-components/src/FeatureIcon/FeatureIcon.stories.tsx, packages/orbit-components/src/Heading/Heading.stories.tsx, packages/orbit-components/src/HorizontalScroll/HorizontalScroll.stories.tsx, packages/orbit-components/src/Icon/Icon.stories.tsx, packages/orbit-components/src/Illustration/Illustration.stories.tsx, packages/orbit-components/src/InputField/InputField.stories.tsx
.
Storybook: https://orbit-mainframev-oreqizer-test-stories.surge.sh
=> Add visual test stories

packages/orbit-components/src/Layout/index.tsx, packages/orbit-components/src/utils/Grid/index.js.flow, packages/orbit-components/src/utils/Grid/index.tsx, packages/orbit-components/src/utils/Grid/types.d.ts
Needed to work with Grid.
Storybook: https://orbit-mainframev-oreqizer-fix-layout.surge.sh
=> Migrate Layout to Tailwind

packages/orbit-components/src/Alert/Alert.stories.tsx, packages/orbit-components/src/Alert/index.tsx, packages/orbit-components/src/TextLink/deprecated/index.ts, packages/orbit-components/src/TextLink/helpers/twClasses.ts
[FEPLT-1698](https://kiwicom.atlassian.net/browse/FEPLT-1698)
Visual Test story was updated and snapshots in Chromatic were also updated **before** the Tailwind migration. Visual regression testing to be made after PR's approval and before merge. **Edit:** Visual tests passed.
[FEPLT-1698]: https://kiwicom.atlassian.net/browse/FEPLT-1698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Storybook: https://orbit-mainframev-tw-migrate-alert.surge.sh
=> Migrate Alert to Tailwind

packages/orbit-components/src/Checkbox/index.tsx, packages/orbit-components/src/InputSelect/InputSelectOption/index.tsx, packages/orbit-components/src/ListChoice/ListChoice.stories.tsx, packages/orbit-components/src/ListChoice/index.tsx
Closes [FEPLT-1690](https://kiwicom.atlassian.net/browse/FEPLT-1690)
Storybook: https://orbit-mainframev-tw-list-choice.surge.sh
[FEPLT-1690]: https://kiwicom.atlassian.net/browse/FEPLT-1690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FEPLT-1690: feat(ListChoice): migrate to Tailwind

packages/orbit-components/src/BadgeList/BadgeListItem/index.js.flow, packages/orbit-components/src/BadgeList/BadgeListItem/index.tsx, packages/orbit-components/src/BadgeList/index.tsx, packages/orbit-components/src/Itinerary/ItineraryBadgeList/ItineraryBadgeListItem.tsx
Closes FEPLT-1685
Storybook: https://orbit-mainframev-tw-badge-list.surge.sh
=> feat(BadgeList): migrate to Tailwind

packages/orbit-components/src/CarrierLogo/CarrierLogo.stories.tsx, packages/orbit-components/src/CarrierLogo/index.tsx, packages/orbit-design-tokens/output/deprecated-tokens.json, packages/orbit-design-tokens/output/docs-tokens.json, packages/orbit-design-tokens/src/dictionary/definitions/component/icon/icon-size.json
Closes FEPLT-1763
Storybook: https://orbit-mainframev-tw-carrier-logo.surge.sh
=> feat(CarrierLogo): migrate to Tailwind

packages/orbit-components/src/Breadcrumbs/index.tsx, packages/orbit-components/src/Loading/index.tsx
- chore(Breadcrumbs): remove useless class
- fix(Loading): use correct font family class
Storybook: https://orbit-mainframev-marco-fix-tw-classes.surge.sh
=> Fix text tailwind classes

packages/orbit-components/src/TileGroup/TileGroup.stories.tsx, packages/orbit-components/src/TileGroup/index.tsx, packages/orbit-components/src/utils/Slide/index.tsx
https://kiwicom.atlassian.net/browse/FEPLT-1744
Storybook: https://orbit-mainframev-oreqizer-tw-tile-group.surge.sh
=> TileGroup to Tailwind

docs/src/components/Dashboard/AllRepositories.tsx, docs/src/components/Dashboard/AllRepositoriesComponent.tsx, docs/src/components/Dashboard/Difference.tsx, docs/src/components/Dashboard/Repository.tsx, docs/src/components/Dashboard/RepositoryComponent.tsx, docs/src/components/Dashboard/Tracking.tsx, packages/orbit-tracking/src/consts.ts, packages/orbit-tracking/src/interfaces.ts
Closes [FEPLT-1790](https://kiwicom.atlassian.net/browse/FEPLT-1790)
[FEPLT-1790]: https://kiwicom.atlassian.net/browse/FEPLT-1790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Storybook: https://orbit-mainframev-chore-extend-tracking-data.surge.sh
=> chore: extend tracking scope

docs/src/data/tailwind-migration-status.yaml, packages/orbit-components/src/TileGroup/index.tsx
from https://github.com/kiwicom/orbit/pull/4105
Storybook: https://orbit-mainframev-oreqizer-tw-tile-group-fix.surge.sh
=> Fix TileGroup hover states and bg colors

docs/src/data/tailwind-migration-status.yaml, packages/orbit-components/src/NotificationBadge/NotificationBadge.stories.tsx, packages/orbit-components/src/NotificationBadge/__tests__/index.test.tsx, packages/orbit-components/src/NotificationBadge/index.tsx
Migrate NotificationBadge to Tailwind
[FEPLT-1719](https://kiwicom.atlassian.net/browse/FEPLT-1719)
[FEPLT-1719]: https://kiwicom.atlassian.net/browse/FEPLT-1719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Storybook: https://orbit-mainframev-tw-notification-badge.surge.sh
=> Migrate NotificationBadge to Tailwind

docs/src/data/tailwind-migration-status.yaml, packages/orbit-components/src/Stepper/Stepper.stories.tsx, packages/orbit-components/src/Stepper/StepperStateless/index.tsx, packages/orbit-components/src/Stepper/__tests__/index.test.tsx
[FEPLT-1696](https://kiwicom.atlassian.net/browse/FEPLT-1696)
Storybook: https://orbit-mainframev-tw-migrate-stepper.surge.sh
[FEPLT-1696]: https://kiwicom.atlassian.net/browse/FEPLT-1696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(Stepper): migrate Stepper to Tailwind

docs/src/data/tailwind-migration-status.yaml, packages/orbit-components/src/Collapse/Collapse.stories.tsx, packages/orbit-components/src/Collapse/index.tsx
[FEPLT-1703](https://kiwicom.atlassian.net/browse/FEPLT-1703)
Storybook: https://orbit-mainframev-tw-collapse.surge.sh
[FEPLT-1703]: https://kiwicom.atlassian.net/browse/FEPLT-1703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Migrate Collapse to Tailwind

packages/orbit-components/src/Card/README.md
Just a simple change in the docs
Storybook: https://orbit-mainframev-jozef-mikusinec-kiwicom-patch-1.surge.sh
=> feat(docs): update README of Card (then -> than)

docs/src/documentation/02-foundation/10-typography/02-circular-pro.mdx
Fix of a typo in typography docs.
=> docs: typography font typo

docs/src/data/tailwind-migration-status.yaml, packages/orbit-components/src/Truncate/Truncate.stories.tsx, packages/orbit-components/src/Truncate/__tests__/index.test.tsx, packages/orbit-components/src/Truncate/index.tsx
Storybook: https://orbit-mainframev-tw-truncate.surge.sh
Closes FEPLT-1728
=> feat(Truncate): migrate to Tailwind

packages/orbit-components/src/Modal/ModalHeader/index.tsx
https://kiwicom.atlassian.net/browse/FEPLT-1837
Storybook: https://orbit-mainframev-oreqizer-fix-modal-z-or-transparent-thing.surge.sh
=> ModalHeader mobile scroll header background

.eslintrc.cjs, docs/src/components/BrandedTile.tsx, docs/src/components/Head/index.tsx, docs/src/components/VisualList.tsx, packages/orbit-components/.eslintrc.cjs, packages/orbit-components/src/BadgeList/BadgeListItem/index.tsx, packages/orbit-components/src/Checkbox/index.tsx, packages/orbit-components/src/ChoiceGroup/components/Feedback.tsx, packages/orbit-components/src/Drawer/index.tsx, packages/orbit-components/src/InputField/index.tsx, packages/orbit-components/src/ListChoice/index.tsx, packages/orbit-components/src/Loading/index.tsx, packages/orbit-components/src/Modal/ModalHeader/index.tsx, packages/orbit-components/src/Modal/ModalSection/index.tsx, packages/orbit-components/src/Modal/index.tsx, packages/orbit-components/src/NavigationBar/index.tsx, packages/orbit-components/src/Popover/components/ContentWrapper.tsx, packages/orbit-components/src/Radio/index.tsx, packages/orbit-components/src/Select/index.tsx, packages/orbit-components/src/Tabs/components/Tab/index.tsx, packages/orbit-components/src/Textarea/index.tsx, packages/orbit-components/src/Toast/ToastMessage.tsx, packages/orbit-components/src/primitives/ButtonPrimitive/index.tsx, packages/orbit-tailwind-preset/src/presets/__tests__/__snapshots__/configs.test.ts.snap, packages/orbit-tailwind-preset/src/presets/foundation/getTailwindTheme.ts
Tailwind ESLint config was not correct so we were missing actual validation in a lot of classes. This addresses that setup and fixes wrong classes.
Storybook: https://orbit-mainframev-fix-tw-eslint-config.surge.sh
=> Improve eslint tailwind config

packages/orbit-components/src/Switch/index.tsx
Reported [here](https://skypicker.slack.com/archives/C04HMMQ6VNE/p1701939845696809)
Storybook: https://orbit-mainframev-fix-switch-hover.surge.sh
Giving solution to [FEPLT-1866](https://kiwicom.atlassian.net/browse/FEPLT-1866)
[FEPLT-1864]: https://kiwicom.atlassian.net/browse/FEPLT-1864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FEPLT-1866]: https://kiwicom.atlassian.net/browse/FEPLT-1866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(Switch): cursor not applied on input

.github/PULL_REQUEST_TEMPLATE.md, docs/src/data/tailwind-migration-status.yaml, packages/orbit-components/src/FeatureIcon/index.tsx
Closes [FEPLT-1721](https://kiwicom.atlassian.net/browse/FEPLT-1721) 
- [ ] Visual regression test suite has been added and run before the migration.
Storybook: https://orbit-mainframev-tw-feature-icon.surge.sh
[FEPLT-1721]: https://kiwicom.atlassian.net/browse/FEPLT-1721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(FeatureIcon): migrate to Tailwind

.github/workflows/cron-update-contributors.yml, .github/workflows/cron-update-icons.yml, .github/workflows/cron-update-statuses.yml, .github/workflows/cron-update-tokens.yml
=> chore: fix actions script on cronjobs

.github/workflows/cron-update-contributors.yml, .github/workflows/cron-update-icons.yml, .github/workflows/cron-update-statuses.yml, .github/workflows/cron-update-tokens.yml
Commits were either not being done correctly (trying to create commits with no changes, or creating commits on master directly that were never pushed) or branches were not being pushed. Github-script action does not push branches so we have to do it before trying to create the Pull request
=> chore: fix commits on cronjobs

.github/ISSUE_TEMPLATE/new-component.md
Fix some strange grammar in the new component issue template that wasn't quite right.
- [ ] Visual regression test suite has been added if does not exist.
- [ ] `tailwind-migration-status.yaml` file has been updated with the migrated component(s).
=> docs: fix some grammar in the new component issue template that sounded odd or had the wrong tense

docs/src/data/tailwind-migration-status.yaml, packages/orbit-components/src/primitives/IllustrationPrimitive/IllustrationPrimitiveList.tsx
Closes [FEPLT-1782](https://kiwicom.atlassian.net/browse/FEPLT-1782)
- ~~[ ] Visual regression test suite has been added if does not exist.~~ no need imo, not a consumable component
[FEPLT-1782]: https://kiwicom.atlassian.net/browse/FEPLT-1782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(Illustration): migrate IllustrationPrimitiveList to tailwind

.github/contribution/testing-conventions.md
Based on what was discussed IRL, this PR is just to update documentation regarding visual regression tests, especially their usage locally and with darwin architecture
[FEPLT-1944](https://kiwicom.atlassian.net/browse/FEPLT-1944)
[FEPLT-1944]: https://kiwicom.atlassian.net/browse/FEPLT-1944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update visual tests contributing docs

.github/workflows/storybook.yml
After #4316 we can be a bit more strict in our permissions
=> ci: fine grain write permissions in storybook job

packages/orbit-components/src/Modal/index.tsx
- [ ] Visual regression test suite has been added if does not exist.
- [ ] `tailwind-migration-status.yaml` file has been updated with the migrated component(s).
=> fix(Modal): ensure the Modal body can scroll

packages/orbit-design-tokens/scripts/fetchBaseTokens.mjs
=> chore(tokens): ignore choice tokens on fetch script

packages/orbit-components/src/Badge/README.md, packages/orbit-components/src/CarrierLogo/README.md, packages/orbit-components/src/primitives/BadgePrimitive/README.md
=> docs: clarify IATA code usage in carrier components

packages/orbit-components/.storybook/main.ts, packages/orbit-components/package.json, yarn.lock
~It does not apply on master. Only in local dev and staging (branches PR)~
Accessibility addon added to Storybook
=> Add accessibility addon to storybook

.github/workflows/update-visual-tests.yml
The 'update-visual-tests.yml' workflow was forgotten in bd761241f6f3b57c220177bb52e16f7d32bdd6ea
=> chore: update Playwright version in all workflows

packages/orbit-components/src/ServiceLogo/ServiceLogo.ct.tsx
=> chore(ServiceLogo): add comments for visual tests config

packages/orbit-components/src/Checkbox/Checkbox.stories.tsx, packages/orbit-components/src/Checkbox/index.tsx, packages/orbit-components/src/ListChoice/ListChoice.stories.tsx
=> fix(Checkbox): prevent changes on readOnly

packages/orbit-components/src/Icon/index.tsx
=> fix(Icon): remove defaultProps in favour of default values 

docs/src/documentation/03-components/07-interaction/segmentedswitch/meta.yml, packages/orbit-components/src/SegmentedSwitch/README.md, packages/orbit-components/src/SegmentedSwitch/SwitchSegment/index.tsx
https://skypicker.slack.com/archives/C7T7QG7M5/p1721396328695559
Closes [FEPLT-2060](https://kiwicom.atlassian.net/browse/FEPLT-2060)
[FEPLT-2060]: https://kiwicom.atlassian.net/browse/FEPLT-2060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SegmentedSwitch fixes

packages/orbit-components/src/TextLink/index.tsx
For now, only `TextLink` but we might need to add support for this in other components in the future.
=> TextLink: add support for data and aria attributes

docs/src/__examples__/Checkbox/DEFAULT.tsx, packages/orbit-components/package.json, packages/orbit-components/src/Box/Box.stories.tsx, packages/orbit-components/src/ButtonGroup/ButtonGroup.stories.tsx, packages/orbit-components/src/Card/Card.stories.tsx, packages/orbit-components/src/CarrierLogo/CarrierLogo.stories.tsx, packages/orbit-components/src/Checkbox/Checkbox.stories.tsx, packages/orbit-components/src/ChoiceGroup/ChoiceGroup.stories.tsx, packages/orbit-components/src/Collapse/Collapse.stories.tsx, packages/orbit-components/src/CountryFlag/CountryFlag.stories.tsx
Closes https://kiwicom.atlassian.net/jira/software/c/projects/FEPLT/boards/404?selectedIssue=FEPLT-2072
=> chore: migrate Checkbox story from CSF2 to CSF3

packages/orbit-components/src/Coupon/Coupon.stories.tsx, packages/orbit-components/src/Dialog/Dialog.stories.tsx, packages/orbit-components/src/Drawer/Drawer.stories.tsx, packages/orbit-components/src/ErrorForms.stories.tsx, packages/orbit-components/src/FeatureIcon/FeatureIcon.stories.tsx, packages/orbit-components/src/Hide/Hide.stories.tsx, packages/orbit-components/src/HorizontalScroll/HorizontalScroll.stories.tsx, packages/orbit-components/src/Icon/Icon.stories.tsx, packages/orbit-components/src/primitives/Primitives.stories.tsx
Closes https://kiwicom.atlassian.net/browse/FEPLT-2073
=> FEPLT-2073: batch2 - migrate from CSF2 to CSF3

packages/orbit-components/src/Heading/Heading.stories.tsx, packages/orbit-components/src/Illustration/Illustration.stories.tsx, packages/orbit-components/src/Inline/Inline.stories.tsx, packages/orbit-components/src/InputField/InputField.stories.tsx, packages/orbit-components/src/InputFile/InputFile.stories.tsx, packages/orbit-components/src/InputGroup/InputGroup.stories.tsx, packages/orbit-components/src/InputSelect/InputSelect.stories.tsx, packages/orbit-components/src/Layout/Layout.stories.tsx
Closes https://kiwicom.atlassian.net/browse/FEPLT-2074
=> FEPLT-2074: Migrate Stories to CSF3 - Batch 3

packages/orbit-components/src/primitives/ButtonPrimitive/index.tsx
Closes https://kiwicom.atlassian.net/browse/FEPLT-2109
=> fix(ButtonPrimitive): make button text non-selectable

packages/orbit-components/.storybook/orbitDecorator.tsx, packages/orbit-components/.storybook/preview.ts
Part of https://kiwicom.atlassian.net/browse/FEPLT-2146
=> chore: add a11y highlighting rules to Storybook

docs/services/changelog.mjs
=> Change remark import after update

docs/plugins/contributors/fetchContributors.mjs
<details open>
This PR filters out a specific contributor, 'devin-ai-integration[bot]', from the list of contributors fetched in the `fetchUsers` function.
<details>
```mermaid
participant F as fetchContributors
participant CF as ContributorFilter
F->>CF: Check contributor data
Note over CF: Original filter: Skip @actions company
Note over CF: New filter added: Skip devin-ai-integration[bot]
CF-->>F: Return filtered contributor
```
</details>
<details>
<table>
<tr><td><a href=https://github.com/kiwicom/orbit/pull/4594/files#diff-8b530ed3d284e9e13b391e4ecc1c259b167a73971178a5 …
=> chore: filter out devin from contributors

packages/orbit-components/src/Card/Card.stories.tsx, packages/orbit-components/src/Card/CardSection/index.tsx, packages/orbit-components/src/Card/components/Header.tsx
https://skypicker.slack.com/archives/C7T7QG7M5/p1738592484912889
<details open>
This PR reverts a previous refactor of the `Card` component aimed at improving accessibility. It restores the original structure and functionality of the `CardSection` and `Header` components.
<details>
```mermaid
actor User
participant Card
participant CardSection
participant Header
participant Button
User->>Card: Views Card
Card->>CardSection: Renders with expandable=true
CardSection->>Button: Creates expandable button
Button->>Header: Renders header content
Header-->>Button: Shows title, description & actions
Note over Button: New button wrapper<br/>with aria controls …
```
=> Revert "feat(Card): refactor component for improved accessibility"

.github/workflows/code-review.yml
<details open>
This PR introduces a GitHub Actions workflow for analyzing pull request diffs using a Gemini-powered analysis script.
<details>
```mermaid
participant Action as GitHub Action
participant Python as Python Script
participant Gemini as Gemini API
participant GitHub as GitHub API
PR->>Action: PR opened/synchronized
Action->>Action: Checkout repository
Action->>Action: Setup Python environment
Action->>Action: Get PR diff
Action->>Python: Execute analyze_pr.py
Python->>Python: Get codebase content
Python->>Python: Prepare analysis prompt
Python->>Gemini: Send prompt for analysis
Gemini-->>Python: Return …
```
=> chore: try Gemini-powered code review

packages/orbit-components/src/Textarea/README.md, packages/orbit-components/src/Textarea/__tests__/index.test.tsx, packages/orbit-components/src/Textarea/index.tsx, packages/orbit-components/src/Textarea/types.d.ts
Closes https://kiwicom.atlassian.net/browse/FEPLT-2263
The accessibility documentation will be done on a separate task.
<details open>
This PR introduces accessibility improvements to the Textarea component by adding `aria-label` and `aria-labelledby` props, and updates the README documentation accordingly.
<details>
```mermaid
participant Textarea
participant Label
participant TextareaElement
participant ErrorTooltip
User->>Textarea: Interacts with component
Textarea->>Label: Renders FormLabel (if label prop exists)
Note over Label: Includes error state<br/>and required indicator
Textarea->>TextareaElement: Renders textarea with: …
```
=> Textarea accessibility improvements

.github/workflows/code-review.yml
<details open>
This PR modifies the GitHub Actions workflow to enable Gemini-powered review on all pull requests by adjusting event types and updating environment variables.
<details>
```mermaid
participant GHA as GitHub Action
participant LLM as LLM Analyzer
participant GH as GitHub API
PR->>GHA: Trigger on PR open/sync
Note over GHA: Add Gemini API Key
GHA->>LLM: Send code for analysis
LLM-->>GHA: Return analysis results
GHA->>GHA: Read analysis from file
GHA->>GH: Create PR comment with analysis
Note over GH: Comment posted with<br/>LLM Analysis results
```
</details>
<details> …
=> chore: enable Gemini-powered review on all pull requests

docs/src/__examples__/Illustration/DEFAULT.tsx, packages/orbit-components/src/Illustration/README.md, packages/orbit-components/src/Illustration/consts.mts, packages/orbit-components/src/Illustration/types.d.ts
JIRA: FEPLT-2369
<details open>
This PR adds a new illustration type called `PriceChange` to the Illustration component.
<details>
```mermaid
participant Types as types.d.ts
participant Consts as consts.mts
participant Docs as README.md
participant Examples as DEFAULT.tsx
Note over Types,Examples: Adding PriceChange Illustration
Types->>Consts: Add "PriceChange" to illustration types
Consts->>Docs: Add "PriceChange" to documentation
Docs->>Examples: Add "PriceChange" to example illustrations
```
</details>
<details>
<table>
<tr><td><a …
=> feat(Illustration): add PriceChange illustration

.github/workflows/code-review.yml
instead of creating a new one all the time.
This addresses feedback shared by the team on this new workflow.
<details open>
This PR updates the workflow to modify an existing comment instead of creating a new one each time, addressing team feedback on the workflow.
<details>
```mermaid
participant GH as GitHub Workflow
participant API as GitHub API
GH->>PR: Get PR Number
GH->>API: List Comments (max 100)
API-->>GH: Return Comments
alt Bot Comment Exists
GH->>API: Update Existing Comment
API-->>PR: Update Comment with LLM Analysis
else No Bot Comment
GH->>API: Create New Comment
API-->>PR: Add New Comment with LLM …
```
=> chore: make Gemini-review update its summary comment

.github/workflows/code-review.yml
This addresses feedback shared by the team on this new workflow.
<details open>
This PR refines the prompt used for code review in the GitHub Actions workflow, making it more concise and actionable. It restructures the request for feedback to focus on key points and maintain consistency.
<details>
```mermaid
participant GH as GitHub Workflow
participant LLM as Language Model
GH->>PR: Fetch PR details & codebase
GH->>LLM: Send enhanced prompt with:
Note over LLM: New structured format:<br/>1. Summary<br/>2. Key Points<br/>3. Style & Consistency
LLM-->>GH: Return formatted review
GH->>PR: Post structured review
``` …
=> chore: make Gemini-review more concise and actionable

docs/src/__examples__/InputFile/DEFAULT.tsx, docs/src/__examples__/InputFile/HELP.tsx, docs/src/__examples__/InputFile/STATES.tsx, docs/src/__examples__/InputFile/button_label.tsx, docs/src/__examples__/InputSelect/DEFAULT.tsx, docs/src/documentation/05-development/04-migration-guides/01-v23.mdx, packages/orbit-components/playroom/snippets/Inputs.ts, packages/orbit-components/src/ErrorForms.stories.tsx, packages/orbit-components/src/FormLabel/__tests__/index.test.tsx, packages/orbit-components/src/FormLabel/index.tsx, packages/orbit-components/src/InputFile/InputFile.stories.tsx, packages/orbit-components/src/InputFile/README.md, packages/orbit-components/src/InputFile/__tests__/index.test.tsx, packages/orbit-components/src/InputFile/index.tsx, packages/orbit-components/src/InputFile/types.d.ts, packages/orbit-components/src/InputSelect/InputSelect.ct-story.tsx, packages/orbit-components/src/InputSelect/InputSelect.stories.tsx, packages/orbit-components/src/InputSelect/README.md, packages/orbit-components/src/InputSelect/__tests__/index.test.tsx, packages/orbit-components/src/InputSelect/index.tsx, packages/orbit-components/src/InputSelect/types.d.ts, packages/orbit-components/src/Tabs/README.md, packages/orbit-components/src/Tabs/components/TabList/index.tsx, packages/orbit-components/src/Tabs/components/TabList/types.d.ts, packages/orbit-components/transforms/transforms-v23.js
Closes https://kiwicom.atlassian.net/browse/FEPLT-2325
<details open>
This PR removes hardcoded `aria-labels` from various components and introduces required props for `labelRemove` in `InputFile` and `labelClear` in `InputSelect` components.
<details>
```mermaid
participant InputFile
participant InputSelect
participant AccessibilitySystem
Note over InputFile,InputSelect: New Accessibility Requirements
User->>InputFile: Interacts with file input
InputFile->>AccessibilitySystem: Required labelRemove="Remove file"
Note right of InputFile: New mandatory prop for<br/>remove button accessibility
User->>InputFile: Clicks remove file button …
```
=> Remove hardcoded aria-labels

docs/src/documentation/03-components/04-overlay/drawer/03-accessibility.mdx, packages/orbit-components/src/Drawer/README.md
AI-generated, with little tweaks by me
FEPLT-2355
<details open>
This PR adds an Accessibility tab for the Drawer component, detailing keyboard interactions, ARIA attributes, and best practices for accessibility.
<details>
```mermaid
participant ToggleElement
participant Drawer
participant FocusManager
participant KeyboardNav
User->>ToggleElement: Clicks/triggers drawer
ToggleElement->>Drawer: Opens drawer (shown=true)
Note over ToggleElement: Sets aria-expanded=true
Note over ToggleElement: Sets aria-controls=drawerID
Drawer->>FocusManager: Trap focus inside drawer
alt Keyboard Navigation
KeyboardNav->>Drawer: Press ESC …
```
=> Add Accessibility tab for the Drawer component

.github/workflows/code-review.yml
<details open>
This PR updates the model used in the `query_gemini` function from `gemini-2.0-flash-thinking-exp-01-21` to `gemini-2.0-flash-001`.
<details>
```mermaid
participant Client
participant query_gemini
participant GenerativeModel
Client->>query_gemini: Send prompt
query_gemini->>GenerativeModel: Initialize model (gemini-2.0-flash-001)
GenerativeModel-->>query_gemini: Return model instance
query_gemini-->>Client: Return response
```
</details>
<details>
<table>
<tr><td><a href=https://github.com/kiwicom/orbit/pull/4724/files#diff-618edb6c8aa70b1c7352dc7e9bea11fb5594 …
=> chore(ci): use Gemini 2.0 Flash model

docs/src/documentation/03-components/05-input/checkbox/03-accessibility.mdx, packages/orbit-components/src/Checkbox/README.md, packages/orbit-components/src/Checkbox/index.tsx, packages/orbit-components/src/Checkbox/types.d.ts
**feat(Checkbox): add aria controls and describedby props**. 
Closes FEPLT-2448
**docs: add Accessibility tab for the Checkbox component**. 
Closes FEPLT-2412
https://kiwicom.atlassian.net/browse/FEPLT-2448
https://kiwicom.atlassian.net/browse/FEPLT-2412
<details open>
This PR adds new accessibility features to the Checkbox component, including new ARIA props and documentation for accessibility best practices.
<details>
```mermaid
actor User
participant Checkbox
participant AriaAttributes
Note over Checkbox: Enhanced with accessibility props
User->>Checkbox: Interacts with checkbox
alt When ariaControls is set …
```
=> Checkbox: new aria props and a11y docs

docs/src/documentation/03-components/10-progress-indicators/skeleton/03-accessibility.mdx, packages/orbit-components/src/Skeleton/README.md
Closes https://kiwicom.atlassian.net/browse/FEPLT-2406
<details open>
This PR adds an Accessibility tab for the Skeleton component, detailing accessibility features, props, best practices, and examples for better usability with assistive technologies.
<details>
```mermaid
participant Skeleton
participant Container
User->>Skeleton: Render with title="Loading content"
Note over Skeleton: Sets aria-hidden="true" on SVG
Note over Skeleton: Creates visually hidden element with title
ScreenReader->>Skeleton: Reads loading state
alt Loading State
Container->>Container: Set aria-busy="true"
Container->>Skeleton: …
```
=> Add Accessibility tab for the Skeleton component

docs/src/documentation/03-components/03-information/notificationbadge/03-accessibility.mdx, packages/orbit-components/src/NotificationBadge/NotificationBadge.stories.tsx, packages/orbit-components/src/NotificationBadge/README.md
Closes https://kiwicom.atlassian.net/browse/FEPLT-2374
<details open>
This PR adds accessibility documentation for the NotificationBadge component, including details on accessibility props, automatic features, best practices, and examples.
<details>
```mermaid
participant NotificationBadge
participant ARIA System
Note over NotificationBadge: Component initialized with<br/>role="status"
alt With Numerical Content
User->>NotificationBadge: View badge with number
NotificationBadge->>ARIA System: Set aria-label="10 unread notifications"
ARIA System->>Screen Reader: Announce "10 unread notifications, status"
else …
```
=> docs(NotificationBadge): add accessibility documentation

docs/src/documentation/03-components/08-visuals/countryflag/03-accessibility.mdx
Closes https://kiwicom.atlassian.net/browse/FEPLT-2402
<details open>
This PR adds accessibility documentation for the CountryFlag component, detailing its props, automatic accessibility features, best practices, and examples of usage.
<details>
```mermaid
actor User
participant SR as Screen Reader
participant CF as CountryFlag
Note over CF: Component can be used in two modes
rect rgb(200, 250, 200)
Note over User,CF: Accessible Mode (with name prop)
User->>CF: Render with name="Czech Republic"
CF->>SR: Announce "Czech Republic, image"
end
rect rgb(240, 240, 240)
Note over User,CF: Decorative Mode (no name prop)
User->>CF: Render without name prop …
```
=> docs(CountryFlag): add a11y docs for CountryFlag component

packages/orbit-components/src/List/README.md, packages/orbit-components/src/List/__tests__/index.test.tsx, packages/orbit-components/src/List/index.tsx, packages/orbit-components/src/List/types.ts
<details open>
This PR adds the `ariaLabelledBy` prop to the List component for improved accessibility, updates the README to include usage examples, and adds a test case to verify the new prop functionality.
<details>
```mermaid
participant Heading
participant List
participant ListItem
App->>Heading: Create with id="flights-heading"
Note over Heading: Renders heading for list
App->>List: Create with ariaLabelledby="flights-heading"
Note over List: Associates list with heading<br/>via aria-labelledby
List->>ListItem: Render list items
Note over ListItem: Display list content
List-->>App: Return accessible list component
```
</details> …
=> fix(List): add ariaLabelledBy prop

docs/src/documentation/03-components/07-interaction/slider/03-accessibility.mdx, packages/orbit-components/src/Slider/README.md, packages/orbit-components/src/Slider/Slider.stories.tsx, packages/orbit-components/src/Slider/__tests__/index.test.tsx, packages/orbit-components/src/Slider/index.tsx, packages/orbit-components/src/Slider/utils/index.ts
- **fix(Slider): keyboard support**
- **docs(Slider): add accessibility documentation**
resolves FEPLT-2376
<details open>
This PR introduces keyboard support for the Slider component and adds accessibility documentation, ensuring that the component is fully keyboard accessible and compliant with accessibility standards.
<details>
```mermaid
participant Slider
participant KeyboardHandler
participant AccessibilityManager
participant ValueController
User->>Slider: Interacts with slider
alt Keyboard Navigation
User->>KeyboardHandler: Presses navigation key
KeyboardHandler->>KeyboardHandler: Check key type
alt Arrow Keys …
```
=> FEPLT-2376: Slider keyboard support fix and a11y docs

docs/src/documentation/03-components/02-structure/separator/03-accessibility.mdx, packages/orbit-components/src/Separator/README.md, packages/orbit-components/src/Separator/index.tsx, packages/orbit-components/src/Separator/types.ts
Closes FEPLT-2389
<details open>
This PR adds accessibility documentation for the Separator component and updates the README to include the new `ariaHidden` prop.
<details>
```mermaid
participant Separator
Note over Separator: New accessibility props added
alt Semantic Separator (Default)
User->>Separator: Render <Separator/>
Separator->>ScreenReader: Announce "Separator"
end
alt Decorative Separator
User->>Separator: Render <Separator ariaHidden/>
Separator->>ScreenReader: No announcement
end
alt Labeled Separator
User->>Separator: Render <Separator label="Contact Information"/>
Separator->>ScreenReader: …
```
=> docs(Separator): add Accessibility documentation and update readme
