icons/package.json
package.json

- Adds new folder for icons project
- Adds base package.json

Icons: Add icons project

---

blkn/src/Typography/index.js

Adjust typography colors to match with designs in zeplin

---

blkn/src/Typography/index.js
blkn/src/constants.js

Introduce constants for blkn

---

blkn/package.json
blkn/readme.md
yarn.lock

- Adds Concurrently script
- Adds readme to BLKN
- Adds instruction on how to develop in blkn locally without publishing
- Adds babel watch

Blkn readme

---

blkn/package.json
blkn/src/Checkbox/Icon.js
blkn/src/Checkbox/index.js
blkn/src/Typography/index.js
blkn/src/index.js
blkn/stories/Checkbox.js

Add Checkbox for blkn

---

blkn/src/Input/Label.js
blkn/src/Input/MaybeError.js
blkn/src/InputTextarea/index.js
blkn/stories/InputTextarea.js

Add textarea

---

blkn/package.json

Update build script to make blkn components distributable

---

blkn/src/constants.js

Add basic colors to constant
https://marvelapp.com/79c0g9e/screen/36355252

BLKN: add colors to constants

---

blkn/.babelrc
blkn/package.json
blkn/src/Select/__tests__/Select.test.js
blkn/src/Select/__tests__/__snapshots__/Select.test.js.snap
blkn/src/Select/index.js
blkn/src/Typography/index.js
blkn/src/index.js
blkn/stories/Select.js
yarn.lock

Add Select component

---

blkn/package.json
blkn/src/index.js
package.json

- Adds postinstall step to generate icons
- rc4 unpublished due to a breaking bug

BLKN: Release 0.0.0-rc5

---

.eslintignore
blkn/package.json
blkn/src/Typography/index.js
blkn/stories/Typography.js
yarn.lock

It also sets "normal" size as default value.

Add storybook examples for Typography component

---

blkn/src/Container/Header.js
blkn/src/Typography/index.js
blkn/stories/Typography.js

Fix font-size of Header

---

blkn/src/Container/Header.js
blkn/stories/Header.js

Closes #47 
~~Blocked by #45~~
---

Header with icon

---

blkn/src/Typography/index.js
blkn/src/constants.js
blkn/stories/Typography.js

BLKN: Improve Typography - new type: active and new variant: medium

---

blkn/src/Container/Section.js
blkn/stories/Section.js

BLKN: add compact type to Section

---

blkn/src/Container/Section.js
blkn/src/constants.js
blkn/stories/Header.js

closes [#53](https://github.com/kiwicom/react-kiwi-ui/issues/53)

BLKN: constants

---

blkn/package.json
blkn/src/SystemMessage/IconWrapper.js
blkn/src/SystemMessage/Message.js
blkn/src/SystemMessage/Title.js
blkn/src/SystemMessage/__tests__/IconWrapper.test.js
blkn/src/SystemMessage/__tests__/Title.test.js
blkn/src/SystemMessage/__tests__/index.test.js
blkn/src/SystemMessage/index.js
blkn/src/constants.js
blkn/src/index.js
blkn/stories/SystemMessage.js
package-lock.json
package.json
yarn.lock

BLKN: 39 system messages

---

blkn/package.json
blkn/src/Button/IconWrapper.js
blkn/src/Button/__tests__/IconWrapper.test.js
blkn/src/Button/__tests__/index.test.js
blkn/src/Button/index.js
blkn/src/constants.js
blkn/stories/Button.js
yarn.lock

BLKN: 37 button

---

blkn/package.json

BLKN: Release 0.1

---

blkn/package.json

Don't include stories.js.flow to package

---

.github/contributing.md
.prettierignore
package.json
readme.md
src/icons/readme.md

Rebranding to Orbit Components

---

.circleci/config.yml
CODEOWNERS

Update Circle CI build settings to match with current structure

---

src/icons/.gitignore

So our icons gitignore ignored itself

Fix icons gitignore ignoring itself

---

.editorconfig
.eslintrc
config/build.js
config/enzymeConfig.js
src/Button/__tests__/IconWrapper.test.js
src/Button/__tests__/index.test.js
src/SystemMessage/__tests__/IconWrapper.test.js
src/SystemMessage/__tests__/Title.test.js
src/SystemMessage/__tests__/index.test.js
src/icons/.eslintrc
src/icons/.gitignore

Let's improve code quality by following steps:
- introduce editorconfig, which was missing
- make sure flow annotation is required across the codebase

Always require flow annotation & introduce editorconfig

---

package.json
src/Button/__tests__/IconWrapper.test.js
src/SystemMessage/SystemMessage.stories.js
src/icons/readme.md
src/index.js
yarn.lock

Fix Icons export

---

src/Button/Button.stories.js
src/Button/__tests__/__snapshots__/index.test.js.snap
src/Button/__tests__/index.test.js
src/Button/index.js

Add children to button

---

.eslintrc
src/Button/Button.stories.js
src/Button/IconWrapper.js
src/Button/__tests__/IconWrapper.test.js
src/Button/__tests__/index.test.js
src/Button/index.js
src/Checkbox/Checkbox.stories.js
src/Checkbox/index.js
src/Container/Header.js
src/Container/Section.js
src/Container/__tests__/Header.test.js
src/Container/__tests__/Section.test.js
src/FieldFeedback/__tests__/FieldFeedback.test.js
src/FieldFeedback/index.js
src/Input/Label.js
src/InputText/index.js
src/InputTextarea/index.js
src/Select/__tests__/Select.test.js
src/Select/index.js
src/SystemMessage/IconWrapper.js
src/SystemMessage/SystemMessage.stories.js
src/SystemMessage/__tests__/IconWrapper.test.js
src/SystemMessage/__tests__/Title.test.js
src/SystemMessage/__tests__/index.test.js
src/SystemMessage/index.js
src/Typography/index.js

Introduce additional eslint rules from import plugin

---

.circleci/config.yml
package.json
yarn.lock

add deployment of Storybook to Github pages

---

.github/contributing.md
readme.md

Update DOCs with new important contribution rules & storybook link

---

.circleci/config.yml
package.json

Fix deployer to correctly skip ci

---

src/Radio/index.js

Added prop value to Radio component

---

.storybook/Storyhosts.test.js
package.json
src/Button/__snapshots__/Button.stories.storyshot
src/Checkbox/__snapshots__/Checkbox.stories.storyshot
src/Container/Section.stories.js
src/Container/__snapshots__/Header.stories.storyshot
src/InputText/__snapshots__/InputText.stories.storyshot
src/InputTextarea/__snapshots__/InputTextarea.stories.storyshot
src/Radio/__snapshots__/Radio.stories.storyshot
src/Select/__snapshots__/Select.stories.storyshot
src/SystemMessage/__snapshots__/SystemMessage.stories.storyshot
src/Typography/__snapshots__/Typography.stories.storyshot
yarn.lock

Closes #68 
- Fully automated (We don't need to worry about a developer forgetting to run this test)
- Diffable in console
- Fast
- Checks that something renders
- JSX generated classnames are not human readable (Unless someone knows how to get the actual CSS values into the snapshot)
- Does not test visual regressions ( Any changes are visible through JSX classnames and the reviewer needs to check the diff manually)
- Needs good discipline on the side of the reviewer
I think this test is a baseline sanity check. We should still invest time into visual regression testing, but this is the easiest test to carry us over. It's important for any utility function refactoring to make sure no unintended changes got into the PR.

Storyshots

---

src/Button/__snapshots__/Button.stories.storyshot
src/SystemMessage/__snapshots__/SystemMessage.stories.storyshot

Fix storyshot snapshots

---

.github/contributing.md

Remove workspaces from Contribution Guide, rewrite testing section

---

src/Checkbox/index.js

Added value prop to checkbox

---

package.json
yarn.lock

Fix Storybook addons channel error

---

.eslintrc

Turned off ESLint rule because of conflict between Flow and ESLint.
closes: #123

Turn off ESLint rule

---

package.json
src/Button/Button.stories.js
src/Button/IconWrapper.js
src/Button/__snapshots__/Button.stories.storyshot
src/Button/__tests__/IconWrapper.test.js
src/Button/__tests__/index.test.js
src/Button/index.js
yarn.lock

Add new button component

---

readme.md
src/icons/readme.md

Added icons/readme.md

---

src/Button/__tests__/index.test.js
src/Heading/Heading.stories.js
src/Heading/__snapshots__/Heading.stories.storyshot
src/Heading/__tests__/__snapshots__/index.test.js.snap
src/Heading/__tests__/index.test.js
src/Heading/index.js
src/index.js

Add new Heading component

---

config/build.js
package.json
src/Button/IconWrapper.js
src/Button/__snapshots__/Button.stories.storyshot
src/Button/index.js
src/CarrierLogo/index.js
src/Heading/index.js
src/Icon/Icon.stories.js
src/Icon/__snapshots__/Icon.stories.storyshot
src/Icon/__tests__/__snapshots__/index.test.js.snap
src/Icon/__tests__/index.test.js
src/Icon/index.js
src/SystemMessage/IconWrapper.js
src/SystemMessage/__snapshots__/SystemMessage.stories.storyshot
src/SystemMessage/index.js
src/Text/index.js
src/TextLink/index.js
src/Theming/ThemeProvider.js
src/Theming/ThemeSwitcher.js
src/Theming/ThemedSample.js
src/Theming/Theming.stories.js
src/Theming/__tests__/ThemedSample.test.js
src/index.js
yarn.lock

New Icon component

---

src/TextLink/TextLink.stories.js
src/TextLink/__snapshots__/TextLink.stories.storyshot
src/TextLink/__tests__/__snapshots__/index.test.js.snap
src/TextLink/__tests__/index.test.js
src/TextLink/index.js

Replaced darken for Hover Token
TextLink uses children instead of title prop
Updated tests

Update TextLink component

---

src/CarrierLogo/CarrierLogo.stories.js
src/CarrierLogo/__snapshots__/CarrierLogo.stories.storyshot
src/CarrierLogo/__tests__/__snapshots__/index.test.js.snap
src/CarrierLogo/__tests__/index.test.js
src/CarrierLogo/index.js

Update stories, use ternary instead of lets

Update CarrierLogo stories

---

src/Text/Text.stories.js
src/Text/__snapshots__/Text.stories.storyshot
src/Text/__tests__/__snapshots__/index.test.js.snap
src/Text/index.js

Update Text component

---

src/index.js

Fix exports

---

package.json

Changelog
```
Button
Alert
Heading
Text
CarrierLogo
moved deprecated components
`console.warn` deprecated components
```

Release v0.0.0-rc8

---

src/Alert/Alert.js
src/Alert/__snapshots__/Alert.stories.storyshot
src/Alert/__tests__/__snapshots__/index.test.js.snap

Updated styling for links in Alert

Update Alert component

---

src/Alert/Alert.js
src/Alert/__snapshots__/Alert.stories.storyshot
src/Alert/__tests__/__snapshots__/index.test.js.snap

Update style in Alert

---

package.json

- refactored and declared props for each component
- rewrote to style-components
- Removed prop `className`
- Usage without <ThemeProvider /> - import from lib/Text/Text
For usage check our storybook
https://kiwicom.github.io/orbit-components/

Release v0.0.0-rc13

---

src/Text/index.js.flow

Fixed missing flow annotation for Text component

FIX: Text component index flow

---

package.json

- Added icon `BaggageStorage`
- Added `<Text>` base import flow declaration
- Theming support in `<CarrierLogo />`
- Added `type` - airline | bus | train to `<CarrierLogo />`
- Fixed Alert content wrapping in IE
For usage check our storybook
https://kiwicom.github.io/orbit-components/

Release v0.0.0-rc14

---

src/Card/Card.js
src/Card/Card.js.flow
src/Card/Card.stories.js
src/Card/CardContent/CardContent.js
src/Card/CardContent/CardContent.js.flow
src/Card/CardContent/index.js
src/Card/CardContent/index.js.flow
src/Card/CardHeader/CardHeader.js
src/Card/CardHeader/CardHeader.js.flow
src/Card/CardHeader/index.js
src/Card/CardHeader/index.js.flow
src/Card/CardSection/CardSection.js
src/Card/CardSection/CardSection.js.flow
src/Card/CardSection/index.js
src/Card/CardSection/index.js.flow
src/Card/__snapshots__/Card.stories.storyshot
src/Card/__tests__/index.test.js
src/Card/index.js
src/Card/index.js.flow
src/index.js
src/index.js.flow

Add a new Card component.
Closes: #119 and #120

Add new Card component

---

package.json

- Added strict proptypes to Select
- Declared flow types for base import
- Added `CircleSmall`, `ItemCompleted`
- Updated `BaggageStorage`, `Circle`, `MenuHamburger`, `NewWindow`
- Added new `<Card />` replacement of `<Section />`
For usage check our storybook
https://kiwicom.github.io/orbit-components/

Release 0.0.0-rc15

---

src/Button/Button.js.flow
src/ButtonLink/ButtonLink.js.flow
src/TextLink/TextLink.js.flow

onClick should return promise
Closes #247

DEV: Flow allow promise in return

---

src/Alert/Alert.js
src/Alert/Alert.stories.js
src/Alert/__snapshots__/Alert.stories.storyshot
src/Alert/__tests__/__snapshots__/index.test.js.snap
src/Button/Button.js
src/Button/__snapshots__/Button.stories.storyshot
src/ButtonLink/ButtonLink.js
src/ButtonLink/__snapshots__/ButtonLink.stories.storyshot
src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
src/TextLink/TextLink.js
src/TextLink/TextLink.js.flow

Fixed flex and color of possible links variation (Button, ButtonLink, TextLink, native a)

FIX: Alert links and flex

---

package.json

Merge when all new and deprecated components are ready.

WIP: Release 0.1.0

---

package.json
yarn.lock

Updated tokens to unify version

Update tokens to 0.1.0

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/new-component.md

DOCS: Update issue templates

---

config/build.js
package.json
readme.md
src/Icon/README.md
src/Icon/__snapshots__/Icon.stories.storyshot
src/Icon/consts.js
src/Icon/index.js.flow
yarn.lock

Changed icons build config.
- Config is now using SVGR which generates icons components with proper JSX attributes.
- Fixed typo `terciary` => `tertiary`.
- Added flow declaration for every icon.
closes #203

ICONS: Change build config

---

src/Heading/Heading.stories.js
src/Heading/README.md
src/Heading/__snapshots__/Heading.stories.storyshot
src/Heading/__tests__/__snapshots__/index.test.js.snap
src/Heading/__tests__/index.test.js
src/Heading/index.js
src/Heading/index.js.flow
yarn.lock

Add prop inverted - white color
Removed createComponentFromTagProp
Refactored StyleHeading component
Improved stories of Heading
Improved enzyme test

UPDATE: Add inverted to Heading

---

src/Textarea/README.md
src/Textarea/Textarea.stories.js
src/Textarea/__snapshots__/Textarea.stories.storyshot
src/Textarea/__tests__/index.test.js
src/Textarea/index.js
src/Textarea/index.js.flow

Changed prop `children` to `value`

FIX: Textarea value prop

---

src/Icon/consts.js
src/Icon/index.js.flow
src/List/List.stories.js

FIX: Icon color names

---

src/Alert/index.js

Was importing all the icons possible. Big bundles. :(

Alert: Fix icon imports

---

src/Checkbox/__snapshots__/Checkbox.stories.storyshot
src/Checkbox/index.js
src/InputField/__snapshots__/InputField.stories.storyshot
src/InputField/index.js
src/Radio/__snapshots__/Radio.stories.storyshot
src/Radio/index.js
src/Select/__snapshots__/Select.stories.storyshot
src/Select/index.js
src/Textarea/__snapshots__/Textarea.stories.storyshot
src/Textarea/index.js

UPDATE: Form components border focuses

---

readme.md

Fixed main image and usage example (needed for orbit.kiwi)

FIX: Root readme.md

---

src/ServiceLogo/README.md
src/ServiceLogo/ServiceLogo.stories.js
src/ServiceLogo/__snapshots__/ServiceLogo.stories.storyshot
src/ServiceLogo/__tests__/__snapshots__/index.test.js.snap
src/ServiceLogo/__tests__/index.test.js
src/ServiceLogo/consts.js
src/ServiceLogo/index.js
src/ServiceLogo/index.js.flow
src/index.js
src/index.js.flow

TODO:
* Grayscale (need be on S3)
* Dynamic sizes

NEW: ServiceLogo component

---

src/Illustration/consts.js
src/Illustration/index.js.flow

New `AirHelp`, `FastTrack` and `OnlineCheckIn`
**Waiting to be uploaded**
Close #338

Illustrations: New from Orbit UI 0.26.0

---

package.json

- NEW: `ServiceLogo`
- NEW: `InputFile`
- NEW: Asterisk at labels
- NEW: Loading
- NEW: Icons: `AirplaneReturn`,  `AirplaneUp`, `GpsIos`
- NEW: Illustration: `AirHelp`, `FastTrack`, `OnlineCheckIn`
- UPDATE: Icons: `AirplaneDown` `AirplaneRight`
- UPDATE: Input with FormLabel in prefix (Compact input)
- UPDATE: Loading button

Release 0.10.0

---

package.json

- NEW: Modal
- NEW: Portal
- FIX: README.md for Icons
- UPDATE: InlineLabel prop in InputField
- DOCS: Move theming to different folder

Release: 0.11.0

---

src/Alert/__snapshots__/Alert.stories.storyshot
src/Button/__snapshots__/Button.stories.storyshot
src/Button/index.js
src/ButtonGroup/__snapshots__/ButtonGroup.stories.storyshot
src/ButtonLink/__snapshots__/ButtonLink.stories.storyshot
src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
src/ButtonLink/index.js
src/InputField/__snapshots__/InputField.stories.storyshot
src/InputFile/__snapshots__/InputFile.stories.storyshot
src/Loading/__snapshots__/Loading.stories.storyshot
src/Modal/__snapshots__/Modal.stories.storyshot

FIX: Add focus to Button

---

package.json

- FIX: Focus in buttons
- FIX: Unnecessary overflows
- FIX: Theming in Button and ButtonLink

Release 0.11.1

---

src/Alert/Alert.stories.js
src/Alert/__snapshots__/Alert.stories.storyshot
src/InputField/InputField.stories.js
src/InputField/__snapshots__/InputField.stories.storyshot
src/InputField/index.js
src/InputGroup/__snapshots__/InputGroup.stories.storyshot
src/ServiceLogo/index.js
src/ServiceLogo/index.js.flow

Updated storybook:
`ServiceLogo` as a suffix in `InputField`
Fixed size of `Button` in `Alert`

UPDATE: ServiceLogo as suffix in Input

---

src/Select/Select.stories.js
src/Select/__snapshots__/Select.stories.storyshot

Added `CountryFlag` as prefix to `Select`

UPDATE: CountryFlag as prefix in Select

---

src/Alert/__snapshots__/Alert.stories.storyshot
src/Button/__snapshots__/Button.stories.storyshot
src/Button/index.js
src/ButtonGroup/__snapshots__/ButtonGroup.stories.storyshot
src/InputFile/__snapshots__/InputFile.stories.storyshot
src/Loading/__snapshots__/Loading.stories.storyshot
src/Modal/__snapshots__/Modal.stories.storyshot

Fixed ugly shadow in bordered buttons

FIX: Bordered buttons border

---

src/Radio/__snapshots__/Radio.stories.storyshot
src/Radio/__tests__/__snapshots__/index.test.js.snap
src/Radio/index.js

Fixed incorrect type in <Radio /> input
Closes #362

FIX: Incorrect type in <Radio />

---

package.json

- UPDATE: CountryFlag as prefix in Select
- UPDATE: ButtonAlert small
- UPDATE: ServiceLogo for Input
- FIX: Incorrect type in <Radio />
- FIX: Bordered buttons border

Release 0.11.2

---

src/InputField/__snapshots__/InputField.stories.storyshot
src/InputField/index.js
src/InputGroup/__snapshots__/InputGroup.stories.storyshot
src/InputGroup/index.js
src/Select/__snapshots__/Select.stories.storyshot
src/Select/index.js

FIX: InputField z-index

---

src/ClickOutside/index.js
src/Modal/ModalHeader/index.js
src/Modal/__snapshots__/Modal.stories.storyshot
src/Modal/index.js

FIX: Modal scroll and height

---

package.json
src/Heading/index.js.flow

Fixed flow type for `StyledHeading`

FIX: Heading flow

---

src/InputField/__snapshots__/InputField.stories.storyshot
src/InputField/index.js
src/InputGroup/__snapshots__/InputGroup.stories.storyshot
src/Select/__snapshots__/Select.stories.storyshot
src/Select/index.js

Fixed unvisible prefix and suffix

FIX: Input, Select prefix and suffix

---

src/Loading/__snapshots__/Loading.stories.storyshot
src/Loading/index.js

Omitted prop `type` in render of Loading

FIX: omit type in Loading

---

src/Alert/Alert.stories.js
src/Alert/__tests__/__snapshots__/index.test.js.snap
src/Alert/consts.js
src/Alert/index.js
src/Alert/index.js.flow

Fixed Alert getting theme from ThemeProvider

FIX: Alert ThemeProvider

---

src/Badge/Badge.stories.js
src/Badge/__tests__/__snapshots__/index.test.js.snap
src/Badge/__tests__/index.test.js
src/Badge/consts.js
src/Badge/index.js
src/Badge/index.js.flow

Fixed Badge getting theme from ThemeProvider

FIX: Badge ThemeProvider

---

src/Badge/Badge.stories.js
src/Badge/__snapshots__/Badge.stories.storyshot
src/Badge/consts.js
src/Badge/index.js
src/Badge/index.js.flow

Added new type `white` to Badge component

UPDATE: Add white type of Badge

---

src/Icon/IconList.js
src/Icon/__snapshots__/Icon.stories.storyshot

Fixed missing quote in import paths.

FIX: Icons list import paths

---

src/Button/index.js
src/ButtonLink/index.js

FIX: href before external condition

---

src/List/ListItem/index.js.flow
src/List/__tests__/__snapshots__/index.test.js.snap
src/List/index.js
src/List/index.js.flow

Fixed List getting theme from ThemeProvider

FIX: List ThemeProvider

---

src/Text/__tests__/__snapshots__/index.test.js.snap
src/Text/index.js
src/Text/index.js.flow

Fixed Text getting theme from ThemeProvider

FIX: Text ThemeProvider

---

src/Radio/__snapshots__/Radio.stories.storyshot
src/Radio/__tests__/__snapshots__/index.test.js.snap
src/Radio/index.js
src/Radio/index.js.flow

Fixed Radio getting theme from ThemeProvider

FIX: Radio ThemeProvider

---

src/List/ListItem/index.js
src/List/__snapshots__/List.stories.storyshot

Changed margin-bottom between `ListItem` to `spaceXXSmall`.
Fixed last-child margin to 0.

FIX: ListItem margin

---

.github/theming.md

Fixed theming docs due to a new version of `orbit-design-tokens`.

FIX: Theming docs

---

.github/theming.md

fix doc: colors -> palette

---

src/Textarea/__tests__/__snapshots__/index.test.js.snap
src/Textarea/consts.js
src/Textarea/index.js
src/Textarea/index.js.flow

Fixed Textarea getting theme from ThemeProvider

FIX: Textarea ThemeProvider

---

src/Heading/__tests__/__snapshots__/index.test.js.snap
src/Heading/consts.js
src/Heading/index.js
src/Heading/index.js.flow

Fixed Heading getting theme from ThemeProvider

FIX: Heading ThemeProvider

---

src/Illustration/__tests__/__snapshots__/index.test.js.snap
src/Illustration/__tests__/index.test.js
src/Illustration/index.js

Fixed Illustration getting theme from ThemeProvider
and adjusted tests for more coverage

FIX: Illustration ThemeProvider

---

src/InputField/__snapshots__/InputField.stories.storyshot
src/TextLink/__snapshots__/TextLink.stories.storyshot
src/TextLink/__tests__/__snapshots__/index.test.js.snap
src/TextLink/index.js
src/TextLink/index.js.flow

Fixed TextLink getting theme from ThemeProvider

FIX: TextLink ThemeProvider

---

src/Checkbox/__snapshots__/Checkbox.stories.storyshot
src/Checkbox/__tests__/__snapshots__/index.test.js.snap
src/Checkbox/consts.js
src/Checkbox/index.js
src/Checkbox/index.js.flow
src/Radio/index.js

Fixed Checkbox getting theme from ThemeProvider

FIX: Checkbox ThemeProvider

---

src/InputGroup/InputGroup.stories.js
src/InputGroup/__tests__/__snapshots__/index.test.js.snap
src/InputGroup/consts.js
src/InputGroup/index.js
src/InputGroup/index.js.flow

Fixed InputGroup getting theme from ThemeProvider

FIX: InputGroup ThemeProvider

---

package.json

- FIX: Doc colors — palette
- FIX: Icon ThemeProvider
- FIX: Textarea ThemeProvider
- FIX: Heading ThemeProvider
- FIX: Illustration ThemeProvider
- FIX: import Illustration readme
- FIX: TextLink ThemeProvider
- FIX: Checkbox ThemeProvider
- FIX: InputField ThemeProvider
- FIX: Checkbox DOM rendering
- FIX: InputGroup ThemeProvider

Release 0.12.1

---

src/CarrierLogo/__snapshots__/CarrierLogo.stories.storyshot
src/CarrierLogo/__tests__/__snapshots__/index.test.js.snap
src/CarrierLogo/__tests__/index.test.js
src/CarrierLogo/consts.js
src/CarrierLogo/index.js
src/CarrierLogo/index.js.flow
src/List/__snapshots__/List.stories.storyshot

Fixed CarrierLogo getting theme from ThemeProvider

FIX: CarrierLogo ThemeProvider

---

src/Alert/__snapshots__/Alert.stories.storyshot
src/Button/Button.stories.js
src/Button/README.md
src/Button/__snapshots__/Button.stories.storyshot
src/Button/__tests__/__snapshots__/index.test.js.snap
src/Button/__tests__/index.test.js
src/Button/index.js
src/Button/index.js.flow
src/ButtonGroup/__snapshots__/ButtonGroup.stories.storyshot
src/ButtonLink/ButtonLink.stories.js
src/ButtonLink/README.md
src/ButtonLink/__snapshots__/ButtonLink.stories.storyshot
src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
src/ButtonLink/__tests__/index.test.js
src/ButtonLink/index.js
src/ButtonLink/index.js.flow
src/InputField/__snapshots__/InputField.stories.storyshot
src/InputFile/__snapshots__/InputFile.stories.storyshot
src/Loading/__snapshots__/Loading.stories.storyshot
src/Modal/__snapshots__/Modal.stories.storyshot

Added `submit` prop to `Button` and `ButtonLink`

UPDATE: Add submit to Button, ButtonLink

---

src/ServiceLogo/index.js.flow

FIX: external flow in ServiceLogo

---

storybooknative/src/CenterView/index.js
storybooknative/src/styled/index.js
storybooknative/src/types/StylesPropType.js

Wrap styled and use flow to validate styles passed to styled

---

.eslintignore
.flowconfig
storybooknative/.storybook/config.js
storybooknative/package.json
storybooknative/src/Button/Button.stories.js
storybooknative/src/Welcome/Welcome.stories.js
storybooknative/storybook/story-loader.js
storybooknative/storybook/storybook.js
storybooknative/yarn.lock

React Native: Fetching stories like in original setup

---

src/Modal/Modal.stories.js
src/Modal/ModalFooter/index.js

FIX: ModalFooter conditional expression

---

src/Stack/Stack.stories.js
src/Stack/__snapshots__/Stack.stories.storyshot
src/Stack/__tests__/__snapshots__/index.test.js.snap
src/Stack/__tests__/index.test.js
src/Stack/index.js
src/index.js.flow

FIX: Stack align-items

---

src/Loading/__snapshots__/Loading.stories.storyshot
src/Loading/index.js

FIX: IE - Loading Button

---

.circleci/config.yml
.gitignore
config/deploymentUtils.js
package.json
yarn.lock

- Every branch is deployed to surge (branch name can have all characters)
- Used cache for faster CI
Thanks a lot @PetrSnobelt 
<br/><br/><br/><url>LiveURL: https://orbit-components-add-staging.surge.sh</url>

ADD: Staging

---

src/List/List.stories.js
src/List/ListItem/index.js
src/List/__snapshots__/List.stories.storyshot

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-listitem-align.surge.sh</url>

FIX: ListItem icon align

---

src/InputFile/__tests__/__snapshots__/index.test.js.snap
src/InputFile/__tests__/index.test.js
src/InputFile/index.js
src/InputFile/index.js.flow

Fixes #459 <br/><br/><br/><url>LiveURL: https://orbit-components-fix-inputfile-closebutton-trigger.surge.sh</url>

FIX: InputFile CloseButton triggers file selection

---

src/InputGroup/InputGroup.stories.js
src/InputGroup/__snapshots__/InputGroup.stories.storyshot
src/InputGroup/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-inputgroup-without-label.surge.sh</url>

FIX: InputGroup without label

---

src/InputGroup/__snapshots__/InputGroup.stories.storyshot
src/Select/Select.stories.js
src/Select/__snapshots__/Select.stories.storyshot
src/Select/__tests__/__snapshots__/Select.test.js.snap
src/Select/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-select-placeholder.surge.sh</url>

FIX: Select placeholder - selected attribute

---

package.json

FIX: ListItem icon align
FIX: InputFile CloseButton triggers file selection #459
FIX: InputGroup without label
FIX: Select placeholder - selected attribute

Release 0.15.1

---

storybooknative/src/Button/index.js
storybooknative/src/Button/index.js.flow
storybooknative/src/Touchable.js

Solution for block prop.
Fixed flow errors.

Block prop + flow fixes

---

src/Checkbox/README.md
src/Checkbox/index.js.flow
src/Radio/README.md
src/Radio/index.js.flow

Closes #499 <br/><br/><br/><url>LiveURL: https://orbit-components-update-optional-label-radio-checkbox.surge.sh</url>

UPDATE: Optional label in Radio and Checkbox

---

src/Portal/index.js

Closes #400 <br/><br/><br/><url>LiveURL: https://orbit-components-fix-portal-ssr.surge.sh</url>

FIX: Portal SSR

---

src/Modal/__snapshots__/Modal.stories.storyshot
src/Modal/index.js

Fixes #488 
https://orbit-components-fix-modal-content-overflow.surge.sh

FIX: Modal absolute content overflow

---

src/Checkbox/__snapshots__/Checkbox.stories.storyshot
src/Checkbox/index.js
src/Radio/__snapshots__/Radio.stories.storyshot
src/Radio/index.js

Fixes #501 <br/><br/><br/><url>LiveURL: https://orbit-components-fix-radio-checkbox-label-height.surge.sh</url>

FIX: Radio and Checkbox label height

---

src/Alert/Alert.stories.js
src/Alert/__snapshots__/Alert.stories.storyshot
src/Alert/index.js
src/List/ListItem/index.js.flow
src/Text/index.js
src/Text/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-alert-text-list-color.surge.sh</url>

FIX: List and Text color in Alert

---

src/Textarea/README.md
src/Textarea/Textarea.stories.js
src/Textarea/__snapshots__/Textarea.stories.storyshot
src/Textarea/__tests__/__snapshots__/index.test.js.snap
src/Textarea/__tests__/index.test.js
src/Textarea/index.js
src/Textarea/index.js.flow

Closes #497 <br/><br/><br/><url>LiveURL: https://orbit-components-update-textarea-fullheight.surge.sh</url>

UPDATE: Textarea fullHeight prop

---

package.json

UPDATE: FLOW: Optional label in Radio and Checkbox #499
UPDATE: Textarea fullHeight prop #497
UPDATE: Orbit-design-tokens
FIX: Portal Server side rendering #400
FIX: Radio and Checkbox label height #501
FIX: Modal absolute content overflow #488
FIX: IE: Tile icon shrink
FIX: List and Text color in Alert
<br/><br/><br/><url>LiveURL: https://orbit-components-release-v0-15-2.surge.sh</url>

Release 0.15.2

---

storybooknative/src/InputField/InputField.stories.js
storybooknative/src/InputField/consts.js
storybooknative/src/InputField/index.js
storybooknative/src/InputField/index.js.flow
storybooknative/storybook/story-loader.js

Basic Input structure

---

storybooknative/src/CenterView/index.js
storybooknative/src/FormLabel/index.js
storybooknative/src/FormLabel/index.js.flow
storybooknative/src/InputField/InputField.stories.js
storybooknative/src/InputField/index.js
storybooknative/src/Types.js

Label styles + inline label prop

---

storybooknative/src/CenterView/index.js
storybooknative/src/FormFeedback/consts.js
storybooknative/src/FormFeedback/index.js
storybooknative/src/FormFeedback/index.js.flow
storybooknative/src/FormLabel/index.js.flow
storybooknative/src/InputField/InputField.stories.js
storybooknative/src/InputField/index.js
storybooknative/src/InputField/index.js.flow

Error and help messages.

---

src/Modal/__snapshots__/Modal.stories.storyshot
src/Modal/index.js

Modal width was wrong, due to the left and right paddings.<br/><br/><br/><url>LiveURL: https://orbit-components-fix-modal-sizing.surge.sh</url>

FIX: Modal width

---

package.json

Added configuration for loki visual testing<br/><br/><br/><url>LiveURL: https://orbit-components-added-loki-configuration.surge.sh</url>

ADDED: Loki configuration

---

src/Table/README.md
src/Table/Table.stories.js
src/Table/TableCell/consts.js
src/Table/TableCell/index.js
src/Table/TableCell/index.js.flow
src/Table/__snapshots__/Table.stories.storyshot

Children in TableCell is optional
It's possible to align text in the TableCell to the left, center and right
<br/><br/><br/><url>LiveURL: https://orbit-components-update-add-align-table.surge.sh</url>

UPDATE: Add align to TableCell

---

src/Button/README.md
src/Button/consts.js
src/Button/index.js
src/Button/index.js.flow

Added `white` type of Button.<br/><br/><br/><url>LiveURL: https://orbit-components-update-button-white.surge.sh</url>

UPDATE: Add white type of Button

---

src/Card/CardSection/index.js
src/Card/__snapshots__/Card.stories.storyshot

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-cardsection-subtitle.surge.sh</url>

FIX: CardSection subTitle render

---

src/RatingStars/README.md
src/RatingStars/RatingStars.stories.js
src/RatingStars/__snapshots__/RatingStars.stories.storyshot
src/RatingStars/__tests__/__snapshots__/index.test.js.snap
src/RatingStars/__tests__/index.test.js
src/RatingStars/index.js
src/RatingStars/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-update-ratingstars-color.surge.sh</url>

UPDATE: RatingStars color prop

---

src/Alert/__snapshots__/Alert.stories.storyshot
src/List/ListItem/index.js
src/List/__snapshots__/List.stories.storyshot
src/List/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-update-list-ul.surge.sh</url>

UPDATE: Render List in ul and li

---

storybooknative/src/InputField/InputField.stories.js
storybooknative/src/InputField/index.js

Focused state

---

src/Stack/README.md

<br/><br/><br/><url>LiveURL: https://orbit-components-update-stack-docs.surge.sh</url>

UPDATE: Stack spacing documentation

---

package.json

FIX: CardSection subTitle !! BC
FIX: Section without CardHeader
UPDATE: RatingStars colors
UPDATE: Render List in ul and li
UPDATE: Stack spacing documentation (shown exact pixels)<br/><br/><br/><url>LiveURL: https://orbit-components-v0-16-1.surge.sh</url>

Release 0.16.1

---

src/Heading/Heading.stories.js
src/Heading/README.md
src/Heading/__snapshots__/Heading.stories.storyshot
src/Heading/consts.js
src/Heading/index.js
src/Heading/index.js.flow

New type `title4` of `<Heading />`

ADD: Heading title4

---

.github/ISSUE_TEMPLATE.md

UPDATE: Issue template

---

src/Badge/__snapshots__/Badge.stories.storyshot
src/Badge/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-badge-white-color.surge.sh</url>

FIX: White Badge color

---

storybooknative/src/InputField/index.js
storybooknative/src/InputField/index.js.flow

InputField - Placeholder

---

src/Checkbox/Checkbox.stories.js
src/Checkbox/__snapshots__/Checkbox.stories.storyshot
src/Checkbox/index.js
src/Checkbox/index.js.flow
src/Radio/Radio.stories.js
src/Radio/__snapshots__/Radio.stories.storyshot
src/Radio/index.js
src/Radio/index.js.flow

The `label` prop opened for `React.Node`, for a case when TextLink is needed.
<br/><br/><br/><url>LiveURL: https://orbit-components-update-checkbox-radio-label.surge.sh</url>

UPDATE: React.Node for label in Radio and Checkbox

---

storybooknative/src/Button/index.js
storybooknative/src/CenterView/index.js
storybooknative/src/Checkbox/index.js
storybooknative/src/Checkbox/index.js.flow
storybooknative/src/Touchable/index.js

https://github.com/kiwicom/mobile/blob/master/packages/shared/src/forms/Checkbox.js

Extracted checkbox code from kiwi-mobile(link in description)

---

src/Modal/Modal.stories.js
src/Modal/ModalFooter/index.js
src/Modal/__snapshots__/Modal.stories.storyshot

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-modalfooter-buttonlink.surge.sh</url>

FIX: ButtonLink's size in ModalFooter

---

src/Portal/index.js

@oreqizer's request
<br/><br/><br/><url>LiveURL: https://orbit-components-update-portal-element.surge.sh</url>

UPDATE: Portal used element fallback

---

storybooknative/src/Text/__tests__/__snapshots__/index.test.js.snap
storybooknative/src/Text/index.js
storybooknative/src/styled/__tests__/lineheight.test.js
storybooknative/src/styled/index.js
storybooknative/src/styled/lineheight.js
storybooknative/src/types/Style.js

<br/><br/><br/><url>LiveURL: https://orbit-components-add-lineheight-helper.surge.sh</url>

Add: Lineheight helper to enable multiplier value

---

src/Modal/__snapshots__/Modal.stories.storyshot
src/Modal/index.js

Closes #543 <br/><br/><br/><url>LiveURL: https://orbit-components-fix-modal-scroll-handler.surge.sh</url>

FIX: Modal scroll handler

---

src/Tile/Tile.stories.js
src/Tile/TileHeader/index.js.flow
src/Tile/__snapshots__/Tile.stories.storyshot
src/Tile/index.js.flow

Tile's description now accepts React.Node<br/><br/><br/><url>LiveURL: https://orbit-components-update-tile-description.surge.sh</url>

UPDATE: Tile description accepts React.Node

---

storybooknative/index.js
storybooknative/package.json
storybooknative/yarn.lock

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-package-json.surge.sh</url>

Fix dependencies in package.json and export components

---

src/TripSector/__snapshots__/TripSector.stories.storyshot
src/TripSegment/__snapshots__/TripSegment.stories.storyshot
src/TripSegment/__tests__/__snapshots__/index.test.js.snap
src/TripSegment/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-tripsegment-align.surge.sh</url>

FIX: TripSegment time text alignment

---

flow-typed/npm/styled-components_v3.x.x.js
package.json
src/Button/index.js.flow
src/ButtonLink/index.js.flow
src/Card/CardHeader/index.js.flow
src/Card/CardSection/index.js.flow
src/CarrierLogo/index.js.flow
src/Heading/index.js.flow
src/InputField/index.js.flow
src/List/ListItem/index.js.flow
src/Loading/index.js.flow
src/Modal/ModalFooter/index.js.flow
src/Modal/ModalHeader/index.js.flow
src/Modal/ModalSection/index.js.flow
src/Select/index.js.flow
src/ServiceLogo/index.js.flow
src/Table/TableBody/index.js.flow
src/Table/TableCell/index.js.flow
src/Table/TableRow/index.js.flow
src/Text/index.js.flow
src/TextLink/index.js.flow
src/Tile/TileHeader/index.js.flow
src/TripSegment/index.js.flow
yarn.lock

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-styledcomponents-flow.surge.sh</url>

UPDATE: Flow to 0.81

---

package.json
src/InputField/index.js
src/Modal/ModalHeader/index.js
src/Tile/index.js
yarn.lock

Updated flow to 0.85 - should be compatible with 0.74 on FE
<br/><url>LiveURL: https://orbit-components-update-flow-0-85.surge.sh</url>

UPDATE: Flow 0.85

---

src/Card/README.md

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-card-docs.surge.sh</url>

FIX: Card docs

---

src/Card/index.js

Use case:
```
<Card>
<Loading>
<Fragment>
<CardHeader />
<CardSection />
</Fragment>
</Loading>
</Card>
```
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-fragment-in-card.surge.sh</url>

FIX: Fragment after Loading in Card

---

src/_deprecated/Card/Card.stories.js
src/_deprecated/Card/CardContent/index.js
src/_deprecated/Card/CardContent/index.js.flow
src/_deprecated/Card/CardHeader/index.js
src/_deprecated/Card/CardHeader/index.js.flow
src/_deprecated/Card/CardSection/index.js
src/_deprecated/Card/CardSection/index.js.flow
src/_deprecated/Card/__snapshots__/Card.stories.storyshot
src/_deprecated/Card/__tests__/index.test.js
src/_deprecated/Card/index.js
src/_deprecated/Card/index.js.flow
src/index.js
src/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-deprecated-card.surge.sh</url>

FIX: Added deprecated Card

---

storybooknative/README.md
storybooknative/package.json
storybooknative/scripts/create-new-component.js

<br/><br/><br/><url>LiveURL: https://orbit-components-add-README-and-createNewComponent-script.surge.sh</url>

Add: README + create-new-component script

---

src/Tile/TileExpandable/index.js

closes #545 
<br/><br/><br/><url>LiveURL: https://orbit-components-545-TileExpandable-timout-bug.surge.sh</url>

FIX: Clear timeout in TileExpandable

---

src/InputField/README.md

Fixed description for `onChange` prop.

FIX: InputField docs

---

src/InputField/__snapshots__/InputField.stories.storyshot
src/InputField/index.js
src/InputGroup/__snapshots__/InputGroup.stories.storyshot
src/InputStepper/__snapshots__/InputStepper.stories.storyshot
src/InputStepper/__tests__/__snapshots__/index.test.js.snap
src/Stack/__snapshots__/Stack.stories.storyshot
src/Stack/__tests__/__snapshots__/index.test.js.snap

Closes #468 <br/><br/><br/><url>LiveURL: https://orbit-components-fix-inputfield-password-visibility.surge.sh</url>

FIX: InputField password visibility in IE

---

src/Stack/__snapshots__/Stack.stories.storyshot
src/TripSector/__snapshots__/TripSector.stories.storyshot
src/TripSector/index.js

Closes #631 <br/><br/><br/><url>LiveURL: https://orbit-components-fix-tripsector-height.surge.sh</url>

FIX: TripSector height

---

src/Stack/__snapshots__/Stack.stories.storyshot
src/TripSector/__snapshots__/TripSector.stories.storyshot
src/TripSegment/__snapshots__/TripSegment.stories.storyshot
src/TripSegment/index.js

Closes #627 <br/><br/><br/><url>LiveURL: https://orbit-components-fix-tripsegment-carrierlogo.surge.sh</url>

FIX: TripSegment CarrierLogo

---

src/Stack/README.md
src/Stack/Stack.stories.js
src/Stack/__snapshots__/Stack.stories.storyshot
src/Stack/__tests__/__snapshots__/index.test.js.snap
src/Stack/__tests__/index.test.js
src/Stack/index.js
src/Stack/index.js.flow

Added missing prop `dataTest` to `Stack` component.
Closes #664 <br/><br/><br/><url>LiveURL: https://orbit-components-update-add-datatest-stack.surge.sh</url>

UPDATE: Add dataTest to Stack

---

src/Checkbox/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-checkbox-flow.surge.sh</url>

FIX: Checkbox flow type

---

src/InputField/__snapshots__/InputField.stories.storyshot
src/InputField/index.js
src/InputGroup/__snapshots__/InputGroup.stories.storyshot
src/InputStepper/__snapshots__/InputStepper.stories.storyshot
src/InputStepper/__tests__/__snapshots__/index.test.js.snap
src/Stack/__snapshots__/Stack.stories.storyshot
src/Stack/__tests__/__snapshots__/index.test.js.snap

Closes #660 <br/><br/><br/><url>LiveURL: https://orbit-components-update-inputfield-compact-fontweight.surge.sh</url>

UPDATE: Compact InputField font-weight

---

src/Card/README.md

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-card-docs.surge.sh</url>

FIX: Card doc

---

src/Modal/index.js

Closes #643 <br/><br/><br/><url>LiveURL: https://orbit-components-fix-modal-keydown-bubble.surge.sh</url>

FIX: Modal keyDown event bubbling

---

src/Card/Card.stories.js
src/Card/CardHeader/index.js
src/Card/CardSection/CardSectionContent/index.js
src/Card/CardSection/CardSectionContent/index.js.flow
src/Card/CardSection/CardSectionHeader/index.js
src/Card/CardSection/CardSectionHeader/index.js.flow
src/Card/CardSection/index.js
src/Card/CardSection/index.js.flow
src/Card/README.md
src/Card/__snapshots__/Card.stories.storyshot
src/Card/__tests__/index.test.js
src/Card/index.js
src/Card/index.js.flow
src/Loading/__snapshots__/Loading.stories.storyshot
src/Stack/Stack.stories.js
src/Stack/__snapshots__/Stack.stories.storyshot

<br/><br/><br/><url>LiveURL: https://orbit-components-card-update.surge.sh</url>

UPDATE: Card

---

src/Card/CardSection/CardSectionContent/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-children-rerender-card.surge.sh</url>

FIX: Card recalculate max-height on update

---

src/Stack/__snapshots__/Stack.stories.storyshot
src/Tile/Tile.stories.js
src/Tile/TileExpandable/index.js
src/Tile/TileExpandable/index.js.flow
src/Tile/__snapshots__/Tile.stories.storyshot

Closes #642 <br/><br/><br/><url>LiveURL: https://orbit-components-fix-tileexpandable-height.surge.sh</url>

FIX: TileExpandable height on update

---

src/Separator/README.md
src/Separator/Separator.stories.js
src/Separator/__snapshots__/Separator.stories.storyshot
src/Separator/__tests__/__snapshots__/index.test.js.snap
src/Separator/__tests__/index.test.js
src/Separator/index.js
src/Separator/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-update-spaceafter-separator.surge.sh</url>

UPDATE: Add spaceAfter to Separator

---

src/InputStepper/index.js

Closes #639 
<br/><br/><br/><url>LiveURL: https://orbit-components-fixed-inputstepper.surge.sh</url>

FIX: InputStepper null minValue or maxValue

---

.storybook/webpack.config.js
package.json
src/Card/CardHeader/index.js
src/Card/index.js
src/Loading/index.js

Closes #712 <br/><br/><br/><url>LiveURL: https://orbit-components-712-patch-CardHeader-for-ie-edge.surge.sh</url>

Patch for CardHeader  IE/Edge bug on production build

---

src/ButtonLink/index.js.flow

Removed unnecessary SyntheticKeyboardEvent from Button.<br/><br/><br/><url>LiveURL: https://orbit-components-fix-flow-button.surge.sh</url>

FIX: Flow: Unnecessary Button SyntheticKeyboardEvent

---

src/Badge/__snapshots__/Badge.stories.storyshot
src/Badge/index.js
src/Card/__snapshots__/Card.stories.storyshot

Close #699 <br/><br/><br/><url>LiveURL: https://orbit-components-fix-badge.surge.sh</url>

FIX: Badge

---

src/Card/Card.stories.js
src/Card/CardHeader/index.js
src/Card/CardHeader/index.js.flow
src/Card/README.md
src/Card/__snapshots__/Card.stories.storyshot

<br/><br/><br/><url>LiveURL: https://orbit-components-cardheader-actions.surge.sh</url>

UPDATE: Support actions in CardHeader

---

src/Modal/Modal.stories.js
src/Modal/ModalContext.js
src/Modal/ModalContext.js.flow
src/Modal/ModalHeader/index.js
src/Modal/ModalHeader/index.js.flow
src/Modal/ModalSection/index.js
src/Modal/__snapshots__/Modal.stories.storyshot
src/Modal/__tests__/__snapshots__/index.test.js.snap
src/Modal/index.js
src/Modal/index.js.flow

Modal is now possible to use without `ModalSection`. It means in combination with `ModalHeader` and `ModalFooter`.<br/><br/><br/><url>LiveURL: https://orbit-components-fix-modal-without-section.surge.sh</url>

UPDATE: Modal usage without ModalSection

---

src/TripSector/README.md

Fixed wrong imports in the documentation.

FIX: TripSector docs imports

---

src/Loading/Loading.stories.js
src/Loading/README.md
src/Loading/__snapshots__/Loading.stories.storyshot
src/Loading/consts.js
src/Loading/index.js
src/Loading/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-add-inlineloader.surge.sh</url>

ADD: inlineLoader type to Loading

---

src/Stack/__snapshots__/Stack.stories.storyshot
src/Table/__snapshots__/Table.stories.storyshot
src/Table/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-table-odd-background.surge.sh</url>

FIX: Odd TableRow background color

---

src/utils/mediaQuery/README.md

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-mq-documentantion.surge.sh</url>

FIX: MQ documentation breakpoints

---

src/InputField/__tests__/index.test.js
src/InputField/index.js
src/InputStepper/__tests__/__snapshots__/index.test.js.snap
src/Stack/__tests__/__snapshots__/index.test.js.snap

Fixed missing InputField ref, did in #732  <br/><br/><br/><url>LiveURL: https://orbit-components-fix-inputfield-ref.surge.sh</url>

FIX: InputField missing ref

---

src/Alert/README.md
src/ChoiceGroup/README.md
src/InputField/README.md
src/InputFile/README.md
src/InputGroup/README.md
src/InputStepper/README.md
src/ListChoice/README.md
src/Loading/README.md
src/Select/README.md
src/Textarea/README.md
src/Tile/README.md

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-translation-docs.surge.sh</url>

FIX: Translation docs

---

src/TripSegment/index.js

Closes #652 <br/><br/><br/><url>LiveURL: https://orbit-components-fix-tripsegment-timeout.surge.sh</url>

FIX: TripSegment setHeight timeout

---

src/InputField/InputField.stories.js
src/InputField/README.md
src/InputField/__snapshots__/InputField.stories.storyshot
src/InputField/__tests__/__snapshots__/index.test.js.snap
src/InputField/__tests__/index.test.js
src/InputField/index.js
src/InputField/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-update-input-field-readonly.surge.sh</url>

UPDATE: Add Inputfield readOnly prop

---

src/InputField/__snapshots__/InputField.stories.storyshot
src/InputField/index.js
src/InputGroup/__snapshots__/InputGroup.stories.storyshot
src/InputStepper/__snapshots__/InputStepper.stories.storyshot
src/InputStepper/__tests__/__snapshots__/index.test.js.snap
src/Modal/__snapshots__/Modal.stories.storyshot
src/Stack/__snapshots__/Stack.stories.storyshot
src/Stack/__tests__/__snapshots__/index.test.js.snap

Fixes #747 <br/><br/><br/><url>LiveURL: https://orbit-components-fix-inputfield-cursor.surge.sh</url>

FIX: InputField cursor position

---

src/CarrierLogo/__tests__/__snapshots__/index.test.js.snap
src/CarrierLogo/index.js
src/Illustration/index.js

Closes #724 <br/><br/><br/><url>LiveURL: https://orbit-components-new-attrs-syntax.surge.sh</url>

DEV: refactor styled-components attrs syntax

---

src/Tile/__tests__/index.test.js
src/Tile/index.js

Fixed tile expandable onClick event <br/><br/><br/><url>LiveURL: https://orbit-components-fix-tile-onclick-calling.surge.sh</url>

FIX: Tile expandable onClick

---

src/Card/index.js.flow

Fixes #769 
<url>LiveURL: https://orbit-components-fix-flow-card-onclose-event.surge.sh</url>

FIX: FLOW: Card onClose event

---

src/TripSegment/index.js
src/TripSegment/index.js.flow

Fixes #762 
Fixes #758 
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-tripsegment-height.surge.sh</url>

FIX: TripSegment height

---

src/Breadcrumbs/BreadcrumbsItem/index.js
src/Breadcrumbs/__snapshots__/Breadcrumbs.stories.storyshot

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-breadcrumb-item-hover-underline.surge.sh</url>

FIX: BreadcrumbItem hover underline

---

src/Stack/__snapshots__/Stack.stories.storyshot
src/Textarea/__snapshots__/Textarea.stories.storyshot
src/Textarea/index.js

FIX: Textarea displayName

---

src/Stack/README.md

Added short documentation for the Stack behaviour<br/><br/><br/><url>LiveURL: https://orbit-components-docs-stack-behaviour.surge.sh</url>

DOCS: Add Stack behavior

---

src/utils/mediaQuery/index.js.flow

Just fixed/improved so IDE know what mediaQueries exist.<br/><br/><br/><url>LiveURL: https://orbit-components-fix-mediaqueries-flow.surge.sh</url>

FIX: Flow type for mediaQueries

---

src/ServiceLogo/README.md
src/ServiceLogo/consts.js
src/ServiceLogo/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-add-servicelogo-usatoday.surge.sh</url>

NEW: UsaToday ServiceLogo

---

src/Card/README.md
src/List/README.md
src/Modal/README.md
src/Table/README.md

<br/><br/><br/><url>LiveURL: https://orbit-components-docs-update-better-imports.surge.sh</url>

DOCS: Update better imports

---

src/Breadcrumbs/Breadcrumbs.stories.js
src/Breadcrumbs/README.md
src/Breadcrumbs/index.js
src/Breadcrumbs/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-breadcrumbs-better-import.surge.sh</url>

UPDATE: Better export BreadCrumbs components

---

src/TripSector/README.md
src/TripSector/TripSector.stories.js
src/TripSector/index.js
src/TripSector/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-tripsector-better-import.surge.sh</url>

UPDATE: Better export TripSector components

---

src/Card/__snapshots__/Card.stories.storyshot
src/CarrierLogo/__snapshots__/CarrierLogo.stories.storyshot
src/CarrierLogo/__tests__/__snapshots__/index.test.js.snap
src/CarrierLogo/index.js
src/List/__snapshots__/List.stories.storyshot
src/Modal/__snapshots__/Modal.stories.storyshot
src/Stack/__snapshots__/Stack.stories.storyshot
src/TripSector/__snapshots__/TripSector.stories.storyshot
src/TripSegment/__snapshots__/TripSegment.stories.storyshot

Closes #821 <br/><br/><br/><url>LiveURL: https://orbit-components-fix-carrierlogo-align.surge.sh</url>

FIX: CarrierLogo diagonal align

---

src/ButtonGroup/README.md

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-button-group.surge.sh</url>

DOCS: Fixed ButtonGroup readme

---

src/Button/README.md
src/Button/__tests__/__snapshots__/index.test.js.snap
src/Button/__tests__/index.test.js
src/Button/index.js
src/Button/index.js.flow
src/ButtonLink/README.md
src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
src/ButtonLink/__tests__/index.test.js
src/ButtonLink/index.js
src/ButtonLink/index.js.flow
src/InputStepper/__tests__/__snapshots__/index.test.js.snap
src/Stack/__tests__/__snapshots__/index.test.js.snap
src/Stack/__tests__/index.test.js

Closes #636 <br/><br/><br/><url>LiveURL: https://orbit-components-update-add-ref-button.surge.sh</url>

UPDATE: Add ref to Button, ButtonLink

---

src/Alert/__snapshots__/Alert.stories.storyshot
src/Card/__snapshots__/Card.stories.storyshot
src/Checkbox/__snapshots__/Checkbox.stories.storyshot
src/InputField/__snapshots__/InputField.stories.storyshot
src/ListChoice/__snapshots__/ListChoice.stories.storyshot
src/Modal/__snapshots__/Modal.stories.storyshot
src/Radio/__snapshots__/Radio.stories.storyshot
src/Stack/__snapshots__/Stack.stories.storyshot
src/Text/Text.stories.js
src/Text/__snapshots__/Text.stories.storyshot
src/Text/index.js
src/TextLink/__snapshots__/TextLink.stories.storyshot
src/TextLink/index.js
src/TextLink/index.js.flow
src/Tile/__snapshots__/Tile.stories.storyshot
src/Tooltip/__snapshots__/Tooltip.stories.storyshot
src/TripSector/__snapshots__/TripSector.stories.storyshot
src/TripSegment/__snapshots__/TripSegment.stories.storyshot
src/_deprecated/Card/__snapshots__/Card.stories.storyshot

<br/><br/><br/><url>LiveURL: https://orbit-components-link-in-text.surge.sh</url>

UPDATE: Link formatting in Text

---

src/Modal/Modal.stories.js
src/Modal/__snapshots__/Modal.stories.storyshot
src/Tooltip/__snapshots__/Tooltip.stories.storyshot
src/Tooltip/__tests__/__snapshots__/index.test.js.snap
src/Tooltip/index.js

Original report: https://monosnap.com/file/xcAbYrdkAq5gIOOrIJiZqt5wWmvlPy<br/><br/><br/><url>LiveURL: https://orbit-components-fix-tooltip-in-modal.surge.sh</url>

FIX: Mobile Tooltip used in Modal

---

src/getTokens.js
src/getTokens.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-get-tokens-own-file.surge.sh</url>

DEV: Added getTokens export as file

---

src/InputField/InputField.stories.js
src/InputField/index.js
src/InputStepper/__tests__/__snapshots__/index.test.js.snap
src/Stack/__tests__/__snapshots__/index.test.js.snap

Closes #756 
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-inputfield-shrink-firefox.surge.sh</url>

FIX: InputField - input doesn't shrink in Firefox

---

src/CountryFlag/__tests__/__snapshots__/index.test.js.snap
src/CountryFlag/__tests__/index.test.js
src/CountryFlag/index.js
src/Illustration/__tests__/__snapshots__/index.test.js.snap
src/Illustration/__tests__/index.test.js
src/Illustration/index.js
src/ServiceLogo/__tests__/__snapshots__/index.test.js.snap
src/ServiceLogo/__tests__/index.test.js
src/ServiceLogo/index.js

Reverts kiwicom/orbit-components#853

Revert "FIX: Cross origin images - prevent sending cookies"

---

src/Alert/README.md
src/Alert/index.js.flow
src/Card/CardSection/index.js.flow
src/Card/README.md

UPDATE: Adding missing promise type for callbacks

---

src/TripSegment/README.md
src/TripSegment/index.js.flow

Closes #879 
<br/><br/><br/><url>LiveURL: https://orbit-components-mainframe-tripsegment.surge.sh</url>

FIX: TripSegment translatation props

---

src/InputField/index.js
src/InputStepper/__tests__/__snapshots__/index.test.js.snap
src/Stack/__tests__/__snapshots__/index.test.js.snap

The value inside disabled InputField had bad color and it was quite impossible to see it Safari.<br/><br/><br/><url>LiveURL: https://orbit-components-fix-inputfield-safari-disabled-color.surge.sh</url>

FIX: InputField disabled value in Safari

---

.github/contributing.md
.github/contribution/commits.md

<br/><br/><br/><url>LiveURL: https://orbit-components-update-docs-squashing-commits.surge.sh</url>

DOCS: Update contribution guides to reflect squash and merge

---

src/Stack/README.md
src/Stack/__tests__/__snapshots__/index.test.js.snap
src/Stack/__tests__/index.test.js
src/Stack/consts.js
src/Stack/helpers/getChildrenMargin.js
src/Stack/index.js.flow

Closes #780 <br/><br/><br/><url>LiveURL: https://orbit-components-update-stack-none-spacing.surge.sh</url>

UPDATE: Add spacing none option to Stack

---

src/Heading/Heading.stories.js
src/Heading/README.md
src/Heading/consts.js
src/Heading/index.js
src/Heading/index.js.flow

Added new type `displaySubtitle` for Heading component.<br/><br/><br/><url>LiveURL: https://orbit-components-add-heading-displaysubtitle.surge.sh</url>

ADD: Heading type displaySubtitle

---

src/Hide/Hide.stories.js
src/Hide/README.md
src/Hide/_tests_/__snapshots__/index.test.js.snap
src/Hide/_tests_/index.test.js
src/Hide/index.js
src/Hide/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-update-hide-display-prop.surge.sh</url>

UPDATE: Adding block prop to Hide component

---

src/InputField/InputField.stories.js
src/InputField/README.md
src/InputField/index.js
src/InputField/index.js.flow
src/InputStepper/__tests__/__snapshots__/index.test.js.snap
src/Stack/__tests__/__snapshots__/index.test.js.snap
src/Tag/index.js
src/Tag/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-tag-in-input.surge.sh</url>

UPDATE: Support tags in <InputField />

---

src/TextLink/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-links-inherit-colors.surge.sh</url>

FIX: Links inherits colors from global style

---

src/Checkbox/README.md
src/InputField/README.md
src/InputFile/README.md
src/InputStepper/README.md
src/Radio/README.md
src/Select/README.md
src/Textarea/README.md

<br/><br/><br/><url>LiveURL: https://orbit-components-docs-ref-syntax.surge.sh</url>

DOCS: Better syntax for creating ref

---

src/InputField/InputField.stories.js
src/InputField/README.md
src/InputField/__tests__/__snapshots__/index.test.js.snap
src/InputField/__tests__/index.test.js
src/InputField/index.js
src/InputField/index.js.flow

Closes #915 <br/><br/><br/><url>LiveURL: https://orbit-components-update-add-autocomplete-inputfield.surge.sh</url>

UPDATE: Add autocomplete to InputField

---

src/Modal/Modal.stories.js
src/Modal/README.md
src/Modal/index.js
src/Modal/index.js.flow

Closes #845 
<br/><br/><br/><url>LiveURL: https://orbit-components-update-add-setscroll-modal.surge.sh</url>

UPDATE: Add setScrollPosition for Modal

---

src/Sticky/README.md
src/Sticky/Sticky.stories.js
src/Sticky/__snapshots__/Sticky.stories.storyshot
src/Sticky/__tests__/index.test.js
src/Sticky/index.js
src/Sticky/index.js.flow
src/index.js
src/index.js.flow
src/utils/scroll/index.js
src/utils/scroll/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-new-FloatingCard.surge.sh</url>

NEW: Sticky component

---

src/Badge/index.js
src/Stack/Stack.stories.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-badge-flex.surge.sh</url>

FIX: Badge flex value

---

src/Breadcrumbs/README.md
src/Breadcrumbs/index.js.flow
src/ButtonGroup/README.md
src/ButtonGroup/index.js.flow
src/ChoiceGroup/README.md
src/ChoiceGroup/index.js.flow
src/InputGroup/README.md
src/InputGroup/index.js.flow
src/List/README.md
src/List/index.js.flow
src/Modal/README.md
src/Modal/index.js.flow
src/Table/README.md
src/Table/TableBody/index.js.flow
src/Table/TableHead/index.js.flow
src/Table/TableRow/index.js.flow
src/Table/index.js.flow

Closes #670 <br/><br/><br/><url>LiveURL: https://orbit-components-fix-flow-maybe-types.surge.sh</url>

FIX: Flow maybe types and children nodes

---

src/Modal/README.md

closes #435 <br/><br/><br/><url>LiveURL: https://orbit-components-docs-modal-focus.surge.sh</url>

UPDATE: Modal accessibility README

---

src/Alert/Alert.stories.js
src/Badge/Badge.stories.js
src/Button/Button.stories.js
src/ButtonLink/ButtonLink.stories.js
src/Card/Card.stories.js
src/Heading/Heading.stories.js
src/Icon/Icon.stories.js
src/Illustration/Illustration.stories.js
src/InputField/InputField.stories.js
src/InputGroup/InputGroup.stories.js
src/List/List.stories.js
src/ListChoice/ListChoice.stories.js
src/Modal/Modal.stories.js
src/RatingStars/RatingStars.stories.js
src/Separator/Separator.stories.js
src/Stack/Stack.stories.js
src/Tag/Tag.stories.js
src/Text/Text.stories.js
src/TextLink/TextLink.stories.js
src/Tile/Tile.stories.js
src/Tooltip/Tooltip.stories.js
src/_deprecated/Card/Card.stories.js

New storybook addon did not support `undefined` values in knobs<br/><br/><br/><url>LiveURL: https://orbit-components-fix-null-values-in-storybook.surge.sh</url>

FIX: null values in playgrounds

---

src/Button/Button.stories.js
src/Button/README.md
src/Button/__tests__/__snapshots__/index.test.js.snap
src/Button/__tests__/index.test.js
src/Button/index.js
src/Button/index.js.flow
src/ButtonLink/ButtonLink.stories.js
src/ButtonLink/README.md
src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
src/ButtonLink/__tests__/index.test.js
src/ButtonLink/index.js
src/ButtonLink/index.js.flow
src/InputStepper/__tests__/__snapshots__/index.test.js.snap
src/Stack/__tests__/__snapshots__/index.test.js.snap

- Adding AriaControls and AriaExpanded props to both Button and ButtonLink
- Updating Focus state to be more visible and consistent
- Updating Button disabled visual state to match ButtonLink behaviour
<br/><br/><br/><url>LiveURL: https://orbit-components-update-button-a11y.surge.sh</url>

UPDATE: Button & ButtonLink accessibility

---

src/Modal/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-modal-first-focus.surge.sh</url>

FIX: Modal first focused element

---

src/TripSegment/__tests__/__snapshots__/index.test.js.snap
src/TripSegment/index.js

Changed because of react warning, which says, that div can't appear as descendant of `<p>` element.
<br/><br/><br/><url>LiveURL: https://orbit-components-mainframe-tripsegment.surge.sh</url>

UPDATE: Use divs for Text in TripSegment

---

src/Modal/ModalFooter/index.js
src/Modal/__tests__/__snapshots__/index.test.js.snap
src/Modal/index.js

Closes #991 <br/><br/><br/><url>LiveURL: https://orbit-components-fix-modal-mount-rendering.surge.sh</url>

FIX: Modal mount rendering

---

src/index.js
src/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-exports-via-index.surge.sh</url>

FIX: add imports into index

---

.circleci/config.yml

<br/><br/><br/><url>LiveURL: https://orbit-components-dev-fix-ci-test.surge.sh</url>

DEV: Fix CI test containers workers

---

.flowconfig

<br/><br/><br/><url>LiveURL: https://orbit-components-dev-fix-flow-workers.surge.sh</url>

DEV: Fix workers for flow

---

src/Popover/components/ContentWrapper.js

Updating spacing to match design proposal. Changes requested by @williamkolmacka <br/><br/><br/><url>LiveURL: https://orbit-components-fix-popover-spacing.surge.sh</url>

FIX: Updating spacing of Popover

---

src/Modal/Modal.stories.js

Request by @honzatmn <br/><br/><br/><url>LiveURL: https://orbit-components-docs-update-short-modal.surge.sh</url>

DOCS: Update short Modal content

---

src/Popover/__tests__/__snapshots__/index.test.js.snap
src/Popover/components/ContentWrapper.js

<br/><br/><br/><url>LiveURL: https://orbit-components-update-tooltip-role.surge.sh</url>

UPDATE: Add role to popover

---

src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
src/Hide/_tests_/__snapshots__/index.test.js.snap
src/Icon/__tests__/__snapshots__/index.test.js.snap
src/Icon/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-icons-flex-shrink.surge.sh</url>

ICONS: disabling the shrink in flex box

---

src/Tile/Tile.stories.js
src/Tile/TileExpandable/index.js

Fixes case with TripSector in Tile<br/><br/><br/><url>LiveURL: https://orbit-components-fix-tile-expandable-dynamic-height.surge.sh</url>

FIX: Tile expandable dynamic height

---

src/Translate/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-import-default-dictionary-file.surge.sh</url>

FIX: import default dictionary file

---

src/utils/Slide/__tests__/__snapshots__/index.test.js.snap
src/utils/Slide/__tests__/index.test.js
src/utils/Slide/index.js

https://monosnap.com/file/WQQCz2tMVchLWHcs1jVV0oSlU00wUa<br/><br/><br/><url>LiveURL: https://orbit-components-fix-cardsection-doubleclick.surge.sh</url>

FIX: Card section collapse on doubleClick

---

src/Modal/Modal.stories.js
src/Modal/ModalContext.js
src/Modal/ModalContext.js.flow
src/Modal/ModalFooter/index.js
src/Modal/ModalHeader/index.js
src/Modal/ModalSection/index.js
src/Modal/README.md
src/Modal/__tests__/__snapshots__/index.test.js.snap
src/Modal/index.js
src/Modal/index.js.flow

Added `isMobileFullPage` for enabling page look for mobile viewports for webview needs.<br/><br/><br/><url>LiveURL: https://orbit-components-update-modal-fullpage-mobile.surge.sh</url>

UPDATE: Mobile fullPage variant for mobile viewport

---

src/Alert/consts.js
src/Alert/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-update-textlink-alert.surge.sh</url>

UPDATE: TextLink color in Alert

---

src/data/dictionary/ar-AE.json
src/data/dictionary/bg-BG.json
src/data/dictionary/cs-CZ.json
src/data/dictionary/da-DK.json
src/data/dictionary/de-DE.json
src/data/dictionary/en-GB.json
src/data/dictionary/es-AR.json
src/data/dictionary/es-ES.json
src/data/dictionary/fi-FI.json
src/data/dictionary/fr-FR.json
src/data/dictionary/he-IL.json
src/data/dictionary/hu-HU.json
src/data/dictionary/it-IT.json
src/data/dictionary/ja-JP.json
src/data/dictionary/ko-KR.json
src/data/dictionary/nb-NO.json
src/data/dictionary/nl-NL.json
src/data/dictionary/pl-PL.json
src/data/dictionary/pt-PT.json
src/data/dictionary/ro-RO.json

<br/><br/><br/><url>LiveURL: https://orbit-components-update-translations.surge.sh</url>

UPDATE: Translations

---

package.json
yarn.lock

DEV: Update orbit-design-tokens 0.6.1

---

.eslintrc
package.json
src/InputField/InputTags/index.js
src/Popover/hooks/useDimensions.js
src/Popover/hooks/useHorizontalPosition.js
src/Popover/hooks/useVerticalPosition.js
yarn.lock

<br/><br/><br/><url>LiveURL: https://orbit-components-dev-add-react-hooks-plugin.surge.sh</url>

DEV: Add eslint-plugin-react-hooks

---

src/Tile/TileHeader/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-tile-rtl-icon.surge.sh</url>

FIX: Tile link icon on RTL

---

src/Tooltip/__tests__/__snapshots__/index.test.js.snap
src/Tooltip/index.js
src/Tooltip/index.js.flow

Updating Tooltip to render to DOM only when `open` is triggered.<br/><br/><br/><url>LiveURL: https://orbit-components-update-tooltip-render.surge.sh</url>

UPDATE: Tooltip render

---

src/Illustration/README.md
src/Illustration/consts.js

https://orbit-components-add-new-illustrations.surge.sh

ADD: BGYFastTrack and NCEFastTrack illustration

---

src/Loading/README.md
src/Tooltip/README.md

<br/><br/><br/><url>LiveURL: https://orbit-components-docs-fix-enums.surge.sh</url>

DOCS: Fix mistakes in enums

---

src/ListChoice/_tests_/__snapshots__/index.test.js.snap
src/ListChoice/index.js
src/ListChoice/index.js.flow

Making behaviour of ListChoice to be more useable in cases like PlacePicker<br/><br/><br/><url>LiveURL: https://orbit-components-update-a11y-listchoice.surge.sh</url>

UPDATE: accessibility of ListChoice

---

src/Button/index.js
src/ButtonLink/index.js
src/InputField/index.js
src/InputFile/index.js
src/Stack/__tests__/__snapshots__/index.test.js.snap

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-button-active-inputs.surge.sh</url>

FIX: Button active state in Inputs

---

webpack.config.js

<br/><br/><br/><url>LiveURL: https://orbit-components-turn-off-warning-umd.surge.sh</url>

DEV: Turn off warnings when generating umd

---

src/InputStepper/README.md
src/Stepper/README.md

<br/><br/><br/><url>LiveURL: https://orbit-components-docs-steppers-path.surge.sh</url>

DOCS: Fix steppers stateless imports

---

package.json
yarn.lock

<br/><br/><br/><url>LiveURL: https://orbit-components-dev-update-token-064.surge.sh</url>

DEV: Update orbit-design-tokens to 0.6.4

---

src/Stepper/StepperStateless/index.js

Fixes: #1029 <br/><br/><br/><url>LiveURL: https://orbit-components-fix-stepper-firefox.surge.sh</url>

FIX: Stepper width in firefox

---

src/Tile/__tests__/__snapshots__/index.test.js.snap
src/Tile/index.js
src/Tile/index.js.flow

Tile is now focusable even if it's not anchor tag. Also adding `keyDown` handler<br/><br/><br/><url>LiveURL: https://orbit-components-update-tile-a11y.surge.sh</url>

UPDATE: Tile accessibility

---

src/Tooltip/helpers/resolveTooltipArrowAlign.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-tooltip-arrow-position.surge.sh</url>

FIX: Tooltip arrow position

---

src/Tooltip/index.js

http://recordit.co/DomNYhWC7c<br/><br/><br/><url>LiveURL: https://orbit-components-fix-tooltip-close-button.surge.sh</url>

FIX: Tooltip close button

---

src/Layout/LayoutColumn/index.js.flow
src/Layout/README.md

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-layoutcolumn-type-docs.surge.sh</url>

FIX: LayoutColumn element type and docs

---

src/Tooltip/README.md
src/Tooltip/Tooltip.stories.js
src/Tooltip/index.js
src/Tooltip/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-add-enabled-prop-to-tooltip.surge.sh</url>

UPDATE: Tooltip enabled prop

---

package.json

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-package-version.surge.sh</url>

FIX: package version

---

src/Illustration/README.md

DOCS: wrong component name of Illustration

---

src/Tooltip/Tooltip.stories.js
src/Tooltip/consts.js
src/Tooltip/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-tooltip-preferred-position-rtl.surge.sh</url>

FIX: Tooltip preferredPosition on RTL

---

src/ButtonLink/__tests__/__snapshots__/index.test.js.snap
src/ButtonLink/helpers/getButtonLinkBoxShadow.js
src/ChoiceGroup/components/FilterWrapper.js
src/Collapse/Collapse.stories.js
src/Collapse/README.md
src/Collapse/_tests_/index.test.js
src/Collapse/index.js
src/Collapse/index.js.flow
src/Slider/components/Handle/index.js
src/utils/Slide/__tests__/__snapshots__/index.test.js.snap
src/utils/Slide/index.js
src/utils/Slide/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-add-collapse-component.surge.sh</url>

NEW: Collapse component

---

src/Popover/Popover.stories.js
src/Popover/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-popover-controlled-handlers.surge.sh</url>

FIX: Popover controlled handlers

---

webpack.config.js

Removed React from UMD package<br/><br/><br/><url>LiveURL: https://orbit-components-umd-package-without-react.surge.sh</url>

FIX: UMD package without React

---

package.json
src/Icon/README.md

<br/><br/><br/><url>LiveURL: https://orbit-components-uploading-icons-font-to-npm.surge.sh</url>

DEV: Uploading icons font to npm

---

src/Tooltip/Tooltip.stories.js
src/Tooltip/index.js

https://take.ms/87h5Og
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-tooltip-scrolling.surge.sh</url>

FIX: Tooltip content scrolling

---

src/Slider/_tests_/index.test.js
src/Slider/index.js
src/utils/boundingClientRect/index.js
src/utils/boundingClientRect/index.js.flow

Fixed Handles moving when zoomed on mobile devices.
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-slider-touchmove.surge.sh</url>

FIX: Slider onTouchMove event and calculation when zoomed

---

src/TripSegment/__tests__/__snapshots__/index.test.js.snap
src/TripSegment/index.js
src/Truncate/README.md
src/Truncate/Truncate.stories.js
src/Truncate/__tests__/index.test.js
src/Truncate/index.js
src/Truncate/index.js.flow
src/index.js
src/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-new-truncate-component.surge.sh</url>

NEW: Truncate component

---

src/Pagination/components/Pages.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-missing-key-pagination.surge.sh</url>

Fix: Missing key in pagination

---

src/Illustration/README.md
src/Illustration/consts.js

<br/><br/><br/><url>LiveURL: https://orbit-components-update-illustration-error404.surge.sh</url>

UPDATE: Add Error404 illustration

---

src/ChoiceGroup/__tests__/__snapshots__/index.test.js.snap
src/ChoiceGroup/index.js
src/DestinationCard/_tests_/__snapshots__/index.test.js.snap
src/DestinationCard/index.js
src/InputField/index.js
src/InputGroup/__tests__/__snapshots__/index.test.js.snap
src/InputGroup/__tests__/index.test.js
src/InputGroup/index.js
src/InputGroup/index.js.flow
src/Modal/__tests__/__snapshots__/index.test.js.snap
src/Modal/index.js
src/Stack/__tests__/__snapshots__/index.test.js.snap
src/Tooltip/index.js

There were different styles of implementations of randomID.<br/><br/><br/><url>LiveURL: https://orbit-components-update-unifying-randomid.surge.sh</url>

DEV: Unifying randomID implemenations

---

src/utils/boundingClientRect/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-ie-bounding-rect.surge.sh</url>

FIX: IE boundingRect positions

---

config/build.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-illustration-list-originals.surge.sh</url>

FIX: Illustration list originals path

---

src/ServiceLogo/consts.js

<br/><br/><br/><url>LiveURL: https://orbit-components-update-servicelogo-iata.surge.sh</url>

UPDATE: Add IATA service logo

---

src/Tooltip/Tooltip.stories.js
src/Tooltip/consts.js
src/Tooltip/helpers/__tests__/calculateTooltipAlign.test.js
src/Tooltip/helpers/__tests__/calculateTooltipPosition.test.js
src/Tooltip/helpers/__tests__/resolveContainerAlign.test.js
src/Tooltip/helpers/__tests__/resolveContainerPosition.test.js
src/Tooltip/helpers/__tests__/resolveTooltipArrowAlign.test.js
src/Tooltip/helpers/__tests__/tooltipPadding.test.js
src/Tooltip/helpers/calculateTooltipAlign.js
src/Tooltip/helpers/calculateTooltipPosition.js
src/Tooltip/hooks/useDimensions.js
src/Tooltip/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-tooltip-calculation-scrolled.surge.sh</url>

FIX: Tooltip calculation when scrolled

---

src/CountryFlag/index.js
src/CountryFlag/index.js.flow

Closes #1189 <br/><br/><br/><url>LiveURL: https://orbit-components-update-country-flag-maybe-type.surge.sh</url>

UPDATE: CountryFlag maybe type for code property

---

src/ServiceLogo/consts.js

<br/><br/><br/><url>LiveURL: https://orbit-components-update-add-axa-servicelogo.surge.sh</url>

UPDATE: Add Axa service logo

---

src/CountryFlag/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-countryflag-shrink.surge.sh</url>

FIX: CountryFlag shrink

---

src/Tile/TileHeader/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-update-tile-padding.surge.sh</url>

FIX: Tile arrow padding 

---

src/List/List.stories.js
src/List/ListItem/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-list-item.surge.sh</url>

FIX: ListItem content space

---

src/ServiceLogo/README.md

<br/><br/><br/><url>LiveURL: https://orbit-components-docs-update-servicelogo.surge.sh</url>

DOCS: Add missing service logos

---

src/Tile/TileHeader/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-tile-spacing.surge.sh</url>

FIX: Tile spacing between title and description

---

src/data/dictionary/ar-AE.json
src/data/dictionary/bg-BG.json
src/data/dictionary/cs-CZ.json
src/data/dictionary/da-DK.json
src/data/dictionary/de-DE.json
src/data/dictionary/en-GB.json
src/data/dictionary/es-AR.json
src/data/dictionary/es-ES.json
src/data/dictionary/fi-FI.json
src/data/dictionary/fr-FR.json
src/data/dictionary/he-IL.json
src/data/dictionary/hu-HU.json
src/data/dictionary/it-IT.json
src/data/dictionary/ja-JP.json
src/data/dictionary/ko-KR.json
src/data/dictionary/nb-NO.json
src/data/dictionary/nl-NL.json
src/data/dictionary/pl-PL.json
src/data/dictionary/pt-PT.json

<br/><br/><br/><url>LiveURL: https://orbit-components-update-translations-data.surge.sh</url>

UPDATE: Translations data

---

src/Select/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-update-select-cursor-disabled.surge.sh</url>

UPDATE: Select not-allowed cursor for disabled state

---

src/ListChoice/_tests_/__snapshots__/index.test.js.snap
src/ListChoice/index.js

Closes #1233 <br/><br/><br/><url>LiveURL: https://orbit-components-fix-listchoice-a11y.surge.sh</url>

FIX: ListChoice accessibility role

---

src/ChoiceGroup/index.js
src/FormFeedback/index.js.flow

Closes #1239 <br/><br/><br/><url>LiveURL: https://orbit-components-fix-formfeedback-flow.surge.sh</url>

FIX: FormFeedback flow file

---

src/Checkbox/Checkbox.stories.js
src/Checkbox/__tests__/__snapshots__/index.test.js.snap
src/Checkbox/index.js

Closes #1234 <br/><br/><br/><url>LiveURL: https://orbit-components-fix-checkbox-event-bubbling.surge.sh</url>

FIX: Checkbox event bubbling when readOnly

---

src/Heading/README.md
src/Heading/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-update-heading-default-element.surge.sh</url>

UPDATE: Default element of Heading component

---

src/Stack/README.md
src/Stack/consts.js
src/Stack/helpers/getAlign.js
src/Stack/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-update-stack-stretch.surge.sh</url>

UPDATE: extending Stack to have stretch

---

src/Tooltip/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-update-tooltip-propagation.surge.sh</url>

UPDATE: Stopping Tooltip event propagation

---

src/PricingTable/PricingTable.stories.js
src/Tooltip/README.md
src/Tooltip/index.js
src/Tooltip/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-tooltip-propagation-event.surge.sh</url>

FIX: Tooltip event bubbling, adding stopPropagation property

---

src/ButtonLink/helpers/getButtonLinkSpacing.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-button-link-const-import.surge.sh</url>

DEV: import right sizes const for the ButtonLink component

---

config/build.js
src/Icon/README.md
src/Icon/__tests__/__snapshots__/index.test.js.snap
src/Icon/__tests__/index.test.js
src/Icon/consts.js
src/Icon/index.js
src/Icon/index.js.flow
src/Pagination/components/CompactPages.js

Prequisite #1263 <br/><br/><br/><url>LiveURL: https://orbit-components-breaking-icon-primary.surge.sh</url>

BREAKING: Removing attention color from Icon

---

src/PricingTable/PricingTableItem/consts.js
src/PricingTable/PricingTableItem/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-pricing-table-active.surge.sh</url>

FIX: PricingTable active element border

---

src/Tooltip/README.md
src/Tooltip/Tooltip.stories.js
src/Tooltip/index.js
src/Tooltip/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-update-tooltip-underline.surge.sh</url>

UPDATE: Tooltip adding prop for removing underline text on children

---

src/List/ListItem/index.js
src/List/ListItem/index.js.flow
src/List/__tests__/__snapshots__/index.test.js.snap
src/List/index.js
src/List/index.js.flow
src/hooks/useMediaQuery.js

<br/><br/><br/><url>LiveURL: https://orbit-components-update-icon-size-list.surge.sh</url>

UPDATE: bigger icon for separated List

---

src/PricingTable/PricingTableItem/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-badge-pricingtable.surge.sh</url>

FIX: Badge overlay in PricingTable

---

src/Popover/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-popover-callback-loop.surge.sh</url>

FIX: Popover callback loop

---

src/Modal/ModalContext.js
src/Modal/ModalContext.js.flow
src/Modal/__tests__/__snapshots__/index.test.js.snap
src/Modal/index.js
src/Popover/__tests__/__snapshots__/index.test.js.snap
src/Popover/components/ContentWrapper.js

<br/><br/><br/><url>LiveURL: https://orbit-components-update-dynamic-zindex-popover.surge.sh</url>

UPDATE: Dynamic z-index for Popover

---

.gitignore
config/flowFiles.js
src/FeatureIcon/FLOW_TEMPLATE.flow
src/FeatureIcon/FeatureIcon.stories.js
src/FeatureIcon/README.md
src/FeatureIcon/__tests__/index.test.js
src/FeatureIcon/consts.js
src/FeatureIcon/index.js
src/PricingTable/PricingTable.stories.js
src/index.js
src/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-new-featureicon-component.surge.sh</url>

NEW: FeatureIcon component

---

src/Alert/index.js
src/Breadcrumbs/index.js
src/Card/index.js
src/DestinationHeader/index.js
src/Drawer/components/DrawerClose.js
src/Modal/index.js
src/NavigationBar/index.js
src/RatingStars/index.js
src/Translate/index.js
src/Translate/index.js.flow
src/hooks/useTranslate.js
src/hooks/useTranslate.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-new-usetranslate-hook.surge.sh</url>

NEW: useTranslate hook

---

src/Drawer/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-drawer-header-padding.surge.sh</url>

FIX: Drawer header padding and DOM render

---

src/List/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-list-flow.surge.sh</url>

FIX: Flow React annotation in List

---

src/Collapse/Collapse.stories.js
src/Collapse/README.md
src/Collapse/index.js
src/Collapse/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-update-collapse-action.surge.sh</url>

UPDATE: Collapse adding actions prop

---

src/List/ListItem/index.js

Making listItem fontweight more heavy, to reflect design.<br/><br/><br/><url>LiveURL: https://orbit-components-update-list-font-weight.surge.sh</url>

UPDATE: ListItem separated fontWeight

---

src/Modal/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-modal-absolute-content-scrolling.surge.sh</url>

FIX: Modal scrolling with absolutely positioned element

---

src/Coupon/Coupon.stories.js
src/Coupon/README.md
src/Coupon/__tests__/index.test.js
src/Coupon/index.js
src/Coupon/index.js.flow
src/Text/index.js
src/index.js
src/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-new-coupon-component.surge.sh</url>

NEW: Coupon component

---

src/List/ListItem/index.js
src/List/ListItem/index.js.flow
src/List/index.js
src/List/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-listitem-lineheight.surge.sh</url>

FIX: lineHeight of ListItem icon

---

src/Collapse/Collapse.stories.js
src/Collapse/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-collapse-onclick.surge.sh</url>

FIX: Collapse onClick handler

---

src/PricingTable/PricingTable.stories.js
src/PricingTable/PricingTableItem/index.js

Fixing shrink on smaller devices, also adding a germany mutation to stroybook for better testing.<br/><br/><br/><url>LiveURL: https://orbit-components-fix-pricetable-shrink.surge.sh</url>

FIX: PricingTableItem shrink

---

src/hooks/useToggle.js
src/hooks/useToggle.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-mainframe-useToggle.surge.sh</url>

NEW: useToggle hook

---

src/NavigationList/NavigationListItem/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-navigationlistitem-svg-align.surge.sh</url>

FIX: NavigationListItem svg alignment

---

src/Tile/TileHeader/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-tile-title-wrapping.surge.sh</url>

FIX: Tile's title wrapping in IE

---

src/Collapse/index.js

<url>LiveURL: https://orbit-components-mainframe-cllps.surge.sh</url>

FIX: Collapse double handleClick firing

---

src/Popover/components/ContentWrapper.js

<br/><br/><br/><url>LiveURL: https://orbit-components-update-popover-overflow.surge.sh</url>

FIX: Popover overflow

---

src/Stepper/_tests_/index.test.js
src/Stepper/index.js
src/Stepper/index.js.flow
src/hooks/useStateWithCallback.js
src/hooks/useStateWithCallback.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-mainframe-stepper.surge.sh</url>

DEV: Stepper to hooks

---

src/Slider/Slider.stories.js
src/Slider/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-update-slider-onchange-callbacks.surge.sh</url>

UPDATE: Slider onChange callbacks behaviour

---

src/PricingTable/PricingTable.stories.js
src/PricingTable/PricingTableItem/index.js
src/PricingTable/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-update-pricingtable-widthsizing.surge.sh</url>

UPDATE: PricingTable layout for less than 3 child

---

src/PricingTable/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-pricingTable-doublerender.surge.sh</url>

FIX: PricingTable double render on desktop

---

src/Button/index.js
src/ButtonLink/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-button-lineheight.surge.sh</url>

FIX: Buttons line-height for multiline content

---

src/Illustration/FLOW_TEMPLATE.flow
src/Illustration/README.md
src/Illustration/consts.js
src/Illustration/index.js

closes #1361
<br/><br/><br/><url>LiveURL: https://orbit-components-update-illustration-display-size.surge.sh</url>

UPDATE: Add display size for Illustration and NomadNeutral

---

src/Popover/components/ContentWrapper.js
src/Popover/hooks/useDimensions.js
src/Popover/hooks/useDimensions.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-update-popover-parentrecursive.surge.sh</url>

UPDATE: Popover getScrollableParent execution optimization

---

src/Popover/Popover.stories.js
src/Popover/__tests__/index.test.js
src/Popover/components/ContentWrapper.js
src/Popover/consts.js
src/Popover/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-update-popover-fixedactions.surge.sh</url>

UPDATE: Popover fixed actions

---

src/Illustration/consts.js
src/Illustration/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-Illustration-size.surge.sh</url>

FIX: Illustration's display size

---

src/index.js.flow

fixes #1384
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-flow-type.surge.sh</url>

FIX: Update flow declaration for "getTokens"

---

src/Button/index.js
src/Button/index.js.flow
src/ButtonLink/index.js
src/ButtonLink/index.js.flow
src/Checkbox/index.js
src/InputField/index.js
src/InputFile/index.js
src/InputStepper/index.js
src/Radio/index.js
src/Select/index.js
src/Slider/components/Bar/index.js
src/Textarea/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-mainframe-frwrdref.surge.sh</url>

FIX: Forwarding of refs

---

src/PricingTable/PricingTable.stories.js
src/PricingTable/PricingTableItem/index.js
src/PricingTable/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-pricing-table-datatest.surge.sh</url>

FIX: Pricing table datatest

---

src/Button/Button.stories.js
src/Button/README.md
src/Button/__tests__/index.test.js
src/Button/index.js
src/Button/index.js.flow
src/ButtonLink/README.md
src/ButtonLink/__tests__/index.test.js
src/ButtonLink/index.js
src/ButtonLink/index.js.flow
src/InputStepper/InputStepperStateless/index.js
src/NavigationList/NavigationListItem/__tests__/index.test.js
src/NavigationList/README.md
src/Pagination/components/ActiveButton.js
src/TextLink/README.md
src/TextLink/index.js
src/TextLink/index.js.flow
src/common/common.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-breaking-component-property.surge.sh</url>

BREAKING: Rename component to asComponent

---

src/Modal/Modal.stories.js
src/Modal/README.md
src/Modal/index.js
src/Modal/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-update-modal-close.surge.sh</url>

UPDATE: Adding option for preventing overlay close on modal

---

src/Breadcrumbs/Breadcrumbs.stories.js
src/Breadcrumbs/BreadcrumbsItem/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-breadcrumbsitem-without-href.surge.sh</url>

FIX: BreadcrumbsItem without href or onClick

---

src/ChoiceGroup/ChoiceGroup.stories.js
src/ChoiceGroup/components/FilterWrapper.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-choicegroup-only-disabled.surge.sh</url>

FIX: ChoiceGroup only selection with disabled

---

src/NotificationBadge/README.md

<br/><br/><br/><url>LiveURL: https://orbit-components-docs-notificationbadge-icon.surge.sh</url>

DOCS: Fix NotificationBadge icon behavior

---

src/hooks/useMediaQuery/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-useMediaquerytypes.surge.sh</url>

FIX: useMediaQuery types

---

src/PricingTable/PricingTable.stories.js
src/PricingTable/PricingTableItem/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-pricingtable-badgefit.surge.sh</url>

FIX: Badge overflow in Pricing table

---

src/Tooltip/README.md
src/Tooltip/Tooltip.stories.js
src/Tooltip/components/TooltipContent.js
src/Tooltip/components/TooltipContent.js.flow
src/Tooltip/helpers/__tests__/sortPositionsAndAligns.test.js
src/Tooltip/helpers/sortPositionsAndAligns.js
src/Tooltip/helpers/sortPositionsAndAligns.js.flow
src/Tooltip/index.js
src/Tooltip/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-update-tooltip-align.surge.sh</url>

UPDATE: Add preferredAlign to Tooltip

---

src/Tooltip/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-tooltip-enabled-handlers.surge.sh</url>

 FIX: Not enabled Tooltip calling handlers

---

src/PictureCard/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-cardplainaction.surge.sh</url>

FIX: PictureCard plain state having actions

---

src/Tile/components/TileContent/index.js
src/Tile/components/TileContent/index.js.flow
src/Tile/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-tile-simple-pointer-cursor.surge.sh</url>

FIX: Pointer cursor for Tile in simple variant

---

src/Breadcrumbs/Breadcrumbs.stories.js
src/Breadcrumbs/BreadcrumbsItem/index.js
src/Breadcrumbs/BreadcrumbsItem/index.js.flow
src/Breadcrumbs/README.md
src/Breadcrumbs/_tests_/index.test.js

<br/><br/><br/><url>LiveURL: https://orbit-components-update-breadcrumps-id.surge.sh</url>

UPDATE: Extending Breadcrumbs for id prop

---

src/Breadcrumbs/Breadcrumbs.stories.js

<br/><br/><br/><url>LiveURL: https://orbit-components-update-breadcrumpsids.surge.sh</url>

DOCS: Updating ID's of breadcrumps

---

src/NavigationBar/README.md

<br/><br/><br/><url>LiveURL: https://orbit-components-mainframe-fixMD.surge.sh</url>

DOC: FIX wrong example in NavigationBar

---

src/PictureCard/__tests__/index.test.js
src/PictureCard/index.js
src/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-mainframe-pcrdf.surge.sh</url>

fix(components): PictureCard href

---

src/Modal/index.js

Closes #964<br/><br/><br/><url>LiveURL: https://orbit-components-fix-clickoutside.surge.sh</url>

FIX: Modal close when you make drop outside of modalWrapper

---

package.json
yarn.lock

<br/><br/><br/><url>LiveURL: https://orbit-components-update-react-deps.surge.sh</url>

DEV: Bump react-dom and react-test-renderer to 16.12.0

---

src/PictureCard/index.js
src/Popover/Popover.stories.js
src/Popover/README.MD
src/Popover/consts.js
src/Popover/helpers/calculateHorizontalPosition.js
src/Popover/helpers/resolvePopoverHorizontal.js
src/Popover/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-update-popover-align.surge.sh</url>

UPDATE: Adding align center option to Popover

---

.circleci/config.yml

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-storybook-ghpages.surge.sh</url>

DEV: fix Storybook build to ghpages

---

.circleci/config.yml
package.json

<br/><br/><br/><url>LiveURL: https://orbit-components-dev-fix-storybook-master.surge.sh</url>

DEV: Use cross-env in build of storybook master

---

src/Card/Card.stories.js
src/Card/README.md
src/Card/components/Header/index.js
src/Card/components/Header/index.js.flow
src/Card/index.js
src/Card/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-mainframe-crdfx.surge.sh</url>

UPDATE: Add onClose to Card component

---

src/utils/Slide/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-slide-click-propagation.surge.sh</url>

FIX: Slide onClick propagation

---

src/Alert/index.js
src/ListChoice/index.js
src/PictureCard/index.js
src/Tile/components/TileExpandable/index.js
src/Tile/index.js
src/deprecated/DestinationCard/index.js
src/utils/handleKeyDown/index.js
src/utils/handleKeyDown/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-mainframe-handleKeyDown.surge.sh</url>

DEV: Utilize handleKeyDown function

---

.storybook/orbitDecorator.js

Adding filter function for removing `undefined`, `null` and empty strings from storybook story source code.<br/><br/><br/><url>LiveURL: https://orbit-components-dev-storybook-code.surge.sh</url>

DEV: Improve Storybook source code structure

---

src/Alert/Alert.stories.js
src/Alert/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-update-figma-alert.surge.sh</url>

UPDATE: Alert sync with native design

---

src/Modal/Modal.stories.js
src/Modal/ModalFooter/index.js
src/Modal/ModalHeader/index.js
src/Modal/ModalSection/index.js
src/Modal/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-update-figma-modal.surge.sh</url>

UPDATE: Modal sync with native design

---

src/Button/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-button-type.surge.sh</url>

fix(button): Fix flow type of the button export

---

src/PricingTable/index.js
src/ThemeProvider/QueryContext/index.js
src/ThemeProvider/QueryContext/index.js.flow
src/ThemeProvider/QueryContext/useMediaQueryContext.js
src/ThemeProvider/index.js
src/hooks/useMediaQuery/index.js
src/hooks/useMediaQuery/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-refactor-usemediaquery-context.surge.sh</url>

refactor(useMediaQuery): To be stored inside ThemeProvider context

---

src/Popover/components/ContentWrapper.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-popover-styles.surge.sh</url>

fix(popover): Border radius on desktop and close button padding

---

src/Popover/Popover.stories.js
src/Popover/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-popover-keydown-open.surge.sh</url>

fix(popover): Opening with onKeyDown event

---

src/PictureCard/PictureCard.stories.js
src/PictureCard/index.js

Wny: There is a use case for smaller pictureCard height in `plain` variant.<br/><br/><br/><url>LiveURL: https://orbit-components-fix-picturecard-height.surge.sh</url>

fix(pictureCard): Enabling height to be smaller than 200

---

src/Alert/Alert.stories.js
src/Alert/README.md

<br/><br/><br/><url>LiveURL: https://orbit-components-DOCS--Adjust-Alert-docs-for-no-icon-w-o-title.surge.sh</url>

docs(Alert): Adjust Alert docs for no icon w/o title

---

src/TextLink/README.md
src/TextLink/TextLink.stories.js
src/TextLink/index.js
src/TextLink/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-update-textlink-title.surge.sh</url>

update(textLink): Adding title prop and attribute

---

src/Modal/ModalHeader/index.js
src/Modal/ModalHeader/index.js.flow
src/Modal/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-update-modal-mobile-title.surge.sh</url>

UPDATE: Change Modal title size to title2

---

src/Tooltip/Tooltip.stories.js
src/Tooltip/components/TooltipContent.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-tooltip-textlink.surge.sh</url>

fix(tooltip): usage of TextLink in content

---

package.json

<br/><br/><br/><url>LiveURL: https://orbit-components-chore-fix-storybook.surge.sh</url>

chore(storybook): fix static deploy to GH pages

---

src/Card/components/Header/index.js
src/Checkbox/index.js
src/Radio/index.js
src/SkipLink/index.js
src/Tag/index.js
src/TextLink/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-refactor-remove-unnecessary-pixels.surge.sh</url>

refactor: Remove unnecessary pixels in CSS declarations

---

src/List/List.stories.js
src/List/ListItem/index.js

There is a need for bigger spacing on mobile and also align should work without title.<br/><br/><br/><url>LiveURL: https://orbit-components-update-listitem-align.surge.sh</url>

style(List): Updating align within list and updating spacing

---

src/Select/index.js
src/Select/index.js.flow
src/SkipNavigation/index.js.flow

Need to be able to put multiple options with same value.  
In order to solve react key issue, we need to have ability to pass custom key prop.

feat(Select): Add optional key to Option

---

src/Tile/README.md
src/Tile/Tile.stories.js
src/Tile/components/TileHeader/index.js
src/Tile/components/TileHeader/index.js.flow
src/Tile/index.js
src/Tile/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-feat-tile-headericon.surge.sh</url>

feat(Tile): introduce noHeaderIcon property

---

src/utils/Grid/README.md

<br/><br/><br/><url>LiveURL: https://orbit-components-docs-grid-children-limitation.surge.sh</url>

docs(grid): Add children count limitation

---

.circleci/config.yml
commitlint.config.js
package.json
yarn.lock

Adding commitlint, spliting #1661 to separate MR as we are not sure yet about the changelog stuff
<br/><br/><br/><url>LiveURL: https://orbit-components-update-commit-lint.surge.sh</url>

feat: Adding commitlint and husky

---

src/Slider/components/Bar/index.js
src/Slider/components/Handle/index.js
src/Slider/components/Histogram/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-update-slider-color.surge.sh</url>

style(slider): updating color

---

src/Tooltip/Tooltip.stories.js
src/Tooltip/components/TooltipContent.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-tooltip-textlink-close.surge.sh</url>

fix(Tooltip): should close when clicked on clickable element

---

src/Hide/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-hide-rendering.surge.sh</url>

fix(Hide): omit rendering of on property

---

src/Modal/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-moda-closecontainer.surge.sh</url>

fix(Modal): click ability under CloseContainer

---

src/InputField/InputField.stories.js
src/InputField/InputTags/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-tag-height.surge.sh</url>

fix(InputField): Tag alignment

---

src/Select/README.md

<br/><br/><br/><url>LiveURL: https://orbit-components-docs-select-key.surge.sh</url>

docs(Select): add key property of Option

---

config/build.js
src/Icon/helpers/whiteListProps.js
src/Icon/helpers/whiteListProps.js.flow
src/Icon/index.js
src/Icon/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-chore-icon-build.surge.sh</url>

chore: improve icon build script

---

src/Button/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-button-white.surge.sh</url>

fix(Button): missing white type in flow definition

---

package.json

<br/><br/><br/><url>LiveURL: https://orbit-components-chore-release-841.surge.sh</url>

chore: release 0.84.1

---

package.json

<br/><br/><br/><url>LiveURL: https://orbit-components-chore-release-0842.surge.sh</url>

chore: release 0.84.2

---

src/Breadcrumbs/Breadcrumbs.stories.js
src/Breadcrumbs/BreadcrumbsItem/index.js
src/Breadcrumbs/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-bread-rtl.surge.sh</url>

fix(Breadcrumbs): render in RTL

---

src/defaultTheme.d.ts

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-ts-defaultTheme.surge.sh</url>

fix(Typescript): defaultTheme, missing instance

---

src/ThemeProvider/index.d.ts
src/defaultTheme.d.ts
src/utils/rtl/index.d.ts
src/utils/transition/index.d.ts

<br/><br/><br/><url>LiveURL: https://orbit-components-fix-ts-globaldeclare.surge.sh</url>

fix: defaultTheme global declaration and references of themeType

---

package.json

<br/><br/><br/><url>LiveURL: https://orbit-components-0-85-2.surge.sh</url>

chore(Release): 0.85.2

---

src/Stack/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-mainframe-typ.surge.sh</url>

fix(MediaQuery): spread type

---

src/Table/README.md
src/Table/Table.stories.js
src/Table/TableCell/consts.js
src/Table/TableCell/index.d.ts
src/Table/TableCell/index.js
src/Table/TableCell/index.js.flow

<br/><br/><br/><url>LiveURL: https://orbit-components-feat-table-align.surge.sh</url>

feat(TableCell): adding white-space and vertical align options

---

src/Stack/consts.js
src/Stack/helpers/getAlign.js
src/Stack/index.d.ts
src/Stack/index.js.flow
src/Tooltip/Tooltip.stories.js

Closes #1929 <br/><br/><br/><url>LiveURL: https://orbit-components-feat-stack-align-baseline.surge.sh</url>

feat(Stack): add baseline to align options

---

src/Portal/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-feat-portal-refactor-hooks.surge.sh</url>

feat(Portal): refactor to hooks

---

src/Dialog/index.js

<br/><br/><br/><url>LiveURL: https://orbit-components-feat-dialog-spacing.surge.sh</url>

feat(Dialog): change spacing between title and description
