.eslintrc, src/Button/Button.stories.js, src/Button/IconWrapper.js, src/Button/__tests__/IconWrapper.test.js, src/Button/__tests__/index.test.js, src/Button/index.js, src/Checkbox/index.js, src/Container/Header.js, src/Container/Section.js, src/Container/__tests__/Header.test.js, src/Container/__tests__/Section.test.js, src/FieldFeedback/__tests__/FieldFeedback.test.js, src/FieldFeedback/index.js, src/Input/Label.js, src/InputText/index.js, src/InputTextarea/index.js, src/Radio/Radio.stories.js, src/Radio/__tests__/index.test.js, src/Radio/index.js, src/Select/__tests__/Select.test.js, src/Select/index.js, src/SystemMessage/IconWrapper.js, src/SystemMessage/SystemMessage.stories.js, src/SystemMessage/__tests__/IconWrapper.test.js, src/SystemMessage/__tests__/Title.test.js, src/SystemMessage/__tests__/index.test.js, src/SystemMessage/index.js, src/Typography/index.js, src/index.js
=> created Radio component

.storybook/preview-head.html, package.json, src/Button/__snapshots__/Button.stories.storyshot, src/Button/__tests__/__snapshots__/index.test.js.snap, yarn.lock
There is a new version of orbit-design-tokens available: https://github.com/kiwicom/orbit-design-tokens/releases/tag/v0.0.2
We need also to import more Roboto weights and styles, because we use them through tokens.
=> Update imported Roboto font and orbit-design-tokens version

src/_deprecated/Checkbox/index.js, src/_deprecated/DeprecatedComponent.js, src/_deprecated/FieldFeedback/index.js, src/_deprecated/InputText/index.js, src/_deprecated/InputTextarea/index.js, src/_deprecated/Radio/index.js, src/_deprecated/Select/index.js, src/_deprecated/SystemMessage/index.js, src/_deprecated/Typography/index.js
Deprecated component was in wrong folder which is not handled by babel, moved to `src/_deprecated/DeprecatedComponent`
=> DEV: Fix build of deprecated component

src/_deprecated/InputTextarea/InputTextarea.js, src/_deprecated/InputTextarea/__snapshots__/InputTextarea.stories.storyshot
Fixes the `Warning: Use the `defaultValue` or `value` props instead of setting children on <textarea>`
=> Give a value to textarea via prop

.npmignore, package.json, yarn.lock
- Improve npmignore to only ship files related to the actual library
- Bump version number
- Resolve unupdated yarn.lock
=> Improve npmignore, bump version number

package.json
- Fixed closable button in Alert component
- rewrited to styled-components
- moved from deprecated
- import from base with `<ThemeProvider>` wrapper
- import from lib `lib/_deprecated/Checkbox` → `lib/Checkbox`
- added new props
- hasError `boolean` - state of checkbox with error
- info React.Node - render additional info
- rewrited to styled-components
- moved from deprecated
- import from base with `<ThemeProvider>` wrapper
- import from lib `lib/_deprecated/Radio` → `lib/Radio`
- added new props
- hasError `boolean` - state of radio with error
- info React.Node - render additional info
- added
- renders `<a/>` or `<button>` based on `href` prop
For usage check our storybook
https://kiwicom.github.io/orbit-components/
=> Release v0.0.0-rc11

src/Heading/Heading.js, src/Heading/Heading.stories.js, src/Heading/__snapshots__/Heading.stories.storyshot, src/Heading/__tests__/__snapshots__/index.test.js.snap, src/Heading/__tests__/index.test.js, src/Heading/index.js
Separated withTheme from Heading component.
Deleted ThemeProvider and unnecessary options from stories.
Updated test.
Added constants for element and type options.
**No more changes**
=> Separate withTheme from Heading component

src/TextLink/TextLink.js
TextLink's `href` prop should be optional. As said in #181
=> TextLink: Make href prop optional

package.json
- Usage without <ThemeProvider /> - import from lib/Heading/Heading
- Changed props - BC!
- url -> href (optional)
- newTab -> external
- Removed prop size
- Added prop rel (optional)
- Can render custom component
- Render a or button based on href prop
- Code
- Deals
- KiwicomCare
- KiwicomGuarantee
- Kiwicom
- Security
- Added styling <TextLink /> or <a /> passed as children
- Added line-height
- Rewrited to styled-components
- moved from deprecated
- import from base with `<ThemeProvider>` wrapper
- import from lib `lib/_deprecated/Select` → `lib/Select`
- Removed prop `required`
- Changed props
- options - receive array with select options, removed visible key
```
[
{ value: 1, label: "First item", disabled: true },
{ value: 2, label: "Second item" },
{ value: 3, label: "Third item" …
```
=> Release v0.0.0-rc12

src/Textarea/README.md, src/Textarea/Textarea.stories.js, src/Textarea/__snapshots__/Textarea.stories.storyshot, src/Textarea/__tests__/__snapshots__/index.test.js.snap, src/Textarea/__tests__/index.test.js, src/Textarea/consts.js, src/Textarea/index.js, src/Textarea/index.js.flow
Default `resize` changed to `vertical`.
Added optional prop `noResize` that sets `resize` to `none`.
Updated test and transition - animating only `border-color` and `box-shadow` due to enabled resizing.
=> UPDATE: Textarea resize

src/FormLabel/__tests__/__snapshots__/index.test.js.snap, src/FormLabel/__tests__/index.test.js, src/FormLabel/index.js, src/FormLabel/index.js.flow, src/InputField/InputField.stories.js, src/InputField/README.md, src/InputField/__snapshots__/InputField.stories.storyshot, src/InputField/__tests__/index.test.js, src/InputField/index.js, src/InputField/index.js.flow, src/InputGroup/__snapshots__/InputGroup.stories.storyshot
=> UPDATE: ContactInput, NEW: Asterisk at label

src/Icon/README.md
Fixed `README.md` for `Icons`. Wrong colors properties.
=> FIX: README.md for Icons

src/Checkbox/__snapshots__/Checkbox.stories.storyshot, src/Checkbox/__tests__/__snapshots__/index.test.js.snap, src/Checkbox/index.js
Fixed: an unnecessary render of prop `hasError` to the DOM of  `label` element.
=> FIX: CheckBox DOM rendering

src/Button/__snapshots__/Button.stories.storyshot, src/Button/index.js, src/ButtonLink/__snapshots__/ButtonLink.stories.storyshot, src/ButtonLink/index.js
Fixed undesirable DOM warning when circled prop has been passed
=> FIX: Circled Button, ButtonLink DOM warning

src/InputFile/__snapshots__/InputFile.stories.storyshot, src/InputFile/index.js, src/InputGroup/__snapshots__/InputGroup.stories.storyshot, src/Select/Select.stories.js, src/Select/__snapshots__/Select.stories.storyshot, src/Select/index.js
Fixed position of help/error in Select and InputFile with `position: relative`.
Closes #436 
Close #449
=> FIX: Select and InputFile help/error position

src/FormFeedback/index.js, src/InputField/__snapshots__/InputField.stories.storyshot, src/InputFile/__snapshots__/InputFile.stories.storyshot, src/Select/__snapshots__/Select.stories.storyshot, src/Stack/__snapshots__/Stack.stories.storyshot, src/Stack/__tests__/__snapshots__/index.test.js.snap, src/Textarea/__snapshots__/Textarea.stories.storyshot
Too much long text for `help` or `error` will be now hidden with a displayed ellipsis. 
Closes #458
=> FIX: Multi-line FormFeedback

src/Modal/__snapshots__/Modal.stories.storyshot, src/Modal/index.js
It was working on our Storybook, but not in the other projects.
=> FIX: Modal height on desktop

src/Tile/TileHeader/index.js, src/Tile/__snapshots__/Tile.stories.storyshot
Icon in Tile was shrinking if the title is too long. Only in IE 11.
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-tile-icon-shrink.surge.sh</url>
=> FIX: Tile icon shrink

src/CarrierLogo/__snapshots__/CarrierLogo.stories.storyshot, src/CarrierLogo/index.js, src/List/__snapshots__/List.stories.storyshot
Fixed wrong rendered size in `StyledCarrierLogo`.
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-carrierlogo-size.surge.sh</url>
=> FIX: CarrierLogo rendered size

src/Stack/README.md
Guys tried to pass `spacing` enums into `spaceAfter`. Added link to `getSpacingToken` func.<br/><br/><br/><url>LiveURL: https://orbit-components-fix-stack-spaceafter-docs.surge.sh</url>
=> FIX: Stack spaceAfter docs

storybooknative/.gitignore
Add the storybook build `./storybook-static` to the `.gitignore` file.
=> UDATE: storybooknative .gitignore

src/Modal/index.js
Added condition that checks if modal is closable
Fixes #553
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-closable-modal-click-outside.surge.sh</url>
=> FIX: non-closable modal onClick outside

src/Modal/__snapshots__/Modal.stories.storyshot, src/Modal/__tests__/__snapshots__/index.test.js.snap, src/Modal/index.js, src/Modal/index.js.flow
Fixed box-shadow in ModalFooter when the Modal is fully scrolled.
Fixed position of CloseContainer during initial animation on Mobile.<br/><br/><br/><url>LiveURL: https://orbit-components-fix-modal-footer-boxshadow.surge.sh</url>
=> FIX: ModalFooter box-shadow, Close position

package.json, yarn.lock
Updated `orbit-design-tokens` to 0.2.5.
Removed `react-icon-base` which is no longer used.<br/><br/><br/><url>LiveURL: https://orbit-components-dev-update-tokens-0-2-5.surge.sh</url>
=> DEV: Update orbit-design-tokens to 0.2.5

src/Modal/README.md
Closes #644 <br/><br/><br/><url>LiveURL: https://orbit-components-fix-modal-datatest-docs.surge.sh</url>
=> FIX: Modal dataTest docs

src/Tile/__tests__/__snapshots__/index.test.js.snap, src/Tile/__tests__/index.test.js, src/Tile/index.js
Closes #675 <br/><br/><br/><url>LiveURL: https://orbit-components-tile-tile-external-security.surge.sh</url>
=> FIX: Tile external security

src/Tile/TileHeader/index.js.flow
Closes #52 <br/><br/><br/><url>LiveURL: https://orbit-components-fix-forbid-function-type.surge.sh</url>
=> FIX: Forbid Function type

src/ServiceLogo/README.md, src/ServiceLogo/consts.js, src/ServiceLogo/index.js.flow
Added missing service logo for `ChinaUnionPay`<br/><br/><br/><url>LiveURL: https://orbit-components-add-chinaunionpay-servicelogo.surge.sh</url>
=> ADD: ChinaUnionPay logo

src/Checkbox/__snapshots__/Checkbox.stories.storyshot, src/Checkbox/__tests__/__snapshots__/index.test.js.snap, src/Checkbox/__tests__/index.test.js, src/Checkbox/index.js, src/InputField/__snapshots__/InputField.stories.storyshot, src/InputField/__tests__/__snapshots__/index.test.js.snap, src/InputField/__tests__/index.test.js, src/InputField/index.js, src/InputFile/__snapshots__/InputFile.stories.storyshot, src/InputFile/__tests__/__snapshots__/index.test.js.snap, src/InputFile/__tests__/index.test.js, src/InputFile/index.js, src/InputStepper/__snapshots__/InputStepper.stories.storyshot, src/InputStepper/index.js, src/Radio/__snapshots__/Radio.stories.storyshot, src/Radio/__tests__/__snapshots__/index.test.js.snap, src/Radio/__tests__/index.test.js, src/Radio/index.js, src/Select/__snapshots__/Select.stories.storyshot, src/Select/__tests__/Select.test.js, src/Select/__tests__/__snapshots__/Select.test.js.snap, src/Select/index.js, src/Textarea/__snapshots__/Textarea.stories.storyshot, src/Textarea/__tests__/__snapshots__/index.test.js.snap, src/Textarea/__tests__/index.test.js, src/Textarea/index.js
Closes #663 <br/><br/><br/><url>LiveURL: https://orbit-components-update-datatest-inputs.surge.sh</url>
=> UPDATE: move dataTest to inputs directly

.storybook/webpack.config.js
Fixed storybook rendering in IE 11 caused by not transpiled `loki` module<br/><br/><br/><url>LiveURL: https://orbit-components-fix-storybook-ie-11.surge.sh</url>
=> FIX: Storybook IE 11

src/Text/README.md, src/Text/index.js, src/Text/index.js.flow
Small possibility of breaking change - if someone explicitly used `weight=regular`.
Closes #651 <br/><br/><br/><url>LiveURL: https://orbit-components-fix-text-wrong-weight.surge.sh</url>
=> FIX: Text wrong weight value

readme.md
Added `styled-components` to the installation guide for clarity.<br/><br/><br/><url>LiveURL: https://orbit-components-docs-readme-styled-components.surge.sh</url>
=> DOCS: Add styled-components to installation guide

src/Checkbox/__snapshots__/Checkbox.stories.storyshot, src/InputField/__snapshots__/InputField.stories.storyshot, src/Radio/__snapshots__/Radio.stories.storyshot, src/Stack/__snapshots__/Stack.stories.storyshot, src/TextLink/README.md, src/TextLink/TextLink.stories.js, src/TextLink/__snapshots__/TextLink.stories.storyshot, src/TextLink/consts.js, src/TextLink/index.js, src/TextLink/index.js.flow, src/TripSector/__snapshots__/TripSector.stories.storyshot
Added optional `size` prop for TextLink. The default behavior is still `inherit` from a parent element.<br/><br/><br/><url>LiveURL: https://orbit-components-update-textlink-size.surge.sh</url>
=> UPDATE: Add size to TextLink

src/InputField/README.md, src/InputField/__snapshots__/InputField.stories.storyshot, src/InputField/index.js, src/InputGroup/__snapshots__/InputGroup.stories.storyshot, src/InputStepper/__snapshots__/InputStepper.stories.storyshot, src/InputStepper/__tests__/__snapshots__/index.test.js.snap, src/InputStepper/index.js, src/Modal/__snapshots__/Modal.stories.storyshot, src/Stack/__snapshots__/Stack.stories.storyshot, src/Stack/__tests__/__snapshots__/index.test.js.snap
Updated docs for usage `ButtonLink` in the `suffix` prop.
Removed webkit spin buttons from `InputField`. The selector was only in the `InputStepper` - removed.
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-inputfield-number-webkit-spin.surge.sh</url>
=> FIX: Remove webkit spin from InputField

src/Modal/README.md
Fixed wrong default value for prop `size`.<br/><br/><br/><url>LiveURL: https://orbit-components-fix-modal-docs-size.surge.sh</url>
=> FIX: Modal docs default size

src/Alert/index.js.flow, src/Badge/index.js.flow, src/ChoiceGroup/index.js.flow, src/InputField/index.js, src/InputField/index.js.flow, src/InputFile/index.js.flow, src/InputGroup/index.js.flow, src/InputStepper/index.js.flow, src/ListChoice/index.js.flow, src/Loading/index.js.flow, src/Select/index.js.flow, src/Textarea/index.js.flow, src/Tile/TileHeader/index.js.flow, src/Tile/index.js.flow, src/common/common.js.flow
Added flow restriction to some props which can receive only translation via component or string
Closes #371
Closes #343 
Closes #331 
Closes #711 <br/><br/><br/><url>LiveURL: https://orbit-components-restrict-flow-to-translation.surge.sh</url>
=> UPDATE: FLOW: Restricted Translation in some components

src/ChoiceGroup/__snapshots__/ChoiceGroup.stories.storyshot, src/ChoiceGroup/__tests__/__snapshots__/index.test.js.snap, src/ChoiceGroup/index.js, src/Stack/__snapshots__/Stack.stories.storyshot
Changed `spaceAfter` of `Heading` to `medium`.<br/><br/><br/><url>LiveURL: https://orbit-components-update-choicegroup-heading-spaceafter.surge.sh</url>
=> UPDATE: ChoiceGroup Heading spaceAfter

src/Modal/ModalFooter/index.js, src/Modal/__tests__/index.test.js
Added possibility to use a string inside ModalFooter.<br/><br/><br/><url>LiveURL: https://orbit-components-update-modalfooter-string.surge.sh</url>
=> FIX: ModalFooter string as children

src/InputField/InputField.stories.js, src/InputField/__snapshots__/InputField.stories.storyshot, src/InputField/index.js, src/InputGroup/__snapshots__/InputGroup.stories.storyshot, src/InputStepper/__snapshots__/InputStepper.stories.storyshot, src/InputStepper/__tests__/__snapshots__/index.test.js.snap, src/Modal/__snapshots__/Modal.stories.storyshot, src/Stack/__snapshots__/Stack.stories.storyshot, src/Stack/__tests__/__snapshots__/index.test.js.snap
Just deleted the attribute `width` directly on the `<input />`.
Tested in Chrome, Firefox, IE 10 - there should not be any visual breaking change of usage in Stack, because the attribute `width` is needed on the first element - in our case `<label />`.
Closes #756 <br/><br/><br/><url>LiveURL: https://orbit-components-fix-inputfield-suffix.surge.sh</url>
=> FIX: InputField suffix text overflow

src/Modal/ModalFooter/index.js, src/Modal/ModalHeader/index.js, src/Modal/__snapshots__/Modal.stories.storyshot, src/Modal/index.js
Fixed:
- Broken mobile header after scrolling in IE
- Modal position in IE (should be centered)
- laggy scrolling on iPad
- hidden footer on iOS
- other bugs reported from MMB
Closes #768 
Closes #794
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-modal-ie-safari.surge.sh</url>
=> FIX: Modal IE and iOS Safari flickering

src/Checkbox/__snapshots__/Checkbox.stories.storyshot, src/Checkbox/index.js, src/ChoiceGroup/__snapshots__/ChoiceGroup.stories.storyshot, src/Radio/__snapshots__/Radio.stories.storyshot, src/Radio/index.js, src/Stack/__snapshots__/Stack.stories.storyshot
Fixed wrapping text in IE 11.
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-radio-checkbox-text-flex.surge.sh</url>
=> FIX: Radio and CheckBox text wrap in IE

src/Alert/README.md, src/Breadcrumbs/README.md, src/Button/README.md, src/ButtonLink/README.md, src/Card/CardSection/CardSectionContent/index.js.flow, src/Card/CardSection/CardSectionHeader/index.js.flow, src/Card/README.md, src/Checkbox/README.md, src/ChoiceGroup/README.md, src/InputField/README.md, src/InputFile/README.md, src/InputGroup/README.md, src/InputStepper/README.md, src/ListChoice/README.md, src/Modal/README.md, src/Radio/README.md, src/Select/README.md, src/Stepper/README.md, src/Tag/README.md, src/TextLink/README.md, src/Textarea/README.md, src/Tile/README.md, src/TripSegment/README.md
Just better typing for docs for callbacks.
<br/><br/><br/><url>LiveURL: https://orbit-components-docs-better-callbacks.surge.sh</url>
=> DOCS: Better typing for call backs

src/Badge/README.md, src/Badge/__snapshots__/Badge.stories.storyshot, src/Badge/__tests__/__snapshots__/index.test.js.snap, src/Badge/index.js, src/Card/__snapshots__/Card.stories.storyshot
Fixed circled badge with an icon or just with some string in IE.
Improved documentation - the `circled` property is meant to be used only for two characters.
Closes #777 <br/><br/><br/><url>LiveURL: https://orbit-components-fix-badge-circled.surge.sh</url>
=> FIX: Circled Badge

src/Modal/index.js
When the `decideFixedFooter` was called inside some children (via context) it caused badly calculated `fullyScrolled` state, because it didn't count with the `scrollTop` value of the `ModalBody` element.
Original report: http://recordit.co/CLQzMIOmPH<br/><br/><br/><url>LiveURL: https://orbit-components-fix-modal-decidefixedfooter.surge.sh</url>
=> FIX: Modal decideFixedFooter method

src/Breadcrumbs/Breadcrumbs.stories.js, src/ChoiceGroup/ChoiceGroup.stories.js, src/Hide/Hide.stories.js, src/ListChoice/ListChoice.stories.js, src/Stepper/Stepper.stories.js, src/Tooltip/Tooltip.stories.js, src/_deprecated/Card/Card.stories.js
Cleaned console warnings for deprecated imports from @storybook/addon-knobs.<br/><br/><br/><url>LiveURL: https://orbit-components-dev-fix-imports-knobs.surge.sh</url>
=> DEV: Get rid of deprecated imports - knobs

src/CountryFlag/__tests__/__snapshots__/index.test.js.snap, src/CountryFlag/__tests__/index.test.js, src/CountryFlag/index.js, src/Illustration/__tests__/__snapshots__/index.test.js.snap, src/Illustration/__tests__/index.test.js, src/Illustration/index.js, src/ServiceLogo/__tests__/__snapshots__/index.test.js.snap, src/ServiceLogo/__tests__/index.test.js, src/ServiceLogo/index.js
Just added crossorigin anonymous to all images that are served from CDN.<br/><br/><br/><url>LiveURL: https://orbit-components-fix-images-cross-origin.surge.sh</url>
=> FIX: Cross origin images - prevent sending cookies

src/utils/mediaQuery/README.md
Update [docs](https://orbit.kiwi/guidelines/media-queries/)'s example of how to use Orbit's media query inside styled-component. Current `mq` does not work, it works with `media`.
=> UPDATE: media query example in docs

src/TripSector/index.js
Closes #870 <br/><br/><br/><url>LiveURL: https://orbit-components-fix-tripsector-icon-bg-ie.surge.sh</url>
=> FIX: TripSector icon background in IE

src/Loading/README.md
If the `loading` is set to false and the children prop is `null`, we have to render something - so the current behavior is alright.
Closes #432 and #522<br/><br/><br/><url>LiveURL: https://orbit-components-fix-loading-false.surge.sh</url>
=> DOCS: Loader with loading false

src/Badge/Badge.stories.js, src/Badge/__tests__/__snapshots__/index.test.js.snap, src/Badge/index.js
When Translate component was used inside Badge. The `flex` display trimmed the whitespaces that are necessary. Fixed just with wrapping `div`.<br/><br/><br/><url>LiveURL: https://orbit-components-fix-badge-with-translate.surge.sh</url>
=> FIX: Badge with translated node

src/Card/Card.stories.js, src/Card/index.js
If there isn't any `CardSectionHeader` CardSectionContent shouldn't has padding-top
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-cardsection-content-space.surge.sh</url>
=> FIX: CardSectionContent space fix

src/fromPlainObject.js, src/fromPlainObject.js.flow
We can't get rid off `orbit-design-tokens` as dependency in projects, when we don't have `fromPlainObject` export.
<br/><br/><br/><url>LiveURL: https://orbit-components-dev-update-tokens-export.surge.sh</url>
=> ADD: fromPlainObject export

src/Modal/index.js
Fix for this report:
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-modal-ie-unwanted-space.surge.sh</url>
=> FIX: Modal IE unwanted space between content and footer

src/ListChoice/_tests_/__snapshots__/index.test.js.snap, src/ListChoice/index.js
Updating render of heading to render to `div` instead of `H1`<br/><br/><br/><url>LiveURL: https://orbit-components-update-ListChoice-a11y.surge.sh</url>
=> UPDATE: ListChoice heading render

src/Sticky/index.js.flow
React was not imported in flow declaration `¯\_(ツ)_/¯`
Fixes #975 <br/><br/><br/><url>LiveURL: https://orbit-components-flow-fix-sticky-react-import.surge.sh</url>
=> FIX: Flow React import in Sticky

src/CountryFlag/index.js
When using `ca-fr` is code, the output of normalization was `anywhere` due to missing replace dash for underscore.<br/><br/><br/><url>LiveURL: https://orbit-components-fix-countryflag-normalization.surge.sh</url>
=> FIX: CountryFlag code normalization

src/Stack/__tests__/__snapshots__/index.test.js.snap, src/Stack/helpers/getDirection.js, src/Stack/helpers/getDirection.js.flow
Live URL: https://orbit-components-update-stack-spacing.surge.sh
=> FIX: Stack default direction in breakpoints

package.json, src/CountryFlag/index.js, yarn.lock
`@kiwicom/js` is not compiled properly and it's breaking usage of `orbit-components` in IE10+.
Removed for now.<br/><br/><br/><url>LiveURL: https://orbit-components-fix-countryflag-warning.surge.sh</url>
=> FIX: CountryFlag warning

src/Popover/README.MD
Fixing a not correct README for `opened` prop.<br/><br/><br/><url>LiveURL: https://orbit-components-update-popover-readme.surge.sh</url>
=> UPDATE: Popover opened readme

src/Select/Select.stories.js, src/Select/index.js
0 was counted as falsy when it can be a valid value.
BEFORE
AFTER
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-select-0-value.surge.sh</url>
=> FIX: 0 value counts as valid filled value in Select

src/common/getSpacingToken/README.md, src/common/getSpacingToken/consts.js, src/common/getSpacingToken/index.js, src/common/getSpacingToken/index.js.flow
Adding `none` option to `spaceAfter` prop - function, so developers can you it like this:
```jsx
<Text spaceAfter={someProperty ? "largest" : "none"} />
```
We can't use maybe type for that, as we need to support `spaceAfter` in media queries in the Stack component and it can be rendered with `null` or `undefined`.<br/><br/><br/><url>LiveURL: https://orbit-components-update-none-spaceafter.surge.sh</url>
=> UPDATE: Add none spaceAfter option

src/Button/index.js, src/ButtonLink/__tests__/__snapshots__/index.test.js.snap, src/ButtonLink/index.js
When someone used combination of `Stack` with `direction="column"` and block Button, the height was broken. https://codesandbox.io/s/orbitsandbox-izupg<br/><br/><br/><url>LiveURL: https://orbit-components-fix-buttons-stack-column.surge.sh</url>
=> FIX: Buttons flex for column Stack

package.json, yarn.lock
Next version throws errors but this is a good first step to bump it again to 96.
<br/><br/><br/><url>LiveURL: https://orbit-components-flow-95.surge.sh</url>
=> DEV: Upgrade Flow to version 0.95.0

src/Layout/README.md, src/Stack/README.md
There was a wrong default in `Stack` `shrink` prop. And `Layout` missed proper `type` prop in readme.<br/><br/><br/><url>LiveURL: https://orbit-components-update-doc-fixes.surge.sh</url>
=> DOCS: Fix Stack shrink and Layout examples 

src/Alert/Alert.stories.js, src/Alert/README.md, src/Alert/__tests__/__snapshots__/index.test.js.snap, src/Alert/index.js, src/Alert/index.js.flow
Adding `inlinActions` prop for cases where there is only a heading and displaying a button under heading wouldn't look ideal.<br/><br/><br/><url>LiveURL: https://orbit-components-update-alert-inline.surge.sh</url>
=> UPDATE: Alert inlineActions prop

src/ButtonGroup/ButtonGroup.stories.js, src/ButtonGroup/index.js
Added deprecation warning for usage `connected` property of ButtonGroup.<br/><br/><br/><url>LiveURL: https://orbit-components-update-buttongroup-connected.surge.sh</url>
=> UPDATE: Deprecate connected prop in ButtonGroup

src/Pagination/README.md
<br/><br/><br/><url>LiveURL: https://orbit-components-docs-pagination-escape.surge.sh</url>
=> DOCS: Fixing wrong escape in pagination

src/FormLabel/index.js
Adding `aria-hidden` to asterisk in label of a required input field. To prevent screen readers reading a label as "Star label".<br/><br/><br/><url>LiveURL: https://orbit-components-update-required-fields-accessibility.surge.sh</url>
=> UPDATE: required field accessibility

src/InputField/InputTags/index.js
Fix for bug on iOS devices, when tags inside `InputField` are not visible.
https://monosnap.com/file/Urm4Rj5hzNwiVhlZG12PIXcCVI9zfY
Problem is not present on all devices (it doesn't appear for example on 6th gen iPad), but can be replicated on iPad Air 2 (physical which is used by QA for testing or configuration below available on browserstack.com ).
https://monosnap.com/file/kSoUOhDlaLslUAKHmusNlHJsLfGcxH
https://monosnap.com/file/pX1pN2yp72kIuQcPqT2CTPvbGgWQfF<br/><br/><br/><url>LiveURL: https://orbit-components-fix-inputfield-tags-ios.surge.sh</url>
=> FIX: Invisible tags inside InputField on iOS

src/Modal/index.js
Limiting `Modal` click outside functionality only to `ModalBody` and `ModalWrapper`.
To prevent modal from closing in special cases when content is nested inside modal, but added to DOM using Portals (Modals, Notifications...).
More in Slack discussion: https://skypicker.slack.com/archives/CAMS40F7B/p1559045983010400<br/><br/><br/><url>LiveURL: https://orbit-components-update-modal-click-outside.surge.sh</url>
=> UPDATE: Modal click outside condition

src/TextLink/index.js
Fixed unnecessary re-rendering when component properties change.<br/><br/><br/><url>LiveURL: https://orbit-components-fix-textlink-component-render.surge.sh</url>
=> FIX: TextLink default component render

src/Button/index.js, src/ButtonLink/index.js
`Button` and `ButtonLink` `href` redirect shouldn't work when button is `disabled`.
Bug in action: https://monosnap.com/file/OivUBrIU35bme3mqJSQfkebXfwk9lU
Fixed by removing `href` and related attributes when buttons are disabled.<br/><br/><br/><url>LiveURL: https://orbit-components-fix-button-link-disabled.surge.sh</url>
=> FIX: Disabled link Buttons shouldn't be clickable

src/TextLink/index.js
When someone used generic `anchor` and not `TextLink` inside Alert's children, there was default font-weight, but should be `500 - fontWeightLinks`.<br/><br/><br/><url>LiveURL: https://orbit-components-fix-alert-anchor-font-weight.surge.sh</url>
=> FIX: Anchor in Alert font weight

src/CountryFlag/README.md
<br/><br/><br/><url>LiveURL: https://orbit-components-docs-fix-countryflag.surge.sh</url>
=> DOCS: Fix default name in CountryFlag

yarn.lock
Just updated `yarn.lock` as it didn't contain `tilde` operator for `orbit-design-tokens`.<br/><br/><br/><url>LiveURL: https://orbit-components-dev-yarn-lock-update.surge.sh</url>
=> DEV: Update yarn.lock

src/Tile/README.md
<br/><br/><br/><url>LiveURL: https://orbit-components-docs-tile-datatest.surge.sh</url>
=> DOCS: Fix missing dataTest for Tile

src/Popover/Popover.stories.js, src/Popover/__tests__/__snapshots__/index.test.js.snap, src/Popover/components/ContentWrapper.js, src/hooks/useClickOutside.js, src/hooks/useClickOutside.js.flow
Fixed case where user had to firstly close first Popover and then open the second one. Now works with one click.<br/><br/><br/><url>LiveURL: https://orbit-components-fix-multiple-popovers-close-open.surge.sh</url>
=> FIX: Multiple Popovers close and open

src/Button/index.js, src/ButtonLink/__tests__/__snapshots__/index.test.js.snap, src/ButtonLink/index.js
When `CountryFlag` was passed into `ButtonLink` or `Button` it was stretched due to old selector.<br/><br/><br/><url>LiveURL: https://orbit-components-fix-countryflag-in-buttons.surge.sh</url>
=> FIX: CountryFlag dimensions in Buttons

src/FeatureIcon/README.md
<br/><br/><br/><url>LiveURL: https://orbit-components-docs-fix-featureicon.surge.sh</url>
=> DOCS: Fix enum in FeatureIcon

src/Modal/README.md
Closes #1359<br/><br/><br/><url>LiveURL: https://orbit-components-docs-fix-modal-portal.surge.sh</url>
=> DOCS: Fix link to Portal component in Modal

src/Modal/ModalFooter/index.js
Close #1344<br/><br/><br/><url>LiveURL: https://orbit-components-fix-modalfooter-ref.surge.sh</url>
=> FIX: ModalFooter cloning child with ref

src/Radio/Radio.stories.js, src/Tooltip/index.js
Changing from inline-block to inline-flex due to Icon not being aligned vertically in center<br/><br/><br/><url>LiveURL: https://orbit-components-fix-radio-icon.surge.sh</url>
=> FIX: Tooltip children wrapper set to inline-flex

src/ChoiceGroup/components/FilterWrapper.js
Removing combined selector &:hover, &:focus-within as it is not rendered correctly in IE and Edge<br/><br/><br/><url>LiveURL: https://orbit-components-fix-choicegroup-focus-ie.surge.sh</url>
=> FIX: ChoiceGroup filter hover and focus

src/Select/index.js
Autofill in chrome caused hidden text to show back up<br/><br/><br/><url>LiveURL: https://orbit-components-fix-autofill.surge.sh</url>
=> FIX: Select autofill text color

package.json, src/Button/index.js, src/ButtonLink/index.js, src/CountryFlag/index.js, src/NavigationList/NavigationListItem/index.js, src/Slider/index.js, yarn.lock
Hi 👋 
I would like to replace `@kiwicom/js` by `@adeira/js`. `@kiwicom/js` will be no longer maintained, along with other open-sourced projects in original universe repo. Adeira is its continuation https://github.com/adeira/universe/tree/master/src/js 
<br/><br/><br/><url>LiveURL: https://orbit-components-use-adeira.surge.sh</url>
=> DEV: Use @adeira/js instead of @kiwicom/js

package.json
Adding `"sideEffects": false` to `package.json` tells module bundlers that none of the modules in this package have side effects, meaning that importing them won't execute anything, so it's safe to tree-shake unused exports.
This applies to the ESM build in `es` directory.
https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
=> FIX: Enable tree-shaking for module bundlers

src/Breadcrumbs/index.js
<br/><br/><br/><url>LiveURL: https://orbit-components-mainframe-breadcrumb.surge.sh</url>
=> FIX: Breadcrumbs falsey value in mapping children

src/Button/README.md
Button prop `block` is deprecated should be `fullWidth` instead.
=> DOCS: Update Button block prop in README

src/Card/CardSection/components/SectionHeader.js, src/Card/CardSection/index.js, src/Card/index.js
There was missing condition, so it was not possible to use custom `header` prop
Also i removed padding in CardSection bottom if there is not children in CardSection. <br/><br/><br/><url>LiveURL: https://orbit-components-mainframe-crdhdrfix.surge.sh</url>
=> FIX: Card header prop, padding in CardSection

.dependabot/config.yml
`: ` should be added automatically when prefix is set 🙂 
<br/><br/><br/><url>LiveURL: https://orbit-components-update-dependabot.surge.sh</url>
=> DEV: update dependabot to prefix commits with "DEV:"

.flowconfig, package.json, src/InputField/index.js, src/InputField/index.js.flow, src/Modal/ModalContext.js, src/Modal/ModalContext.js.flow, src/Modal/ModalFooter/index.js, src/Modal/ModalHeader/index.js, src/Modal/ModalSection/index.js, src/Popover/components/ContentWrapper.js, src/Slider/components/Bar/index.js.flow, src/Slider/index.js, src/Tile/components/TileContent/index.js, src/Tile/components/TileContent/index.js.flow, src/Tile/components/TileExpandable/index.js, src/hooks/useMediaQuery/index.js, src/utils/Grid/index.js, src/utils/mediaQuery/index.js, yarn.lock
- update flow to latest version (`0.115.0`)
- fix broken flow types where possible - mostly refs
- broken checks which I found too difficult to fix (and benefit of fixing them is not high) are disabled following this guide: https://medium.com/flow-type/upgrading-flow-codebases-40ef8dd3ccd8<br/><br/><br/><url>LiveURL: https://orbit-components-update-flow-bin.surge.sh</url>
=> DEV: Update flow-bin to 0.115.0

src/utils/mediaQuery/README.md
This pull request only changes the ReadMe.md for mediaQuery.
<br/><br/><br/><url>LiveURL: https://orbit-components-docs-example-for-media-queries.surge.sh</url>
=> DOCS: Add theme to example for media queries

src/Stack/README.md
Stack prop `grow` has default value `true` not `false`
=> DOCS: Fix wrong default value for grow in Stack

src/Select/Select.stories.js, src/Select/index.js
This fix is needed for case where `Select` has `customValueText` and it's autofilled by webkit based browser.
In that case autofilled `value` would be displayed, overflowing `customValueText`.<br/><br/><br/><url>LiveURL: https://orbit-components-fix-select-autofill.surge.sh</url>
=> FIX: Select autofill setting

src/Tag/Tag.stories.js, src/Tag/index.js
What: Removing `cursor:pointer;` hover, focus and active states from non-actionable type of `Tag`
Why: By specification, Tag offers a label that can optionally be selected and unselected or removed. So forcing cursor: pointer; is not desired. <br/><br/><br/><url>LiveURL: https://orbit-components-fix-tag-pointer.surge.sh</url>
=> FIX: Tag displaying cursor:pointer and states on non-actionable type

src/Checkbox/Checkbox.stories.js, src/TextLink/README.md, src/TextLink/TextLink.stories.js, src/TextLink/index.js, src/TextLink/index.js.flow
Why: In some cases TextLink is used to open a new tab but with bubbling it will select e.g. CheckBox which is undesired behaviour.<br/><br/><br/><url>LiveURL: https://orbit-components-update-add-stoppropagation-textlink.surge.sh</url>
=> UPDATE: Add stopPropagation property to TextLink

src/PricingTable/PricingTable.stories.js, src/PricingTable/PricingTableItem/index.js, src/PricingTable/PricingTableItem/index.js.flow, src/PricingTable/README.md, src/PricingTable/__tests__/index.test.js, src/PricingTable/index.js, src/PricingTable/index.js.flow
Adding a `hasError` and removing state, to support non selected variant.
Why: There was a need to make PricingTable more customisable 
<br/><br/><br/><url>LiveURL: https://orbit-components-update-pricing-table-uncontrolled.surge.sh</url>
=> BREAKING: PricingTable uncontrolled

src/ChoiceGroup/ChoiceGroup.stories.js, src/ChoiceGroup/README.md, src/ChoiceGroup/components/FilterWrapper.js, src/ChoiceGroup/components/FilterWrapper.js.flow, src/ChoiceGroup/index.js, src/ChoiceGroup/index.js.flow
Why: We can't provide generic translation key for this use case as it's very dependent on the actual usage and also language context.
<br/><br/><br/><url>LiveURL: https://orbit-components-update-add-onlyselectiontext-choicegroup.surge.sh</url>
=> UPDATE: Add onlySelectionText property to filter ChoiceGroup

.gitignore, config/build.js
Added a file on build listing airport illustrations. No new tests required and no components added. <br/><br/><br/><url>LiveURL: https://orbit-components-docs-add-airport-illustration-data.surge.sh</url>
=> DOCS: Add data file for airport illustrations

src/Illustration/README.md
Removed illustrations that have been moved to AirportIllustration.<br/><br/><br/><url>LiveURL: https://orbit-components-docs-update-illustration-list.surge.sh</url>
=> DOCS: Removed airports from list of illustrations

src/Modal/index.js
Fixing calling a onClose callback on mobile devices, the callback was on a bad element causing it to not call onClose on mobile.<br/><br/><br/><url>LiveURL: https://orbit-components-fix-modalOverlay.surge.sh</url>
=> FIX: Modal close on mobile devices

src/InputField/InputField.stories.js, src/InputField/README.md, src/InputField/__tests__/index.test.js, src/InputField/index.js, src/InputField/index.js.flow, src/Select/README.md, src/Select/Select.stories.js, src/Select/__tests__/Select.test.js, src/Select/index.js, src/Select/index.js.flow, src/common/common.js.flow
Adding `dataAttrs` property to InputField and Select, so devs are able to pass custom `data-*` attributes to the root DOM elements.<br/><br/><br/><url>LiveURL: https://orbit-components-updaate-inputs-dataattrs.surge.sh</url>
=> UPDATE: Add dataAttrs property to InputField and Select

src/Button/index.js
Why: according to specs element `div` is not allowed as child of element `button`. So I'm changing the elements to `span` which are allowed.
=> FIX: Semantic of a button

src/AirportIllustration/AirportIllustration.stories.js, src/AirportIllustration/FLOW_TEMPLATE.flow, src/AirportIllustration/README.md, src/AirportIllustration/index.js, src/Illustration/FLOW_TEMPLATE.flow, src/Illustration/Illustration.stories.js, src/Illustration/README.md, src/Illustration/index.js, src/primitives/IllustrationPrimitive/README.md, src/primitives/IllustrationPrimitive/__tests__/index.test.js, src/primitives/IllustrationPrimitive/index.js, src/primitives/IllustrationPrimitive/index.js.flow
Why: Sometimes we want to use different `alt` on the DOM element than the illustration name. It doesn't always cover the exact context.<br/><br/><br/><url>LiveURL: https://orbit-components-feat-illustration-alt-optional.surge.sh</url>
=> feat(illustrations): Add optional alt property

src/Tile/README.md, src/Tile/Tile.stories.js, src/Tile/__tests__/index.test.js, src/Tile/components/TileExpandable/index.js, src/Tile/components/TileExpandable/index.js.flow, src/Tile/components/TileWrapper/index.js, src/Tile/components/TileWrapper/index.js.flow, src/Tile/index.js, src/Tile/index.js.flow
Adding title attribute to enable native tooltip on hover to appear, useful for adding extra piece of information.
@vepor What do you think about the naming? I was not able to think of anything better that that, due to already having a Title a Description taken 🤔 <br/><br/><br/><url>LiveURL: https://orbit-components-update-tile-title.surge.sh</url>
=> feat(Tile): Adding title attribute

src/InputField/index.js, src/InputFile/index.js, src/InputGroup/index.js, src/Select/index.js, src/Textarea/index.js
This reverts commit c9b67164
Why: We need to revert native design sync for form elements, because some legacy implementations don't count with usage of grey inputs on not white background.  
<br/><br/><br/><url>LiveURL: https://orbit-components-revert-form-elements.surge.sh</url>
=> revert(FormElements): native design sync

src/Tooltip/components/TooltipContent.js
Extends #1742
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-tooltip-close-mobile.surge.sh</url>
=> fix(Tooltip): with clickable element should close on mobile

src/Button/README.md, src/ButtonLink/README.md, src/TextLink/README.md, src/common/common.js.flow
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-types-ascomponent.surge.sh</url>
=> fix: types of asComponent

package.json, yarn.lock
<br/><br/><br/><url>LiveURL: https://orbit-components-chore-update-tokens.surge.sh</url>
=> chore: bump @kiwicom/orbit-design-tokens from 0.9.0 to 0.10.0

src/InputStepper/index.d.ts
I had this error when running my type-checking with TS:
```
node_modules/@kiwicom/orbit-components/lib/InputStepper/index.d.ts(35,24): error TS7051: Parameter has a name but no type. Did you mean 'arg0: number'?
```
<br/><br/><br/><url>LiveURL: https://orbit-components-RobinCsl-patch-1.surge.sh</url>
=> fix(InputStepper): improve TypeScript definition

.storybook/manager.js
If `addon-knobs` is registered first, it will show up as the first tab.
Every time I open a Storybook Playground page, I have to click on Knobs before I can start "playing".
<br/><br/><br/><url>LiveURL: https://orbit-components-sampi-storybook-addon-knobs-first.surge.sh</url>
=> chore(Storybook): open 'Knobs' panel by default

src/Breadcrumbs/_tests_/index.test.js, src/Breadcrumbs/index.js
<br/><br/><br/><url>LiveURL: https://orbit-components-sampi-breadcrumbs-mobile-back.surge.sh</url>
=> fix(Breadcrumbs): add mobile back button onClick

src/primitives/IllustrationPrimitive/index.js
There is a issue when Illustration has a parent with flex properties, causing it to shrink unnecessary <br/><br/><br/><url>LiveURL: https://orbit-components-fix-illustration-shrink.surge.sh</url>
=> fix(IllustrationPrimitive): defaulting flex shrink to false

package.json, yarn.lock
Instead of prettifying all `*.md` files on every push, we prettify only staged `*.md` files on every commit, which is much more performant.
<br/><br/><br/><url>LiveURL: https://orbit-components-chore-lint-staged.surge.sh</url>
=> chore: prettify only staged *.md files on commit

examples/Collapse/DEFAULT.json, examples/Coupon/DEFAULT.json, src/Collapse/__examples__/DEFAULT.js, src/Coupon/__examples__/DEFAULT.js
So it works at orbit.kiwi
<br/><br/><br/><url>LiveURL: https://orbit-components-docs-examples.surge.sh</url>
=> docs: fix markup for Coupon example

src/Breadcrumbs/Breadcrumbs.stories.js, src/Breadcrumbs/__tests__/index.test.js, src/Breadcrumbs/index.d.ts, src/Breadcrumbs/index.js, src/Breadcrumbs/index.js.flow
This will allow the back breadcrumb to be a link when needed
<br/><br/><br/><url>LiveURL: https://orbit-components-bread-crumbs-href.surge.sh</url>
=> feat(Breadcrumbs): add backHref prop

src/Heading/index.d.ts, src/Textarea/index.d.ts
Adjust the TS types for the` TextArea` (add `ref` attribute), and the `Heading` ( use the `As` type instead of `Element`).
=> fix(types): adjust Typescript types for Heading and TextArea

src/Breadcrumbs/index.d.ts, src/Tile/index.d.ts, src/primitives/ButtonPrimitive/index.d.ts
- export `BreadcrumbsItem` component type from the index.d.ts file on `Breadcrumbs`
- add `noHeaderIcon` and `htmlTitle` to `Tile` props
- add `Ref` prop to `Button`
=> fix(types): adjust Breadcrumbs, Tile, Button type declarations and exports

src/Stack/index.d.ts
add `readonly as?: string` to the types definition of `Stack`, which was missing
=> fix(Stack): add the "as" attribute to typescript types

src/InputField/index.d.ts
<br/><br/><br/><url>LiveURL: https://orbit-components-fix-inputfield-inputmode.surge.sh</url>
=> fix(InputField): missing inputMode in typescript props

src/utils/mediaQuery/consts.d.ts, src/utils/mediaQuery/index.d.ts
Added a new module `@kiwicom/orbit-components/lib/utils/mediaQuery/consts`, which exports the types for `mediaQuery/consts`. This is needed to correctly type the `QUERIES` object (using it for SSR breakpoints definitions). 
Before there were not present and typescript would infer the wrong type for the keys on the client.
=> feat(MediaQuery): add Typescript types for MediaQuery/consts

.circleci/config.yml, .github/workflows/main.yml, package.json
1. fix build failure in compressed size action
2. run Lerna's [`bootstrap` command](https://github.com/lerna/lerna/tree/f6e7a13e60fefc523d701efddfcf0ed41a77749b/commands/bootstrap) in CI, which symlinks packages and other stuff
Btw, we should run `yarn bootstrap` locally to first initialize the monorepo and when adding/removing packages. Currently we only have one `orbit-components`, but when we add `orbit-design-tokens`, `bootstrap` script is needed to symlink the dependency.
=> ci: bootstrap packages

lerna.json
As agreed, I'm removing exact cross-dependency versioning to leave the strategy that we were using before. We can always change it later if needed.<br/><br/><br/><url>LiveURL: https://orbit-components-chore-monorepo-fixes.surge.sh</url>
=> chore: remove exact cross-dependency versioning

.github/workflows/main.yml, package.json
<br/><br/><br/><url>LiveURL: https://orbit-components-ci-fix-compressed-size.surge.sh</url>
=> ci: add missing build step to compressed size

packages/orbit-components/jest.config.js
By adding `displayName` to all projects we can use [`--selectProjects`](https://jestjs.io/docs/en/cli#--selectprojects-project1--projectn) to run tests only for specific projects.
<br/><br/><br/><url>LiveURL: https://orbit-components-chore-jest-display-name.surge.sh</url>
=> chore: add display name to Jest project

package.json, packages/orbit-components/package.json
- `buildExample.js` uses `prettier`, so it needs to be in the dependencies
- this mistake slipped past us because I made a mistake in the `test-ci` script, now it's fixed
<br/><br/><br/><url>LiveURL: https://orbit-components-chore-add-prettier-to-orbit-components.surge.sh</url>
=> Add prettier to orbit-components dependencies

.github/workflows/deploy.yml
Because we use `github.head_ref` (branch name) variable for deployment to surge, we don't have to do it for pushes to master. We use GH pages for master branch. <br/><br/><br/><url>LiveURL: https://orbit-chore-deploy-run.surge.sh</url>
=> chore: don't run deploy on master branch

packages/babel-plugin-orbit-components/jest.config.js
<br/><br/><br/><url>LiveURL: https://orbit-chore-babel-plugin-jest-config.surge.sh</url>
=> chore: fix typo in Babel plugin's Jest config

.github/workflows/test.yml
I've forgot to add `if` expression to the deploy step, so it doesn't run on master branch.<br/><br/><br/><url>LiveURL: https://orbit-fix-deploy-master.surge.sh</url>
=> chore: add if expression to deploy step

.github/workflows/release.yml
Tags are prefixed with the package name since converting to the monorepo.
<br/><br/><br/><url>LiveURL: https://orbit-ci-fix-release.surge.sh</url>
=> ci: fix release workflow tag pattern

packages/orbit-components/src/Breadcrumbs/index.js
According to discussion in [*plz-orbit*](https://skypicker.slack.com/archives/CAMS40F7B/p1601040561004300)<br/><br/><br/><url>LiveURL: https://orbit-fix-breadcrumbs.surge.sh</url>
=> fix(Breadcrumbs): add check for absence of props on mobile

packages/orbit-components/src/Tile/components/TileHeader/index.js, packages/orbit-components/src/Tile/index.js
[jira backlog issue](https://jira.kiwi.com/browse/ORBIT-1044)
prop `external` for `TileHeader` just was missing.<br/><br/><br/><url>LiveURL: https://orbit-fix-tile.surge.sh</url>
=> fix(Tile): newWindow icon on external 

packages/orbit-components/icons/package.json, packages/orbit-components/package.json
While icons can be imported from the root entry point:
```js
import { Icons } from "@kiwicom/orbit-components"
```
this way all icons end up in the bundle. Instead we should provide another entry point just for icons:
```js
import { Accommodation } from "@kiwicom/orbit-components/icons";
```
This way tools that support ES, like webpack, will import from
`@kiwicom/orbit-components/es/icons`. Others will import from `*/lib/icons`.
<br/><br/><br/><url>LiveURL: https://orbit-feat-import-icons.surge.sh</url>
=> feat: add an agnostic entry point for icons

.github/workflows/release.yml
I incorrectly fixed it in #2240. See the [filter pattern cheat sheet](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet).<br/><br/><br/><url>LiveURL: https://orbit-ci-fix-tag-pattern.surge.sh</url>
=> ci: fix invalid tag pattern

packages/babel-plugin-orbit-components/package.json, packages/babel-plugin-orbit-components/scripts/testRequire.js
When I got the error in the former screenshot (it was for another module), it took me a while to figure out what it meant even though I was the one who reviewed the PR that added this test, so I wanted to improve the error message.
Before:
After:
<br/><br/><br/><url>LiveURL: https://orbit-test-babel-plugin-dx.surge.sh</url>
=> test: improve failure message for the Babel plugin

.gitattributes
// every contributor now pushes git changes from unix OS as far as i know,
// but just in case if someone would like to contribute from windows,
// it will be useful to enforce eol to lf
<br/><br/><br/><url>LiveURL: https://orbit-fix-line-endings.surge.sh</url>
=> fix: force eol to lf

packages/orbit-components/src/AirportIllustration/__tests__/index.test.js, packages/orbit-components/src/Alert/__tests__/index.test.js, packages/orbit-components/src/Badge/__tests__/index.test.js, packages/orbit-components/src/Breadcrumbs/__tests__/index.test.js, packages/orbit-components/src/Breadcrumbs/index.js
- chore: update Jest libdef
- test(AirportIllustration): use TestingLibrary
- test(Alert): use Testing Library
- test(Badge): use Testing Library
- test(Breadcrumbs): use Testing Library
- chore(Breadcrumbs): remove implied ARIA role
<br/><br/><br/><url>LiveURL: https://orbit-test-enzyme-to-testing-library.surge.sh</url>
=> Move to Testing Library in AirportIllustration, Alert, Badge and Breadcrumbs

package.json, packages/orbit-components/package.json
Lerna publishes packages by running the publish command for each package
individually, therefore `prepublishOnly` in the root `package.json` will
never run. This should be the correct place for it.
<br/><br/><br/><url>LiveURL: https://orbit-build-prepublish-only.surge.sh</url>
=> build: move prepublishOnly to correct package.json

packages/babel-plugin-orbit-components/__tests__/__snapshots__/index.test.js.snap, packages/babel-plugin-orbit-components/__tests__/index.test.js, packages/babel-plugin-orbit-components/index.js
This was supposed to be part of #2237.<br/><br/><br/><url>LiveURL: https://orbit-fix-babel-import-icons.surge.sh</url>
=> fix: support icons entry point with Babel plugin

packages/orbit-components/src/InputGroup/index.d.ts, packages/orbit-components/src/Layout/LayoutColumn/index.d.ts
It seems that you don't have any `tsc --noEmit` job on CI nor on your
local development environment; I realise this is because there are some
issues with `@types/styled-components` depending on `@types/react-native`
and other things.
I would suggest to still run `tsc --noEmit` on your local machine
for some sanity check, to ensure no broken types are shipped.
<br/><br/><br/><url>LiveURL: https://orbit-rcsl-fix-types.surge.sh</url>
=> fix: fix InputGroup/LayoutColumn TS typing

packages/orbit-components/src/Collapse/index.js, packages/orbit-components/src/primitives/ButtonPrimitive/index.d.ts, packages/orbit-components/src/primitives/ButtonPrimitive/index.js, packages/orbit-components/src/primitives/ButtonPrimitive/index.js.flow, yarn.lock
- The passed label will now be read by the screen reader
- The screen reader will read collapsed or expanded
<br/><br/><br/><url>LiveURL: https://orbit-tbergq-fix-collapsable-a11y.surge.sh</url>
=> fix: move collapsable aria labels to the focusable button

commitlint.config.js
Adds the `improve` type to the commitlint configuration, so now you can do commits with the `improve` type. This is useful for huge tooling and platform changes, like the commit of this MR of course 😂
e.g. of usage (also in the commit)
```
improve(Something): adds a lot of awesome changes
```
=> improve(Commitlint): add the improve type to commitlint

config/eslintJS.js, packages/orbit-components/src/Breadcrumbs/__tests__/index.test.js, packages/orbit-components/src/CallOutBanner/__tests__/index.test.js, packages/orbit-components/src/Heading/__tests__/index.test.js, packages/orbit-components/src/InputGroup/__tests__/index.test.js, packages/orbit-components/src/Layout/consts.js, packages/orbit-components/src/Select/__tests__/Select.test.js, packages/orbit-components/src/Slider/__tests__/index.test.js, packages/orbit-components/src/Slider/components/Histogram/_tests_/index.test.js, packages/orbit-components/src/Textarea/__tests__/index.test.js, packages/orbit-components/src/Tile/components/TileContent/__tests__/index.test.js, packages/orbit-components/src/primitives/TooltipPrimitive/hooks/__tests__/useDimensions.test.js, packages/orbit-components/src/utils/Slide/__tests__/client.test.js, packages/orbit-components/src/utils/Slide/__tests__/server.test.js, packages/orbit-components/src/utils/validateDecrement/__test__/index.test.js
- forbid usage of [focused-tests](https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/no-focused-tests.md)
- consistent `it` [consistent-test-it](https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/consistent-test-it.md)
- removed identical titles [no-identicial-title](https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/no-identical-title.md)
Fixes #2348.
and etc. <br/><br/><br/><url>LiveURL: https://orbit-chore-eslint-jest-only.surge.sh</url>
=> chore: eslint jest rules

packages/orbit-components/src/utils/Grid/Grid.stories.js, packages/orbit-components/src/utils/Grid/README.md, packages/orbit-components/src/utils/Grid/__tests__/index.test.js, packages/orbit-components/src/utils/Grid/helpers/getViewportGridStyles.js, packages/orbit-components/src/utils/Grid/index.d.ts, packages/orbit-components/src/utils/Grid/index.js, packages/orbit-components/src/utils/Grid/index.js.flow
Added `width` property so developers can provide the container needed width in their use case. This property was also added to MediaQuery object.<br/><br/><br/><url>LiveURL: https://orbit-feat-grid-width.surge.sh</url>
=> feat(Grid): add width property

packages/orbit-components/src/TextLink/index.d.ts
Fixed `ariaCurrent` property that was marked as optional in Flow definition, but not in the TS definition.<br/><br/><br/><url>LiveURL: https://orbit-fix-textlink-aria-def.surge.sh</url>
=> fix(TextLink): ariaCurrent should in optional in TS definition

packages/orbit-components/src/utils/transition/__tests__/index.test.js, packages/orbit-components/src/utils/transition/index.js
- Transitions can be deactivated by explicitly setting theme.transitions to false
<br/><br/><br/><url>LiveURL: https://orbit-animations-default-on.surge.sh</url>
=> feat(orbit): transitions defaults to on

.github/workflows/deploy_master.yml, .github/workflows/test.yml, .yarnclean, package.json, tsconfig.json
- chore: fix clashing types in TypeScript
- chore: simplify TypeScript configuration
- ci: start type checking with TypeScript
<br/><br/><br/><url>LiveURL: https://orbit-test-typescript.surge.sh</url>
=> Fix TypeScript checking and include it in CI

packages/orbit-components/.storybook/orbitDecorator.js, packages/orbit-components/package.json
closes #2346
The idea is that we add a wrapping `<div>` with a specific ID to the decorator that adds the source code at the bottom. This way we can tell Loki to only take a screenshot of that `<div>` and not the whole page, therefore skipping story-code changes.
The area of the screenshot to be taken by Loki:
Before merging:
* Help me run the visual regression tests (I don't have docker locally, the documentation is "coming soon", and it's getting late) cc @silvenon ,
* Make sure that absolutely positioned elements are captured correctly (that is the only caveat of this wrapper `<div>` solution.
---------------------------------
<br/><br/><br/><url>LiveURL: https://orbit-sampi-fix-2346.surge.sh</url>
=> feat(Loki): skip code blocks

packages/orbit-components/src/CountryFlag/__tests__/index.test.js, packages/orbit-components/src/CountryFlag/index.js, packages/orbit-components/src/CountryFlag/index.js.flow
- test(CountryFlag): rewrite to Testing Library
- fix(CountryFlag): stop exporting getCountryProps
This should be rebased upon merging because it contains multiple commits. This change could've technically gone into the `test` commit, but I'm leaving 0.0001% chance that someone was actually this function, which seems internal in all regards.
<br/><br/><br/><url>LiveURL: https://orbit-test-testing-library-country-flag.surge.sh</url>
=> Rewrite tests for CountryFlag to TestingLibrary

.github/contribution/testing-conventions.md
We'll stick with `should` naming convention. I updated that section of the testing conventions to make it more clear and moved it to the top so it's the first thing that people read. Let me know what you think.
<br/><br/><br/><url>LiveURL: https://orbit-docs-update-testing-conventions.surge.sh</url>
=> docs: update conventions about test format

packages/orbit-components/src/Tooltip/__tests__/mobile.test.js, packages/orbit-components/src/primitives/MobileDialogPrimitive/components/DialogContent.flow.js, packages/orbit-components/src/primitives/MobileDialogPrimitive/components/DialogContent.js, packages/orbit-components/src/primitives/MobileDialogPrimitive/index.js
=> fix(Tooltip): do not propagate the onClick event on mobile when stopPropagate is set to true

packages/orbit-components/transforms/Stack-spacing.js, packages/orbit-components/transforms/__testfixtures__/Stack-spacing.input.js, packages/orbit-components/transforms/__testfixtures__/Stack-spacing.output.js, packages/orbit-components/transforms/__tests__/Stack-spacing.test.js
Adding codemod to be able to shift usages of Stack to updated spacings that are coming in #2457.
```bash
yarn global add jscodeshift
jscodeshift --transform https://raw.githubusercontent.com/kiwicom/orbit/master/packages/orbit-components/transforms/Stacj-spacing.js [path] --parser=babel|babylon|flow|ts|tsx
```
=> improve: add codemod for spacing of Stack

packages/orbit-components/src/InputField/__tests__/index.test.js
- added some additional assertions like `ref`
- I couldn't test `font-size` because jsdom doesn't support inheritance
- make other tests more minimal, focusing strictly on what's needed
<br/><br/><br/><url>LiveURL: https://orbit-test-testing-library-input-field.surge.sh</url>
=> test(InputField): rewrite to Testing Library

packages/orbit-components/src/InputFile/index.js
Focusing the input was previously triggering the `onChange` event handler, now `onFocus` is properly being forwarded. This should not be a problem, but is technically breaking for anyone that was relying on this behavior.
This behavior was there from the beginning, I assume it's a mistake because the component takes `onFocus` which it doesn't use.
<br/><br/><br/><url>LiveURL: https://orbit-fix-input-file-onFocus.surge.sh</url>
=> fix(InputFile): forward onFocus event handler

.github/workflows/deploy_master.yml
Missed this step in the import of `orbit-design-tokens`.<br/><br/><br/><url>LiveURL: https://orbit-fix-master-deploy-tokens.surge.sh</url>
=> chore: fix master deploy because of missing build step of design tokens

.prettierignore, packages/orbit-components/CHANGELOG.md, packages/orbit-design-tokens/CHANGELOG.md
- stop prettifying changelogs because they are auto-generated
- remove all info from @kiwicom/orbit-design-tokens changelog because
the release doesn't contain anything new, it's just a side-effect of
importing to monorepo
- update @kiwicom/orbit-components changelog with missing info
<br/><br/><br/><url>LiveURL: https://orbit-docs-changelogs.surge.sh</url>
=> docs: update changelogs

.github/workflows/deploy_master.yml, .github/workflows/main.yml, .github/workflows/test.yml
Let's add some color to the GItHub Workflow outputs so it's easier to skim.
<br/><br/><br/><url>LiveURL: https://orbit-sampi-github-workflow-colors.surge.sh</url>
=> ci: force cli colors on GitHub Workflows

packages/orbit-components/src/InputGroup/__tests__/index.test.js, packages/orbit-components/src/InputGroup/index.js
I removed our implementation of preserving `ref` in input children
because `cloneElement` already preserves refs by default.
https://reactjs.org/docs/react-api.html#cloneelement
<br/><br/><br/><url>LiveURL: https://orbit-test-testing-library-input-group.surge.sh</url>
=> test(InputGroup): rewrite to Testing Library

packages/orbit-components/src/Inline/__tests__/index.test.js, packages/orbit-components/src/Inline/index.js
This way if someone applies margin to `Inline`, e.g. if it's nested
inside a component like `Stack`, its negative margin won't be
overridden.
<br/><br/><br/><url>LiveURL: https://orbit-fix-inline-inner.surge.sh</url>
=> fix(Inline): add inner wrapper for negative margin

packages/orbit-components/src/primitives/ButtonPrimitive/__tests__/index.test.js, packages/orbit-components/src/primitives/ButtonPrimitive/index.js
[jira ticket](https://jira.kiwi.com/browse/ORBIT-681)
If button rendered as div, it should react onEnter and onSpace clicks.
Hope i did not miss something, @vepor can you check? <br/><br/><br/><url>LiveURL: https://orbit-fix-button-a11y.surge.sh</url>
=> feat(Button): div behave like button, a11y

packages/orbit-components/src/Accordion/Accordion.stories.js, packages/orbit-components/src/Accordion/AccordionSection/components/SectionFooter.js
Not the problem of Accordion component, but how story example with Stack is written
[ORBIT-1461](https://jira.kiwi.com/browse/ORBIT-1461)
<br/><br/><br/><url>LiveURL: https://orbit-fix-accordion-footer.surge.sh</url>
=> fix(Accordion): Accordion sticky footer story

packages/orbit-components/src/Modal/index.js
When user interaction is done inside the modal, the focus of activeElement will be lost and `modalBody` or `modalContent` will be focused.<br/><br/><br/><url>LiveURL: https://orbit-fix-modal-focus.surge.sh</url>
=> fix(Modal): lost focus on user interaction

packages/orbit-components/src/Modal/__tests__/index.test.js
Tests fix in #2484.<br/><br/><br/><url>LiveURL: https://orbit-test-modal-focus.surge.sh</url>
=> test(Modal): ensure that child doesn't lose focus

packages/orbit-components/src/ListChoice/__tests__/index.test.js
- Should not be squashed (as we agreed, i suppose it's time me to start use that our agreement) 
- 2 commits (switch to testing-library and focus test)<br/><br/><br/><url>LiveURL: https://orbit-feat-testing-library-listchoice.surge.sh</url>
=> ListChoice tests

packages/orbit-components/src/primitives/TooltipPrimitive/index.js
Calling was aborting stuff like `change` event on chekcbox, so Checkbox nested inside Tooltip doesn't work. This bug was introduced in #2230, where a piece of functionality was accidentally copied to `TooltipPrimitive`. I wonder how is this supposed to work on mobile, though… what should happen when you click on an interactive element to show the tooltip? This question is unrelated to this PR because that's how it always worked, I'm just wondering.
I was not able to test this fix because this bug is too complicated for jsdom, we need Cypress.
Request from #plz-orbit: https://skypicker.slack.com/archives/CAMS40F7B/p1605019864259600
<br/><br/><br/><url>LiveURL: https://orbit-fix-tooltip-checkbox.surge.sh</url>
=> fix(Tooltip): only call `preventDefault` on mobile

.github/workflows/test.yml
::set-env was disabled, so i've updated it
<br/><br/><br/><url>LiveURL: https://orbit-chore-update-actions.surge.sh</url>
=> chore: replaced deprecated action env

.yarnrc, package.json
This is because we ran into this longstanding issue when we tried to
install gatsby-plugin-sharp and gatsby-transformer-sharp:
https://github.com/yarnpkg/yarn/issues/7807
<br/><br/><br/><url>LiveURL: https://orbit-downgrade-yarn.surge.sh</url>
=> chore: downgrade Yarn

packages/orbit-components/src/utils/rtl/index.js.flow
When we converted Flow types to exact in #2331, types of RTL utilities
should have stayes inexact because, other than the theme,
styled-components interpolations also receive component props.
As an additional precautionary measure, now they are explicitly inexact
in case we ever make exact types the default.
<br/><br/><br/><url>LiveURL: https://orbit-fix-rtl-spacing-flow-type.surge.sh</url>
=> fix(RTL): fix Flow types of utilities

.eslintrc.js, packages/orbit-components/src/Modal/__tests__/index.test.js, packages/orbit-components/src/Modal/__typetests__/index.js, packages/orbit-components/src/Modal/__typetests__/index.tsx, packages/orbit-components/src/Modal/index.d.ts, packages/orbit-components/src/Modal/index.js, packages/orbit-components/src/Modal/index.js.flow
Reading scroll position was unintentionally possible when Modal was a class component because people could access Modal's elements through refs and read their `scrollTop`, but they had to duplicate Modal's logic for figuring out which element to read based on the viewport.
These changes implement official API for this called `getScrollPosition` which handles this internally.
Initially I thought of exposing `scrollPosition` value, but as we’ve discussed we would then have to read it all the time, which has performance implications, then I thought of `scrollingElement`, but it would be tedious for people to constantly check whether `scrollingElement.current` exists, and besides we only want to allow them to read scroll position and nothing more, so eventually I came up with …
=> fix: expose getScrollPosition in Modal

packages/orbit-components/src/Popover/components/ContentWrapper.js
Issue in [plz-orbit](https://skypicker.slack.com/archives/CAMS40F7B/p1606426217336800)
appears only when actions prop is present, on mobile is ok, broken on desktop
<br/><br/><br/><url>LiveURL: https://orbit-fix-Popover.surge.sh</url>
=> fix(Popover): popover bottom position issue

packages/orbit-components/src/Pagination/__tests__/index.test.js, packages/orbit-components/src/Pagination/index.js
- `useMediaQuery` instead of `Hide`
- added `title` (aria-label) when `hideLables` is true<br/><br/><br/><url>LiveURL: https://orbit-refactor-pagination.surge.sh</url>
=> refactor(Pagination): useMediaQuery instead of Hide, title

packages/orbit-components/src/Accordion/index.js.flow
It turned out that people who use `Accordion` need to be able to pass any node as `children`.<br/><br/><br/><url>LiveURL: https://orbit-fix-accordion-children-type.surge.sh</url>
=> fix(Accordion): allow any children type in Flow

docs/package.json
This is necessary because orbit.kiwi uses components from
@kiwicom/orbit-components, without it adding it to dependencies the
build fails.
<br/><br/><br/><url>LiveURL: https://orbit-chore-docs-add-missing-dependency.surge.sh</url>
=> chore: add @kiwicom/orbit-components depenency

jest.config.js, jest.json, package.json
Having to explicitly specify the JSON configuration when running Jest is limiting when running `npx jest`, and there are no advantages.
<br/><br/><br/><url>LiveURL: https://orbit-chore-jest-config-json.surge.sh</url>
=> chore: use standard file for Jest configuration

packages/orbit-components/src/Wizard/index.js, packages/orbit-components/src/data/dictionary/en-GB.json
I didn't use the `fetch-translations` script because credentials weren't the only problem, it seems like it wasn't used for a while because I got an error for some short codes. I just added the translation script to `en-GB.json` instead, let me know if I was supposed to do it in a different way.
<br/><br/><br/><url>LiveURL: https://orbit-fix-wizard-translation.surge.sh</url>
=> fix(Wizard): translate progress label on mobile

config/eslintJS.js, docs/config/jest-setup.js, docs/gatsby-config.js, docs/gatsby-node.js, docs/jest.config.js, docs/package.json, docs/src/__tests__/mdx-components.test.tsx, docs/src/components/Code.tsx, docs/src/hooks/__tests__/useIsUrlExternal.test.ts, docs/src/hooks/useIsUrlExternal.ts, docs/src/mdx-components.tsx, docs/src/templates/Doc.tsx, docs/src/templates/Guide.tsx, jest.config.js, package.json, yarn.lock
This was based on the review comments I received in #2541.
- docs: solve syntax highlighting better
- docs: fetch guide info via id in the template
- chore: install type declarations for @mdx-js/react
- docs: remove MDX mapping for `<h1>`
- docs: get the most out of MDX component mapping
- docs: configure testing
- docs: refine MDX anchor style and handle external
- docs: adjust color of `<code>` in links
One thing I left out is guides URL, we'll do this separately after we agree on a complete content strategy, based on #2571.
<br/><br/><br/><url>LiveURL: https://orbit-docs-review-improvements.surge.sh</url>
=> Various improvements in docs setup

package.json, packages/orbit-components/.storybook/main.js, packages/orbit-components/.storybook/orbitDecorator.js, yarn.lock
- Recently we had this question in [plz-orbit](https://skypicker.slack.com/archives/CAMS40F7B/p1607078251385500). So i think it would be nice to add that addon for such cases, when users need to check how component looks like on different bgs.
<br/><br/><br/><url>LiveURL: https://orbit-chore-storybook-bgs.surge.sh</url>
=> chore: add storybook-backgrounds

.eslintrc.js, packages/orbit-components/src/Translate/__tests__/index.test.js, packages/orbit-components/src/Translate/index.js
The tests were testing lower level API instead of the component itself. Now we're testing `pureTranslate` indirectly through the Translate component because that's the API that people are using.
Mocking `window.matchMedia` was necessary because `ThemeProvider` requires it.<br/><br/><br/><url>LiveURL: https://orbit-testing-library-translate.surge.sh</url>
=> test(Translate): test React component directly

packages/orbit-components/src/primitives/MobileDialogPrimitive/__tests__/index.test.js
I tried to test `aria-describedby`, but there doesn't appear to be a Testing Library query for this.
<br/><br/><br/><url>LiveURL: https://orbit-testing-library-mobile-dialog-primitive.surge.sh</url>
=> test(MobileDialogPrimitive): rewrite to Testing Library

commitlint.config.js
I assume this was intended for committing changes to React components, but we also have hooks, helpers, etc. Having to commit the scope as PascalCase doesn't make sense, so we're disabling this rule.
This has been driving me crazy 😅 <br/><br/><br/><url>LiveURL: https://orbit-improve-commitlint-liberal-scope.surge.sh</url>
=> improve: stop enforcing commit scope case

packages/orbit-components/src/Popover/helpers/__tests__/getScrollableParent.test.js
I had to be more specific by using `HTMLDivElement` instead of just
`HTMLElement` because after rewriting to Testing Library `document.body`
was being found as the scrollable parent. Using `toBeInstanceOf` made it
really easy to discover why `HTMLElement` wasn't working because the
answer was right there in the error message when the last test failed.
<br/><br/><br/><url>LiveURL: https://orbit-testing-library-popover-helper.surge.sh</url>
=> test(Popover): rewrite helper to Testing Library

packages/orbit-components/src/Modal/Modal.stories.js, packages/orbit-components/src/Modal/ModalContext.d.ts, packages/orbit-components/src/Modal/ModalContext.js, packages/orbit-components/src/Modal/ModalContext.js.flow, packages/orbit-components/src/Modal/ModalHeader/index.js, packages/orbit-components/src/Modal/__tests__/index.test.js, packages/orbit-components/src/Modal/index.js
The header background overlay existed only with close button, but it's
necessary if `ModalHeader` has `title` prop, too. This fix ensures this by
checking whether a nested `ModalHeader` has `title`.
Now the name `CloseContainer` is confusing because it implies that it's
strictly related to the close button, which is no longer the case, so we
should eventually start cleaning up Modal.
- [request](https://skypicker.slack.com/archives/CAMS40F7B/p1609862807464300)
<br/><br/><br/><url>LiveURL: https://orbit-fix-modal-header-without-close.surge.sh</url>
=> fix(Modal): ensure header overlay if title exists

docs/gatsby-config.js, docs/package.json, docs/src/mdx-components.tsx, yarn.lock
This adds basic support for images in MDX. I think it's OK without using `gatsby-root-import`, @silvenon . But if you'd like me to try it, we can.<br/><br/><br/><url>LiveURL: https://orbit-docs-mdx-images.surge.sh</url>
=> feat: add support for images in MDX

tasks/eslintCI.js
The initial assumption was that `files.json` file by the GitHub Action [Get Changed Files](https://github.com/lots0logs/gh-action-get-changed-files) contained the sum of files from `files_modified.json`, `files_added.json`, `files_deleted.json`, and `files_renamed.json`, but it appears that sometimes it also contained files that were created and then deleted in the _same_ PR, and those files were not a part of `files_deleted.json` so they were not being filtered out.
So now instead of `files.json` we're concatentating files from `files_added.json`, `files_modified.json`, and `files_renamed.json`.<br/><br/><br/><url>LiveURL: https://orbit-ci-fix-eslint-ci.surge.sh</url>
=> ci: fix bug where deleted files were being linted

packages/babel-plugin-orbit-components/package.json
Other workspaces define `build` script as something that needs to happen
before publish, but here it was a part of the test script. It's handy
to be able to just run `npx lerna run build`, so keeping the name
`build` consistent is useful.
<br/><br/><br/><url>LiveURL: https://orbit-improve-babel-plugin-script-names.surge.sh</url>
=> improve: improve Babel plugin's script names

packages/eslint-plugin-orbit-components/jest.config.js
This prints out the `eslint-plugin-orbit-components` label in Jest
output like the rest of the workspaces.
<br/><br/><br/><url>LiveURL: https://orbit-improve-eslint-plugin-jest-config.surge.sh</url>
=> improve: add Jest display name for ESLint plugin

yarn.lock
Not sure where this section came from, but I keep getting this change when I run `npx lerna bootstrap`, so I guess we don't need it anymore.
<br/><br/><br/><url>LiveURL: https://orbit-chore-yarn-lockfile.surge.sh</url>
=> chore: update Yarn lockfile

babel.config.js
with upgrade to new adeira, seems like we have to add that option to a plugin, because it uses by default new [JSX transform. ](https://github.com/adeira/universe/tree/master/src/babel-preset-adeira#new-jsx-transform)<br/><br/><br/><url>LiveURL: https://orbit-chore-babel-preset-adeira-config.surge.sh</url>
=> chore(adeira): use classic reactRuntime

docs/src/components/Code.tsx
<br/><br/><br/><url>LiveURL: https://orbit-docs-fix-no-language.surge.sh</url>
=> docs: fix error when language is not specified

docs/package.json, docs/src/components/ArrowRight.tsx, docs/src/components/ButtonLink.tsx, docs/src/components/Card.tsx, docs/src/pages/index.tsx, yarn.lock
I added buttons bellow the title, some of the cards, linked them to documents etc. There are many things still missing from the landing page, but it's much better to merge bit by bit than everything at once, especially in this early stage where we have to write a lot of code.
- icons in cards are missing because we don't have the SVGs yet
- the description of the Patterns card is missing, in Figma it's the same as the one in Components card
- some of the cards aren't linked because they don't have the corresponding docunment added to the codebase yet
- the "Show all items" button doesn't do anything yet
<br/><br/><br/><url>LiveURL: https://orbit-feat-landing-page.surge.sh</url>
=> feat: add more content to the landing page

packages/orbit-components/src/Accordion/index.d.ts
Noticed, that `Accordion` ts declarations missing `onExpand`<br/><br/><br/><url>LiveURL: https://orbit-fix-accordion-ts-declarations.surge.sh</url>
=> fix(Accordion): missing onExpand ts

docs/gatsby-config.js, docs/gatsby-node.js, docs/package.json, docs/src/documentation/04-design-patterns/01-progressive-disclosure.mdx, yarn.lock
Both client- and server-side
The redirects should work in production builds (e.g., `yarn build && yarn serve`), but not necessarily development builds.
=> feat(docs): add options for redirects

docs/src/documentation/05-development/01-guides/01-developing-layouts.mdx, docs/src/documentation/05-development/01-guides/02-dictionary.mdx, docs/src/documentation/05-development/01-guides/03-using-component-types.mdx, docs/src/documentation/05-development/01-guides/04-no-exporting-components.mdx, docs/src/documentation/05-development/01-guides/05-eslint-plugin.mdx, docs/src/documentation/05-development/02-utilities/01-media-queries.mdx, docs/src/documentation/05-development/02-utilities/02-rtl-languages.mdx, docs/src/documentation/05-development/03-hooks/usefocustrap.mdx, docs/src/documentation/05-development/03-hooks/usemediaquery.mdx, packages/orbit-components/src/ThemeProvider/README.md, packages/orbit-components/src/Translate/README.md, readme.md
Includes replacing links to `/.github/dictionary.md` in this repo.<br/><br/><br/><url>LiveURL: https://orbit-docs-development.surge.sh</url>
=> docs: add content for development section

packages/eslint-plugin-orbit-components/package.json, packages/eslint-plugin-orbit-components/src/rules/buttonHasTitle.ts, yarn.lock
`button-has-title` is using types from `@babel/core`, exported by `@babel/types`, neither of which were defined in `dependencies` of `eslint-plugin-orbit-components`, meaning that it was relying on a transient dependency with an uncertain version number. #2660 fleshed out this problem, and research showed that the working version of `@babel/types` is `7.12.10`, so I installed it, locked the version number, and now it's being used directly instead of `@babel/core`.
Closes #2673.
Closes #2674. It's a more straightforward alternative.<br/><br/><br/><url>LiveURL: https://orbit-fix-eslint-button-has-minimal.surge.sh</url>
=> fix: stop relying on a transient dependency

packages/orbit-components/src/Checkbox/index.js.flow, packages/orbit-components/src/InputField/index.js.flow, packages/orbit-components/src/InputStepper/index.js.flow, packages/orbit-components/src/Radio/index.js.flow, packages/orbit-components/src/Select/index.js.flow
Removed `...Ref` from `index.js.flow` files, where `AbstractComponent` is possible to use<br/><br/><br/><url>LiveURL: https://orbit-chore-remove-ref.surge.sh</url>
=> chore: use AbstractComponent instead of Ref type spread

.github/dependabot.yml
Closes #2682.
<br/><br/><br/><url>LiveURL: https://orbit-dependabot-ignore-babel-typesb.surge.sh</url>
=> chore: ignore updates of @babel/types

docs/src/components/Tile.tsx, docs/src/pages/index.tsx
To align with the Jira ticket, and it's a better name.
<br/><br/><br/><url>LiveURL: https://orbit-docs-rename-card-to-tile.surge.sh</url>
=> docs: rename Card component to Tile

packages/orbit-design-tokens/package.json
This prevents mixing files between branches.
I recommend cherry-picking this to `dev/tokens` as well, that way switching back and forth won't cause unexpected problems. I had an error when I tried to open the documentation, but then remembered the possibility that the new and old files are mixed together, and deleting the directories worked.
<br/><br/><br/><url>LiveURL: https://orbit-build-design-tokens-clean.surge.sh</url>
=> build: clean before building design tokens

packages/orbit-design-tokens/src/dictionary/definitions/foundation/palette/blue.json, packages/orbit-design-tokens/src/dictionary/definitions/foundation/palette/cloud.json, packages/orbit-design-tokens/src/dictionary/definitions/foundation/palette/green.json, packages/orbit-design-tokens/src/dictionary/definitions/foundation/palette/ink.json, packages/orbit-design-tokens/src/dictionary/definitions/foundation/palette/orange.json, packages/orbit-design-tokens/src/dictionary/definitions/foundation/palette/product.json, packages/orbit-design-tokens/src/dictionary/definitions/foundation/palette/red.json, packages/orbit-design-tokens/src/dictionary/definitions/foundation/palette/social.json, packages/orbit-design-tokens/src/dictionary/definitions/foundation/palette/white.json, packages/orbit-design-tokens/src/dictionary/definitions/global/palette/blue.json, packages/orbit-design-tokens/src/dictionary/definitions/global/palette/cloud.json, packages/orbit-design-tokens/src/dictionary/definitions/global/palette/green.json, packages/orbit-design-tokens/src/dictionary/definitions/global/palette/ink.json, packages/orbit-design-tokens/src/dictionary/definitions/global/palette/orange.json, packages/orbit-design-tokens/src/dictionary/definitions/global/palette/product.json, packages/orbit-design-tokens/src/dictionary/definitions/global/palette/red.json, packages/orbit-design-tokens/src/dictionary/definitions/global/palette/social.json, packages/orbit-design-tokens/src/dictionary/definitions/global/palette/white.json
Renamed shades of colors from `hover` to `secondary` and `active` to `tertiary` because of new semantic meaning.
=> feat(tokens): rename palette shades to secondary and tertiary

docs/src/components/Prose.tsx
The reason for this is that we don't want nested headings, like in the `Tile` component, to have unexpected margins. One such example is in #2706.
=> docs: limit Prose margins to direct children

package.json, packages/orbit-components/package.json
This makes it possible for each workspace to define their own
`postinstall` script instead of having to call them from the root. This
also makes the development experience friendlier because now installing
dependencies inside `packages/orbit-components`, for example, will run
the `ponstinstall` script for that workspace.
=> improve: define postinstall scripts per-workspace

packages/eslint-plugin-orbit-internal/package.json
This way it will run for people who install dependencies from root as well, because of the `postinstall` script in root.
Orbit.kiwi: https://orbit-docs-improve-eslint-internal-postinstall.surge.sh
Storybook: https://orbit-improve-eslint-internal-postinstall.surge.sh
=> improve: use `postinstall` instead of `install`

.eslintrc.js, docs/src/utils/common.ts
It's tidier to collect all paths where we want to disable this rule, and may encourage us to type exports where that's important.
Very minor change, but somewhat useful to keep this all in one place.
Orbit.kiwi: https://orbit-docs-improve-explicit-module-boundary-types.surge.sh
Storybook: https://orbit-improve-explicit-module-boundary-types.surge.sh
=> improve: use single override for disabling a rule

packages/orbit-components/src/Modal/Modal.stories.js, packages/orbit-components/src/Modal/README.md, packages/orbit-components/src/Modal/index.d.ts, packages/orbit-components/src/Modal/index.js, packages/orbit-components/src/Modal/index.js.flow
Should fix `autoFocus` when `InputField` inside `Modal`, the idea is to pass `autoFocus={false}` to Modal explicitly, when it has `<InputField autoFocus />` inside.  
[request in plz-orbit ](https://skypicker.slack.com/archives/CAMS40F7B/p1613572978238500)
Orbit.kiwi: https://orbit-docs-feat-modal-autofocus.surge.sh
Storybook: https://orbit-feat-modal-autofocus.surge.sh
=> feat(Modal): autofocus

packages/orbit-components/src/hooks/useIntersect/__typetests__/index.js, packages/orbit-components/src/hooks/useIntersect/__typetests__/index.tsx, packages/orbit-components/src/hooks/useIntersect/index.d.ts, packages/orbit-components/src/hooks/useIntersect/index.js, packages/orbit-components/src/hooks/useIntersect/index.js.flow, yarn.lock
The type of `ref` was too broad compared to the actual object. Now it reflects exactly what we're sending, and to confirm that types are working properly we added them to the source code, along with type tests. You can see that I also changed what we're actually sending as `ref` because I don't want people to be able to run `setState(prevState => {})`. Not that something bad could happen, but I want us to provide a specific API, without any unexpected extra stuff.
Also, I removed the SSR check which is seemingly unnecessary (correct me if I'm wrong). `useEffect` doesn't run on the server, so the check seemed overly cautious and it was technically breaking the rule of hooks. (Not sure why ESLint wasn't complaining about it before, though.)
Not sure what Yarn lockfile update was about, but …
=> fix(useIntersect): simplify `ref` type

packages/orbit-design-tokens/src/dictionary/build.ts, packages/orbit-design-tokens/src/dictionary/definitions/global/z-indices.json, packages/orbit-design-tokens/src/dictionary/transforms/attributes/index.ts, packages/orbit-design-tokens/src/dictionary/transforms/values/index.ts
Added old z-index values to global tokens.
Because the original intention of `attribute/nov/alias` was to create value of the original reference, it didn't count with case when the global (or component-specific) token is not connected to the foundation via reference alias.
=> feat(tokens): add z-index values to global tokens

packages/orbit-design-tokens/src/dictionary/build.ts, packages/orbit-design-tokens/src/dictionary/definitions/foundation/space.json, packages/orbit-design-tokens/src/dictionary/definitions/global/space.json, packages/orbit-design-tokens/src/dictionary/transforms/attributes/index.ts
Rename spacing tokens to proportion based format.
I had the change the proposed schema, because it will be very limiting to use `2-x` (or camelCased variant `2x`) as a token name. 
See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Identifier_after_number
The problem would be mainly noticeable in the foundation usage, e.g. if somebody would like to change the spacings token via `createTheme` function he would have to pass these properties in different way – which is not that common when comes to usage of object in Javascript. It would be also limitation for us. See further code examples.
The definition for spacing token would like this:
```js
const space = {
"2x": "value",
"4x": "value",
...
}
```
Then also the mapping from foundation to …
=> feat(tokens): rename spacing scale to proportion based

packages/orbit-components/src/Slider/index.d.ts, packages/orbit-components/src/Slider/index.js.flow, packages/orbit-components/src/Slider/utils/calculateCountOf.d.ts
added declaration export, this util is used inside of one of the examples
Orbit.kiwi: https://orbit-docs-fix-add-export-for-slider-util.surge.sh
Storybook: https://orbit-fix-add-export-for-slider-util.surge.sh
=> fix(Slider): add TypeScript declaration for calculateOf util

packages/orbit-components/src/CallOutBanner/index.d.ts
There is an error inside tsx file when `CallOutBanner` has `illustration` prop. Noticed during the creation of examples. 
Orbit.kiwi: https://orbit-docs-fix-calloutbanner-ts-type.surge.sh
Storybook: https://orbit-fix-calloutbanner-ts-type.surge.sh
=> fix(CallOutBanner): illustration type

docs/utils/warnings.js, gulpfile.js
Always check only for variables needed for performing that particular task, instead of checking for unnecessarily failing if someone doesn't have a variable needed for a task they never happen to perform.
Orbit.kiwi: https://orbit-docs-improve-loading-env-variables.surge.sh
Storybook: https://orbit-improve-loading-env-variables.surge.sh
=> improve: check only needed environment vars

packages/eslint-plugin-orbit-components/__tests__/customColors.test.ts, packages/eslint-plugin-orbit-components/docs/rules/custom-colors.md, packages/eslint-plugin-orbit-components/src/configs/recommended.ts, packages/eslint-plugin-orbit-components/src/index.ts, packages/eslint-plugin-orbit-components/src/rules/customColors.ts
Added eslint rule to check custom written styles, which should use our tokens. Did not provide individual error message for each property, so feel free to advice if you think it's needed. Currently checks next properties: `box-shadow`, `color`, `background`, `color`, `font-size`, `line-height`, `border-radius`, `z-index`. I think for `left` and `right` we should have separate rule.
Orbit.kiwi: https://orbit-docs-feat-custom-colors-rule.surge.sh
Storybook: https://orbit-feat-custom-colors-rule.surge.sh
=> feat(eslint-plugin-orbit): custom-styles

packages/eslint-plugin-orbit-components/__tests__/defaultTheme.test.ts, packages/eslint-plugin-orbit-components/docs/rules/default-theme.md, packages/eslint-plugin-orbit-components/src/configs/recommended.ts, packages/eslint-plugin-orbit-components/src/index.ts, packages/eslint-plugin-orbit-components/src/rules/defaultTheme.ts
Added new rule, called it `default-theme`, as we discussed it earlier, that we should prevent some cases of wrong defaultTheme usage
Orbit.kiwi: https://orbit-docs-feat-defaultTheme-eslint.surge.sh
Storybook: https://orbit-feat-defaultTheme-eslint.surge.sh
=> feat(eslint-plugin-orbit): default-theme rule

packages/eslint-plugin-orbit-components/__tests__/rtlUtils.test.ts, packages/eslint-plugin-orbit-components/docs/rules/rtl-utils.md, packages/eslint-plugin-orbit-components/src/configs/recommended.ts, packages/eslint-plugin-orbit-components/src/index.ts, packages/eslint-plugin-orbit-components/src/rules/rtlUtils.ts
The rule which should help enforce usage of our RTL utility functions and avoid mistakes like `$({theme}) => theme.rtl ? "right: " : "left: "}) 8px`
Orbit.kiwi: https://orbit-docs-feat-rtl-rule.surge.sh
Storybook: https://orbit-feat-rtl-rule.surge.sh
=> feat(eslint-plugin-orbit): rtl-utils rule

packages/orbit-components/package.json
Currently deploy command both builds and deploys. In the CI, we restore an artifact of the built Storybook, so it shouldn't need to build again.
Orbit.kiwi: https://orbit-docs-fix-ci-deploy-storybook.surge.sh
Storybook: https://orbit-fix-ci-deploy-storybook.surge.sh
=> fix(ci): deploy storybook only, not build

packages/orbit-components/src/Wizard/index.d.ts
Incorrect type. It's not generic and causes an error inside `tsx` file when `Wizard` is used. 
Orbit.kiwi: https://orbit-docs-fix-wizard-s.surge.sh
Storybook: https://orbit-fix-wizard-s.surge.sh
=> fix(Wizard): remove incorrect React.ReactChildren

docs/src/components/Breadcrumbs.tsx
Links without slash break tab design, at least in development.
Orbit.kiwi: https://orbit-docs-docs-fix-breadcrumbs-path.surge.sh
Storybook: https://orbit-docs-fix-breadcrumbs-path.surge.sh
=> docs: fix breadcrumb links

docs/src/components/DocLayout.tsx, docs/src/components/ReactExample/index.tsx, docs/src/pages/mdx-examples.mdx
and fix check for missing example
and add example use
The previous check failed as it's not possible to destructure something undefined.
Orbit.kiwi: https://orbit-docs-fix-example-use.surge.sh
Storybook: https://orbit-fix-example-use.surge.sh
=> fix(docs): enable ReactExample use

packages/orbit-components/src/TextLink/__tests__/index.test.js, packages/orbit-components/src/TextLink/index.js
Fixed #2853 
Orbit.kiwi: https://orbit-docs-fix-textlink-click.surge.sh
Storybook: https://orbit-fix-textlink-click.surge.sh
=> fix(TextLink): called twice when stopPropagation specified

docs/src/components/Navbar.tsx, docs/src/components/Sidenav/index.tsx, packages/orbit-components/src/index.js
When scrolling while Sidenav is open, Sidenav would scroll along the content, so in order to make it fixed we need to render it in a portal.
Let me know if I'm overlooking something.
Orbit.kiwi: https://orbit-docs-docs-sidenav-portal.surge.sh
Storybook: https://orbit-docs-sidenav-portal.surge.sh
=> docs: render Sidenav in Portal

packages/eslint-plugin-orbit-components/__tests__/rtlUtils.test.ts, packages/eslint-plugin-orbit-components/__tests__/useRtl.test.ts, packages/eslint-plugin-orbit-components/docs/rules/use-rtl.md, packages/eslint-plugin-orbit-components/src/configs/recommended.ts, packages/eslint-plugin-orbit-components/src/index.ts, packages/eslint-plugin-orbit-components/src/rules/useRtl.ts, packages/orbit-components/src/utils/rtl/README.md
As we discussed before. Create a separate rule for RTL literal values. 
Orbit.kiwi: https://orbit-docs-feat-use-rtl.surge.sh
Storybook: https://orbit-feat-use-rtl.surge.sh
=> feat(eslint-plugin-orbit): useRtl rule

packages/orbit-components/src/hooks/useBoundingRect/__typetests__/index.js, packages/orbit-components/src/hooks/useBoundingRect/__typetests__/index.tsx, packages/orbit-components/src/hooks/useBoundingRect/index.d.ts
BREAKING CHANGE: In TypeScript `useBoundingRect` now requires a type parameter based on which HTML element it measures:
```tsx
function App() {
const [dimensions, ref] = useBoundingRect<HTMLDivElement>();
return <div ref={ref} />;
}
```
Orbit.kiwi: https://orbit-docs-fix-ts-use-bounding-rect.surge.sh
Storybook: https://orbit-fix-ts-use-bounding-rect.surge.sh
=> fix(useBoundingRect): fix TypeScript declaration

docs/src/components/Footer.tsx
I've refactored a bit footer component, I will have to put a `Vercel` logo there soon. Noticed, that it can be done a bit more simply via `Stack`. Now it much the initial design, since the height of both parts of footer are equal to the height of the proposed design from Will. 
Orbit.kiwi: https://orbit-docs-feat-verce-banner.surge.sh
Storybook: https://orbit-feat-verce-banner.surge.sh
=> refactor(Footer): small changes to footer

docs/plugins/sandbox/gatsby-node.js, docs/plugins/sandbox/helpers.js
react-live can't have types inside. Left the types inside examples and omited them via ast remove.
Orbit.kiwi: https://orbit-docs-docs-omittypes-to-react-live.surge.sh
Storybook: https://orbit-docs-omittypes-to-react-live.surge.sh
=> fix(examples): omit types for react-live

.github/workflows/lint-prose.yml
The original issue seems fixed: https://github.com/errata-ai/vale-action/issues/33
Orbit.kiwi: https://orbit-docs-fix-vale-version.surge.sh
Storybook: https://orbit-fix-vale-version.surge.sh
=> ci: restore Vale check

docs/src/mdx-components.tsx
The fix for the icon being inline is maybe a little hacky. 🤷
Orbit.kiwi: https://orbit-docs-fix-external-icon.surge.sh
Storybook: https://orbit-fix-external-icon.surge.sh
=> fix(docs): external icon

packages/orbit-components/package.json
Popular packages like [downshift](https://github.com/downshift-js/downshift/blob/f18b031644105e4046b361c4e0109ed5494fbf1e/package.json#L66) do it like this, so I think it's a good idea.
Rel. #2858.
Orbit.kiwi: https://orbit-docs-react-peer-dependency-version.surge.sh
Storybook: https://orbit-react-peer-dependency-version.surge.sh
=> fix: update React peer dependency versions

docs/src/components/BrandedTile.tsx, docs/src/components/Tile.tsx, docs/src/pages/index.tsx
fixed visual bugs on the front page, now it should look better. For icons inside `Tile/BrandedTile` set `display: none` on smallMobile and mediumMobile, I suppose it just takes the space and we can turn it off for such small viewports. 
Another thing, that can be discussed is usage of relative values, we have a lot of `rems`, but we do not change the base value, it can be useful for reducing the margin/padding size for narrow viewports, i doubt that we have to have `32px` padding for Tile on `smallMobile`
Orbit.kiwi: https://orbit-docs-fix-front-page.surge.sh
Storybook: https://orbit-fix-front-page.surge.sh
=> docs: fix front page layout

package.json
In certain cases, for example after changing images, old versions stay cached, so we need to delete Gatsby's cache.
Orbit.kiwi: https://orbit-docs-clean-docs-script.surge.sh
Storybook: https://orbit-clean-docs-script.surge.sh
=> improve: add script for deleting gatsby cache

packages/orbit-design-tokens/src/dictionary/definitions/global/duration.json, packages/orbit-design-tokens/src/dictionary/transforms/values/index.ts, packages/orbit-design-tokens/src/dictionary/utils/__tests__/is.test.ts, packages/orbit-design-tokens/src/dictionary/utils/is.ts
Added global tokens for duration – the same naming and values as in old version. The only difference that it won't be a part of foundation.
=> feat(tokens): add global duration tokens

packages/orbit-components/src/Tag/index.js, packages/orbit-design-tokens/src/dictionary/build.ts, packages/orbit-design-tokens/src/dictionary/definitions/component-specific/alert-deprecated.json, packages/orbit-design-tokens/src/dictionary/definitions/component-specific/badge-deprecated.json, packages/orbit-design-tokens/src/dictionary/definitions/component-specific/button/button-large-padding.json, packages/orbit-design-tokens/src/dictionary/definitions/component-specific/button/button-normal-padding.json, packages/orbit-design-tokens/src/dictionary/definitions/component-specific/button/button-padding.json, packages/orbit-design-tokens/src/dictionary/definitions/component-specific/button/button-small-padding.json, packages/orbit-design-tokens/src/dictionary/definitions/component-specific/table-deprecated.json, packages/orbit-design-tokens/src/dictionary/formatters/javascript-tokens.ts, packages/orbit-design-tokens/src/dictionary/formatters/xml-tokens.ts, packages/orbit-design-tokens/src/dictionary/transforms/attributes/index.ts, packages/orbit-design-tokens/src/dictionary/transforms/values/index.ts, packages/orbit-design-tokens/src/dictionary/utils/__tests__/determinate.test.ts, packages/orbit-design-tokens/src/dictionary/utils/__tests__/is.test.ts, packages/orbit-design-tokens/src/dictionary/utils/__tests__/string.test.ts, packages/orbit-design-tokens/src/dictionary/utils/errorMessage.ts, packages/orbit-design-tokens/src/dictionary/utils/is.ts, packages/orbit-design-tokens/src/dictionary/utils/string.ts, packages/orbit-design-tokens/src/js/__tests__/transparentColor.test.ts
Added first batch of spacing tokens – mostly for Button and Alert.
The spacing have to be defined separately from the value attribute. It gets compiled/flatten in the formatters directly.
=> feat(tokens): add specific spacing tokens for components

packages/orbit-design-tokens/src/dictionary/definitions/component-specific/deprecated/backgrounds.json
Added deprecated tokens for background properties that doesn't have to exist in the future – it can be replaced either by elevation level tokens, or we don't have to store `"transparent"` value, because it's not necessary.
=> feat(tokens): add deprecated background tokens

docs/src/documentation/03-components/01-action/textlink/01-guidelines.mdx
Orbit.kiwi: https://orbit-docs-docs-textlink-colors.surge.sh
Storybook: https://orbit-docs-textlink-colors.surge.sh
=> feat(docs): add guidelines on TextLink colors

packages/orbit-components/src/Button/index.d.ts, packages/orbit-components/src/Button/index.js, packages/orbit-components/src/Button/index.js.flow, packages/orbit-components/src/ButtonLink/index.d.ts, packages/orbit-components/src/ButtonLink/index.js, packages/orbit-components/src/ButtonLink/index.js.flow, packages/orbit-components/src/SocialButton/index.d.ts, packages/orbit-components/src/SocialButton/index.js, packages/orbit-components/src/SocialButton/index.js.flow, packages/orbit-components/src/primitives/ButtonPrimitive/README.md, packages/orbit-components/src/primitives/ButtonPrimitive/index.d.ts, packages/orbit-components/src/primitives/ButtonPrimitive/index.js.flow, packages/orbit-components/src/primitives/Primitives.stories.js
Removed redundant property `size` from the ButtonPrimitive component. It didn't have any effect on the styles, because we use `fontSize` and `height` properties to setup CSS attributes related to actual size.
Orbit.kiwi: https://orbit-docs-fix-buttonprimitive-size.surge.sh
Storybook: https://orbit-fix-buttonprimitive-size.surge.sh
=> fix(ButtonPrimitive): remove redundant size property

packages/orbit-components/src/BaggageStepper/README.md, packages/orbit-components/src/BaggageStepper/Stepper.stories.js, packages/orbit-components/src/BaggageStepper/Stepper/Button.js, packages/orbit-components/src/BaggageStepper/Stepper/consts.js, packages/orbit-components/src/BaggageStepper/Stepper/helpers/getBoxShadow.js, packages/orbit-components/src/BaggageStepper/Stepper/index.d.ts, packages/orbit-components/src/BaggageStepper/Stepper/index.js, packages/orbit-components/src/BaggageStepper/Stepper/index.js.flow, packages/orbit-components/src/BaggageStepper/__tests__/index.test.js, packages/orbit-components/src/BaggageStepper/index.d.ts, packages/orbit-components/src/BaggageStepper/index.js, packages/orbit-components/src/BaggageStepper/index.js.flow
`BaggageStepper` for Baggage. Core functionality is copied from the original `Stepper`, adjusted with custom button via primitive, because of the size/box-shadow
dev: [ORBIT-1760](https://jira.kiwi.com/browse/ORBIT-1760)
design: [ORBIT-1745](https://jira.kiwi.com/browse/ORBIT-1745) 
slack discussion: [here](https://skypicker.slack.com/archives/CAMS40F7B/p1619443241298700?thread_ts=1618819835.251800&cid=CAMS40F7B)
Storybook: https://orbit-feat-kulibabamstepper.surge.sh
=> feat(BaggageStepper): init

packages/orbit-components/src/ButtonLink/index.js
[bug](https://monosnap.com/file/asMoM3jcJUIUfBD08RYa3Z8A5A5sSg), also [bug](https://monosnap.com/file/6IZ9ANOKVOAIF7IVLqOBqOM7juk3Mu)
Storybook: https://orbit-fix-icon-size.surge.sh
=> fix(ButtonLink): pass size prop to icons

packages/orbit-components/src/Modal/index.js
There is a bug with the Modal fixed footer, got it from QA, they need to update the orbit version, so we need to release ASAP, there is also a separate icon bug, which was already fixed, that should be asap released. Did not find a quick solution for fixing that. I mean, it's Modal and even a small change here can lead to some bug :D 
CLS is an important thing ofc, but it can be fixed later. @silvenon wdy? if you can fix that quickly, use this PR, otherwise, we can create ticket for CLS and check more properly issues in all components, not just Modal. 
Storybook: https://orbit-fix-modal-fixed-footer.surge.sh
=> revert(Modal): revert CLS changes

docs/tsconfig.json
It causes an error and doesn't appear to help anything. It was accidentally merged in #2914.
Storybook: https://orbit-docs-remove-tsconfig.surge.sh
=> chore: remove unnecessary TypeScript config file

.github/workflows/lint-prose.yml, .github/workflows/main.yml, .github/workflows/test_and_deploy.yml
This should fix the problem of warnings in CI builds.
Storybook: https://orbit-ci-figma-token.surge.sh
=> ci: add Figma token

yarn.lock
In b453299e compressed size of Orbit components grew from 484 to 648 kB because a merge conflict in yarn.lock was resolved by deleting and generating it again, so the file size bump was caused by a combination of changes in dependency versions. There were a lot of changes and I didn't even know where to look.
This change brings the size down to 490 kB by replacing the current yarn.lock with the properly resolved one (Yarn can do it automatically) and runnning `yarn install` to apply the new changes.
I'm not sure if this is going to cause any problems with our current code, as we've been working with regenerated `yarn.lock` for some time. Fingers crossed.
Storybook: https://orbit-fix-compressed-size.surge.sh
=> fix: bring down file size of Orbit components

package.json, packages/orbit-components/package.json
This builds strictly what is necessary for measuring size, seems to reduce the duration by about 4m.
Storybook: https://orbit-ci-faster-compressed-size.surge.sh
=> ci: improve speed of size GitHub workflow

packages/orbit-components/src/Modal/README.md, packages/orbit-components/src/Modal/index.d.ts, packages/orbit-components/src/Modal/index.js, packages/orbit-components/src/Modal/index.js.flow
This prop is an escape hatch because Modal animation is currently implemented by transitioning the `top` CSS property, which results in a bad Cumulative Layout Shift score.
I wasn't sure whether to document it, as it's an escape hatch which we'll probably get rid of.
- [the original suggestion](https://skypicker.slack.com/archives/C9NJQS970/p1619528876094700?thread_ts=1619527814.093300&cid=C9NJQS970)
Storybook: https://orbit-feat-modal-disable-animation.surge.sh
=> feat(Modal): add disableAnimation prop

packages/orbit-components/src/HorizontalScroll/HorizontalScroll.stories.js, packages/orbit-components/src/HorizontalScroll/README.md, packages/orbit-components/src/HorizontalScroll/index.d.ts, packages/orbit-components/src/HorizontalScroll/index.js, packages/orbit-components/src/HorizontalScroll/index.js.flow
Added `scroll-snap-type` to `HorizontalScroll`. Two props, to turn it on and the type for the property. 
Storybook: https://orbit-feat-horizontalscroll-snap.surge.sh
=> feat(HorizontalScroll): add scroll-snap-type

packages/orbit-design-tokens/src/dictionary/definitions/global/palette/white.json
It goes against the normal definition of other colors, but we need a way how to define all deprecated old names.
=> feat(tokens): update deprecated white palette shades

docs/__tests__/gatsby-node.test.js, docs/gatsby-node.js, docs/utils/document.js
This (hopefully) fixes the problem of error caused by missing keys in `metaFileDataMap`, the assumption being that the data didn't get stored because those nodes got cached, and therefore skipped, so we're using the same API to store metadata, too. This assumption is based on the fact that the problem goes away after clearing Gatsby cache.
Storybook: https://orbit-fix-metaFileDataMap-cache.surge.sh
=> fix: store URL metadata in Gatsby cache

docs/plugins/sandbox/gatsby-node.js
Storybook: https://orbit-fix-sandbox-prettify.surge.sh
=> fix(sandbox): prettify the outputed code

docs/src/components/ReactExample/Preview.tsx
In the Slider example dragging the Slider to either extreme causes an overflow, so moving padding to StyledPreviewWrapper instead avoids that.  Also, adding a small bottom padding avoids cutting off box shadow of the sliding head.
Storybook: https://orbit-docs-preview-padding.surge.sh
=> fix: prevent overflow in example preview

docs/src/components/ReactExample/Preview.tsx
Examples currently inherit the theme from orbit.kiwi, but we should use the default theme so that they always look the same.
Did I do it correctly?
Storybook: https://orbit-docs-examples-default-theme.surge.sh
=> fix: use default theme for examples

packages/orbit-components/src/Wizard/CheckCircle.js, packages/orbit-components/src/Wizard/WizardStep.js, packages/orbit-components/src/Wizard/WizardStepIcon.js, packages/orbit-components/src/Wizard/__tests__/loose.test.js
An additional refactor here is replacing the CheckCircle Orbit icon with a custom one in order to avoid the hack of placing the background circle and simplify the code for Wizard step icon.
Storybook: https://orbit-feat-wizard-improvements.surge.sh
=> fix(Wizard): increase clickable area of steps

packages/orbit-components/package.json, packages/orbit-components/src/ChoiceGroup/ChoiceGroup.stories.js, packages/orbit-components/src/ChoiceGroup/README.md, packages/orbit-components/src/ChoiceGroup/__tests__/index.test.js, packages/orbit-components/src/ChoiceGroup/__typetests__/index.tsx, packages/orbit-components/src/ChoiceGroup/index.d.ts, packages/orbit-components/src/ChoiceGroup/index.js, packages/orbit-components/src/ChoiceGroup/index.js.flow, yarn.lock
By accepting a function as `children` we're increasing the flexibility of rendering, for example now people can combine `react-window` with ChoiceGroup.
- [Slack request](https://skypicker.slack.com/archives/C9B1H0ACW/p1622462413007500)
Storybook: https://orbit-feat-choice-group-flexibility.surge.sh
=> feat(ChoiceGroup): increase rendering flexibility

docs/plugins/contributors/gatsby-node.js
There is no need to have `docs/.env` when we can use root `.env`. This improves rate limit because without `docs/.env` the requests were not authenticated.
Storybook: https://orbit-docs-fix-octokit-auth.surge.sh
=> chore: fix path to environment variables

docs/plugins/contributors/gatsby-node.js
While the pre-commit hook takes care of this, it's very confusing to see the un-prettified file in the working tree. Now the JSON will be prettified as it's being written.
Storybook: https://orbit-docs-prettify-fetched-users.surge.sh
=> improve: prettify fetched users

docs/src/components/Layout.tsx
The development mode toggle didn't work in pages that use `Layout` instead of `DocLayout` because `Layout` didn't provide the context.
Storybook: https://orbit-docs-dev-mode-toggle-footer.surge.sh
=> docs: fix development mode toggle in footer

docs/src/components/FancyLink.tsx, docs/src/components/Github/TeamMember.tsx, docs/src/components/HeaderLink.tsx, yarn.lock
so as i wrote before, the problem is in icons, seems like a forgot to change one import and that's why webpack analyzer does not show reduce of bundle size. Now it's reduced and is about 800kb compare to 2.2mb in gzip. 
Storybook: https://orbit-fix-bundle-size.surge.sh
=> fix: reduce bundle size

.github/contribution/docs.md, .github/styles/Kiwi/Contractions.yml, .github/styles/Vocab/Kiwi/accept.txt, docs/plugins/gatsby-remark-figma-images/index.js, docs/src/documentation/02-foundation/02-accessibility.mdx, docs/src/documentation/03-components/01-action/textlink/01-guidelines.mdx, docs/src/documentation/03-components/03-information/alert/01-guidelines.mdx, docs/src/documentation/03-components/03-information/notificationbadge/01-guidelines.mdx, docs/src/documentation/03-components/04-overlay/dialog/01-guidelines.mdx, docs/src/documentation/03-components/05-input/listchoice/01-guidelines.mdx, docs/src/documentation/03-components/07-interaction/slider/01-guidelines.mdx, docs/src/documentation/03-components/07-interaction/switch/01-guidelines.mdx, docs/src/documentation/03-components/08-visuals/icon/01-guidelines.mdx, docs/src/documentation/03-components/10-progress-indicators/loading/01-guidelines.mdx, docs/src/documentation/03-components/11-navigation/pagination/01-guidelines.mdx, docs/src/documentation/03-components/component.md.template, docs/src/documentation/04-design-patterns/02-action-components.mdx, docs/src/documentation/06-kiwi-use/02-content/01-voice-and-tone/02-empathetic.mdx, docs/src/documentation/06-kiwi-use/02-content/02-grammar-and-mechanics.mdx, docs/src/documentation/06-kiwi-use/02-content/04-specific-areas/social-media/02-visual-treatment.mdx, docs/src/documentation/06-kiwi-use/02-content/04-specific-areas/technical-content/01-principles.mdx, docs/src/documentation/06-kiwi-use/02-content/04-specific-areas/technical-content/02-tone.mdx, docs/src/documentation/06-kiwi-use/02-content/04-specific-areas/technical-content/04-language.mdx, docs/src/documentation/06-kiwi-use/03-guides/03-working-with-figma/01-basics.mdx, docs/src/documentation/06-kiwi-use/03-guides/03-working-with-figma/02-structure.mdx, docs/src/documentation/06-kiwi-use/03-guides/03-working-with-figma/03-design-flow.mdx, docs/src/documentation/06-kiwi-use/03-guides/03-working-with-figma/05-handoff.mdx
And fix a broken build when an improper node ID is supplied for Figma images.
And fix some styling issues.
Storybook: https://orbit-docs-guides.surge.sh
=> docs: add guides

docs/gatsby-config.js
To avoid having to filter by domain.
Storybook: https://orbit-fix-prod-google-analytics.surge.sh
=> fix: don't use Google Analytics in preview

docs/src/components/Search/SearchModal.tsx
It's a bit annoying if you lose focus out of the search input and the results will hide.
Storybook: https://orbit-docs-search-results.surge.sh
=> feat(docs): don't hide search results when out of focus

docs/src/components/Bookmarks/index.tsx, docs/src/components/Navbar.tsx
List bookmarks vertically and hide UI for managing bookmarks because this functionality doesn't exist yet.
Storybook: https://orbit-fix-hide-bookmark-editing.surge.sh
=> Hide bookmarks UI with missing functionality and list bookmarks vertically

.github/workflows/storybook.yml
In case `SURGE_TOKEN` changes the domain must change too in order to be
able to continue deploying because only the owner of the token can
deploy to a given domain by default unless they add a collaborator.
Let's see if this works…
Storybook: https://orbit-silvenon-namespace-surge-domain.surge.sh
=> ci: add current owner of Surge token to domain

package.json, yarn.lock
Bumped version with `bin/monstra.js` fix 
Storybook: https://orbit-silvenon-fix-monstra-bin.surge.sh
=> chore: bump monstra to 0.9.2

packages/orbit-components/src/ButtonLink/helpers/getButtonLinkTypeToken.js
Changed in #2100
Storybook: https://orbit-silvenon-chore-buttonlink-use-design-tokens.surge.sh
=> fix(ButtonLink): use proper design tokens

packages/orbit-components/src/InputField/index.js
Related to [Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1628069883005000).
Storybook: https://orbit-silvenon-fix-input-ios.surge.sh
=> fix(InputField): value color on iOS Safari when disabled

packages/orbit-components/src/Modal/Modal.stories.js, packages/orbit-components/src/Modal/ModalHeader/index.d.ts, packages/orbit-components/src/Modal/ModalHeader/index.js, packages/orbit-components/src/Modal/ModalHeader/index.js.flow, packages/orbit-components/src/Modal/README.md
[Slack request. ](https://skypicker.slack.com/archives/CAMS40F7B/p1628082105007800). 
It should be possible to turn off `MobileHeader`, added the prop, which is default set to `true`. 
Storybook: https://orbit-silvenon-feat-no-mobile-header.surge.sh
=> feat(Modal): add mobileHeader prop

packages/orbit-components/src/Modal/Modal.stories.js, packages/orbit-components/src/Modal/ModalContext.d.ts, packages/orbit-components/src/Modal/ModalContext.js, packages/orbit-components/src/Modal/ModalContext.js.flow, packages/orbit-components/src/Modal/ModalHeader/index.d.ts, packages/orbit-components/src/Modal/ModalHeader/index.js, packages/orbit-components/src/Modal/README.md, packages/orbit-components/src/Modal/index.d.ts, packages/orbit-components/src/Modal/index.js, packages/orbit-components/src/Modal/index.js.flow
[Slack request. ](https://skypicker.slack.com/archives/CAMS40F7B/p1628082105007800)
Related to: #2634, #3063 
Not sure about condition, which sets `CloseContainer`, did not want to leave there only `onClose and hasCloseButton`. In my opinion, it should appear only if `onClose` passed. 
Storybook: https://orbit-silvenon-fix-close-container.surge.sh
=> fix(Modal): hide closeContainer with mobileHeader set to false

.eslintrc.js, docs/src/components/DocLayout/index.tsx, docs/src/components/FigmaIframe.tsx, docs/src/documentation/03-components/03-information/badge/01-guidelines.mdx
Added `FigmaIframe` component. For @williamkolmacka, in order to add examples from Figma. 
Storybook: https://orbit-silvenon-docs-small-visual-fixes.surge.sh
=> docs: add FigmaIframe component

package.json, packages/orbit-design-tokens/package.json
This script is important for development, so running it automatically after every install helps when switching between branches where tokens need to be rebuilt.
Storybook: https://orbit-silvenon-improve-postinstall-build-tokens.surge.sh
=> improve: build tokens on postinstall

.github/foundation.md, docs/src/documentation/03-design-tokens/01-general.mdx, docs/src/documentation/03-design-tokens/02-installation.mdx, packages/orbit-design-tokens/docs/SCHEMA.md
Added some tweaks and wrapped the docs seemingly according to how the rest of our docs is wrapped. Not sure what are the rules, though, I forgot where are the docs for that.
=> docs: tweak and wrap design tokens docs

packages/orbit-components/src/hooks/useLockScrolling/index.js
This fixes a bug on iOS Safari where locking scroll was causing body not to take up full width of the screen because body-scroll-lock sets only top and left position.
Storybook: https://orbit-silvenon-fix-scroll-lock-positioning.surge.sh
=> fix(useLockScrolling): fix body positioning on iOS

packages/orbit-components/src/utils/rtl/README.md
=> fix: rtl doc code example goes wrong

packages/orbit-components/src/Badge/index.js
Added border to type `white` as we discussed before. 
Storybook: https://orbit-silvenon-fix-white-badge-border.surge.sh
=> fix(Badge): add border to type white

packages/orbit-components/src/Drawer/index.js
On iOS it's impossible to scroll Drawer content because `useLockScrolling` doesn't receive the scrollable container ref.
Storybook: https://orbit-silvenon-fix-drawer-content-scroll.surge.sh
=> fix(Drawer): fix iOS bug with scrolling content

.eslintrc.js, docs/package.json, docs/tsconfig.json, package.json, tsconfig.json
If we check docs separately `docs/styled.d.ts` won't cause problems when changing the global type for default theme.
Storybook: https://orbit-silvenon-chore-fix-typescript-errors.surge.sh
=> chore: fix TypeScript errors

docs/src/__examples__/Alert/DEFAULT.tsx, packages/orbit-components/src/Alert/index.js
`:not` doesn't increase CSS specificity, so that's cool!
Storybook: https://orbit-silvenon-fix-alert-link-style.surge.sh
=> feat(Alert): properly style links in Alert

packages/orbit-components/src/Icon/index.js, packages/orbit-components/src/primitives/TooltipPrimitive/__tests__/__snapshots__/index.test.js.snap
On orbit.kiwi the default `display` for `<svg>` elements is `block`, so `vertica-align: middle` didn't work, and icons in Alert components were incorrectly aligned.
Storybook: https://orbit-silvenon-fix-icon-inline-block.surge.sh
=> fix(Icon): explicitly set expected `display`

packages/orbit-components/cypress/integration/index.tsx, packages/orbit-components/src/hooks/useLockScrolling/index.js
Currently we don't merge theme given to `ThemeProvider` with default theme, so unless people merge it themselves, `lockScrolling` will be falsy and `useLockScrolling` will not lock scrolling. Instead of merging the given with the default theme, which might cause unexpected changes, we'll simply treat `lockScrolling` as `true` if it's not being set.
Storybook: https://orbit-silvenon-fix-theme-lock-scrolling-default.surge.sh
=> fix(useLockScrolling): ensure that scroll is locked by default

packages/orbit-components/src/InputField/InputTags/index.js, packages/orbit-components/src/InputField/index.js, packages/orbit-components/src/Popover/index.d.ts
- [Fixes slack request. ](https://skypicker.slack.com/archives/CAMS40F7B/p1632485533109900). Plus there was a bug with too small spacing in normal inputs (not in error forms). 
- Fixed type definition in the `Popover`
Storybook: https://orbit-silvenon-fix-small-fixes.surge.sh
=> fix(InputField): label before tags and spacing

docs/package.json, docs/src/components/ReactExample/Example.tsx, docs/src/components/ReactExample/components/ViewportsRuler.tsx, docs/src/components/ReactExample/consts.tsx, docs/src/components/ReactExample/index.tsx, docs/src/templates/Sandbox/index.tsx, yarn.lock
There were multiple problems with the viewport ruler, the biggest one being that it was computing container width too soon, so the initial width ended up being 0, making the ruler unusable. This refactor uses ResizeObserver instead of using the `resize` event of the entire window, and fixes some other bugs along the way.
Storybook: https://orbit-silvenon-fix-sandbox-viewport-ruler.surge.sh
=> refactor: rewrite viewport ruler

packages/orbit-components/.storybook/orbitTheme.js
the old logo is not accessible, because the web is down. 
Storybook: https://orbit-silvenon-fix-storybook-logo.surge.sh
=> fix(storybook): logo url

packages/orbit-components/src/hooks/useToggle/index.d.ts, packages/orbit-components/src/hooks/useToggle/index.js.flow
It defaults to false.
Storybook: https://orbit-silvenon-rcsl-use-toggle-types.surge.sh
=> fix(useToggle): make typings reflect initial param is optional

packages/orbit-components/src/Heading/__tests__/index.test.jsx, packages/orbit-components/src/Heading/index.jsx
In some cases Heading can be used with unsupported props, for example the library `markdown-to-jsx` passes `className` automatically, but Heading mistakenly treats it as a viewport and fails when it tries to access it as an object. Now we're filtering out props which aren't viewports, and simply ignore them.
Storybook: https://orbit-silvenon-fix-heading-filter-viewports.surge.sh
=> fix(Heading): fix error when passing unsupported props

packages/orbit-components/src/ErrorFormTooltip/Tooltip/consts.js, packages/orbit-components/src/ErrorFormTooltip/Tooltip/index.jsx
You can see that the tooltip is falling off-screen in orbit.kiwi examples because the constant `SIDE_NUDGE` wasn't actually being used for positioning, so using it for limiting tooltip width was problematic. Now we're properly syncing the two.
Also, by using `min` I'm trying to prevent tooltip from falling off-screen if the viewport width happens to be smaller than the width of the container + padding, but that's an edge case and just a precaution.
Let me know if I did this correctly 🤞
Storybook: https://orbit-silvenon-fix-error-form-tooltip-side-nudge.surge.sh
=> fix: prevent form tooltip from falling off-screen

packages/orbit-components/src/Popover/components/ContentWrapper.jsx
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1636718118131300). We used the wrong media query because mobile styles stop applying from `isLargeMobile`. 
Storybook: https://orbit-silvenon-fix-popover-onclose.surge.sh
=> fix(Popover): useClickOutside after isLargeMobile

.github/actions/node/action.yml, docs/src/__examples__/InputField/ERROR.tsx, docs/src/__examples__/InputField/HELP.tsx, docs/src/__examples__/InputField/REQUIRED.tsx
#3122 by @mainframev removed examples for InputField, which made sense for the InputField component page. But it left the [Forms and errors page](https://orbit.kiwi/design-patterns/form-errors/) with 3 instances of `Could not find example with the id:`. This PR restores those examples.
=> fix: restore examples for error forms

.yarnrc
Bump Yarn to 1.22.17. We were using a lower version as a workaround for the [missing `sharp` module](https://github.com/yarnpkg/yarn/issues/7807), but that workaround didn't work because I'm often getting that error, so let's bump Yarn considering that it doesn't matter.
Btw, every time I get that error (when I run orbit.kiwi), I run `npm rebuild sharp` and that solves it, so it's not a big problem.
Storybook: https://orbit-silvenon-chore-bump-yarn.surge.sh
=> chore: bump Yarn

packages/orbit-components/src/hooks/useMediaQuery/index.js
Older browsers like Safari 13 don't support `addEventListener` and `removeEventListener` on `MediaQueryList`.
Storybook: https://orbit-silvenon-fix-use-media-query-fallback.surge.sh
=> fix(useMediaQuery): add a fallback for older browsers

docs/src/components/DocNavigation/__tests__/index.test.tsx, docs/src/components/DocNavigation/index.tsx
Tests are here, but implementation is missing.
Storybook: https://orbit-silvenon-docs-nav-components-alphabetical.surge.sh
=> docs: flatten and alphabetize list of components in navigation

packages/orbit-components/src/utils/mediaQuery/__typetests__/index.ts, packages/orbit-components/src/utils/mediaQuery/index.d.ts
Storybook: https://orbit-silvenon-rcsl-fix-overlord-mediaquery.surge.sh
=> fix(getBreakpointWidth): improve typings through overloading

packages/orbit-components/src/Heading/index.jsx
For some reason `viewports` ends up being `undefined` in some cases, even though it should always be at least an empty object considering that it's a rest prop. Until we figure out why this happens we're adding a temporary fix so that this doesn't cause an error in production.
Storybook: https://orbit-silvenon-fix-heading-viewports-undefined.surge.sh
=> fix(Heading): temporary fix for `viewports` being `undefined`

docs/plugins/contributors/fetchedUsers.json, docs/src/components/DocLayout/index.tsx, docs/src/components/Tabs/Tab.tsx, docs/src/components/Tabs/consts.ts, docs/src/components/Tabs/helpers.ts, docs/src/components/Tabs/index.tsx
The tab shadow was very noticeably clipping on the left, especially stacked tabs on hover.
Storybook: https://orbit-silvenon-docs-tabs-shadow-clip.surge.sh
=> fix: prevent tab shadow clipping

docs/src/templates/Tracking/ComponentPage.tsx
external source links are working fine on localhost, but after deployment, they are appended to the root url, removed `external` prop, because links for members are working fine without it.
Storybook: https://orbit-silvenon-fix-instances-links.surge.sh
=> docs(tracking): fix sources links

docs/src/documentation/05-development/03-hooks/uselockscrolling.mdx, packages/orbit-components/src/hooks/useLockScrolling/README.md
I noticed that many of our pages have titles shown twice, which is an unfortunate side-effect of importing readmes, so this page also features one way to avoid that, as well as an awkward trick to sneak in the Alert component into a readme 😄 
Storybook: https://orbit-silvenon-docs-use-lock-scrolling.surge.sh
=> docs(useLockScrolling): document in orbit.kiwi

packages/orbit-components/src/Layout/Layout.stories.jsx, packages/orbit-components/src/Layout/LayoutColumn/index.d.ts, packages/orbit-components/src/Layout/LayoutColumn/index.jsx, packages/orbit-components/src/Layout/LayoutColumn/index.jsx.flow, packages/orbit-components/src/Layout/consts.js
- [Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1641897079019700)
I also extracted the recommended alternative to Layout for booking:
```jsx
import React from "react";
import mq from "@kiwicom/orbit-components/lib/utils/mediaQuery";
import styled, { css } from "styled-components";
const StyledGrid = styled.div`
${({ theme }) => css`
box-sizing: content-box;
display: grid;
grid-template-areas:
"breadcrumbs"
"main"
"sidebar";
max-width: 1140px;
margin: 0 auto;
padding: 0 ${theme.orbit.spaceMedium};
row-gap: ${theme.orbit.spaceMedium};
${mq.tablet(css`
grid-template-areas:
"breadcrumbs breadcrumbs"
"main sidebar";
grid-template-columns: 7fr minmax(272px, 3fr);
column-gap: ${theme.orbit.spaceMedium};
`)};
${mq.desktop(css`
padding: 0 ${theme.orbit.spaceLarge};
column-gap: …
```
=> feat(Layout): accommodate breacrumbs on booking

packages/orbit-components/src/ErrorFormTooltip/Tooltip/index.jsx, packages/orbit-components/src/ErrorFormTooltip/Tooltip/index.jsx.flow, packages/orbit-components/src/ErrorFormTooltip/index.d.ts, packages/orbit-components/src/ErrorFormTooltip/index.jsx, packages/orbit-components/src/ErrorFormTooltip/index.jsx.flow, packages/orbit-components/src/ErrorForms.stories.jsx, packages/orbit-components/src/FormLabel/index.jsx, packages/orbit-components/src/InputField/README.md, packages/orbit-components/src/InputField/index.d.ts, packages/orbit-components/src/InputField/index.jsx, packages/orbit-components/src/InputField/index.jsx.flow, packages/orbit-components/src/InputFile/README.md, packages/orbit-components/src/InputFile/index.d.ts, packages/orbit-components/src/InputFile/index.jsx, packages/orbit-components/src/InputFile/index.jsx.flow, packages/orbit-components/src/InputGroup/README.md, packages/orbit-components/src/InputGroup/index.d.ts, packages/orbit-components/src/InputGroup/index.jsx, packages/orbit-components/src/InputGroup/index.jsx.flow, packages/orbit-components/src/Select/README.md, packages/orbit-components/src/Select/index.d.ts, packages/orbit-components/src/Select/index.jsx, packages/orbit-components/src/Select/index.jsx.flow, packages/orbit-components/src/Textarea/README.md, packages/orbit-components/src/Textarea/index.d.ts, packages/orbit-components/src/Textarea/index.jsx, packages/orbit-components/src/Textarea/index.jsx.flow
- added new prop for error forms, if someone would like to disable closable help
small visual changes:
- label icons for help changed colors from secondary to info.
- close icon moved on top
Storybook: https://orbit-silvenon-fix-error-forms.surge.sh
=> error forms small changes

packages/orbit-components/src/Itinerary/ItinerarySegment/ItinerarySegmentDetail/index.jsx
Truncate long texts in `ItinerarySegmentDetail`. Let's wait until the discussion and design will be updated for badges, we can use there `HorizontalScroll`
Storybook: https://orbit-silvenon-fix-itinerary.surge.sh
=> fix(Itinerary): truncate possible long texts

docs/src/__examples__/Separator/DEFAULT.tsx, packages/orbit-components/src/Card/components/CardWrapper/index.jsx, packages/orbit-components/src/Popover/components/ContentWrapper.jsx, packages/orbit-components/src/Separator/README.md, packages/orbit-components/src/Separator/Separator.stories.jsx, packages/orbit-components/src/Separator/index.d.ts, packages/orbit-components/src/Separator/index.jsx, packages/orbit-components/src/Separator/index.jsx.flow, packages/orbit-components/src/SocialButton/index.jsx, packages/orbit-components/src/primitives/ButtonPrimitive/index.jsx
UI fixes for:
- Collapse ([ORBIT-1979](https://jira.kiwi.com/browse/ORBIT-1979))
- the problem was that `:focus` styles in ButtonPrimitve were overriding `:hover` styles, so I did some editing there, also now `:active` styles should work better
- SocialButton ([ORBIT-1992](https://jira.kiwi.com/browse/ORBIT-1992))
- Popover ([ORBIT-1984](https://jira.kiwi.com/browse/ORBIT-1984))
- bottom corners weren't rounded when actions were present because of the actions' white background, one solution was to set `overflow: hidden` on the entire Popover, but I didn't want some unintended consequences so I went for the safer option of rounding corners of the actions container
- Separator ([ORBIT-1987](https://jira.kiwi.com/browse/ORBIT-1987))
The two remaining ones are ButtonMobileStore and Card, but …
=> UI fixes for Collapse, SocialButton, Popover and Separator

packages/orbit-components/src/ErrorFormTooltip/Tooltip/helpers/resolvePlacement.js, packages/orbit-components/src/ErrorFormTooltip/Tooltip/index.jsx
Decided to do it in a quicker way with current `popper`, as far as we discovered, that moving to `floating-ui` will not hide the console warnings in our tests. Plus i found `floating-ui` api is not sufficient and more uncomfortable to implement. It's missing `auto` in placement, plus it's much harder to place tooltip correctly with dynamic placement and arrow. 
Storybook: https://orbit-silvenon-fix-errorforms-pos.surge.sh
=> fix(ErrorFormTooltip): fix visual alignment

packages/orbit-components/src/BaggageStepper/__tests__/index.test.jsx, packages/orbit-components/src/InputField/__tests__/index.test.jsx, packages/orbit-components/src/InputFile/__tests__/index.test.jsx, packages/orbit-components/src/InputGroup/__tests__/index.test.jsx, packages/orbit-components/src/InputStepper/__tests__/index.test.jsx, packages/orbit-components/src/Modal/__tests__/index.test.jsx, packages/orbit-components/src/Select/__tests__/Select.test.jsx, packages/orbit-components/src/SkipNavigation/__tests__/index.test.jsx, packages/orbit-components/src/Slider/__tests__/index.test.jsx, packages/orbit-components/src/Stepper/__tests__/index.test.jsx, packages/orbit-components/src/Textarea/__tests__/index.test.jsx
We still had `act` warnings, so I fixed those and changed the existing fixes with what I think is the most straightforward solution. One way to make it self-documenting is to create a utility that does the empty `act` call named `flushQueue` or something, and add comments to document it, let me know what you think.
This solution should work both for Popper and Floating UI. floating-ui/floating-ui#1521
Storybook: https://orbit-silvenon-test-popper-act-warnings.surge.sh
=> Better usage of `@testing-library/user-event` and clear up remaining `act` warnings

packages/orbit-components/src/hooks/useTransition/__tests__/index.test.jsx, packages/orbit-components/src/hooks/useTransition/index.d.ts, packages/orbit-components/src/hooks/useTransition/index.js, packages/orbit-components/src/hooks/useTransition/index.js.flow
The Toast implementation in #3187 uses CSS Animations, but I think this is unnecessary, you can get by with just CSS Transitions. The problem with the current Toast implementation is that it stays in the DOM after fading out, so you won't be able to click on something below it if you need to, which will be very confusing because Toast is invisible, so I recommend unmounting Toast after fading out.
The problem with animating the presence of an element in the DOM is a well-known one, and has already been solved by libraries like react-transition-group (more specifically, its CSSTransition component), which I used as an inspiration for this hook. Currently it's undocumented because it's intended primarily for internal use, but people are welcome to try it.
I considered using [Headless UI's …
=> feat: add new experimental hook `useTransition`

docs/src/documentation/05-development/03-hooks/usetransition.mdx, packages/orbit-components/src/hooks/useTransition/README.md, packages/orbit-components/src/hooks/useTransition/__tests__/index.test.jsx, packages/orbit-components/src/hooks/useTransition/index.d.ts, packages/orbit-components/src/hooks/useTransition/index.js, packages/orbit-components/src/hooks/useTransition/index.js.flow
This also adds a tweak to `useTransition` API. Instead of the `enter` property I decided it would be better to pass the `state` property.
Storybook: https://orbit-silvenon-docs-use-transition.surge.sh
=> Document useTransition hook

packages/orbit-components/src/ErrorForms.stories.jsx, packages/orbit-components/src/InputField/index.jsx
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1643896085551969)
Storybook: https://orbit-silvenon-fix-hover-errorforms.surge.sh
=> fix(InputField): enable tooltip on hover when disabled

packages/orbit-components/src/Tile/README.md, packages/orbit-components/src/Tile/Tile.stories.jsx, packages/orbit-components/src/Tile/__tests__/index.test.jsx, packages/orbit-components/src/Tile/index.d.ts, packages/orbit-components/src/Tile/index.jsx, packages/orbit-components/src/Tile/index.jsx.flow, packages/orbit-components/src/TileGroup/README.md, packages/orbit-components/src/TileGroup/TileGroup.stories.jsx, packages/orbit-components/src/TileGroup/__tests__/index.test.jsx, packages/orbit-components/src/TileGroup/index.d.ts, packages/orbit-components/src/TileGroup/index.jsx, packages/orbit-components/src/TileGroup/index.jsx.flow
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1646043279927369)
Storybook: https://orbit-silvenon-feat-tile-as.surge.sh
=> feat: add tile and tilegroup as prop

docs/src/documentation/03-components/03-information/toast/01-guidelines.mdx
The final paragraph of the Toast component Content description was duplicated.
This removes the extra copy.
=> Remove duplicate ¶ from Toast content

.github/workflows/size.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>
=> Set permissions for GitHub actions

docs/src/data/component-status.yaml
Currently, there is a mistake – component that we do not have and is not defined in our repo is defined here with released state, so rather making everything here a default N/A.
Storybook: https://orbit-mainframev-hrach-patch-1.surge.sh
=> docs: component status is N/A for all Android components

docs/src/documentation/01-getting-started/02-for-developers.mdx, packages/orbit-components/README.md
[ORBIT-1520](https://jira.kiwi.com/browse/ORBIT-1520)
The `orbit-components` package now has a README file, based on other packages' README and also on the public documentation page.
While reading the documentation page I noticed references to kiwi.com devs and internal slack channels and I decided to remove them, since they should not be relevant for people outside kiwi.com. If this change is not desired, the last commit can be removed.
Storybook: https://orbit-mainframev-chore-create-readme-for-orbit-components.surge.sh
=> docs: readme for orbit components

packages/orbit-components/src/Tooltip/README.md, packages/orbit-components/src/Tooltip/__tests__/index.test.jsx, packages/orbit-components/src/Tooltip/index.d.ts, packages/orbit-components/src/Tooltip/index.jsx, packages/orbit-components/src/Tooltip/index.jsx.flow, packages/orbit-components/src/primitives/TooltipPrimitive/README.md, packages/orbit-components/src/primitives/TooltipPrimitive/index.d.ts, packages/orbit-components/src/primitives/TooltipPrimitive/index.jsx, packages/orbit-components/src/primitives/TooltipPrimitive/index.jsx.flow
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1664966991843809)
Storybook: https://orbit-mainframev-feat-add-onshow-callback.surge.sh
=> feat: add onShow properties for Tooltip and TooltipPrimitive 

packages/babel-plugin-orbit-components/index.js, packages/orbit-components/src/BadgeList/BadgeListItem/index.d.ts, packages/orbit-components/src/BadgeList/BadgeListItem/index.jsx, packages/orbit-components/src/BadgeList/BadgeListItem/index.jsx.flow, packages/orbit-components/src/Itinerary/Itinerary.stories.jsx, packages/orbit-components/src/Itinerary/ItineraryBadgeList/ItineraryBadgeListItem.d.ts, packages/orbit-components/src/Itinerary/ItineraryBadgeList/ItineraryBadgeListItem.jsx, packages/orbit-components/src/Itinerary/ItineraryBadgeList/ItineraryBadgeListItem.jsx.flow, packages/orbit-components/src/Itinerary/ItineraryBadgeList/index.d.ts, packages/orbit-components/src/Itinerary/ItineraryBadgeList/index.jsx, packages/orbit-components/src/Itinerary/ItineraryBadgeList/index.jsx.flow, packages/orbit-components/src/Itinerary/index.d.ts, packages/orbit-components/src/Itinerary/index.jsx, packages/orbit-components/src/Itinerary/index.jsx.flow, packages/orbit-components/src/index.d.ts, packages/orbit-components/src/index.js, packages/orbit-components/src/index.js.flow
Add new `ItineraryBadgeListItem`, which is a slightly modified version of the original BadgeListItem for Itinerary. 
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1664876251315189?thread_ts=1664875481.009669&cid=CAMS40F7B)
Storybook: https://orbit-mainframev-feat-itinerary-badge-list-item.surge.sh
=> feat(ItineraryBadgeListItem): add new ItineraryBadgeListItem

packages/orbit-components/src/primitives/TooltipPrimitive/__tests__/__snapshots__/index.test.jsx.snap, packages/orbit-components/src/primitives/TooltipPrimitive/index.jsx
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1665477949634829)
Storybook: https://orbit-mainframev-fix-tooltip-req.surge.sh
=> fix(Tooltip): add max-width and render as flex instead of block

docs/src/documentation/01-getting-started/02-for-developers.mdx, docs/src/documentation/02-foundation/02-accessibility.mdx, docs/src/documentation/03-components/09-text/text/01-guidelines.mdx, docs/src/documentation/03-components/09-text/text/02-react.mdx, docs/src/documentation/03-components/12-layout/layout/01-guidelines.mdx, docs/src/documentation/03-components/12-layout/layout/02-react.mdx
Text and Layout were redirecting to the components page. There was also a wrong link to the Button's documentation on the Developers main page.
Routes fixed:
- [Components page](https://orbit.kiwi/components/):
- Clicking the Layout button now redirects to the page with all layout components.
- Clicking the Text button now redirects to the page with all text components
- [Developers main page](https://orbit.kiwi/getting-started/for-developers/):
- Clicking the Components link under **_Main Sections_** now redirects to the components main page.
Storybook: https://orbit-mainframev-fix-layout-docs-link.surge.sh
=> fix(docs): fix text and layout redirects

packages/orbit-components/src/Table/index.jsx
While working on the new Table for Docs, I noticed this small bug on the Table. The shadow on the mobile version was not disappearing even if the user scrolled all the way horizontally.
Before:
Now:
Storybook: https://orbit-mainframev-fix-table-shadow-responsiveness.surge.sh
=> fix(Table): responsive shadow was not correct

.github/contribution/README.md, packages/orbit-components/src/Accordion/Accordion.stories.jsx, packages/orbit-components/src/Accordion/index.jsx
Fixes #3561 
An id update was missed during some id work, which resulted in the accordion checking against the wrong id to determine whether it should be expanded or not.
Tested in storybook
=> fix(Accordion): not expanding

packages/orbit-components/src/LinkList/README.md, packages/orbit-components/src/LinkList/__tests__/index.test.jsx, packages/orbit-components/src/LinkList/index.d.ts, packages/orbit-components/src/LinkList/index.jsx, packages/orbit-components/src/LinkList/index.jsx.flow, packages/orbit-components/src/Stack/README.md, packages/orbit-components/src/Stack/Stack.stories.jsx, packages/orbit-components/src/Stack/helpers/__tests__/shouldUseFlex.test.js, packages/orbit-components/src/Stack/helpers/getChildrenMargin.js, packages/orbit-components/src/Stack/helpers/getChildrenMargin.js.flow, packages/orbit-components/src/Stack/helpers/getDirectionSpacingTemplate.js, packages/orbit-components/src/Stack/helpers/getDirectionSpacingTemplate.js.flow, packages/orbit-components/src/Stack/helpers/getGap.js, packages/orbit-components/src/Stack/index.d.ts, packages/orbit-components/src/Stack/index.jsx, packages/orbit-components/src/Stack/index.jsx.flow, yarn.lock
We forgot about margin collapsing and that created unnecessary complications on FE repositories, let's revert for now and left it as a feature change. When everybody will be ready for that. 
For LinkList just reverted as it was before
Storybook: https://orbit-mainframev-revert-spacing-changes.surge.sh
=> revert(Stack): remove gap change

docs/__tests__/__snapshots__/gatsby-node.test.ts.snap, docs/__tests__/gatsby-node.test.ts, docs/gatsby-node.ts, docs/src/components/Breadcrumbs.tsx, docs/src/components/DocLayout/index.tsx, docs/src/components/DocNavigation/__tests__/index.test.tsx, docs/src/components/DocNavigation/index.tsx, docs/src/components/Search/SearchModal.tsx, docs/src/templates/Doc.tsx, docs/src/templates/Overview.tsx, docs/src/utils/document.ts, docs/utils/document.ts
On docs, the `trail` field was renamed to `breadcrumbs` as it is considered more accurate.
Storybook: https://orbit-mainframev-refactor-rename-trail-to-breadcrumbs.surge.sh
=> refactor(docs): rename trail to breadcrumbs

packages/orbit-components/src/SegmentedSwitch/README.md, packages/orbit-components/src/SegmentedSwitch/index.d.ts
It was being documented as `defaultCheck`, but it should be `defaultChecked`.
Storybook: https://orbit-mainframev-fix-incorrect-defaultChecked-segmentedSwitch.surge.sh
=> fix(SegmentedSwitch): incorrect defaultChecked prop name

packages/orbit-components/src/Tooltip/index.jsx, packages/orbit-components/src/primitives/MobileDialogPrimitive/README.md, packages/orbit-components/src/primitives/MobileDialogPrimitive/__tests__/index.test.jsx, packages/orbit-components/src/primitives/MobileDialogPrimitive/index.d.ts, packages/orbit-components/src/primitives/MobileDialogPrimitive/index.jsx, packages/orbit-components/src/primitives/MobileDialogPrimitive/index.jsx.flow
[Slack request #1](https://skypicker.slack.com/archives/CAMS40F7B/p1666695579504919)
[Slack request #2](https://skypicker.slack.com/archives/CAMS40F7B/p1666696607559829)
Storybook: https://orbit-mainframev-fix-missing-on-shown.surge.sh
=> fix: missing onShow prop for MobileDialog inside Tooltip 

packages/orbit-components/src/Box/index.jsx, packages/orbit-components/src/ErrorFormTooltip/__tests__/index.test.jsx, packages/orbit-components/src/InputField/__tests__/index.test.jsx, packages/orbit-components/src/InputGroup/__tests__/index.test.jsx, packages/orbit-components/src/LinkList/index.jsx, packages/orbit-components/src/Popover/__tests__/index.test.jsx, packages/orbit-components/src/SegmentedSwitch/__tests__/index.test.jsx, packages/orbit-components/src/Textarea/__tests__/index.test.jsx, packages/orbit-components/src/Tooltip/__tests__/index.test.jsx, packages/orbit-components/src/deprecated/InputStepper/__tests__/index.test.jsx, packages/orbit-components/src/primitives/TooltipPrimitive/__tests__/index.test.jsx
Removed the test warnings. One issue is connected with `react-popper` and there is nothing that we can do currently, only hide that test warnings. 
Storybook: https://orbit-mainframev-fix-test-warnings.surge.sh
=> test: remove test warnings

docs/gatsby-config.ts, docs/package.json, docs/src/components/HeaderBox.tsx, docs/src/components/RocketImage.tsx, docs/src/consts.ts, docs/src/pages/index.tsx, yarn.lock
Rocket image is now using the new gatsby-plugin-image and no longer has an enter transition.
Grey background on the homepage was added on desktop version
Storybook: https://orbit-mainframev-docs-change-homepage-image.surge.sh
=> docs: change homepage image

docs/src/components/DocLayout/primitives/StyledMobileTocWrapper.ts, docs/src/components/Navbar/Links.tsx, docs/src/components/Search/SearchButton.tsx
This addresses two requests made [here](https://skypicker.slack.com/archives/GSGN9BN6Q/p1667480757876079), [here](https://skypicker.slack.com/archives/GSGN9BN6Q/p1667480796161609) and [here](https://skypicker.slack.com/archives/GSGN9BN6Q/p1667412776648439?thread_ts=1667213430.557639&cid=GSGN9BN6Q).
Table of Contents is now no longer visible in desktop and tablets.
The order of the Foundation and Components links on the Navbar was changed.
SearchButton color is now according to the design.
Storybook: https://orbit-mainframev-docs-minor-adjustments.surge.sh
=> Docs: minor adjustments (ToC and Foundation before Components)

docs/gatsby-node.ts, docs/src/components/DocLayout/TopBar.tsx, docs/src/components/DocLayout/index.tsx, docs/src/components/DocLayout/primitives/StyledDocNavigationWidth.tsx, docs/src/components/DocLayout/primitives/StyledMiddle.tsx, docs/src/documentation/02-foundation/10-typography/01-general.mdx, docs/src/documentation/03-components/02-structure/tabs/01-guidelines.mdx, docs/src/documentation/03-components/02-structure/tabs/meta.yml, docs/src/pages/404.tsx, docs/src/templates/Doc.tsx, docs/src/templates/Overview.tsx
It is now possible to add custom storybook and headerlinks (usually for Github) on the meta.yml file.
This also allows to hide the button when it is defined to `false`.
The Tabs documentation page was broken and is now fixed.
Storybook: https://orbit-mainframev-docs-add-custom-topbar-links.surge.sh
=> Docs: add custom topbar links + fix tabs documentation page

packages/orbit-components/src/InputField/index.tsx
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#autocorrect
[why](https://baymard.com/labs/touch-keyboard-types)
=> feat(InputField): set autoCorrect and autoCapitalize explicitly to off

docs/src/__examples__/CarrierLogo/MULTIPLE.tsx, docs/src/documentation/03-components/08-visuals/carrierlogo/01-guidelines.mdx, packages/orbit-components/src/CarrierLogo/CarrierLogo.stories.tsx, packages/orbit-components/src/CarrierLogo/README.md, packages/orbit-components/src/CarrierLogo/index.tsx, packages/orbit-components/src/CarrierLogo/types.ts
CarrierLogo now supports inline stacking of logos, as it is needed for the SHOT project.
=> feat: add inlineStacked property to CarrierLogo

packages/orbit-components/src/Box/__tests__/index.test.tsx, packages/orbit-components/src/Box/normalize.ts
The wrap property in Box component was evaluating its value wrongly.
One test was also changed so it actually failed before and passes now.
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1669201347964819)
=> fix(Box): wrap property was calculated incorrectly

packages/orbit-components/src/Heading/index.tsx
https://www.a11yproject.com/posts/how-to-accessible-heading-structure/
about our discussion inside the repo analysis doc. I think it's a better approach, do not to introduce a breaking change without forcing users to pick an element.
=> fix(Heading): add missing role='heading' for div rendered as Heading

packages/orbit-components/src/primitives/TooltipPrimitive/helpers/resolveBackgroundColor.ts
The background color of the tooltip was incorrect, as noticed during pair programming.
=> fix(Tooltip): background color

packages/orbit-components/src/Modal/index.tsx
When a Modal is full page on Modal, it does not render the dark overlay, avoiding a flash happening occasionally.
[Slack report](https://skypicker.slack.com/archives/CAMS40F7B/p1669303701390719)
=> fix(Modal): don't render overlay if is full page

packages/orbit-components/src/primitives/ButtonPrimitive/components/ButtonPrimitiveContentChildren.tsx
This avoid multi-line text inside button to be misaligned
[Slack context](https://skypicker.slack.com/archives/CAMS40F7B/p1669886645300519)
=> feat(Button): add line-height: 1

packages/orbit-components/src/Button/Button.stories.tsx, packages/orbit-components/src/Button/README.md, packages/orbit-components/src/Button/index.tsx, packages/orbit-components/src/Button/types.d.ts, packages/orbit-components/src/primitives/ButtonPrimitive/common/__tests__/__snapshots__/getCommonProps.test.ts.snap, packages/orbit-components/src/primitives/ButtonPrimitive/common/__tests__/getCommonProps.test.ts, packages/orbit-components/src/primitives/ButtonPrimitive/common/getCommonProps.ts, packages/orbit-components/src/primitives/ButtonPrimitive/components/ButtonPrimitiveContentChildren.tsx, packages/orbit-components/src/primitives/ButtonPrimitive/index.tsx, packages/orbit-components/src/primitives/ButtonPrimitive/types.d.ts
It is now possible to center the content of a fullWidth button.
=> feat(Button): add centered prop for fullWidth

packages/orbit-components/src/Itinerary/ItinerarySegment/index.tsx
Fixes the issue with incorrect counting of elements. React.Children.count counts elements that are not even rendered.
=> fix(ItinerarySegment): fix incorrect counting of elements

packages/orbit-components/src/CarrierLogo/index.tsx
Width was incorrectly set to a fixed value even when inlineStacked was set to true. This was detected when using the component for the first time.
**Before:**
**After:**
=> fix(CarrierLogo): correct width when inlineStacked

packages/orbit-components/src/Card/CardSection/components/SectionContent.tsx
Looks like redundant padding, check how currently it looks with "onlySection" in storybook
=> fix(Card): remove additional padding in CardSection

docs/src/__examples__/Button/ICONS.tsx
=> docs: fix button only icon example

packages/orbit-components/src/InputField/__tests__/index.test.tsx, packages/orbit-components/src/InputField/index.tsx, packages/orbit-components/src/Select/__tests__/Select.test.tsx, packages/orbit-components/src/Select/index.tsx, packages/orbit-components/src/Textarea/__tests__/index.test.tsx, packages/orbit-components/src/Textarea/index.tsx
Added `aria-invalid` and `aria-describedby` to InputField, Select and Textarea components.
[ORBIT-1960](https://kiwicom.atlassian.net/browse/ORBIT-1960)
=> Add aria-invalid and aria-describedby to form components

.github/workflows/cron-tracking.yml
fixed action for tracking, it should have correct ssh to execute all scripts we have for tracking
=> chore: setup ssh for tracking action

docs/src/documentation/03-components/07-interaction/collapse/01-guidelines.mdx
=> docs(Collapse): fix link pointing to wrong page

packages/orbit-components/src/FormLabel/index.tsx, packages/orbit-components/src/InputGroup/index.tsx, packages/orbit-components/src/SegmentedSwitch/SwitchSegment/index.tsx
As reported here, the difference in the line-height of the form labels was causing misalignment between components that use it. Adjusting the line-height allows all input components to have the same height and alignment.
This also includes a fix in the SegmentedSwitch option height, so it matches Figma
=> Fix: form label line height

packages/orbit-components/src/Illustration/Illustration.stories.tsx, packages/orbit-components/src/Text/Text.stories.tsx, packages/orbit-components/src/Text/index.tsx
When adding the margin prop, the default value of 0 was incorrectly replaced by the browser default value on `Text`component.
This also removed the deprecated `spaceAfter` props from storybook knobs on `Text` and `Illustration` components.
=> Fix: default margins on text

packages/orbit-components/src/ErrorFormTooltip/__tests__/useErrorTooltip.test.tsx, packages/orbit-components/src/ErrorFormTooltip/hooks/useErrorTooltip.ts, packages/orbit-components/src/InputField/index.tsx, packages/orbit-components/src/InputFile/index.tsx, packages/orbit-components/src/SegmentedSwitch/index.tsx, packages/orbit-components/src/Select/index.tsx, packages/orbit-components/src/Textarea/index.tsx
The `useErrorTooltip` hook now receives a new parameter that indicates if it has a tooltip to handle or not. If not, it avoids state update calls that were unnecessary.
Tests to the hook were also added.
All components using the hook were also updated to the correct usage.
[ORBIT-2464](https://kiwicom.atlassian.net/browse/ORBIT-2464)
After this is merged, an update on #3705 is advised, so it avoids further conflicts in the future.
=> Remove state update from useErrorTooltip hook

docs/src/documentation/02-foundation/04-color/01-colors.mdx
As reported in Slack, docs were outdated from what changed in 4.0.0
=> chore(docs): fix text color instructions

packages/orbit-components/src/Itinerary/Itinerary.stories.tsx, packages/orbit-components/src/Itinerary/ItinerarySegment/ItinerarySegmentBanner/index.tsx
An `ItinerarySegmentBanner` was always displaying a chevron, even if it was not clickable. This is now controlled and the chevron is only displayed if `onClick` is defined.
[ORBIT-2576](https://kiwicom.atlassian.net/browse/ORBIT-2576)
=> fix(Itinerary): only display chevron if Banner is clickable

packages/orbit-components/src/Modal/index.tsx
On mobile, the Modal had an incorrect border-top-left-radius.
[ORBIT-2578](https://kiwicom.atlassian.net/browse/ORBIT-2578)
=> fix(Modal): border-radius on mobile

packages/orbit-components/src/Accordion/Accordion.stories.tsx, packages/orbit-components/src/Radio/index.tsx, packages/orbit-components/src/Text/index.tsx
This PR addresses multiple issues:
- The `Accordion` component had a broken story because of a missing import
- `StyledLabel` is now exported (to be used internally) on `Radio` component. It is not exported to be used by Orbit users, though.
- The `StyledText` component's `element` prop now has `p` as default value
=> Fix Accordion Story + export StyledLabel from Radio + add default value to element prop in StyledText

packages/orbit-components/src/Select/index.tsx
The Select component had a white background on its container, that would conflict with the border-radius effect.
Before:
After:
Resolves #3695
=> fix(Select): remove white bg from container

packages/orbit-components/src/Timeline/TimelineStep/primitives/StyledProgressLine.ts
Current: ![Screenshot 2023-02-16 at 16 30 44](https://user-images.githubusercontent.com/14054752/219411754-cae7b289-3147-4d5c-a52f-7ebc8403a716.png)
Fixed:
=> fix(Timeline): fix the last bold line in TimelineStep on desktop

packages/orbit-components/src/Modal/ModalHeader/index.tsx, packages/orbit-components/src/Modal/index.tsx
[Slack thread](https://skypicker.slack.com/archives/CAMS40F7B/p1670580968891149).
This is a visual breaking change because there can be users relying on the margin.
=> feat: remove default margin top from modal header

.eslintrc.js, docs/styled.d.ts, packages/orbit-components/src/Illustration/TYPESCRIPT_TEMPLATE.template, packages/orbit-components/src/Tabs/components/Tab/types.d.ts, packages/orbit-components/src/Tabs/components/TabList/types.d.ts, packages/orbit-components/src/Tabs/components/TabPanel/types.d.ts, packages/orbit-components/src/Tabs/components/TabPanels/types.d.ts, packages/orbit-components/src/Tabs/types.d.ts, packages/orbit-components/src/primitives/IllustrationPrimitive/types.d.ts
added `no-undef` rule in order to prevent such issues as in `Tabs` component with unresolved types
includes #3754
=> fix: d.ts lint issues

packages/orbit-components/src/Timeline/TimelineStep/components/TimelineStepDesktop.tsx
The Step title of the Itinerary was not horizontally centered when the text wrapped into multiple lines. This fixes that problem.
**Before:**
**After:**
=> fix(Timeline): correctly align text inside a Modal

packages/orbit-components/src/Itinerary/Itinerary.stories.tsx, packages/orbit-components/src/Itinerary/ItinerarySegment/index.tsx, packages/orbit-components/src/Itinerary/ItineraryStatus/index.tsx, packages/orbit-components/src/Itinerary/ItineraryStatus/types.d.ts, packages/orbit-components/src/Itinerary/README.md
This addresses two issues:
- Text can now be selected inside the expanded part of ItinerarySegmentDetails without triggering the close action
- When a segment was wrapped in ItineraryStatus, it would always have the actionable style. It can now be controlled. (A story was updated to display this use case)
Docs were also updated regarding new and required props.
[Slack thread](https://skypicker.slack.com/archives/CAMS40F7B/p1678437139773419)
=> Fix Itinerary expand issues

packages/orbit-components/src/Stack/helpers/getGap.ts
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1678714906521569)
Based on [`-webkit-touch-callout`](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-touch-callout) and `supports` query. It's being used only on iOS Safari, that allow us to trigger only it. 
tested on iOS Safari 13
=> fix(Stack): fix gap issue for iOS Safar < 14.1

packages/orbit-components/src/Itinerary/Itinerary.stories.tsx, packages/orbit-components/src/Itinerary/ItineraryTemporaryText/index.tsx
After #3749 and #3760 this is, hopefully, the last fix related to this. By changing prop names, the prop drilling was not correct. This PR fixes that.
Also changed a story for better visibility of the feature.
**Before:**
**Now:**
=> fix(Itinerary): type colors were not being correctly applied

packages/orbit-components/src/CarrierLogo/index.tsx
As decided [here](https://skypicker.slack.com/archives/GSGN9BN6Q/p1678786374077159)
=> fix(CarrierLogo): remove shadow from inlineStacked variation

packages/orbit-components/src/Checkbox/index.tsx, packages/orbit-components/src/InputField/helpers/formElementFocus.ts, packages/orbit-components/src/Radio/index.tsx, packages/orbit-components/src/SegmentedSwitch/SegmentedSwitch.stories.tsx, packages/orbit-components/src/SegmentedSwitch/SwitchSegment/index.tsx, packages/orbit-components/src/Stepper/StepperStateless/index.tsx, packages/orbit-components/src/Switch/index.tsx, packages/orbit-components/src/Tile/components/TileWrapper/index.tsx, packages/orbit-components/src/utils/common/index.ts
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1678724132897789)
As we decided to use the default browser outline instead of box-shadow before, which in my opinion is totally ok, however, there are situations like this one, when we rely on default input focus behavior and the color of the outline may be different depending on the browser, operating systems and user's preferences, that's why I think we should implicitly force it to be blue only, so requests like this will not appear anymore.
=> fix: segmented switch outline and role

packages/orbit-components/src/primitives/ButtonPrimitive/types.d.ts
As reported [here](https://skypicker.slack.com/archives/C9B1H0ACW/p1679572113495029?thread_ts=1679569778.541529&cid=C9B1H0ACW).
=> fix(Button): fullWidth prop type was incorrectly set

packages/orbit-components/src/Alert/AlertButton/index.tsx
Reported [here](https://skypicker.slack.com/archives/CAMS40F7B/p1679666899559119).
The `children` prop was needed for padding calculation but was being captured and not passed to the function.
=> fix(AlertButton): padding was not correct when there was an icon

packages/orbit-components/src/Tabs/README.md
=> feat(docs): fix type of onChange prop of Tabs

packages/orbit-components/src/Modal/Modal.stories.tsx, packages/orbit-components/src/Modal/ModalFooter/__tests__/index.test.tsx, packages/orbit-components/src/Modal/ModalFooter/index.tsx, packages/orbit-components/src/Modal/__tests__/index.test.tsx
The issue is quite the same as we had before inside `Itinerary` when conditions were falsy and it was still counting it with `React.Children.count`, there are several ways how to fix it, filter the nodes with `React.isValidElement` and left `React.Children.count` or use `React.Children.toArray(children).length`
=> fix(ModalFooter): count children properly

docs/gatsby-node.ts, docs/package.json, docs/services/changelog.mjs, docs/services/checkLinks.ts, docs/src/data/log.md, scripts/publish.mjs, yarn.lock
[Slack request](https://skypicker.slack.com/archives/CAMS40F7B/p1680008830557049)
Instead of having it `onPreBuild` hook inside Gatsby, it makes sense to update it every time we are making a release and that's why moved it to our publish script.
=> docs: fix changelog

docs/src/__examples__/BadgeList/DEFAULT.tsx, packages/orbit-components/src/BadgeList/BadgeList.stories.tsx, packages/orbit-components/src/BadgeList/BadgeListItem/index.js.flow, packages/orbit-components/src/BadgeList/BadgeListItem/index.tsx, packages/orbit-components/src/BadgeList/BadgeListItem/types.d.ts, packages/orbit-components/src/BadgeList/README.md, packages/orbit-components/src/BadgeList/consts.ts
BadgeListItem now accepts size prop for changing the text size. Size can be small (default) or normal.
The icon wrapper size was also updated to match Figma's size. The Icon size is also off regarding Figma, but it seemed too small if figma size is applied, so no changes were made.
**Update:** as confirmed with designers, icon size is always the same and the `size` prop should be on the item, rather than on the parent wrapper component.
=> feat(BadgeListItem): add size prop

packages/orbit-components/package.json, packages/orbit-components/src/Toast/README.md, packages/orbit-components/src/Toast/Toast.stories.tsx, packages/orbit-components/src/Toast/ToastMessage.tsx, packages/orbit-components/src/Toast/ToastRoot.tsx, packages/orbit-components/src/Toast/__tests__/index.test.tsx, packages/orbit-components/src/Toast/index.js.flow, packages/orbit-components/src/Toast/index.tsx, packages/orbit-components/src/Toast/types.d.ts, yarn.lock
The icon was not rendered when the Toast was triggered by a promise.
There was also an infinite re-render problem, solved in this commit. The infinite re-render problem was caused by a workaround to a known issue on react-hot-toast that was fixed in the latest version. By upgrading, the workaround can be removed, removing the infinite re-render as well.
BREAKING CHANGE: the createToastPromise function now receives three arguments. The first two are required and similar to what was accepted before, except the icon. The third one is for handling the icon on different toast types. Check documentation for further details.
=> fix(Toast): icon on Promisse Toast was not rendered + infinite re-render fixed

docs/src/__examples__/Modal/FIXED_FOOTER.tsx, packages/orbit-components/src/ErrorForms.stories.tsx, packages/orbit-components/src/Modal/Modal.stories.tsx, packages/orbit-components/src/Modal/ModalFooter/index.tsx, packages/orbit-components/src/SkipLink/SkipLink.stories.tsx
BREAKING CHANGE: visual breaking change on ModalFooter. Flex-none is no longer applied on largeMobile and bigger. A layout component wrapper might be needed.
https://kiwicom.atlassian.net/browse/ORBIT-2711
This PR is opened against #3815 to avoid pipeline errors. It will be redirected to `master` once the other branch is merged
=> feat(Modal): remove flex-none from ModalFooter

.env.example, package.json, scripts/publish.mjs, yarn.lock
Updated `.env.example` to include vars for Slack API and tracking. 
Changed the changelog message a bit, since we are still posting only Orbit changes. 
Added `dry` option to preview changelog before release without posting the message to slack, github message and npm release
=> chore: improve publishing script

packages/orbit-components/src/Tabs/components/Tab/index.tsx
As requested [here](https://www.figma.com/file/t1UrPvmfjrRZGgLKhZwiSW?node-id=3090:12761#434710865), text should not wrap, but instead grow indefinitely.
=> feat(Tab): add min-width to avoid text wrap

docs/src/__examples__/Popover/DEFAULT.tsx, packages/orbit-components/src/Popover/Popover.stories.tsx, packages/orbit-components/src/Popover/README.md, packages/orbit-components/src/Popover/__tests__/index.test.tsx, packages/orbit-components/src/Popover/index.js.flow, packages/orbit-components/src/Popover/index.tsx, packages/orbit-components/src/Popover/types.d.ts
It was asked [here](https://skypicker.slack.com/archives/CAMS40F7B/p1683046391312509) and [here](https://skypicker.slack.com/archives/CAMS40F7B/p1677168767536869). 
In my opinion, we should not have that delay we had before, although, it looks like setTimeout here was also used for removing the flickering on the initial render. It works fine with 0, because of the nature of the event loop. So I decided to keep the hook, but reduce the timeout to 0, just to look it more visually faster. 
Added the prop to control that, if somebody still would need to have control, but I won't be useful much, just for case.
Also, do not think we should be 100% neat on that and mark it as breaking change. Can be as normal feature by mentioning that we just reduced the timeout.
=> feat(Popover): add renderTimeout prop

packages/orbit-components/src/Desktop/__tests__/index.test.tsx, packages/orbit-components/src/Hide/__tests__/index.test.tsx, packages/orbit-components/src/Hide/index.tsx, packages/orbit-components/src/Mobile/__tests__/index.test.tsx
Prop `on` was being propagated to the rendered DOM element It has been removed, as it is unintentional
=> fix(Hide): remove on prop from rendered element

packages/orbit-components/src/Itinerary/ItinerarySeparator/types.d.ts
Otherwise, TypeScript would report the following error:
```
Import declaration conflicts with local declaration of 'Props'.
```
=> fix(ItinerarySeparator): rename imported Props to avoid naming conflict

lint-staged.config.js, packages/orbit-components/tsconfig-build.json, tsconfig.base.json
We had `skipLibCheck` set even before full migration to TS and it's migrated after we fully migrated 😄 
`skipLibCheck` in tsconfig is a confusing name because it also skips the declarations files of the project.
I removed that option from the main base config, if necessary, we can explicitly set it to the package's configs or docs, but for components, we need to have it removed, if errors will appear with some library, I think we can ignore them explicitly.
=> chore: remove skipLibCheck from ts and add ts-check to lint-staged

docs/src/documentation/03-components/01-action/button/01-guidelines.mdx, docs/src/documentation/03-components/03-information/alert/01-guidelines.mdx
The [Component Structure image](https://orbit.kiwi/components/action/button/#component-structure) on the Button docs page was showing the image for the Alert component. This weird behavior happens for an even more weird reason: we were giving the same name to the imported image on both the Alert and Button files. Renaming them to unique names seems to solve the problem.
=> docs: fix WebStructureImages by renaming them

docs/src/__examples__/Box/DEFAULT.tsx, docs/src/__examples__/Text/ALIGN.tsx, docs/src/__examples__/Text/DEFAULT.tsx, packages/orbit-components/src/Box/Box.stories.tsx, packages/orbit-components/src/Box/README.md, packages/orbit-components/src/Box/index.js.flow, packages/orbit-components/src/Box/types.d.ts, packages/orbit-components/src/Table/TableCell/consts.ts, packages/orbit-components/src/Table/TableCell/index.js.flow, packages/orbit-components/src/Table/TableCell/types.d.ts, packages/orbit-components/src/Text/README.md, packages/orbit-components/src/Text/consts.ts, packages/orbit-components/src/Text/index.js.flow, packages/orbit-components/src/Text/types.d.ts, packages/orbit-components/src/utils/rtl/index.js.flow, packages/orbit-components/src/utils/rtl/index.ts, packages/orbit-components/src/utils/rtl/types.d.ts
The utility functions for text alignment `left` and `right` in `packages/orbit-components/src/utils/rtl/index.ts` have their native versions directly in css -- "start" and "end". I think it would be nice if we could use those directly. Since this looked simple, I decided to shoot a MR, but if I missed some nontrivial things, feel free to take this MR as just a feature request 😄
=> Allow "start" and "end" align, deprecate rtl/textAlign

packages/orbit-components/config/build/buildIcons.mts, packages/orbit-components/config/build/buildSize.mts, packages/orbit-components/config/build/compileSource.mts, packages/orbit-components/config/build/consts.mts, packages/orbit-components/config/build/generateDeclarations.mts, packages/orbit-components/config/build/index.mts, packages/orbit-components/config/checkIcons.mts, packages/orbit-components/config/checkIconsCli.mts, packages/orbit-components/config/createSVGFont.mts, packages/orbit-components/config/typeFiles.mts, packages/orbit-components/tsconfig-build.json
This is caused by internal component (rtl/RenderInRtl) that we use inside stories, no need for that to be in the bundle 
Also removed the ts suppressions inside build files
=> chore: exclude RenderInRtl from build

packages/orbit-components/src/Select/index.tsx, packages/orbit-components/src/Select/types.d.ts, packages/orbit-components/src/SkipNavigation/index.tsx, packages/orbit-components/src/SkipNavigation/types.d.ts
Reported [here](https://skypicker.slack.com/archives/CAMS40F7B/p1685526457132239).
During the inlineLabel and size refactoring of Select, this bug was introduced. The condition for prefix is no longer needed because of the way the customValueText is rendered
[ORBIT-2767](https://kiwicom.atlassian.net/browse/ORBIT-2767)
=> fix(Select): fixed spacing between prefix and customValueText

packages/orbit-components/src/Modal/ModalFooter/__tests__/index.test.tsx, packages/orbit-components/src/Modal/ModalFooter/index.tsx
Getting back accidentally removed condition for checking if children element is array or not. 
[Slack request](https://skypicker.slack.com/archives/C9B1H0ACW/p1686053579542679)
=> fix(ModalFooter): wrap elements in StyledChild only when multiple

packages/orbit-components/src/Select/README.md, packages/orbit-components/src/Select/index.tsx
This fixes what was reported [in Slack](https://skypicker.slack.com/archives/CAMS40F7B/p1685526457132239), regarding not being able to open the Select by clicking the Prefix.
This also addresses an issue with the disabled style that was spotted during the implementation of this task.
This is also waiting on a design decision about truncating the inlineLabel when it is too large. However, I feel that can be added later to unblock these bugs.
[ORBIT-2768](https://kiwicom.atlassian.net/browse/ORBIT-2768)
=> Fix Select prefix and disabled styles issues

packages/orbit-components/src/InputField/index.tsx
This was introduced in #3851. The commit can be a chore because the bug was actually never released, so no need to mention it on the changelog 🙂
=> chore: allow InputField to accept tabIndex=0

packages/orbit-components/src/HorizontalScroll/index.tsx
Reported [here](https://skypicker.slack.com/archives/CAMS40F7B/p1686735217397959)
=> fix(HorizontalScroll): arrows now only display if it's overflowing

packages/orbit-components/src/Itinerary/ItinerarySegment/ItinerarySegmentBanner/index.tsx
Reported [here](https://skypicker.slack.com/archives/CAMS40F7B/p1686830163608249). Instead of inheriting the `cursor` property from the `ItinerarySegment`, the `ItinerarySegmentBanner` now applies the correct cursor based on whether or not they have an `onClick` defined.
=> fix(Itinerary): correct cursor is now applied to ItinerarySegmentBanner

packages/orbit-components/src/InputSelect/InputSelect.stories.tsx, packages/orbit-components/src/InputSelect/InputSelect.styled.ts, packages/orbit-components/src/InputSelect/InputSelectOption/index.tsx, packages/orbit-components/src/InputSelect/README.md, packages/orbit-components/src/InputSelect/index.js.flow, packages/orbit-components/src/InputSelect/index.tsx, packages/orbit-components/src/InputSelect/types.d.ts, packages/orbit-components/src/ListChoice/index.tsx
Reported [here](https://skypicker.slack.com/archives/CAMS40F7B/p1687446287291309).
The Option of InputSelect now supports a prefix. Added a missing `z-index` property to the Dropdown. And center aligned the icon of the ListChoice, since it can now receive other things from the InputSelect (flags were misaligned, for instance)
=> feat/Add prefix to InputSelect Option

packages/orbit-components/src/Slider/Slider.stories.tsx, packages/orbit-components/src/Slider/index.tsx, packages/orbit-components/src/Slider/utils/index.ts
defaultValue comparison was not being made correctly. Therefore, it was triggering a state update all the time, overcoming the actual value update from the user's interaction.
**Update:** During inspection with Search, another bug was noticed, that was actually present even before this branch was created. So it was impossible to slide over the currently selected value. This was fixed by removing the verifications of new values, which, from my understanding, were legacy to the older implementation without hooks. But review is appreciated 🙏 
Reported [here](https://skypicker.slack.com/archives/CAMS40F7B/p1687859299240369).
=> fix(Slider): range Slider was not updating correctly

packages/orbit-components/src/Illustration/README.md, packages/orbit-components/src/Illustration/consts.mts, packages/orbit-components/src/Illustration/index.js.flow, packages/orbit-components/src/Illustration/types.d.ts
Adds the NoFlightChange illustration.
Still waiting for deploy and upload on the internal repository.
=> feat(Illustration): add NoFlightChange illustration

packages/orbit-components/src/TextLink/index.tsx
Type secondary should have predominance over Alert type.
[ORBIT-2837](https://kiwicom.atlassian.net/browse/ORBIT-2837)
**Before:**
**Now:**
```jsx
<Alert>
<TextLink type="secondary">blue</TextLink>
</Alert>
```
=> fix(TextLink): allow secondary type inside Alert

packages/orbit-components/src/CountryFlag/__tests__/index.test.tsx, packages/orbit-design-tokens/output/docs-tokens.json, packages/orbit-design-tokens/output/tokens.css, packages/orbit-design-tokens/output/tokens.less, packages/orbit-design-tokens/output/tokens.scss, packages/orbit-design-tokens/output/tokens.styl, packages/orbit-design-tokens/output/tokens.xml, packages/orbit-design-tokens/src/__tests__/__snapshots__/index.test.ts.snap, packages/orbit-design-tokens/src/dictionary/definitions/component/icon/icon-size.json, packages/orbit-design-tokens/src/js/createTokens.ts
The token `widthCountryFlag` changed from 24px to 20px during the Styled Dictionary / Tailwind migration, unexpectedly.
The token is being used to get the src from images.kiwi and the test is only asserting that the src URL contains the correct country code, it does not assert the width, that is also part of the URL. So it silently broke.
This PR improves the test and fixes the token value.
[FEPLT-1627](https://kiwicom.atlassian.net/browse/FEPLT-1627)
=> Fix country flag width token

packages/orbit-components/src/InputSelect/__tests__/index.test.tsx, packages/orbit-components/src/InputSelect/index.tsx
This feature was missing from the previous batch of fixes/features introduced.
InputSelect now clears any selected option if the text field is cleared.
=> fix(InputSelect): clearing the input now clears the selected option

packages/orbit-components/src/ServiceLogo/__tests__/index.test.tsx, packages/orbit-design-tokens/output/docs-tokens.json, packages/orbit-design-tokens/output/tokens.css, packages/orbit-design-tokens/output/tokens.less, packages/orbit-design-tokens/output/tokens.scss, packages/orbit-design-tokens/output/tokens.styl, packages/orbit-design-tokens/output/tokens.xml, packages/orbit-design-tokens/src/__tests__/__snapshots__/index.test.ts.snap, packages/orbit-design-tokens/src/dictionary/definitions/component/icon/icon-size.json, packages/orbit-design-tokens/src/js/createTokens.ts
The token `heightServiceLogoMedium` changed from 24px to 20px during the Styled Dictionary / Tailwind migration, unexpectedly.
The token is being used to get the src from images.kiwi and the test is only asserting that the src URL contains the correct country code, it does not assert the width, that is also part of the URL. So it silently broke.
This PR improves the test and fixes the token value.
=> Fix ServiceLogo height token

docs/src/components/DesignTokensList/components/DesignTokenName.tsx, docs/src/components/TailwindClassnames/index.tsx
Small 💅 the tailwind classnames list was mistakenly mentioning tokens, instead of classnames. This PR fixes that.
Storybook: https://orbit-mainframev-docs-fix-tw-classnames-tooltip-text.surge.sh
=> docs: adjust tailwind classnames tooltip text

docs/src/documentation/05-development/03-hooks/useclickoutside.mdx, docs/src/documentation/05-development/04-migration-guides/v9.mdx, packages/orbit-components/src/hooks/useClickOutside/README.md, packages/orbit-components/src/hooks/useRandomId/README.md
Adds documentation for `useClickOutside` hook and completes the v9 migration guide.
This PR is opened against the branch that started the v9 migration guide. Base branch will change after #3950 is merged.
Storybook: https://orbit-mainframev-v9-migration-guide.surge.sh
=> V9 migration guide + useClickOutside docs

docs/src/__examples__/Theme/default.tsx, docs/src/components/__tests__/TableOfContents.test.tsx, docs/src/documentation/02-foundation/10-typography/02-circular-pro.mdx, docs/src/documentation/05-development/03-hooks/useclickoutside.mdx, docs/src/documentation/05-development/04-migration-guides/v9.mdx, docs/src/pages/examples/{Example.id}.tsx, docs/src/pages/playground-full.tsx, docs/wrapWithProviders.tsx, packages/orbit-components/package.json, packages/orbit-components/src/OrbitProvider/RandomId/Provider.tsx, packages/orbit-components/src/OrbitProvider/ThemeProvider.stories.tsx, packages/orbit-components/src/OrbitProvider/index.tsx, packages/orbit-components/src/OrbitProvider/types.d.ts, packages/orbit-components/src/hooks/useClickOutside/README.md, packages/orbit-components/src/hooks/useLockScrolling/__tests__/index.test.tsx, packages/orbit-components/src/hooks/useMediaQuery/__tests__/index.test.tsx, packages/orbit-components/src/hooks/useRandomId/README.md, packages/orbit-components/src/hooks/useRandomId/__tests__/index.test.tsx, packages/orbit-components/src/hooks/useRandomId/index.ts, packages/orbit-components/src/utils/rtl/RenderInRtl.tsx, packages/orbit-themer/src/App.tsx, yarn.lock
This is to allow for React 17/18 compatibility, with additional steps required for React 17 compat.
BREAKING CHANGE: Message to be amended
---
This is a proposal to use dependency injection and allow for React 17 compat while updating Orbit to React 18 primitives like useId.
Storybook: https://orbit-mainframev-rcsl-abstract-react-uid.surge.sh
=> feat: abstract away react-uid and remove it from deps

packages/orbit-components/cypress/integration/index.tsx, packages/orbit-components/cypress/integration/pages/heading-media-query-props.tsx, packages/orbit-components/cypress/integration/pages/heading-media-query.test.ts, packages/orbit-components/src/Alert/index.tsx, packages/orbit-components/src/Heading/__tests__/index.test.tsx, packages/orbit-components/src/Heading/index.js.flow, packages/orbit-components/src/Heading/index.tsx, packages/orbit-components/src/Heading/twClasses.ts, packages/orbit-components/src/Modal/ModalHeader/index.tsx, packages/orbit-components/src/Truncate/index.tsx
Heading component migrated to Tailwind.
Tests are relying on styles (recommended) but also on classes (unrecommended) for the media queries, until a better solution is found.
Storybook: https://orbit-mainframev-migrate-Heading-tailwind.surge.sh
=> Migrate Heading to tailwind

packages/orbit-components/src/Stack/Stack.stories.tsx, packages/orbit-components/src/Stack/index.tsx, packages/orbit-components/src/common/tailwind/spacing.ts, packages/orbit-components/src/utils/mediaQuery/consts.ts
There were two problems that caused those issues reported by Marco: 
- inline just had wrong condition instead of checking it to false it was applying full-width when inline is true.
- the other problem was a bit more complex and I just reused Search solution with having getProperty function, otherwise spacing and directions are not working correctly with media query properites 
Storybook: https://orbit-mainframev-fix-stack-issue.surge.sh
=> chore(Stack): fix stack issues after refactoring to Tailwind

packages/orbit-components/src/Radio/index.tsx
Adding conditio to Glyph background in order to show visible indication of checked state and disabled state together
Storybook: https://orbit-mainframev-fix-radio-disabled-check.surge.sh
=> fix(Radio): add visibile indication of checked state when disabled

.github/CONTRIBUTING.md
Just quickly added a few sentences about how to add tokens. Might be useful to have it in contributing guidelines if someone will struggle with adding new tokens, it refers to SCHEMA file and add basic info about how to add them.
Storybook: https://orbit-mainframev-docs-extend-contribution-guidelines.surge.sh
=> docs: extend contributing.md about tokens addition

packages/orbit-components/src/Drawer/__tests__/index.test.tsx, packages/orbit-components/src/Wizard/__tests__/compact.test.tsx
This commit was originally in #3942 because it was thought to be cause by loading Tailwind CSS into the test environment. However, the latest pipeline run failed because of the same problem, so we are including it in master now.
Storybook: https://orbit-mainframev-fix-test-timeout.surge.sh
=> chore: fix test timeout

packages/orbit-components/package.json, packages/orbit-components/src/OrbitProvider/index.tsx, packages/orbit-components/tailwind.config.ts
This PR addresses three things:
- The typo in the tailwind.config.ts inside `orbit-components`
- ~The brokens examples caused by #3979 because OrbitProvider expects a single child~ This was replaced by allowing OrbitProvider to receive multiple children
- The tailwind config does not include pre-flight for testing 
With this, there are possible future work:
- Type checks should run for the tailwind.config files as well
- ~The type of prop `children` on `OrbitProvider` should ensure it only gets a single child.~
Storybook: https://orbit-mainframev-fix-tw-config-and-docs.surge.sh
=> Fix Tailwind config and OrbitProvider children

packages/orbit-components/src/Wizard/index.tsx
If `labelProgress` is not defined, the `<b>` spacing was still being rendered, causing the title to be misaligned.
Before:
After:
Storybook: https://orbit-mainframev-fix-wizard-label-render.surge.sh
=> fix(Wizard): title now renders correctly even without labelProgress

packages/orbit-components/src/Text/Text.stories.tsx, packages/orbit-components/src/Text/__tests__/index.test.tsx, packages/orbit-components/src/Text/index.tsx
With Tailwind, default value can't be `left`, but should be `start`, so that it is correctly aligned in RTL.
Storybook: https://orbit-mainframev-fix-text-alignment-default.surge.sh
=> fix(Text): default value for align is now start

docs/src/documentation/05-development/04-migration-guides/v9.mdx
This Pull Request aims to fix the migration guide for orbit-components@v9.
In the current docs, it's suggested to use `useRandomId` but this hook is not part of `react-uid` package.
While in the component description, it is correctly stated to use `useUID` instead. 
https://github.com/kiwicom/orbit/blob/015f84a9a74f0b5f05de30f4b747158d1126b249/packages/orbit-components/src/OrbitProvider/index.tsx#L12-L21
=> docs: use correct hook in react@17 example

packages/orbit-components/src/Card/components/Header/index.tsx
As reported [here](https://skypicker.slack.com/archives/C7T7QG7M5/p1693468169219649), actions should always be vertically center aligned.
@oreqizer consider this change on the TW migration as well 🙏 
Storybook: https://orbit-mainframev-fix-card-actions-alignment.surge.sh
=> fix(Card): header actions are now vertically center aligned

packages/orbit-components/src/Stack/Stack.stories.tsx
While reviewing some Stack code, I noticed that our docs look… odd. This fixes the alignment in our stories.
**Before:**
**Now:**
Storybook: https://orbit-mainframev-docs-fix-stack-story-align.surge.sh
=> docs: fix Stack story default alignment

packages/orbit-components/src/Alert/Alert.stories.tsx, packages/orbit-components/src/Alert/index.tsx, packages/orbit-components/src/TextLink/deprecated/index.ts, packages/orbit-components/src/TextLink/index.tsx
A TextLink inside an Alert should have different styles, based on its own type and also the Alert's type. With TW migration that logic was lost. This gets it back.
Storybook: https://orbit-mainframev-adjust-textlink-alert-styles.surge.sh
=> Adjust TextLink + Alert styles

packages/orbit-tracking/package.json, packages/orbit-tracking/src/react-scanner.config.ts, yarn.lock
Our data for September was corrupted because of the slightly wrong glob pattern, it was collecting a much smaller amount (as only js files). Also included a new version of our fork of react-scanner, that includes an update to node >= 18 and a fix that throws warnings instead of exceptions, if the script fails to parse a file (happens on a couple of files on Balkan that do not include Orbit components) 
Storybook: https://orbit-mainframev-chore-fix-glob-tracking.surge.sh
=> chore(tracking): fix the glob pattern and update react-scanner

.github/workflows/publish.yml, packages/orbit-tailwind-preset/package.json
- ensure building packages in the right order
- prevent lerna from running prepublish script
Storybook: https://orbit-mainframev-marco-publish-build.surge.sh
=> ci: add build step to publish workflow

.github/workflows/test.yml
General job was executing 3 types os checks. They all now have their own job each.
Also removed the TODO as we _should_ run the pipeline for every PR. We can just have less restrict required checks on non-master PRs, but that can be configured somewhere else 
After this is approved and before is merged, I will change the required checks on the branch rules to reflect the new jobs.
**Time changes** (compared with [the latest run](https://github.com/kiwicom/orbit/actions/runs/6237496256)):
| Scenario | Test workflow time (excluding Cypress and Docs) | Jobs duration |
|---|---|---|
| This branch | 8m 50s | Types (4m 37s), Lint (8m 50s), Unit (8m 5s) |
| Before | 15m 59s | General (15m 59s) |
Not only we can detect failures earlier (if a test fails, we don't have to wait for types and lint to …
=> chore: split general checks into multiple jobs

docs/src/data/log.md, packages/babel-plugin-orbit-components/CHANGELOG.md, packages/babel-plugin-orbit-components/package.json, packages/orbit-components/CHANGELOG.md, packages/orbit-components/package.json
- @kiwicom/babel-plugin-orbit-components@4.2.4
- @kiwicom/orbit-components@9.3.1
---
Published bug fix for @kiwicom/orbit-components@9.3.1 manually
* npm done
* GitHub releases done
To make sure the versioning (and changelogs) are correct in `master` branch, cherry-picking the release commit here.
The actual fix wouldn't be seen anymore in `master` branch since the component was already migrated to Tailwind, hence no real point in re-writing history. The tag should be enough.
Storybook: https://orbit-mainframev-rcsl-fix-changelog.surge.sh
=> chore: publish

.github/contribution/testing-conventions.md, docs/src/components/ComponentStructure/__tests__/index.test.tsx, packages/orbit-components/src/Card/__tests__/index.test.tsx, packages/orbit-components/src/Collapse/__tests__/index.test.tsx, packages/orbit-components/src/ErrorFormTooltip/__tests__/index.test.tsx, packages/orbit-components/src/InputField/__tests__/index.test.tsx, packages/orbit-components/src/InputFile/__tests__/index.test.tsx, packages/orbit-components/src/InputGroup/__tests__/index.test.tsx, packages/orbit-components/src/InputSelect/__tests__/index.test.tsx, packages/orbit-components/src/Popover/__tests__/index.test.tsx, packages/orbit-components/src/SegmentedSwitch/__tests__/index.test.tsx, packages/orbit-components/src/Select/__tests__/Select.test.tsx, packages/orbit-components/src/SkipNavigation/__tests__/index.test.tsx, packages/orbit-components/src/Slider/__tests__/index.test.tsx, packages/orbit-components/src/Tabs/__tests__/index.test.tsx, packages/orbit-components/src/Textarea/__tests__/index.test.tsx, packages/orbit-components/src/Toast/__tests__/index.test.tsx, packages/orbit-components/src/Tooltip/__tests__/index.test.tsx, packages/orbit-components/src/Tooltip/__tests__/mobile.test.tsx, packages/orbit-components/src/Wizard/__tests__/compact.test.tsx, packages/orbit-components/src/Wizard/__tests__/loose.test.tsx, packages/orbit-components/src/hooks/useTransition/__tests__/index.test.tsx, packages/orbit-components/src/primitives/MobileDialogPrimitive/__tests__/index.test.tsx, packages/orbit-components/src/primitives/TooltipPrimitive/__tests__/index.test.tsx
Having an act wrapper for user event actions seems a redundant thing to have, tests are working fine without 
We also started to receive warnings about the wrong usage of the act and [I later found this comment](https://github.com/testing-library/react-testing-library/issues/1061#issuecomment-1419824786)
Storybook: https://orbit-mainframev-chore-fix-test-suits.surge.sh
=> test: remove act wrappers for user event actions

scripts/post-changelog.mjs
By default they were sorted by semver
Closes [FEPLT-1761](https://kiwicom.atlassian.net/browse/FEPLT-1761)
Storybook: https://orbit-mainframev-marco-fix-changelog-most-recent-tag.surge.sh
=> ci: fix changelog script to sort tags by creation date

packages/orbit-components/src/ErrorFormTooltip/Tooltip/index.tsx
During TW migration, one positioning class was missing the RTL selector.
Before:
Now:
Storybook: https://orbit-mainframev-fix-error-form-tooltip-arrow-position.surge.sh
=> fix(ErrorFormTooltip): arrow was misplaced

packages/orbit-components/src/primitives/MobileDialogPrimitive/components/DialogContent.tsx
[Reported on Slack](https://skypicker.slack.com/archives/C7T7QG7M5/p1696338848003649)
Storybook: https://orbit-mainframev-fix-tooltip-overflow.surge.sh
=> fix(Dialog): hide scroll bar, but keep scrolling behaviour

packages/orbit-components/src/tmp-tailwind/Switch/Switch.stories.tsx, packages/orbit-components/src/tmp-tailwind/Switch/__tests__/index.test.tsx, packages/orbit-components/src/tmp-tailwind/Switch/index.tsx, packages/orbit-tailwind-preset/src/presets/__tests__/__snapshots__/configs.test.ts.snap, packages/orbit-tailwind-preset/src/presets/components/index.ts
For height and width values I decided not to use tokens because tokens are associated with spacing and those size values are very much independent from any spacing scale.
Storybook: https://orbit-mainframev-tw-switch.surge.sh
=> migrate Switch to Tailwind

packages/orbit-components/src/Itinerary/Itinerary.stories.tsx, packages/orbit-components/src/Itinerary/ItinerarySegment/ItinerarySegmentDetail/index.tsx
[Reported in Slack](https://skypicker.slack.com/archives/C7T7QG7M5/p1695212720944469)
I tested that on Booking directly by applying the calc logic
Storybook: https://orbit-mainframev-fix-itinerary-details.surge.sh
=> fix(ItinerarySegmentDetail): fix overflowing content issue

docs/src/pages/playground.tsx
As we already have multiple requests about clearing the local storage in playground, adding that feature there too, as in the examples. 
Storybook: https://orbit-mainframev-docs-add-refresh-button.surge.sh
=> docs: add restore to default button to playground

packages/orbit-tailwind-preset/README.md
The code snippet for the tailwind.config.js file is expanded to account for monorepo setups where the Orbit components node module might be hoisted elsewhere.
Relates to [FEPLT-1777](https://kiwicom.atlassian.net/browse/FEPLT-1777)
Storybook: https://orbit-mainframev-rcsl-expand-orbit-preset-docs.surge.sh
[FEPLT-1777]: https://kiwicom.atlassian.net/browse/FEPLT-1777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FEPLT-1777: chore(tailwind): make setup instructions more robust

docs/src/__examples__/Illustration/DEFAULT.tsx, packages/orbit-components/src/Illustration/README.md, packages/orbit-components/src/Illustration/consts.mts, packages/orbit-components/src/Illustration/index.js.flow, packages/orbit-components/src/Illustration/types.d.ts
Adding a new Illustration called FlightDisruptions
Storybook: https://orbit-mainframev-add-flight-disruption-illustration.surge.sh
=> feat(Illustration): add FlightDisruptions illustration

docs/src/documentation/05-development/04-migration-guides/03-v10.mdx, packages/orbit-tailwind-preset/README.md
Storybook: https://orbit-mainframev-rcsl-font-instructions.surge.sh
=> docs: add instructions to customize font family for TW

packages/orbit-components/src/Tile/Tile.stories.tsx, packages/orbit-components/src/Tile/__tests__/index.test.tsx, packages/orbit-components/src/Tile/components/TileContent/index.tsx, packages/orbit-components/src/Tile/components/TileHeader/index.js.flow, packages/orbit-components/src/Tile/components/TileHeader/index.tsx, packages/orbit-components/src/Tile/components/TileWrapper/index.js.flow, packages/orbit-components/src/Tile/components/TileWrapper/index.tsx, packages/orbit-components/src/TileGroup/index.tsx
https://kiwicom.atlassian.net/browse/FEPLT-1701
Storybook: https://orbit-mainframev-oreqizer-tw-tile.surge.sh
Chromatic visual test: https://www.chromatic.com/build?appId=6523bafdbc6087c220b3cc48&number=148
=> Migrate Tile to Tailwind

packages/orbit-components/src/Stack/index.tsx
On #4071 we started to verify a condition on viewport properties that should not be required. The condition is now only required for the classes that it actually affects.
Commit is labeled as a chore as this is a fix to an unreleased bug.
Storybook: https://orbit-mainframev-fix-stack-viewports.surge.sh
=> Stack: Fix classes not applied in viewports

packages/orbit-components/src/InputSelect/InputSelect.styled.ts
Fixes a bug in FF & Safari for `<InputSelect>` where the child widths collapse as <label> is usually inline.
When focusing on the input element of the `<InputSelect>` component, the list of options isn't clearly visible to users of: Firefox (MacOS & Windows) and Safari (MacOS) while the viewport is is >576px. I think the cause was due to the top level  <label> being inline so it's children were collapsing.
=> fix(InputSelect): make root label block

packages/orbit-components/src/Separator/Separator.stories.tsx
it's needed for #4125 
Storybook: https://orbit-mainframev-test-add-visual-test-separator.surge.sh
=> test(Separator): add visual test

docs/src/data/tailwind-migration-status.yaml, packages/orbit-components/src/ButtonMobileStore/ButtonMobileStore.stories.tsx, packages/orbit-components/src/ButtonMobileStore/__tests__/index.test.tsx, packages/orbit-components/src/ButtonMobileStore/consts.ts, packages/orbit-components/src/ButtonMobileStore/index.tsx
FEPLT-1717
- [ ] Visual regression test suite has been run after the PR approval and no visual changes were identified. **— will be executed and accepted after approve, to include the new version**
The updated visual tests were not executed prior to the migration because the component migration is extremely simple.
Storybook: https://orbit-mainframev-tw-button-mobile-store.surge.sh
=> ButtonMobileStore: migrate to Tailwind

packages/orbit-components/src/Card/index.tsx
Quick bug fix for the Card component. Before by default was full width on main wrapper. It should always take 100% width of a parent container, so it has to be by default *width: 100%*, to avoid issues when it's used inside other components like Modal, Stack and etc. 
[Slack report
](https://skypicker.slack.com/archives/C7T7QG7M5/p1699448442326269)
=> fix(Card): add missing w-full

packages/orbit-components/src/TextLink/helpers/twClasses.ts
Noticed, that we do not have a line height for TextLink. We have to check other components as well. Preflight is affecting the line-height. [Slack thread](https://skypicker.slack.com/archives/C05FDP4UM3N/p1699352169104469). [Resolves FEPLT-1800](https://kiwicom.atlassian.net/browse/FEPLT-1800)
Storybook: https://orbit-mainframev-fix-text-link-line-height.surge.sh
=> fix(TextLink): add missing line-height

packages/orbit-tailwind-preset/README.md
Update Readme.md of talwind-preset with a warning . Relevant thread: https://skypicker.slack.com/archives/C7T7QG7M5/p1699019615348309
Closes [FEPLT-1795](https://kiwicom.atlassian.net/browse/FEPLT-1795)
Storybook: https://orbit-mainframev-alexandrahavlikova-readme-tailwind-preset.surge.sh
[FEPLT-1795]: https://kiwicom.atlassian.net/browse/FEPLT-1795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add tailwind preflight disabling warning

packages/orbit-components/src/Card/CardSection/CardSection.ct-story.tsx, packages/orbit-components/src/Card/CardSection/CardSection.ct.tsx, packages/orbit-components/src/Card/CardSection/index.tsx
https://skypicker.slack.com/archives/C7T7QG7M5/p1699604167098469
Storybook: https://orbit-mainframev-oreqizer-fix-card-interaction.surge.sh
=> fix(Card): only capture keys on expandable sections

docs/src/data/tailwind-migration-status.yaml, packages/orbit-components/src/ChoiceGroup/README.md, packages/orbit-components/src/ChoiceGroup/components/Feedback.js.flow, packages/orbit-components/src/ChoiceGroup/components/Feedback.tsx, packages/orbit-components/src/ChoiceGroup/components/FilterWrapper.tsx, packages/orbit-components/src/ChoiceGroup/index.tsx
Closes FEPLT-1707
Storybook: https://orbit-mainframev-tw-choice-group.surge.sh
=> feat(ChoiceGroup): migrate to Tailwind

packages/orbit-components/package.json
This should finally fix [this issue](https://skypicker.slack.com/archives/C7T7QG7M5/p1699626858575329). Although the output is different than with `loose: false`, it still should fix it, since class properties defined in [the constructor](https://stackoverflow.com/questions/60026651/safari-unexpected-token-expected-an-opening-before-a-methods-paramet)
the screenshots of output (after vs before) 
Storybook: https://orbit-mainframev-fix-browser-support.surge.sh
=> fix: update browserlist in package.json

packages/orbit-components/src/InputField/InputTags/index.tsx
There was a typo on the class
Storybook: https://orbit-mainframev-inputfield-tags-fix.surge.sh
=> Fix whitespace class in InputTags

packages/orbit-components/src/InputField/InputTags/index.tsx
The `rtl:space-x-reverse` class was missing so that spacing is correctly applied on RTL
Storybook: https://orbit-mainframev-input-field-missing-rtl-spacing-class.surge.sh
=> Add space-x-reverse class for rtl in InputTag

docs/src/data/log.md, packages/orbit-components/CHANGELOG.md
The usage of `<select>` (as text) was [breaking the Gatsby build](https://github.com/kiwicom/orbit/actions/runs/6892312173/job/18749293540). This changes to not include the brackets `<>`.
Storybook: https://orbit-mainframev-fix-changelog-11-0-0.surge.sh
=> chore: fix changelog for 11.0.0

packages/orbit-components/src/Itinerary/ItinerarySegment/ItinerarySegmentDetail/types.d.ts, packages/orbit-components/src/Itinerary/README.md
Updates the docs of ItinerarySegmentDetail to match the implementation.
N/A
N/A
Storybook: https://orbit-mainframev-jozef-itinerary-segment-detail-docs.surge.sh
=> docs(Itinerary): the content prop

packages/orbit-components/src/Hide/__tests__/index.test.tsx, packages/orbit-components/src/Hide/index.tsx, packages/orbit-components/src/Modal/ModalFooter/index.tsx, packages/orbit-components/src/deprecated/Desktop/__tests__/index.test.tsx, packages/orbit-components/src/deprecated/Mobile/__tests__/index.test.tsx, packages/orbit-tailwind-preset/src/presets/__tests__/__snapshots__/configs.test.ts.snap, packages/orbit-tailwind-preset/src/presets/components/index.ts
Fixes reported issue [FEPLT-1819](https://kiwicom.atlassian.net/browse/FEPLT-1819)
[FEPLT-1819]: https://kiwicom.atlassian.net/browse/FEPLT-1819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Storybook: https://orbit-mainframev-fix-hide-and-screens-issue.surge.sh
=> fix(Hide): use native tailwind breakpoint range classes

packages/orbit-components/tsconfig.json
Noticed ts warnings inside stories, and added `jsx: react` to tsconfig to remove them, this does not affect the build, so it's safe and just for removing the warning. 
Storybook: https://orbit-mainframev-chore-ts-add-jsx.surge.sh
=> chore: add jsx react to tsconfig

packages/orbit-components/src/Breadcrumbs/index.tsx
I highly recommend setting `noImplicitAny` to true in tsconfig. It would have prevented this error. (I'm certainly turning it on in fe/mmb bc wtf :D )
N/A
N/A
=> fix(Breadcrumbs): the spaceAfter prop

docs/plugins/contributors/fetchedUsers.json
- Automatically generated PR on 2023-11-24.
- Updates contributors for docs
Storybook: https://orbit-mainframev-docs-update-contributors.surge.sh
=> chore: update contributors

packages/orbit-components/src/Popover/index.tsx
Some folks haven't migrated to React 18 yet, so we must continue to use our useRandomId hook instead of React.useId directly.
Slack: https://skypicker.slack.com/archives/C7T7QG7M5/p1700834303233829
- [ ] Visual regression test suite has been added and run before the migration.
- [ ] `tailwind-migration-status.yaml` file has been updated with the migrated component(s).
Storybook: https://orbit-mainframev-rcsl-fix-popover-use-id.surge.sh
=> fix(Popover): use useRandomId hook instead of React.useId directly

packages/orbit-components/src/Layout/index.tsx
https://kiwicom.atlassian.net/browse/FEPLT-1831
Storybook: https://orbit-mainframev-oreqizer-remove-layoutprop.surge.sh
=> Remove accidental props pass from Layout to Grid

packages/orbit-components/src/Popover/__tests__/index.test.tsx, packages/orbit-components/src/Popover/components/ContentWrapper.tsx, packages/orbit-components/src/hooks/useClickOutside/index.ts
The outside click hook was triggering the close before the event was captured by interactable components. This was changed just for the Popover, so no breaking behavior should occur.
[FEPLT-1841](https://kiwicom.atlassian.net/browse/FEPLT-1841)
[FEPLT-1841]: https://kiwicom.atlassian.net/browse/FEPLT-1841?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Storybook: https://orbit-mainframev-fix-clik-outside-popup-with-link.surge.sh
=> fix(Popover): links inside tooltips inside content are now clickable

packages/orbit-components/src/Timeline/README.md, packages/orbit-components/src/Timeline/Timeline.stories.tsx, packages/orbit-components/src/Timeline/TimelineStep/components/TimelineStepDesktop.tsx, packages/orbit-components/src/Timeline/TimelineStep/components/TimelineStepMobile.tsx, packages/orbit-components/src/Timeline/TimelineStep/index.js.flow, packages/orbit-components/src/Timeline/TimelineStep/primitives/StyledText.ts, packages/orbit-components/src/Timeline/TimelineStep/types.d.ts
Recently we got several requests regarding `Timeline`. They are quite small, so I resolved all of them in a single PR 
This PR gives a solution to these requests: 
- redundant margins in `TimelineStep` with `spaceAfter` prop, removed for Desktop, for Mobile only the last one.  ([request](https://skypicker.slack.com/archives/C7T7QG7M5/p1699366523532359))
- optional children in `TimelineStep` ([request](https://skypicker.slack.com/archives/C7T7QG7M5/p1700837336908099),  [FEPLT-1840](https://kiwicom.atlassian.net/browse/FEPLT-1840)) 
- height issue with desktop `Timeline`, when there are no one or more `subLabel` props ([request](https://skypicker.slack.com/archives/C7T7QG7M5/p1701691187175999)) 
[FEPLT-1840]: https://kiwicom.atlassian.net/browse/FEPLT-1840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …
=> Timeline: fixing multiple requests

docs/src/documentation/03-components/12-layout/layout/01-guidelines.mdx, docs/src/documentation/03-components/13-responsive/hide/01-guidelines.mdx, docs/src/documentation/03-components/14-utility/truncate/01-guidelines.mdx, packages/orbit-components/src/Hide/__tests__/index.test.tsx, packages/orbit-components/src/Hide/index.tsx, packages/orbit-components/src/deprecated/Desktop/__tests__/index.test.tsx
"smallMobile" is the smallest screen size that Orbit recognizes. It ought to hide everything for screens of size 0px - 413px.
The alternative would be to add a new screen size smaller than "smallMobile".
Also removes deprecated components Desktop and Mobile from docs
Storybook: https://orbit-mainframev-jozef-hide-small-mobile.surge.sh
=> Make "smallMobile" of the Hide component hide stuff on screens of size 0-320px

packages/orbit-components/src/Popover/components/ContentWrapper.tsx, packages/orbit-components/src/Popover/index.tsx
Reported [here](https://skypicker.slack.com/archives/C04HMMQ6VNE/p1701938825267999). It wasn't present in the component before and caused bug, so I think better will be to remove `max-w-fit`. 
Storybook: https://orbit-mainframev-fix-popover-issues-reported.surge.sh
Giving solution to [FEPLT-1865](https://kiwicom.atlassian.net/browse/FEPLT-1865)
[FEPLT-1865]: https://kiwicom.atlassian.net/browse/FEPLT-1865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(Popover): remove redundant max-w-fit class

packages/orbit-components/src/primitives/ButtonPrimitive/sizes.ts
Removed enforcing of icon sizes in `ButtonPrimitive` 
icon sizes for props `iconLeft` and `iconRight` are regulated by `size` prop of `ButtonPrimitive` 
icons in children should be controlled by their size prop individually as it was before, otherwise, it leads to bugs, like reported [here](https://skypicker.slack.com/archives/C04HMMQ6VNE/p1701938430885789) 
Storybook: https://orbit-mainframev-fix-button-primitive-with-icons.surge.sh
Giving solution to [FEPLT-1869
](https://kiwicom.atlassian.net/browse/FEPLT-1869)
=> fix(ButtonPrimitive): do not force icon sizes in children

packages/orbit-components/src/Dialog/README.md
Reported live by @ArtemKutafin 
Storybook: https://orbit-mainframev-fix-dialog-readme-onClose-prop.surge.sh
=> docs(Dialog): fix bad description for onClose prop

packages/orbit-components/src/Drawer/Drawer.stories.tsx, packages/orbit-components/src/Drawer/index.tsx
As we agreed to return it as it was before, because it's just easier and won't require any hack for users to resolve the visual bug in `title` 
Storybook: https://orbit-mainframev-fix-drawer-padding.surge.sh
=> fix(Drawer): noPadding should affect only wrapper

packages/orbit-components/package.json
Just removed carrots to avoid situations like [this](https://skypicker.slack.com/archives/C05FDP4UM3N/p1702547609300429?thread_ts=1702460689.042279&cid=C05FDP4UM3N) , when there is a available higher versions 
of let's say tokens package and it has some unspotted breaking change(
Storybook: https://orbit-mainframev-chore-use-exact-versions.surge.sh
=> chore: use exact versions of tokens and tailwind

docs/src/docs-table.tsx
Some style selectors were introduced during the migration to Tailwind. This PR adjusts that selector and avoid the `striped` default style (that was previously being overwritten via styles).
Storybook: https://orbit-mainframev-docs-fix-table.surge.sh
[FEPLT-1820](https://kiwicom.atlassian.net/browse/FEPLT-1820)
[FEPLT-1820]: https://kiwicom.atlassian.net/browse/FEPLT-1820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: fix table style after tw migration

packages/orbit-components/src/primitives/ButtonPrimitive/index.tsx
Reported [here](https://skypicker.slack.com/archives/C7T7QG7M5/p1699451085622079) 
Before migration to Tailwind `ButtonPrimitive` had `flex: 0 0 auto` 
Added a small story to replicate the behavior, where you can see that it's fixed 
Giving solution to [FEPLT-1804](https://kiwicom.atlassian.net/browse/FEPLT-1804)
[FEPLT-1804]: https://kiwicom.atlassian.net/browse/FEPLT-1804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Storybook: https://orbit-mainframev-fix-button-missing-flex-and-shrink.surge.sh
=> fix(ButtonPrimitive): add missing shrink-0 and grow-0

packages/orbit-tailwind-preset/src/presets/__tests__/__snapshots__/configs.test.ts.snap, packages/orbit-tailwind-preset/src/presets/__tests__/configs.test.ts, packages/orbit-tailwind-preset/src/presets/components/index.ts
As stated questioned [here](https://skypicker.slack.com/archives/C05FDP4UM3N/p1702999264540639) and stated [here](https://github.com/kiwicom/orbit/blob/master/packages/orbit-tailwind-preset/README.md), it should be by default `false` 
Storybook: https://orbit-mainframev-fix-tailwind-preflight-def.surge.sh
=> fix(tailwind): set disablePreflight to false by default

packages/orbit-components/src/Icon/IconList.tsx
The Icon list story was broken. This PR fixes that
**Before:**
**Now:**
Storybook: https://orbit-mainframev-docs-fix-icons-list.surge.sh
=> docs: fix icons list story

packages/orbit-components/src/Timeline/TimelineContext.tsx, packages/orbit-components/src/Timeline/TimelineStep/components/TimelineStepDesktop.tsx, packages/orbit-components/src/Timeline/TimelineStep/index.tsx, packages/orbit-components/src/Timeline/index.tsx
Related to [this](https://skypicker.slack.com/archives/GSGN9BN6Q/p1703068328514249) and [this](https://skypicker.slack.com/archives/C7T7QG7M5/p1701691187175999) 
Although it was fixed, in case there is no `subLabel` provided to any `TimelineStep`, there is additional spacing that is not desired 
Storybook: https://orbit-mainframev-fix-timeline-placement-sublabewl.surge.sh
=> fix(TimelineStep): move subLabel below timeline

packages/orbit-components/src/Popover/components/ContentWrapper.tsx
Max height was not set at all on small devices when the content had actions,
preventing the scroll from working properly.
https://skypicker.slack.com/archives/C7T7QG7M5/p1704291076964889
Storybook: https://orbit-mainframev-marco-fix-popover.surge.sh
=> fix(Popover): fix max-height when content has actions

packages/orbit-components/src/Itinerary/ItineraryTemporaryText/index.tsx
Truncate component was only targeting text and heading classes, not contemplating the TemporaryText styled component.
Reported [here](https://skypicker.slack.com/archives/C7T7QG7M5/p1702566892095489).
Storybook: https://orbit-mainframev-fix-temporary-text-truncate.surge.sh
=> fix(Itinerary): some text wasn't truncating properly

packages/orbit-components/src/Card/index.tsx, packages/orbit-components/src/Layout/LayoutColumn/index.tsx
We used to have negative margins in the first Card inside LayoutColumn, it was applied for Mobile, to remove the Card padding and have content "full-width" on Mobile, without paddings on the sides. I guess it was an accidental breaking change and better will be to get it back, maybe it was removed during the Card migration to TW 
The Slack-related [thread](https://skypicker.slack.com/archives/C7T7QG7M5/p1701769129228689)
Storybook: https://orbit-mainframev-fix-layout-padding.surge.sh
=> fix(Layout): get back negative margins on Mobile in LayoutColumn

.github/workflows/publish.yml
1. Run [Publish](https://github.com/kiwicom/orbit/actions/workflows/publish.yml) workflow in `marco/prerelease` branch
2. Check always "Dry run" and compare the outputs with and without "Prerelease" checked.
Storybook: https://orbit-mainframev-marco-prerelease.surge.sh
=> ci: allow prereleases on publish workflow

packages/orbit-components/src/Breadcrumbs/index.tsx
Reported [here](https://skypicker.slack.com/archives/C7T7QG7M5/p1704710523485419) and discussed [here](https://skypicker.slack.com/archives/C05FDP4UM3N/p1704715157783819?thread_ts=1704714259.984389&cid=C05FDP4UM3N). Using the div instead of Fragment avoid Stacks to add extra spacing between the two elements.
Storybook: https://orbit-mainframev-fix-breadcrumbs-mobile-spacing.surge.sh
=> fix(Breadcrumbs): remove extra top spacing on mobile

packages/orbit-components/src/Card/index.tsx
Reported [here](https://skypicker.slack.com/archives/C7T7QG7M5/p1704719626364449)
Storybook: https://orbit-mainframev-fix-Card-border-radius.surge.sh
=> fix(Card): border radius incorrectly set on mobile

packages/orbit-components/src/primitives/ButtonPrimitive/__tests__/index.test.tsx, packages/orbit-components/src/primitives/ButtonPrimitive/index.tsx
The problem with `type` was reported [here](https://skypicker.slack.com/archives/C7T7QG7M5/p1704728934322549) and took the opportunity to add the `role` attribute as well so that accessibility is improved.
Storybook: https://orbit-mainframev-feat-add-type-and-role-button.surge.sh
=> feat(ButtonPrimitive): improve accessibility by using type and role

docs/src/__examples__/Popover/DEFAULT.tsx, docs/src/__examples__/Popover/TRIGGER.tsx
Reported [here](https://skypicker.slack.com/archives/C7T7QG7M5/p1705071967841679). The OrbitProvider was missing,
Storybook: https://orbit-mainframev-docs-fix-popover-example-provider.surge.sh
=> docs: fix Popover example with missing OrbitProvider

docs/src/pages/playground-full.tsx
One can now use `Icons.[X]` on the playground, avoiding the clash with the `Seat` name, and also allowing more code snippets compatibility.
Full context [here](https://skypicker.slack.com/archives/C7T7QG7M5/p1705306119592589?thread_ts=1705066629.203219&cid=C7T7QG7M5).
Storybook: https://orbit-mainframev-docs-add-Icons-to-playground.surge.sh
=> docs: add Icons to playground

packages/orbit-components/src/Modal/index.tsx
Reported [here](https://skypicker.slack.com/archives/C7B5YNYHW/p1704968537274009). Not sure tbh, if this is happening somewhere not in Cypress, but added check for safety. 
Storybook: https://orbit-mainframev-fix-modal.surge.sh
=> fix(Modal): check if e.target.className exists

packages/orbit-components/src/Itinerary/ItinerarySegment/ItinerarySegmentDetail/index.tsx
Added a small 💅🏻 , that potentially can cause appearing of horizontal scroll 
before: 
after: 
Storybook: https://orbit-mainframev-fix-itinerary-missing-overflow.surge.sh
=> fix(Itinerary): add overflow:hidden to ItinerarySegmentDetail

packages/orbit-components/src/Modal/ModalHeader/index.tsx, packages/orbit-components/src/Modal/index.tsx
Reported [here](https://skypicker.slack.com/archives/C7T7QG7M5/p1705057780289579).
Before
After
Storybook: https://orbit-mainframev-fix-modal-modal-title-transition.surge.sh
=> fix(Modal): remove modal header transition on mobile

packages/orbit-components/src/Itinerary/ItinerarySegment/ItinerarySegmentDetail/index.tsx
Reported [here](https://skypicker.slack.com/archives/C7T7QG7M5/p1705066629203219).
Before:
Now:
Storybook: https://orbit-mainframev-fix-itinerary-icon-in-segment.surge.sh
=> fix(Itinerary): icon sizes were incorrect inside SegmentDetail

packages/orbit-components/src/Loading/index.tsx
Reported [here](https://skypicker.slack.com/archives/C7T7QG7M5/p1704981489011759) 
also noticed, that the button loader is way too big compared to the [previous](https://orbit-mainframev-chore-nx.surge.sh/?path=/story/loading--button-loading) one 
Storybook: https://orbit-mainframev-fix-loading-custom-size.surge.sh
=> fix(Loading): remove redundant padding and get back icon 20px size

docs/src/components/ReactExample/Example.tsx, docs/src/hooks/useSandbox.ts
Removes persistence of code between editor and iframes. It's saving only during usage, on initial usage always default code is used.
Storybook: https://orbit-mainframev-docs-change-key-of-docs.surge.sh
=> docs: remove persistence of code in playground

packages/orbit-components/src/Card/CardSection/index.tsx
[Reported here](https://skypicker.slack.com/archives/C7T7QG7M5/p1705421647331399)
Storybook: https://orbit-mainframev-fix-card-issue.surge.sh
=> fix(Card): remove loosy equality check for children in CardSection

docs/src/components/DesignTokensList/components/DesignTokenColor.tsx
When we adopted `rgba` values for the color tokens, we left the <alpha-value> placeholder as is, as it's meant to be used through opacity modifiers (docs: https://tailwindcss.com/docs/accent-color#changing-the-opacity).
For example: bg-blue-light/50 to apply a 50 percent opacity to a light blue background.
- [ ] Visual regression test suite has been added if does not exist.
- [ ] `tailwind-migration-status.yaml` file has been updated with the migrated component(s).
Storybook: https://orbit-mainframev-rcsl-fix-docs.surge.sh
=> fix(docs): ensure Tailwind color preview renders correctly

.github/workflows/size.yml, .github/workflows/storybook.yml, .github/workflows/test.yml
Tokens are no longer needed, since icons are statically stored on the repo. They will also be removed from the repo secrets
=> chore: remove streamline tokens

.github/workflows/cron-update-contributors.yml, .github/workflows/cron-update-icons.yml, .github/workflows/cron-update-statuses.yml, .github/workflows/cron-update-tokens.yml
In the sequence of removing default assignee and reviewer, I have replaced the action that creates the PR for our cronjobs. It will now use the official GH action.
=> chore: update cronjobs with new gh actions

.github/workflows/publish.yml
Closes [FEPLT-1943](https://kiwicom.atlassian.net/browse/FEPLT-1943)
[FEPLT-1943]: https://kiwicom.atlassian.net/browse/FEPLT-1943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
- Bot has write permissions
- Bot can bypass required PR in `master` branch.
=> ci: use orbit bot to publish releases

.github/CONTRIBUTING.md
Add missing `yarn components build` to the contributing.md to be able to develop locally.
=> docs: add missing components build cmd to contributing info

packages/orbit-design-tokens/scripts/fetchBaseTokens.mjs
Our tokens cronjob [was failing](https://github.com/kiwicom/orbit/actions/runs/7801192554/job/21275717181) because it was always trying to commit files that, in the end, were only modified by removing the empty line at EOF.
This empty line was added because the `fetch:colors` script generates the palette files every time, without formatting it with prettier rules, hence the absence of an empty line at EOF.
Now we use prettier to format the document, avoiding false changes
=> chore: format generated tokens file

.github/workflows/cron-tracking.yml, .github/workflows/cron-update-contributors.yml, .github/workflows/cron-update-icons.yml, .github/workflows/cron-update-statuses.yml, .github/workflows/cron-update-tokens.yml
Yet another two improvements to our cronjobs. We can now trigger the tracking one manually. And we avoid pipeline fail by conditionally running the action that tries to create a PR (it now only runs if there are new files)
=> Cronjob improvements

packages/orbit-components/src/Wizard/index.tsx
As reported [here](https://skypicker.slack.com/archives/C7T7QG7M5/p1707814668163539), the progress label should be kept inline.
=> Wizard: don't wrap progress label

commitlint.config.js, docs/src/data/tailwind-migration-status.yaml, packages/orbit-components/src/utils/toggleDown/index.ts, packages/orbit-components/src/utils/toggleUp/index.ts
- chore: add missing tailwind migrated components
- feat: deprecate toggleUp and toggleDown utilities
These utilities are not being used by anyone.
- chore: ignore snapshots folders in commitlint
=> chore: add missing tailwind migrated components

.github/workflows/storybook.yml
According to the GitHub docs, the Dependabot gets read-only permissions
on the GITHUB_TOKEN. Since we want to create a comment with the staging
Storybook link, we need to grant write permission in the CI job.
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#changing-github_token-permissions
Closes [FEPLT-1950](https://kiwicom.atlassian.net/browse/FEPLT-1950)
[FEPLT-1950]: https://kiwicom.atlassian.net/browse/FEPLT-1950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ci: allow Dependabot user to write in PRs

.github/workflows/storybook.yml
Following the merge of #4311 all master deploys of storybook were failing because one could not push to GH Pages, as the permissions only had write permissions on pull requests. This should bring those permissions back without affecting the dependabot
=> ci: add write-all to storybook permissions

docs/src/components/Navbar/Links.tsx, packages/orbit-components/src/Icon/createIcon.tsx
Icon components now have their props correctly typed.
[FEPLT-1920](https://kiwicom.atlassian.net/browse/FEPLT-1920)
[FEPLT-1920]: https://kiwicom.atlassian.net/browse/FEPLT-1920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(Icon): icon components are now correctly typed

packages/orbit-components/src/Modal/ModalFooter/index.tsx, packages/orbit-components/src/Modal/ModalHeader/index.tsx, packages/orbit-components/src/Modal/ModalSection/index.tsx, packages/orbit-components/src/Modal/index.tsx
Adds the missing class to make overflow visible on bigger devices.
By adding `lm:overflow-visible` to the Modal, the rounded corners were being missed. Therefore, more rounded corner classes needed to be added. To simplify, and for further documentation, I'd leave the comments inline on this PR.
[FEPLT-1979](https://kiwicom.atlassian.net/browse/FEPLT-1979)
[FEPLT-1979]: https://kiwicom.atlassian.net/browse/FEPLT-1979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(Modal): overflow now works correctly on large mobile and bigger

packages/orbit-components/src/InputSelect/index.tsx
InputSelect component now applies the filter to the options when they change via props. In the past, it was applying only when the input changed. If the options received via props changed as well, the filtering was applied before the change, so it was not applied on the correct set of options.
[FEPLT-1985](https://kiwicom.atlassian.net/browse/FEPLT-1985)
[FEPLT-1985]: https://kiwicom.atlassian.net/browse/FEPLT-1985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(InputSelect): it now filters options when they change via props

packages/orbit-components/package.json, yarn.lock
Version 0.33 includes prebuilt binaries that we want to avoid while using yarn 1
We would need to install dependencies using `--ignore-engines`, which is something I feel we should avoid
=> chore: downgrade sharp version

lerna.json
Lerna now ignores changes in config scripts that have no changes on the client side of packages
This avoids that changes on the scripts folder inside `orbit-design-tokens` and on the config folder inside `orbit-components` cause a bump on the package version.
=> chore: ignore config scripts in lerna publish

packages/orbit-components/config/fetchIcons.mts
"All icons" no longer exists. Two new groups added.
Full context [here](https://skypicker.slack.com/archives/C7T7QG7M5/p1716373246695409?thread_ts=1716370556.909449&cid=C7T7QG7M5).
=> chore: update frame names to fetch icon groups from Figma

packages/orbit-components/config/fetchIcons.mts
Parenthesis chars are being used and they need to be escaped
This will fix the problem observed in [#4358](https://github.com/kiwicom/orbit/pull/4358)
=> chore: escape chars in icon fetching script

packages/orbit-components/src/Itinerary/ItinerarySegment/ItinerarySegmentDetail/index.tsx
Adding type check for `title`, `name` and `value` in order to fix the `[object Object]` in the key.
Closes FEPLT-1999
=> fix(Itinerary): add type check for key prop in ItinerarySegmentDetail

packages/orbit-components/src/Itinerary/Itinerary.stories.tsx, packages/orbit-components/src/Itinerary/ItinerarySegment/ItinerarySegmentDetail/index.tsx, packages/orbit-components/src/Itinerary/ItinerarySegment/context.tsx, packages/orbit-components/src/Itinerary/ItinerarySegment/index.tsx, packages/orbit-components/src/Itinerary/ItinerarySegment/types.d.ts, packages/orbit-components/src/Itinerary/README.md
The issue with usage of `ItinerarySegmentDetails` is that even if there is some `onClick` handler provided in the `ItinerarySegment`, this is not being executed when user clicks anywhere in the expanded `ItinerarySegmentDetails` due to stopPropagation in the `Slide` component used in the `ItinerarySegmentDetail` when content is provided. It fires only when user clicks anywhere around the element (within the `ItinerarySegment`).
- I added `onExpand` and `onCollapse` props to be fired when expand/collapse occurs
- I added all three props to https://orbit.kiwi/components/structure/itinerary/react/#itinerarysegment
Closes FEPLT-2043
=> fix(Itinerary): add onExpand and onCollapse props into ItinerarySegment

packages/orbit-components/src/ButtonLink/index.tsx, packages/orbit-components/tailwind.config.ts
The reported issue was caused by the "sticky hover" issue on mobile devices. We weren't handling it for ButtonLink so I changed hover styles only when hover is applicable.
Closes FEPLT-2045
=> fix(ButtonLink): handle hover state on mobile

.github/workflows/cron-update-icons.yml
This PR includes news settings of GitHub actions workflow - once the once the PR is (automatically) created then its respective GH actions are triggered.
Jira ticket: https://kiwicom.atlassian.net/browse/FEPLT-2003
=> chore: run workflow once the PR is created by job

.github/workflows/lint-prose.yml
There is a limitation on the action that can't be executed when the PR has more than 300 files. Limiting this so the job does not fail in bigger PRs.
=> Limit prose action to 300 changed files

packages/orbit-components/src/Accordion/Accordion.stories.tsx, packages/orbit-components/src/BadgeList/BadgeList.stories.tsx, packages/orbit-components/src/Breadcrumbs/Breadcrumbs.stories.tsx, packages/orbit-components/src/SegmentedSwitch/SegmentedSwitch.stories.tsx, packages/orbit-components/src/Tag/Tag.stories.tsx, packages/orbit-components/src/Wizard/Wizard.stories.tsx
Some changes in [Storybook update PR](https://github.com/kiwicom/orbit/pull/4407) were accidentally removed [during the final rebase](https://github.com/kiwicom/orbit/compare/670e48d1c49863fb9619175f688b3965d0452f0a..9c1d46a3b13cc82d9152f2a2475e91537a75d3e6). This PR is adding them back.
Closes https://kiwicom.atlassian.net/browse/FEPLT-2082
=> Fix accidentally broken stories

packages/orbit-components/src/InputSelect/index.tsx
We were using title as key in`InputSelectOption` for the dropdown which was causing duplicate keys if there were options with the same title (and different value). I changed the keys to be created from title-value combination to secure uniqueness. Once this was done, filtering started to work properly and options were not duplicated.
Closes https://kiwicom.atlassian.net/browse/FEPLT-2096
=> fix(InputSelect): use option value as key

.github/ISSUE_TEMPLATE/bug_report.md, docs/src/documentation/01-getting-started/02-for-developers.mdx, packages/orbit-components/README.md, readme.md
The given example was broken so it was replaced it by the playground.
For the issue template we just provide an example
=> docs: Remove references to orbit codesandbox

packages/orbit-components/src/Itinerary/Itinerary.stories.tsx, packages/orbit-components/src/LinkList/LinkList.stories.tsx, packages/orbit-components/src/List/List.stories.tsx, packages/orbit-components/src/ListChoice/ListChoice.stories.tsx, packages/orbit-components/src/Loading/Loading.stories.tsx, packages/orbit-components/src/Modal/Modal.stories.tsx, packages/orbit-components/src/NavigationBar/NavigationBar.stories.tsx, packages/orbit-components/src/NotificationBadge/NotificationBadge.stories.tsx
Closes https://kiwicom.atlassian.net/browse/FEPLT-2075
=> FEPLT-2075: storybook migration b4

packages/orbit-components/src/Accordion/AccordionSection/components/SectionHeader.tsx
When it had no actions and was not expandable, we were still giving space for actions, leaving the spacing inconsistent
=> FEPLT-2123: fix(Accordion): spacing with no actions was wrong

packages/orbit-components/src/Tile/Tile.stories.tsx, packages/orbit-components/src/TileGroup/TileGroup.stories.tsx, packages/orbit-components/src/Timeline/Timeline.stories.tsx, packages/orbit-components/src/Toast/Toast.stories.tsx, packages/orbit-components/src/Tooltip/Tooltip.stories.tsx, packages/orbit-components/src/Wizard/Wizard.stories.tsx, packages/orbit-components/src/primitives/MobileDialogPrimitive/MobileDialogPrimitive.stories.tsx, packages/orbit-components/src/primitives/TooltipPrimitive/TooltipPrimitive.stories.tsx, packages/orbit-components/src/utils/Grid/Grid.stories.tsx
Closes https://kiwicom.atlassian.net/browse/FEPLT-2079
=> Migrate Stories to CSF3 - Batch 8

packages/orbit-components/src/Checkbox/index.tsx, packages/orbit-components/src/Radio/index.tsx
During #4427 some visual bugs were introduced. This PR addresses them:
- Hover style while checked and disabled
- Active style while disabled
FEPLT-2148
=> Fix checkbox+radio disabled styles

docs/src/__examples__/Heading/DEFAULT.tsx, docs/src/documentation/03-components/09-text/heading/03-accessibility.mdx, packages/orbit-components/.storybook/orbitDecorator.tsx, packages/orbit-components/cypress/integration/pages/heading-media-query-props.tsx, packages/orbit-components/cypress/integration/pages/media-queries.tsx, packages/orbit-components/src/Card/README.md, packages/orbit-components/src/Card/components/Header.tsx, packages/orbit-components/src/Heading/README.md, packages/orbit-components/src/Heading/__tests__/index.test.tsx, packages/orbit-components/src/Heading/index.tsx, packages/orbit-components/src/Heading/types.d.ts
Two new props added `role` and `level`. They're conditional props and allow to define the role and level of the rendered elements.
The component also no longer automatically renders `role="heading"` when the rendered element is a `div`.
FEPLT-2155
=> Add accessibility props to Heading

docs/src/documentation/03-components/08-visuals/seat/03-accessibility.mdx, docs/src/documentation/05-development/04-migration-guides/01-v18.mdx, packages/orbit-components/src/Seat/README.md, packages/orbit-components/src/Seat/Seat.stories.tsx, packages/orbit-components/src/Seat/components/SeatLegend/index.tsx, packages/orbit-components/src/Seat/components/SeatLegend/types.d.ts, packages/orbit-components/src/Seat/index.tsx, packages/orbit-components/src/Seat/types.d.ts
Proposal for adding accessibility to Seat component.
New prop `aria-labelledby` added to Seat component. The `title` and `description` props no longer have default values (Breaking change).
New prop `aria-label` added to SeatLegend component.
New accessibility documentation page added for Seat component.
FEPLT-2157
=> Add accessibility props to Seat

.github/workflows/cron-update-icons.yml
Automation currently disabled while there are some fast-moving changes. Only manual triggers
=> Disable update icons automation

packages/orbit-components/src/primitives/MobileDialogPrimitive/index.tsx, packages/orbit-components/src/primitives/TooltipPrimitive/__tests__/index.test.tsx, packages/orbit-components/src/primitives/TooltipPrimitive/components/TooltipWrapper.tsx, packages/orbit-components/src/primitives/TooltipPrimitive/index.tsx
Also did some cleanup by moving a component to an external file.
I tried to use [useDismiss](https://floating-ui.com/docs/useDismiss) from floating-ui but there were some conflicts with accepting other events so I ended up just hardcoding an event listener.
For the tests, I used `toBeVisible` because it asserts CSS, that changes immediately to `invisible`. There is a delay on the re-render, so we would have to wait before using `toBeInTheDocument`
FEPLT-2159
=> Tooltip now closes on ESC key press

packages/orbit-components/src/ErrorFormTooltip/Tooltip/types.d.ts, packages/orbit-components/src/ErrorFormTooltip/types.d.ts, packages/orbit-components/src/InputField/InputField.stories.tsx, packages/orbit-components/src/InputField/README.md, packages/orbit-components/src/InputField/index.tsx, packages/orbit-components/src/InputField/types.d.ts, packages/orbit-components/src/InputFile/index.tsx, packages/orbit-components/src/InputGroup/InputGroup.stories.tsx, packages/orbit-components/src/InputGroup/README.md, packages/orbit-components/src/InputGroup/consts.ts, packages/orbit-components/src/InputGroup/index.tsx, packages/orbit-components/src/InputGroup/types.d.ts, packages/orbit-components/src/Select/README.md, packages/orbit-components/src/Select/Select.stories.tsx, packages/orbit-components/src/Select/index.tsx, packages/orbit-components/src/Select/types.d.ts
Closes https://kiwicom.atlassian.net/browse/FEPLT-2176 
<details open>
This PR introduces accessibility enhancements to various components by adding `ariaLabel` props and updating related documentation.
<details>
```mermaid
participant Select
participant InputGroup
Note over InputField,Select: Added aria-label support
User->>InputGroup: Interacts with form components
InputGroup->>InputField: Passes label as ariaLabel
InputField-->>Screen Reader: Provides accessibility context
InputGroup->>Select: Passes label as ariaLabel
Select-->>Screen Reader: Provides accessibility context
Note over …
```
=> Select a11y enhancements

docs/src/documentation/05-development/04-migration-guides/01-v19.mdx
The following breaking changes were missing from the migration guide:
- The size prop was removed from InputGroup
- The inputSize prop was removed from ErrorFormTooltip.
<details open>
This PR updates the v19 migration guide to include the removal of the `size` prop from `InputGroup` and the `inputSize` prop from `ErrorFormTooltip`.
<details>
```mermaid
participant Dev as Developer
participant App as Application
participant Components as UI Components
Dev->>App: Start Migration to v19
rect rgb(200, 200, 200)
Note over Dev,Components: Component Updates
Dev->>Components: Replace UserSingle with UserSingleLight
Dev->>Components: Remove size prop from …
```
=> Update v19 migration guide with size prop removal

packages/orbit-components/src/Collapse/Collapse.stories.tsx, packages/orbit-components/src/Collapse/__tests__/index.test.tsx, packages/orbit-components/src/Collapse/index.tsx
Closes https://kiwicom.atlassian.net/browse/FEPLT-2186
<details open>
This PR fixes an accessibility violation by addressing interactive nested elements in the Collapse component.
<details>
```mermaid
actor User
participant Label
participant IconButton
participant CollapseComponent
participant Content
Note over Label,IconButton: Two ways to trigger collapse
alt Click Label
User->>Label: Clicks label
Label->>CollapseComponent: Triggers handleClick()
CollapseComponent->>Content: Toggles visibility
else Click Icon Button
User->>IconButton: Clicks button
IconButton->>CollapseComponent: Triggers handleClick()
CollapseComponent->>Content: Toggles visibility …
```
=> Collapse: fix a11y violation (interactive nested elements)

.github/workflows/publish.yml, .github/workflows/storybook-playroom.yml, docs/src/components/Footer.tsx, docs/src/components/Navbar/Links.tsx, docs/src/documentation/01-getting-started/02-for-developers.mdx, packages/orbit-components/README.md, readme.md, scripts/post-changelog.mjs
<details open>
This PR adds deployment configurations for Playroom and updates various components and documentation to reflect the new Playroom feature.
<details>
```mermaid
participant CI as CI/CD Pipeline
participant Build as Build Process
participant Deploy as Deployment
participant UI as User Interface
CI->>Build: Add Playroom build steps
Note over Build: yarn components build:playroom
Note over Build: yarn components build:storybook
Build->>Deploy: Deploy to Surge
Note over Deploy: Generate version tag
Note over Deploy: Create Playroom domain
Deploy->>UI: Add Playroom links
Note over UI: Add to Navbar
Note over UI: Add to Footer
Note over UI: …
```
=> chore: add Playroom deployment

packages/orbit-components/src/Alert/Alert.stories.tsx
Replaced `message` arg with `children` arg following the pattern from other stories. Also removed `button` arg and hardcoded `inlineActions`.
<details open>
This PR modifies the Alert story by replacing the `message` argument with `children`, removing the `button` argument, and updating the render methods accordingly.
<details>
```mermaid
participant Story
participant Alert
participant AlertButton
User->>Story: Views Alert Story
Story->>Alert: Renders with updated configuration
Note over Alert: New default children text added
alt Icon Handling
Story->>Alert: Process icon prop
Alert-->>Story: Return Icon component or true
end
alt …
```
=> chore: fix Alert story

packages/orbit-components/src/Card/Card.stories.tsx, packages/orbit-components/src/Card/CardSection/index.tsx, packages/orbit-components/src/Card/components/Header.tsx
I got inspired here: https://kittygiraudel.com/2022/04/02/accessible-cards/#wrapping-up
Closes https://kiwicom.atlassian.net/browse/FEPLT-2196 
Closes: https://kiwicom.atlassian.net/browse/FEPLT-2196
<details open>
This PR refactors the Card component to improve accessibility by enhancing the structure and semantics of the CardSection and Header components.
<details>
```mermaid
participant CardSection
participant Header
participant Actions
participant Stack
User->>CardSection: Clicks expandable section
CardSection->>Header: Renders header with title/description
Header-->>CardSection: Header rendered
alt Has Actions …
```
=> Card: refactor component for improved accessibility

packages/orbit-components/.storybook/main.ts
This re-enables the storybook controls. We are really not using the reactDogen features anyway, so we can disabled them.
<details open>
This PR re-enables the storybook controls by modifying the stories path and removing unused reactDocgen configuration.
<details>
```mermaid
participant SB as Storybook Config
participant FS as File System
SB->>FS: Configure stories pattern
Note over SB,FS: Set pattern to "../src/**/*.stories.*"
FS-->>SB: Load matching story files
```
</details>
<details>
<table>
<tr><td><a href=https://github.com/kiwicom/orbit/pull/4588/files#diff-994e6f1d31 …
=> Fix storybook controls

.github/workflows/storybook-playroom.yml, packages/orbit-components/playroom.config.js
Because in GH_PAGES the base url starts with /orbit/, we need that configuration on the playroom config.
All other deployments (on surge) can be kept as they were.
FEPLT-2217
<details open>
This PR modifies the deployment configuration for the playroom in the master branch, ensuring the correct base URL is set based on the branch being deployed.
<details>
```mermaid
participant GH as GitHub Action
participant Env as Environment
participant Deploy as Deployment
GH->>Env: Set IS_MASTER_BRANCH flag
alt is master branch
GH->>Deploy: Deploy to production
Deploy->>Deploy: Use /orbit/playroom baseUrl
Deploy->>Deploy: Deploy to GitHub Pages
else is not master …
```
=> Fix playroom deployment in master branch

packages/orbit-components/playroom.config.js
Missing a `/`
<details open>
This PR adds a missing `/` in the `baseUrl` configuration for the playroom setup.
<details>
```mermaid
participant PlayroomConfig
participant Environment
App->>Environment: Check IS_MASTER_BRANCH
Environment-->>PlayroomConfig: Return branch status
alt IS_MASTER_BRANCH is true
PlayroomConfig-->>App: Use "/orbit/playroom/" baseUrl
else IS_MASTER_BRANCH is false
PlayroomConfig-->>App: Use "/playroom/" baseUrl
end
```
</details>
<details>
<table>
<tr><td><a href=https://github.com/kiwicom/orbit/pull/4593/files#diff-033ffa0d3e8d2ddc295 …
=> Add missing / in baseUrl

.github/workflows/publish.yml, scripts/post-changelog.mjs
<details open>
This PR fixes the Playroom deployment by adding build steps for Playroom and Storybook in the GitHub Actions workflow, and updates the Playroom link generation in the changelog script.
<details>
```mermaid
participant CI as CI/CD Pipeline
participant Build as Build Process
participant Git as Git Operations
participant Docs as Documentation
CI->>Build: Execute build steps
Note over Build: yarn tokens build
Note over Build: yarn tailwind-preset build
Note over Build: yarn components build
Build->>Build: Build Playroom (new)
Build->>Build: Build Storybook (new)
CI->>Git: Get latest tag version
Git-->>CI: Return version info
CI->>Docs: …
```
=> chore: fix Playroom deployment

docs/src/__examples__/Stepper/DEFAULT.tsx, docs/src/documentation/03-components/07-interaction/stepper/03-accessibility.mdx, packages/orbit-components/src/Stepper/README.md, packages/orbit-components/src/Stepper/Stepper.stories.tsx, packages/orbit-components/src/Stepper/StepperStateless/index.tsx, packages/orbit-components/src/Stepper/index.tsx, packages/orbit-components/src/Stepper/types.d.ts
Closes https://kiwicom.atlassian.net/browse/FEPLT-2195 
This PR fixes these a11y violations:
```
Ensure buttons have discernible text
Ensure every form element has a label
```
<details open>
This PR introduces accessibility fixes for the Stepper component, ensuring compliance with a11y standards by adding necessary ARIA attributes.
<details>
```mermaid
participant Stepper
participant Input
participant Increment Button
participant Decrement Button
Note over Stepper: New Accessibility Props Added
User->>Stepper: Interacts with component
alt Focus on Input
Screen Reader->>Input: Reads aria-label from …
```
=> Stepper accessibility fixes

docs/src/documentation/03-components/07-interaction/switch/03-accessibility.mdx, packages/orbit-components/src/Switch/README.md, packages/orbit-components/src/Switch/Switch.stories.tsx, packages/orbit-components/src/Switch/index.tsx, packages/orbit-components/src/Switch/types.d.ts
Closes https://kiwicom.atlassian.net/browse/FEPLT-2212
<details open>
This PR adds accessibility properties to the Switch component, enhancing its usability with assistive technologies. It introduces `ariaControls`, `ariaLabel`, and updates the documentation accordingly.
<details>
```mermaid
participant Switch
participant ControlledElement
Note over Switch: Enhanced with aria attributes
User->>Switch: Interacts with Switch
Switch-->>ScreenReader: Announces aria-label/labelledby
alt Switch controls another element
Switch-->>ControlledElement: References via aria-controls
ScreenReader->>User: Announces …
```
=> Add accessibility props to Switch

packages/orbit-components/src/Popover/Popover.stories.tsx, packages/orbit-components/src/Popover/README.md, packages/orbit-components/src/Popover/__tests__/index.test.tsx, packages/orbit-components/src/Popover/index.tsx
closes https://kiwicom.atlassian.net/browse/FEPLT-2185 
<details open>
This PR adds functionality to close the Popover component when the ESC key is pressed, enhancing user experience and accessibility.
<details>
```mermaid
participant Popover
participant Document
Note over User,Document: New Keyboard Interactions
alt Enter Key Press
User->>Popover: Press Enter (when focused)
Popover->>Popover: Show content
Popover->>Document: Add keydown listener
end
alt Click Interaction
User->>Popover: Click trigger
Popover->>Popover: Show content
Popover->>Document: Add keydown listener
end
alt Escape Key Press
User->>Document: Press Escape …
```
=> fix(Popover): popover content now closes on ESC key press

.github/workflows/publish.yml, scripts/post-changelog.mjs
This PR addresses 3 issues:
- We were trying to deploy playroom even on dry-run
- The URL for the playroom deployment was not being generated correctly
- The messaged published in Slack did not have the correct playroom link
FEPLT-2238
<details open>
This PR fixes issues related to the deployment of Playroom, including preventing deployment during dry runs, correcting the URL generation for Playroom, and ensuring the correct link is published in Slack.
<details>
```mermaid
participant GH as GitHub Workflow
participant Build as Build Process
participant Surge as Surge.sh
Note over GH: Workflow starts
alt dryrun is false …
```
=> Fix playroom deployment

docs/src/documentation/03-components/02-structure/tile/03-accessibility.mdx, docs/src/documentation/03-components/02-structure/tilegroup/03-accessibility.mdx, packages/orbit-components/src/Tile/Tile.stories.tsx, packages/orbit-components/src/Tile/components/TileHeader/index.tsx, packages/orbit-components/src/TileGroup/TileGroup.stories.tsx, packages/orbit-components/src/utils/Slide/index.tsx
Heading level inside Tile is no longer enforced.
Accessibility documentation for the Tile and TileGroup components added.
Fixed some accessibility issues in Tile and TileGroup stories.
Fixed the cursor on the Slide component (used in Tile).
FEPLT-2232
<details open>
This PR enhances accessibility for the Tile and TileGroup components, adds documentation, and fixes cursor issues in the Slide component.
<details>
```mermaid
participant Tile
participant TileGroup
participant Accessibility
User->>Tile: Interacts with Tile
alt Tile with href
Tile->>Accessibility: Renders as <a> element
Accessibility->>Tile: Applies htmlTitle attribute
else …
```
=> Tile + TileGroup Accessibility

docs/src/documentation/03-components/05-input/select/03-accessibility.mdx, packages/orbit-components/src/Select/README.md, packages/orbit-components/src/Select/Select.stories.tsx, packages/orbit-components/src/Select/__tests__/Select.test.tsx, packages/orbit-components/src/Select/index.tsx, packages/orbit-components/src/Select/types.d.ts
Closes: https://kiwicom.atlassian.net/browse/FEPLT-2252
Adjusted stories to remove violations, added aria-labelledby, added Accessibility tab.
I also made adjustment to the component to solve the issue with Tooltip content (when error/help are displayed) being part of the label instead of just being part of `aria-describedby`:
Before:
After:
<details open>
This PR improves accessibility for the Select component by adding `aria-labelledby` and `aria-label` properties, and adjusting the Tooltip content handling.
<details>
```mermaid
participant Select
participant AriaAttributes
User->>Select: Interacts with …
```
=> Improve accessibility for Select

docs/src/__examples__/Tag/FILTERS.tsx
<details open>
This PR adds the `OrbitProvider` and `defaultTheme` to the Tag example, enhancing the component's styling and theming capabilities.
<details>
```mermaid
participant FilterInterface
participant TransportFilter
participant BagsFilter
participant StopsFilter
participant ResultsDisplay
User->>FilterInterface: Views Amsterdam to Barcelona route
User->>TransportFilter: Toggles transport options
TransportFilter-->>ResultsDisplay: Updates visible transport cards
User->>BagsFilter: Adjusts cabin/checked bags
BagsFilter-->>ResultsDisplay: Filters based on baggage allowance
User->>StopsFilter: Selects number of stops …
```
=> docs: add OrbitProvider to a Tag example

docs/src/documentation/03-components/09-text/heading/03-accessibility.mdx, packages/orbit-components/src/Heading/README.md
<details open>
This PR adjusts the documentation for the Heading component, improving clarity on props and their usage, particularly regarding accessibility.
<details>
```mermaid
participant Heading
participant DOM
User->>Heading: Render Heading Component
alt No 'as' prop specified
Heading->>DOM: Render as div (decorative only)
else as="div" with role="heading"
Heading->>DOM: Render div with role="heading"
Note over Heading,DOM: Requires level prop (1-6)
else as="h1" to "h6"
Heading->>DOM: Render semantic heading element
Note over Heading,DOM: role & level props not allowed
end
```
</details>
<details>
<summary><b>Files …
=> Heading docs adjustments

packages/orbit-components/src/CountryFlag/index.tsx
FEPLT-2332
<details open>
This PR introduces a generic orbit class to the CountryFlag component, enhancing its styling capabilities.
<details>
```mermaid
participant CountryFlag
participant div
participant img
App->>CountryFlag: Render with size prop
CountryFlag->>div: Create container
Note over div: Add className with:<br/>- orbit-country-flag<br/>- rounded-50<br/>- bg-country-flag-background<br/>- size-specific classes
div->>img: Render image
Note over img: Apply full size and<br/>shrink-0 classes
```
</details>
<details>
<table>
<tr><td><a …
=> CountryFlag: add generic orbit class

docs/src/documentation/05-development/04-migration-guides/01-v20.mdx, packages/orbit-components/src/Badge/README.md, packages/orbit-components/src/Badge/types.d.ts, packages/orbit-components/src/Itinerary/Itinerary.ct-story.tsx, packages/orbit-components/src/Itinerary/Itinerary.stories.tsx, packages/orbit-components/src/Modal/Modal.stories.tsx
BREAKING CHANGE: The Bagde component removed its border prop as
it was never utilized in the codebase. Migration steps are to remove
this prop from your Badge components, no visual change will occur.
Related to https://kiwicom.atlassian.net/browse/FEPLT-2251
<details open>
This PR removes the unused `border` prop from the `Badge` component and updates the documentation and examples accordingly.
<details>
```mermaid
participant Badge
participant ItinerarySegmentDetail
Note over Badge: Removed 'border' prop
App->>Badge: Create Badge (without border prop)
Badge-->>App: Render Badge
App->>ItinerarySegmentDetail: Create with Badge as …
```
=> fix(Badge): remove ununsed border prop

docs/src/documentation/03-components/03-information/badge/01-guidelines.mdx, docs/src/documentation/03-components/03-information/badge/03-accessibility.mdx, packages/orbit-components/src/primitives/BadgePrimitive/index.tsx
closes FEPLT-2251
<details open>
This PR introduces accessibility improvements for the Badge component, including guidelines for screen reader support and proper use of aria attributes.
<details>
```mermaid
participant User as Screen Reader User
participant Badge as Badge Component
participant SR as Screen Reader
Note over Badge: Added role="status"
Note over Badge: Support for ariaLabel prop
User->>Badge: Interacts with Badge
alt Badge with Icon Only
Badge->>SR: Announces ariaLabel
SR->>User: Reads meaningful context<br/>(e.g. "4 passengers")
else Badge with Decorative Icon + Text
Badge->>SR: Icon marked as aria-hidden="true"
SR->>User: Reads badge …
```
=> Badge a11y

docs/src/documentation/03-components/10-progress-indicators/loading/03-accessibility.mdx, packages/orbit-components/src/Loading/Loading.stories.tsx, packages/orbit-components/src/Loading/README.md, packages/orbit-components/src/Loading/__tests__/index.test.tsx, packages/orbit-components/src/Loading/index.tsx, packages/orbit-components/src/Loading/types.d.ts
<details open>
This PR improves the accessibility of the Loading component by adding new props and enhancing its functionality.
<details>
```mermaid
participant Loading
participant Loader
App->>Loading: Render Loading Component
Note over Loading: Check if text prop exists
alt Has text prop
Loading->>Loading: Force div element
else No text prop
Loading->>Loading: Use asComponent prop (default: div)
end
Loading->>Loader: Render with title & type
Loader->>Loader: Create SVG with role="img"
Loader->>Loader: Add title element
alt Screen Reader Active
Loader->>ScreenReader: Announce title content
end
Loading-->>App: …
```
=> feat(Loading): improve accessibility of the Loading component

docs/src/documentation/03-components/02-structure/table/03-accessibility.mdx, docs/src/documentation/05-development/04-migration-guides/01-v20.mdx, packages/orbit-components/src/Table/README.md, packages/orbit-components/src/Table/Table.stories.tsx, packages/orbit-components/src/Table/TableCell/index.tsx, packages/orbit-components/src/Table/TableCell/types.d.ts, packages/orbit-components/src/Table/index.tsx
I didn't find any wrong usage of `scope` in the repositories so the problem was most likely only in our stories. But to prevent wrong usage in the future, I changed the types to allow `scope` only for `th` element. I added it to migration guide as a note for the users to be aware of it as advised by Marco.
Closes https://kiwicom.atlassian.net/browse/FEPLT-2243
<details open>
This PR enhances the accessibility of the Table component by restricting the usage of the `scope` prop to only the `th` element. It also updates the documentation and migration guide accordingly.
<details>
```mermaid
participant TableCell …
```
=> Make Table accessible

docs/src/documentation/03-components/05-input/inputfield/03-accessibility.mdx, packages/orbit-components/src/InputField/InputField.stories.tsx, packages/orbit-components/src/InputField/README.md, packages/orbit-components/src/InputField/__tests__/index.test.tsx, packages/orbit-components/src/InputField/index.tsx, packages/orbit-components/src/InputField/types.d.ts
Closes https://kiwicom.atlassian.net/browse/FEPLT-2248 
<details open>
This PR introduces accessibility improvements for the `InputField` component, including the addition of `ariaLabelledby` prop and enhancements to the documentation regarding accessibility usage.
<details>
```mermaid
participant Label
participant ARIA
User->>InputField: Interacts with input field
alt Using Custom Label
InputField->>Label: Connect using "for" attribute
Label-->>Screen Reader: Announce label content
end
alt Using Built-in Label
InputField->>ARIA: Set aria-label
InputField->>ARIA: Set aria-labelledby …
```
=> InputField accessibility improvements

packages/orbit-components/src/Toast/README.md, packages/orbit-components/src/Toast/Toast.stories.tsx, packages/orbit-components/src/Toast/ToastMessage.tsx, packages/orbit-components/src/Toast/ToastRoot.tsx, packages/orbit-components/src/Toast/__tests__/index.test.tsx, packages/orbit-components/src/Toast/types.d.ts
The `createToast` function now accepts `ariaProps` as part of the `options` argument object.
This allows for better accessibility configuration on the toasts displayed.
The accessibility documentation will be done on a separate task.
FEPLT-2310
<details open>
This PR enhances the `createToast` function to accept `ariaProps` for improved accessibility, allowing configuration of ARIA attributes for toast notifications.
<details>
```mermaid
participant createToast
participant ToastRoot
participant ToastMessage
App->>ToastRoot: Initialize with ToastRoot
Note over App: Application wants to show toast
App->>createToast: createToast(message, …
```
=> Toast accessibility

packages/orbit-components/src/InputField/index.tsx
Closes https://kiwicom.atlassian.net/browse/FEPLT-2358
<details open>
This PR modifies the `InputField` component to render the label element conditionally based on the presence of error, help, or label props when inlineLabel is true. It also updates the rendering of the label element to use a variable for better flexibility.
<details>
```mermaid
participant InlineLabelElement
participant FormLabel
User->>InputField: Render with props
InputField->>InputField: Check inlineLabel condition
alt inlineLabel true & (error || help || label)
InputField->>InlineLabelElement: Render as "label"
else …
```
=> fix(InputField): render label element once, show block tooltip icon

docs/src/__examples__/CarrierLogo/ACCESSIBILITY.tsx, docs/src/snippets/short-nonvisual.mdx, packages/orbit-components/src/CarrierLogo/CarrierLogo.stories.tsx, packages/orbit-components/src/CarrierLogo/README.md, packages/orbit-components/src/CarrierLogo/index.tsx, packages/orbit-components/src/CarrierLogo/types.d.ts, packages/orbit-components/src/List/List.stories.tsx
The `ariaHidden` prop was added to allow the image to be hidden, if it is placed next to text that describes it.
Documentation was also slightly improved. But dedicated A11Y docs will be added on a separate task.
FEPLT-2280
<details open>
This PR adds the `ariaHidden` prop to the `CarrierLogo` component to improve accessibility by allowing the logo to be hidden from screen readers when it is accompanied by descriptive text.
<details>
```mermaid
participant CarrierLogo
participant Text
Note over CarrierLogo: New ariaHidden prop added
alt ariaHidden=true
User->>+CarrierLogo: View carrier logo …
```
=> CarrierLogo Accessibility

docs/src/__examples__/Collapse/DEFAULT.tsx, docs/src/components/DocLayout/index.tsx, docs/src/components/DocNavigation/Collapse.tsx, docs/src/components/DocNavigation/DocNavigationItem.tsx, docs/src/documentation/05-development/04-migration-guides/01-v21.mdx, packages/orbit-components/playroom/snippets/BasicComponents.ts, packages/orbit-components/playroom/snippets/Layouts.ts, packages/orbit-components/src/ChoiceGroup/index.tsx, packages/orbit-components/src/Collapse/Collapse.ct-story.tsx, packages/orbit-components/src/Collapse/Collapse.stories.tsx, packages/orbit-components/src/Collapse/README.md, packages/orbit-components/src/Collapse/__tests__/index.test.tsx, packages/orbit-components/src/Collapse/index.tsx, packages/orbit-components/src/Collapse/types.d.ts, packages/orbit-components/src/Drawer/Drawer.stories.tsx, packages/orbit-components/transforms/aria-labels-v21.js
Added two new required props, for the labels to the Button that toggles the collapsed space.
Added codemod and migration guide for this breaking change.
Also added a small fix to ChoiceGroup, as it was adding `aria-labelledby` id of an element that would not be rendered (if `label` was not defined).
The accessibility documentation of Collapse will be done on a separate task.
FEPLT-2255
<details open>
This PR introduces new required props for the `Collapse` component to enhance accessibility by providing labels for the expand and collapse buttons. It also includes a migration guide and a fix for the `ChoiceGroup` component regarding the `aria-labelledby` attribute.
<details>
<summary><b>Diagrams of code …
=> Collapse Accessibility

docs/src/__examples__/ButtonMobileStore/DEFAULT.tsx, docs/src/__examples__/ButtonMobileStore/TYPES.tsx, docs/src/documentation/05-development/04-migration-guides/01-v21.mdx, packages/orbit-components/src/ButtonMobileStore/README.md, packages/orbit-components/src/ButtonMobileStore/__tests__/index.test.tsx, packages/orbit-components/src/ButtonMobileStore/index.tsx, packages/orbit-components/src/ButtonMobileStore/types.d.ts, packages/orbit-components/transforms/aria-labels-v21.js
Prop to be used as title for the image, enhancing accessibility.
The accessibility documentation will be done on a separate task.
FEPLT-2279
<details open>
This PR adds a required `alt` prop to the `ButtonMobileStore` component for improved accessibility, along with updates to examples and documentation to reflect this change.
<details>
```mermaid
participant ButtonMobileStore
Note over ButtonMobileStore: New required 'alt' prop added
User->>ButtonMobileStore: Renders component with type="appStore"
alt Without alt text (Before)
ButtonMobileStore-->>Screen Reader: No accessibility description
else With alt …
```
=> ButtonMobileStore: add title prop and make alt required

packages/orbit-components/src/InputField/index.tsx
<details open>
This PR modifies the `InputField` component to remove the tooltip icon when the `label` is null, ensuring that the label is displayed only when it has a value.
<details>
```mermaid
participant FormLabel
User->>InputField: Render with label prop
Note over InputField: Check if inlineLabel is false
alt inlineLabel is false and label exists
InputField->>FormLabel: Render label with required prop
else inlineLabel is true
InputField->>InputField: Skip label rendering
end
```
</details>
<details>
<table>
<tr><td><a …
=> fix(InputField): remove tooltip icon when label is null

docs/src/components/DocNavigation/Collapse.tsx
With the change in Collapse, the docs broke because of misnaming of label props
<details open>
This PR fixes the label prop in the Collapse component to correctly use `customLabel` instead of `label`.
<details>
```mermaid
participant Collapse
participant OrbitCollapse
participant StyledCollapseLabel
User->>Collapse: Renders with props (expanded, customLabel)
Collapse->>OrbitCollapse: Initializes with expanded state
Collapse->>StyledCollapseLabel: Wraps customLabel
OrbitCollapse-->>User: Displays collapsible content
User->>OrbitCollapse: Clicks expand/collapse
OrbitCollapse-->>User: Toggles content visibility
```
</details>
<details> …
=> Fix collapse label on docs

packages/orbit-components/src/AirportIllustration/AirportIllustration.stories.tsx, packages/orbit-components/src/AirportIllustration/README.md, packages/orbit-components/src/AirportIllustration/__tests__/index.test.tsx, packages/orbit-components/src/AirportIllustration/index.tsx
Closes https://kiwicom.atlassian.net/browse/FEPLT-2275 
<details open>
This PR adds an `alt` attribute to the `AirportIllustration` component for improved accessibility and updates the README to reflect this change.
<details>
```mermaid
participant Client
participant AirportIllustration
participant IllustrationPrimitive
participant DOM
Client->>AirportIllustration: Render with props (name, size, alt)
Note over AirportIllustration: Default alt="" if not provided
AirportIllustration->>IllustrationPrimitive: Forward props with alt
IllustrationPrimitive->>DOM: Render img element with alt attribute
DOM-->>Client: Display illustration with alt text
``` …
=> AirportIllustration accessibility

packages/orbit-components/src/Timeline/Timeline.stories.tsx, packages/orbit-components/src/Timeline/TimelineStep/components/TextWrapper.tsx, packages/orbit-components/src/Timeline/TimelineStep/components/TimelineStepDesktop.tsx, packages/orbit-components/src/Timeline/TimelineStep/components/TypeIcon.tsx
For now, it only adds `aria-current="step"` on the active step and silences the announcement of the icon used for the step.
Accessibility documentation will be done on a separate task.
Improvements on how to announce steps status are still TBD.
FEPLT-2256
<details open>
This PR improves the accessibility of the Timeline component by adding `aria-current="step"` to the active step and silencing the announcement of the icon used for the step.
<details>
```mermaid
participant Timeline
participant TimelineStep
participant TextWrapper
participant TypeIcon
User->>Timeline: Views Timeline in Modal
Note over Timeline: Added Modal with …
```
=> Timeline: improve component accessibility

packages/orbit-components/src/Tabs/components/Tab/index.tsx, packages/orbit-components/src/Tabs/components/TabPanel/index.tsx
Closes https://kiwicom.atlassian.net/browse/FEPLT-2271 
I also added `role`, `aria-labelledby` attributes to the `TabPanel` file. Based on that, voice can read that respective content is connected to the active tab.
<details open>
This PR improves accessibility for the Tab and TabPanel components by adding appropriate ARIA roles and attributes.
<details>
```mermaid
participant Tab
participant TabPanel
Note over Tab,TabPanel: Accessibility Enhancements
Tab->>Tab: Add unique ID (tab-{index})
Tab->>Tab: Add focus z-index
Tab->>Tab: Add padding-x
TabPanel->>TabPanel: Add role="tabpanel"
TabPanel->>TabPanel: Link to Tab via …
```
=> Tab: improve accessibility

docs/src/documentation/03-components/01-action/button/03-accessibility.mdx, packages/orbit-components/src/Loading/index.tsx, packages/orbit-components/src/Loading/types.d.ts, packages/orbit-components/src/primitives/ButtonPrimitive/index.tsx, packages/orbit-components/src/primitives/Primitives.stories.tsx
This includes:
- Addition of `ariaHidden` to `Loading` component. This allows the glyph to be ignored by screen readers.
- The ButtonPrimitive in loading state will make use of this. The button is responsible for announcing its state.
- Update the Button a11y docs, because it's a one sentence only.
FEPLT-2270
<details open>
This PR adds the `ariaHidden` prop to the `Loading` component to improve accessibility by allowing the loading indicator to be ignored by screen readers. The `ButtonPrimitive` component is updated to utilize this new prop when in a loading state. Additionally, the accessibility documentation for the Button has been updated.
<details>
```mermaid …
```
=> Button primitive a11y + Loading ariaHidden prop

packages/orbit-components/src/AirportIllustration/types.d.ts, packages/orbit-components/src/Illustration/types.d.ts
Diff generated after running `yarn components build`.
This diff prevented lerna from publishing releases.
<details open>
This PR adjusts type files to templates, ensuring that the interface content is correctly referenced from the specified template file.
<details>
```mermaid
participant Types
participant Template
Note over Types: Adding documentation about<br/>interface source
Types->>Template: Fetch interface content from<br/>TYPESCRIPT_TEMPLATE.template
Note over Types: Applied to both:<br/>- AirportIllustration/types.d.ts<br/>- Illustration/types.d.ts
```
</details>
<details>
<table> …
=> chore: adjust type files to templates

packages/orbit-components/src/Breadcrumbs/README.md, packages/orbit-components/src/Breadcrumbs/index.tsx, packages/orbit-components/src/Breadcrumbs/types.d.ts
Closes 
https://kiwicom.atlassian.net/browse/FEPLT-2278
<details open>
This PR adds an `ariaLabel` prop to the `Breadcrumbs` component for improved accessibility and updates the README to reflect this change.
<details>
```mermaid
participant Breadcrumbs
Note over Breadcrumbs: Added new props:<br/>- id<br/>- ariaLabel
User->>Breadcrumbs: Interact with component
Breadcrumbs->>Screen Reader: Provide aria-label="Breadcrumb"<br/>(default value)
Note over Screen Reader: Improved accessibility<br/>through ARIA labeling
alt Custom ARIA Label
User->>Breadcrumbs: Set custom ariaLabel prop
Breadcrumbs->>Screen Reader: …
```
=> Breadcrumbs accessibility

packages/orbit-components/src/SocialButton/helpers/getSocialButtonIcon.tsx, packages/orbit-components/src/SocialButton/index.tsx
Closes https://kiwicom.atlassian.net/browse/FEPLT-2305
<details open>
This PR enhances the accessibility of the `SocialButton` component by adding `ariaHidden` attributes to the icons and the `ChevronForwardIcon`.
<details>
```mermaid
participant Client
participant SocialButton
participant getSocialButtonIcon
participant Icons
Client->>SocialButton: Render with type prop
SocialButton->>getSocialButtonIcon: Get icon for type
alt type is APPLE
getSocialButtonIcon->>Icons: Return Apple icon
else type is FACEBOOK
getSocialButtonIcon->>Icons: Return Facebook icon
else type is GOOGLE
getSocialButtonIcon->>Icons: Return Google icon
else type is X …
```
=> SocialButton accessibility

docs/src/documentation/03-components/05-input/inputfield/03-accessibility.mdx, docs/src/documentation/03-components/05-input/select/03-accessibility.mdx, packages/orbit-components/src/InputField/README.md, packages/orbit-components/src/InputField/index.tsx, packages/orbit-components/src/InputField/types.d.ts, packages/orbit-components/src/InputGroup/InputGroup.stories.tsx, packages/orbit-components/src/InputGroup/README.md, packages/orbit-components/src/InputGroup/__tests__/index.test.tsx, packages/orbit-components/src/InputGroup/index.tsx, packages/orbit-components/src/InputGroup/types.d.ts, packages/orbit-components/src/Select/README.md, packages/orbit-components/src/Select/index.tsx, packages/orbit-components/src/Select/types.d.ts
I replaced outer div with `fieldset` for better accessibility - `fieldset` has role "group" and is setting label from legend so it's not necessary to set it separately via `aria-labelledby`. I added new props `ariaLabel` and `ariaLabelledby`.
`aria-describedby` wasn't working properly as id of InputGroup's tooltip wasn't propagated to children and these were setting `aria-describedby` id to not visible tooltip. To fix this I added `ariaDescribedby` prop to both Select and InputField components and also did some refactoring as they were setting `shown` value even if component had no `error`/`help` which was adding `aria-describedby` prop incorrectly. As both already had Accessibility tab created, I added info about `ariaDescribedby` prop (it was matter of seconds with Cursor).
I removed …
=> InputGroup accessibility

docs/src/documentation/05-development/04-migration-guides/01-v23.mdx, packages/orbit-components/src/Box/README.md, packages/orbit-components/src/Box/TYPESCRIPT_TEMPLATE.template, packages/orbit-components/src/Box/index.tsx, packages/orbit-components/src/Box/types.d.ts, packages/orbit-components/src/NavigationBar/README.md, packages/orbit-components/src/NavigationBar/index.tsx, packages/orbit-components/src/NavigationBar/types.d.ts, packages/orbit-components/src/Stack/README.md, packages/orbit-components/src/Stack/index.tsx, packages/orbit-components/src/Stack/types.d.ts
We currently don't have any `header` element on the page. Based on my research, I believe the NavigationBar component should have `header` tag and children rendered inside this component should be `nav` elements (when appropriate). As there shouldn't be more than one element on the page with `role="banner"` (role of `header` element), I believe `ariaLabel` prop is redundant here and should be set on the children `nav` elements so I removed it.
As `Stack` component supports `as` prop that can be used to convert current `div` elements to `nav` elements, I added `ariaLabel` prop there so it can ease the migration.
I created [new task](https://kiwicom.atlassian.net/browse/FEPLT-2396) to refactor Nitro's TopNav to use `nav` elements and add SkipNavigation.
Closes …
=> NavigationBar accessibility

docs/src/documentation/03-components/07-interaction/stepper/03-accessibility.mdx, docs/src/documentation/05-development/04-migration-guides/01-v23.mdx, packages/orbit-components/src/Stepper/README.md, packages/orbit-components/src/Stepper/StepperStateless/index.tsx, packages/orbit-components/src/Stepper/index.tsx, packages/orbit-components/src/Stepper/types.d.ts, packages/orbit-components/transforms/transforms-v23.js
This commit will replace aria-labelledby attribute by aria-describedby in input element and also add aria-describedby to buttons. This will ensure that the content of the title/text with respective id will be announced by VO when button is triggered.
Closes https://kiwicom.atlassian.net/browse/FEPLT-2307
<details open>
This PR replaces the `aria-labelledby` attribute with `aria-describedby` in input elements and adds `aria-describedby` to buttons in the Stepper component to improve accessibility for screen readers.
<details>
```mermaid
participant Stepper
participant Decrement Button
participant Input Field …
```
=> Stepper accessibility

packages/orbit-components/src/ChoiceGroup/index.tsx
Based on the observation at: https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/examples/checkbox/ 
We've found out that the accessibility structure of our ChoiceGroup component is not correct. This PR includes improvement of the component. mainly the announcement flow by screen reader.
<details open>
Refactored the `ChoiceGroup` component to improve accessibility by correcting the ARIA roles and properties.
<details>
```mermaid
participant CG as ChoiceGroup
participant Group as Group Container
participant Children as Children Handler
participant Stack as Stack Component
participant Filter as FilterWrapper
CG->>Group: Create group with aria-labelledby …
```
=> feat(ChoiceGroup): refactor component for improved accessibility

packages/orbit-components/src/Button/types.d.ts
This PR removes invalid className prop type on the button component. It's overwritten in the implementation and having it in types was misleading to users as the styles were never applied.
FEPLT-2331
<details open>
This PR removes the invalid `className` prop type from the `ButtonProps` interface, which was misleading as it was overwritten in the implementation.
<details>
```mermaid
participant ButtonPrimitive
participant ButtonProps
participant Types
ButtonPrimitive->>Types: Exports Size type
ButtonPrimitive->>ButtonProps: Extends ButtonCommonProps
Note over ButtonProps: Omits className from ButtonCommonProps
ButtonProps->>Types: Defines Type & Size …
```
=> fix(Button): remove invalid className prop type

packages/orbit-components/src/Dialog/index.tsx, packages/orbit-components/src/Dialog/types.d.ts
Closes #4708
<details open>
This PR fixes the import of prop types for the `Heading` component in the `Dialog` component and updates the `Heading` usage to include a `role` prop set to `undefined`.
<details>
```mermaid
participant D as Dialog Component
participant H as Heading Component
Note over D: Receives title prop
D->>H: Renders title with new props
Note over H: Applies new properties:<br/>type="title3"<br/>align="center"<br/>largeMobile.align="start"<br/>as={titleAs}
H-->>D: Returns styled heading
D->>D: Renders final dialog<br/>with formatted title
```
</details>
<details>
<table> …
=> Fix prop type import on Dialog

docs/src/documentation/03-components/02-structure/tabs/03-accessibility.mdx, packages/orbit-components/src/Tabs/README.md, packages/orbit-components/src/Tabs/Tabs.stories.tsx
Closes https://kiwicom.atlassian.net/browse/FEPLT-2339
<details open>
This PR adds accessibility documentation for the Tabs component, including props, implementation details, best practices, and code examples.
<details>
```mermaid
participant TabList
participant Tab
participant TabPanel
User->>TabList: Focuses on TabList
TabList->>Screen Reader: Announces "ariaLabel" or "ariaLabelledby"
User->>Tab: Selects Tab
Tab->>Screen Reader: Announces tab state (selected/disabled)
Tab->>TabPanel: Controls associated panel
TabPanel->>Screen Reader: Announces panel content
Note over TabList,TabPanel: Accessibility …
```
=> Add Accessibility docs for Tabs

docs/src/documentation/03-components/03-information/alert/03-accessibility.mdx, packages/orbit-components/src/Alert/Alert.stories.tsx, packages/orbit-components/src/Alert/README.md
Closes https://kiwicom.atlassian.net/browse/FEPLT-2342
<details open>
This PR adds accessibility documentation for the Alert component, including details on accessibility props and best practices.
<details>
```mermaid
participant Alert
participant CloseButton
Note over Alert: New Accessibility Features
User->>Alert: Interacts with Alert
alt Alert is Closable
Alert->>Alert: Check labelClose prop
Alert-->>Screen Reader: Announce close button label
User->>CloseButton: Focus on close button
CloseButton-->>Screen Reader: Announce "labelClose" text
User->>CloseButton: Click close
CloseButton->>Alert: Trigger …
```
=> Add Accessibility docs for Alert

docs/src/documentation/03-components/05-input/textarea/03-accessibility.mdx, packages/orbit-components/src/Textarea/README.md
AI-generated, with little tweaks by me
FEPLT-2356
<details open>
This PR adds an Accessibility tab for the Textarea component, detailing its accessibility features and best practices for usage.
<details>
```mermaid
participant User with Screen Reader
participant Textarea Component
participant ARIA System
User with Screen Reader->>Textarea Component: Interacts with textarea
alt Using visible label
Textarea Component->>ARIA System: Uses label prop
ARIA System->>User with Screen Reader: Announces "Label Text"
else Using aria-label
Textarea Component->>ARIA System: Uses ariaLabel prop
ARIA System->>User with Screen Reader: Announces aria-label content …
```
=> Add Accessibility tab for the Textarea component

docs/src/__examples__/Popover/DEFAULT.tsx, docs/src/__examples__/Popover/TRIGGER.tsx, docs/src/documentation/03-components/04-overlay/popover/03-accessibility.mdx, packages/orbit-components/src/Popover/Popover.stories.tsx, packages/orbit-components/src/Popover/README.md, packages/orbit-components/src/Popover/index.tsx
Closes https://kiwicom.atlassian.net/browse/FEPLT-2341, https://kiwicom.atlassian.net/browse/FEPLT-2392
<details open>
This PR adds accessibility documentation for the Popover component and updates the component's props to enhance accessibility features.
<details>
```mermaid
participant Trigger as Popover Trigger
participant Popover
User->>Trigger: Focuses on trigger element
Screen Reader-->>User: Announces trigger state and role
Note over Trigger,Popover: New ARIA attributes added:<br/>aria-controls<br/>aria-haspopup<br/>aria-expanded
User->>Trigger: Clicks/Presses Enter
Trigger->>Popover: Opens popover …
```
=> Add Accessibility docs for Popover

docs/src/documentation/03-components/02-structure/accordion/03-accessibility.mdx, packages/orbit-components/src/Accordion/README.md
AI-generated, with little tweaks 
FEPLT-2346
<details open>
This PR adds an Accessibility tab for the Accordion component, detailing its accessibility features, props, keyboard navigation, and best practices.
<details>
```mermaid
participant Accordion
participant AccordionSection
User->>Accordion: Loads accordion component
Note over Accordion: Initializes with loading state<br/>and expanded section tracking
alt When expandOnTileClick is true
Accordion->>AccordionSection: Applies ARIA attributes
AccordionSection->>AccordionSection: Sets role="button"
AccordionSection->>AccordionSection: Sets aria-expanded …
```
=> docs: add Accessibility tab for the Accordion component

.cursor/rules/accessibility-docs.mdc
<details open>
This PR introduces a set of rules for generating accessibility documentation files, detailing the structure, content requirements, and guidelines for documenting accessibility features in components.
<details>
```mermaid
participant Dev as Developer
participant Doc as Accessibility Doc
participant Readme as README.md
participant Comp as Component
Dev->>Doc: Create accessibility.mdx file
Note over Doc: Place in correct directory structure
Dev->>Doc: Add required frontmatter
Dev->>Doc: Document sections
Note over Doc: - Accessibility Props<br/>- Automatic Features<br/>- Best Practices<br/>- Keyboard Navigation<br/>- Examples
Dev->>Readme: …
```
=> chore: add cursor rule for generating accessibility docs

docs/src/documentation/03-components/03-information/toast/03-accessibility.mdx
Closes https://kiwicom.atlassian.net/browse/FEPLT-2349 
<details open>
This PR adds documentation for the accessibility features of the Toast component, including props, automatic features, best practices, and examples.
<details>
```mermaid
participant Toast
Note over Toast: Supports two roles:<br/>status (default) & alert
alt Normal Toast
User->>Toast: createToast("message")
Toast->>ScreenReader: Announce politely
else Critical Toast
User->>Toast: createToast("error", {role: "alert"})
Toast-->>ScreenReader: Announce immediately
end
alt Mouse Interaction
User->>Toast: Hover
Toast->>Toast: Pause dismissal timer …
```
=> docs: Toast accessibility docs

docs/src/documentation/03-components/05-input/inputfield/03-accessibility.mdx
Added missing aria-* attributes previously not documented and adjusted the document based on the new rules for the accessibility documentation.
Closes https://kiwicom.atlassian.net/browse/FEPLT-2345
<details open>
This PR updates the accessibility documentation for the InputField component by adding missing `aria-*` attributes and adjusting the content based on new accessibility documentation rules.
<details>
```mermaid
participant ARIA System
User->>InputField: Interacts with field
InputField->>ARIA System: Set automatic attributes
Note over ARIA System: Sets aria-invalid if error …
```
=> Adjust Accessibility docs for the InputField component

docs/src/documentation/03-components/05-input/listchoice/03-accessibility.mdx, packages/orbit-components/src/ListChoice/README.md
AI generated, with couple of tweaks.
FEPLT-2351
<details open>
This PR adds an Accessibility tab for the ListChoice component, detailing its accessibility features, props, and best practices.
<details>
```mermaid
participant ListChoice
Note over ListChoice: Component initialized with props
alt Selectable ListChoice
User->>ListChoice: Focus on element
ListChoice->>ScreenReader: Announce title & role="checkbox"
User->>ListChoice: Press Space/Enter
ListChoice->>ListChoice: Toggle selected state
ListChoice->>ScreenReader: Announce checked/unchecked state
else Navigation ListChoice
User->>ListChoice: Focus on …
```
=> docs: add Accessibility tab for the ListChoice component

docs/src/documentation/03-components/08-visuals/featureicon/01-guidelines.mdx, docs/src/documentation/03-components/08-visuals/featureicon/03-accessibility.mdx, packages/orbit-components/src/FeatureIcon/README.md
closes FEPLT-2408
<details open>
This PR updates the documentation for the `FeatureIcon` component, including accessibility guidelines and prop descriptions.
<details>
```mermaid
participant FeatureIcon
Note over FeatureIcon: Component can be used with or without alt text
alt With Empty Alt Text (Decorative)
User->>FeatureIcon: Render with alt=""
FeatureIcon-->>ScreenReader: Skip announcement
Note over ScreenReader: Only announces adjacent text
else With Descriptive Alt Text
User->>FeatureIcon: Render with alt="description"
FeatureIcon-->>ScreenReader: Announce alt text
Note over ScreenReader: Announces …
```
=> Edit FeatureIcon component documentation

packages/orbit-components/src/utils/Slide/README.md
Closes FEPLT-2404
<details open>
This PR adds accessibility documentation for the `Slide` component, including props, automatic accessibility features, best practices, and an example usage.
<details>
```mermaid
actor User
participant Button
participant Slide
participant Content
User->>Button: Clicks "Toggle Details"
Button->>Button: Updates aria-expanded state
Button->>Slide: Sets expanded={true}
Slide->>Slide: Sets aria-hidden={false}
Slide->>Content: Animates expansion
Note over Content: Shows content with<br/>maxHeight constraint
User->>Button: Clicks again
Button->>Button: Updates aria-expanded state
Button->>Slide: Sets expanded={false} …
```
=> docs(Slide): add accessibility docs

packages/orbit-components/package.json
By changing the peerDeps, we should now support both React 18.3 and React 19 versions.
<details open>
This PR updates the peer dependencies for React and React DOM to support versions 18.3 and above.
<details>
```mermaid
participant OC as Orbit Components
participant React as React >=18.3.0
participant ReactDOM as ReactDOM >=18.3.0
Note over OC,ReactDOM: Added peer dependencies
OC->>React: Requires >=18.3.0
OC->>ReactDOM: Requires >=18.3.0
```
</details>
<details>
<table>
<tr><td><a href=https://github.com/kiwicom/orbit/pull/4747/files#diff-ced9b8c475e111867f2bd565020cd6b2ae …
=> Support react 19 in peerDeps

docs/src/documentation/03-components/08-visuals/airportillustration/03-accessibility.mdx, packages/orbit-components/src/AirportIllustration/README.md
Closes https://kiwicom.atlassian.net/browse/FEPLT-2365
<details open>
This PR adds accessibility documentation for the `AirportIllustration` component, detailing accessibility props, automatic features, best practices, and examples for usage.
<details>
```mermaid
participant User as Screen Reader User
participant AI as AirportIllustration
participant SR as Screen Reader
Note over AI: Default role="presentation"
alt role="presentation" (Default)
User->>AI: Encounters illustration
AI->>SR: Skip illustration
SR->>User: No announcement
else role="img" with alt text
User->>AI: Encounters illustration
AI->>SR: Read alt description
SR->>User: Announces alt …
```
=> docs(AirportIllustration): add a11y docs for AirportIllustration component

docs/src/documentation/03-components/01-action/textlink/03-accessibility.mdx, packages/orbit-components/src/Breadcrumbs/types.ts, packages/orbit-components/src/TextLink/README.md, packages/orbit-components/src/TextLink/TextLink.stories.tsx, packages/orbit-components/src/TextLink/__tests__/index.test.tsx, packages/orbit-components/src/TextLink/index.tsx, packages/orbit-components/src/TextLink/types.ts
Closes https://kiwicom.atlassian.net/browse/FEPLT-2361
I made the changes in order to fix [the reported violation](https://accesstime.notion.site/Price-breakdown-modal-have-accessibility-issues-1ea87ab0aeef813683ccd98eb6ddb929) (point 1).
<details open>
This PR adds accessibility documentation for the TextLink component, addressing reported accessibility violations and providing best practices for usage.
<details>
```mermaid
participant TextLink
participant DOM
Note over TextLink: Component Initialization
alt Has href prop
TextLink->>DOM: Render as <a> element
else No href prop
TextLink->>DOM: Render as …
```
=> Add TextLink accessibility documentation

packages/orbit-components/src/TextLink/index.tsx, packages/orbit-components/src/TextLink/types.ts
This allows for a broader onClick type. The previous type definition broke for users that had props defined as just AnchorElement.
<details open>
This PR updates the `onClick` prop type in the `TextLink` component to allow for a broader type definition, accommodating users with props defined as just `AnchorElement`.
<details>
```mermaid
actor User
participant TextLink
participant EventHandler
User->>TextLink: Clicks TextLink
TextLink->>EventHandler: onClickHandler(event)
alt stopPropagation is true
EventHandler->>EventHandler: ev.stopPropagation()
end
alt onClick handler exists
EventHandler->>EventHandler: onClick(event)
end
EventHandler-->>TextLink: …
```
=> fix(TextLink): onClick prop type was incorrectly set

packages/orbit-components/src/Modal/index.tsx
When the DOM changed, the focusable list of elements was not updated. By using the MutationObserver, we can update the list of focusable elements.
This was tested with the playroom snippet (paste it as `code` query param):
```
N4Igxg9gJgpiBcIA8UCWA3ABGANgQwGcCA5PAWxgF4AdEAIwHMBaAdwAtUAXGJgOwgBOZPDkwAHJgGYADNMxsmBMAJgxetAHzVemTEgDCEXtwAenLTt2ZgACgCUmShuvarVlZwCuAnTddurJABZaBFMADNUExgoADEICG4BCwCApAAVPDoCFNS0zLoAGVQCc388-KyNAswARiQAegLcircMrMxOAE8xKlo6QlQwTRqAJkbm8taJrOLSlumCgAU8XhgcHKnWvWXV9YXt3SQAIU9OTiNqjtrMU-OjOsa7i94Dw5Ozl6u6OtvPh-GDWely20yaWRWaxwbwq7TokP2oO2H3urzGf1RjyB-1eSOmwLRHVGGJemEBBJheRm8L20LxbXBNKhm0ssMZLLZISgIjedgA3FMAL6C-yNQzGGBmCyNNDoCwgAA0IBYqCgnDYBAQAG0ACy1HUKgCchtGAF1BUA
```
However, to properly test it, you'd need to rebase this branch with the one from #4755. With that …
=> fix(Modal): focus trap was not reacting to DOM changes

docs/src/documentation/03-components/01-action/buttonmobilestore/03-accessibility.mdx, packages/orbit-components/src/ButtonMobileStore/ButtonMobileStore.stories.tsx, packages/orbit-components/src/ButtonMobileStore/index.tsx, packages/orbit-components/src/ButtonMobileStore/types.ts
Closes [FEPLT-2385](https://kiwicom.atlassian.net/browse/FEPLT-2360)
<details open>
This PR adds accessibility documentation for the ButtonMobileStore component, detailing its accessibility features, props, best practices, and examples.
<details>
```mermaid
participant ButtonMobileStore
Note over ButtonMobileStore: Component renders as either<br/>link (a) or button based on href
alt Has href prop
User->>ButtonMobileStore: Clicks store button
ButtonMobileStore->>Screen Reader: Announces "link, image, [alt text], [title]"
ButtonMobileStore-->>User: Opens store URL in new tab
else No href prop …
```
=> docs(ButtonMobileStore): add accessibility documentation

packages/orbit-components/src/InputGroup/InputGroup.stories.tsx, packages/orbit-components/src/InputGroup/__tests__/index.test.tsx, packages/orbit-components/src/InputGroup/index.tsx, packages/orbit-components/src/InputGroup/types.ts
resolves FEPLT-2750
<details open>
This PR adds a `required` prop to the `InputGroup` component to display a visual indicator for required fields.
<details>
```mermaid
participant InputGroup
participant FormLabel
participant ARIA
User->>InputGroup: Render with required=true
InputGroup->>FormLabel: Pass required prop
FormLabel-->>InputGroup: Render label with asterisk (*)
InputGroup->>ARIA: Set aria-required=true
ARIA-->>User: Accessible required state
```
</details>
<details>
<table>
<tr><td><a href=https://github.com/kiwicom/orbit/pull/4770/files#diff-90394 …
=> feat(InputGroup): add required prop to display visual indicator

packages/orbit-components/src/Toast/README.md, packages/orbit-components/src/Toast/Toast.stories.tsx, packages/orbit-components/src/Toast/ToastRoot.tsx, packages/orbit-components/src/Toast/types.ts
Closes https://kiwicom.atlassian.net/browse/FEPLT-2767
<details open>
This PR introduces a new prop `useTopSafeAreaInset` to the `Toast` component, allowing it to respect the mobile device's top safe area to prevent notifications from being obscured by system UI elements.
<details>
```mermaid
participant ToastRoot
participant Device
App->>ToastRoot: Initialize Toast with useTopSafeAreaInset
alt useTopSafeAreaInset is true
ToastRoot->>Device: Get safe-area-inset-top value
Device-->>ToastRoot: Return safe area inset
ToastRoot->>ToastRoot: Calculate top offset with safe area
else useTopSafeAreaInset is false
ToastRoot->>ToastRoot: Use …
```
=> feat(Toast): add new useTopSafeAreaInset prop

packages/orbit-components/src/Stack/index.tsx
Closes https://kiwicom.atlassian.net/browse/FEPLT-2907
<details open>
This PR modifies the `shouldUseFlex` function to include `ariaLabel` in the list of properties that determine whether to use flex layout.
<details>
```mermaid
participant Stack
participant shouldUseFlex
participant PropertyValidator
Stack->>shouldUseFlex: Check if flex should be used
shouldUseFlex->>PropertyValidator: Validate properties
Note over PropertyValidator: Check against allowed props:<br/>spacing, spaceAfter, dataTest,<br/>children, ariaLabel
PropertyValidator-->>shouldUseFlex: Return validation result
shouldUseFlex-->>Stack: Return flex decision
```
</details>
<details> …
=> fix(Stack): incorrectly rendered as flex when ariaLabel was provided

packages/orbit-components/src/Checkbox/FakeCheckbox/index.tsx
Directly import the only needed icon, to reduce the bundle size.
<details open>
This PR updates the import statement for the `Check` icon in the `FakeCheckbox` component to directly import the needed icon, which helps in reducing the bundle size.
<details>
```mermaid
participant FC as FakeCheckbox
participant CI as Check Icon
Note over FC,CI: Import Check icon component
FC->>CI: Import from "../../icons/Check"
```
</details>
<details>
<table>
<tr><td><a href=https://github.com/kiwicom/orbit/pull/4814/files#diff-0109bedee1be985ed0e8e1573093795e5db8cab4b3c6f0f634b8f3849c59763f …
=> Fix import of Check icon in FakeCheckbox

docs/src/documentation/03-components/08-visuals/servicelogo/03-accessibility.mdx, packages/orbit-components/src/ServiceLogo/README.md, packages/orbit-components/src/ServiceLogo/ServiceLogo.stories.tsx, packages/orbit-components/src/ServiceLogo/TYPESCRIPT_TEMPLATE.template, packages/orbit-components/src/ServiceLogo/__tests__/index.test.tsx, packages/orbit-components/src/ServiceLogo/index.tsx, packages/orbit-components/src/ServiceLogo/types.ts
Closes https://kiwicom.atlassian.net/browse/FEPLT-2381 and https://kiwicom.atlassian.net/browse/FEPLT-2382
<details open>
This PR adds accessibility features to the `ServiceLogo` component by introducing `alt` and `role` props, along with an accessibility documentation tab.
<details>
```mermaid
participant ServiceLogo
User->>ServiceLogo: Render with alt text
alt Has alt prop
ServiceLogo->>ServiceLogo: Set role="img"
ServiceLogo->>ScreenReader: Announce logo with alt text
else No alt prop
ServiceLogo->>ServiceLogo: Set role="presentation"
ServiceLogo->>ScreenReader: Skip logo announcement
end
Note over …
```
=> ServiceLogo: add alt and role props to improve accessibility, add accessibility doc tab

packages/orbit-components/src/Radio/FakeRadio/index.tsx
Closes https://kiwicom.atlassian.net/browse/FEPLT-2927
I've checked the change in the following scenarios:
- wrapped by Stack, Box, div, span ✅ 
- with set BG color on a wrapping element ✅ 
- added local build into Booking repo ✅ 
- checked in MMB locally ✅ 
Playroom:
<details open>
This PR removes the `fullwidth` property from the `FakeRadio` component and adjusts the styling accordingly.
<details>
```mermaid
actor User
participant Radio
participant FakeRadio
participant Styles
User->>Radio: Interacts with radio
Radio->>FakeRadio: Updates state (checked/disabled/error)
FakeRadio->>Styles: Applies visual feedback
alt is checked
Styles-->>FakeRadio: …
```
=> fix(Radio): remove fullwidth property for FakeRadio

packages/orbit-components/src/HorizontalScroll/index.tsx, packages/orbit-components/src/Itinerary/ItinerarySegment/ItinerarySegmentDetail/index.tsx, packages/orbit-components/src/Itinerary/ItinerarySegment/index.tsx
* added data attr so the selector is more resilient
* element is clickable only when the section has no horizontal scroll - in that case the click is used to navigate within the scroll area = this should keep the accessibility intact, but have nicer UX if there are not too many carriers listed
FEPLT-2889
<details open>
This PR enhances the `ItinerarySegment` component by adding a data attribute for better selector resilience and modifies click behavior based on horizontal scroll presence.
<details>
```mermaid
participant ItinerarySegment
participant HorizontalScroll
participant ItinerarySegmentDetail
User->>ItinerarySegment: Clicks on …
```
=> fix(ItinerarySegment): enable click when horizontal scroll is absent

packages/orbit-components/src/HorizontalScroll/index.tsx, packages/orbit-components/src/Itinerary/Itinerary.stories.tsx, packages/orbit-components/src/Itinerary/ItinerarySegment/index.tsx
As reported, ItinerarySegment could be focused via keyboard even if it was not interactive. The same for HorizontalScroll (it only becomes interactive if there is some overflow).
This PR addresses both scenarios
FEPLT-2976
<details open>
This PR adjusts the keyboard focus behavior for `ItinerarySegment` and `HorizontalScroll` components to ensure they are only focusable when interactive.
<details>
```mermaid
actor User
participant HorizontalScroll
participant ItinerarySegment
participant Keyboard
Note over HorizontalScroll: Adds tabIndex when overflowing
alt When Segment is Interactive
User->>ItinerarySegment: Clicks segment …
```
=> Adjust keyboard focus itinerary segment

packages/orbit-components/src/Drawer/types.ts
<details open>
This PR makes the `shown` prop optional in the `Props` interface of the Drawer component, reflecting its default value.
<details>
```mermaid
participant Drawer
Note over Drawer: Added 'shown' boolean prop
App->>Drawer: Initialize with shown={boolean}
Note right of Drawer: Controls visibility state
```
</details>
<details>
<table>
<tr><td><a href=https://github.com/kiwicom/orbit/pull/4851/files#diff-e64811f2b979e0413670bda1ff68c1a5338c8009c0b6044b1df51a529f27dd49>packages/orbit-components/src/Drawer/types.ts</a></td><td>Updated the …
=> fix(Drawer): make shown prop optional as it has default value

packages/orbit-components/src/InputField/index.tsx
closes FEPLT-3058
<details open>
This PR adds rounded styles for autofill inputs in the `InputField` component to enhance its appearance.
<details>
```mermaid
participant Browser
participant AutofillSystem
User->>InputField: Interacts with input field
Browser->>AutofillSystem: Triggers autofill
AutofillSystem->>InputField: Applies autofill
Note over InputField: Applies rounded corners (200px)<br/>for both webkit and standard<br/>autofill states
InputField-->>User: Shows styled autofilled input
```
</details>
<details>
<table> …
=> fix(InputField): add autofill rounded styles for better appearance
